# Generated by Django 5.1.4 on 2026-03-23 21:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0001_initial"),
        ("paper_trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("REVIEWED", "Reviewed"),
                            ("STALE", "Stale"),
                        ],
                        default="REVIEWED",
                        max_length=12,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("FAVORABLE", "Favorable"),
                            ("NEUTRAL", "Neutral"),
                            ("UNFAVORABLE", "Unfavorable"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("rationale", models.TextField(blank=True)),
                ("lesson", models.TextField(blank=True)),
                ("recommendation", models.TextField(blank=True)),
                (
                    "entry_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "current_market_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "price_delta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "pnl_estimate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "market_probability_at_trade",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "market_probability_now",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("signals_context", models.JSONField(blank=True, default=list)),
                ("risk_decision_at_trade", models.CharField(blank=True, max_length=12)),
                (
                    "reviewed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_reviews",
                        to="markets.market",
                    ),
                ),
                (
                    "paper_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_reviews",
                        to="paper_trading.paperaccount",
                    ),
                ),
                (
                    "paper_trade",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="paper_trading.papertrade",
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["paper_account", "review_status"],
                        name="postmortem__paper_a_92c996_idx",
                    ),
                    models.Index(
                        fields=["market", "outcome"],
                        name="postmortem__market__14ffd0_idx",
                    ),
                    models.Index(
                        fields=["outcome", "-reviewed_at"],
                        name="postmortem__outcome_5795b9_idx",
                    ),
                ],
            },
        ),
    ]
