# Generated by Django 5.1.4 on 2026-03-27 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DegradedModeState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("research_degraded", "Research degraded"),
                            ("execution_degraded", "Execution degraded"),
                            ("rollout_disabled", "Rollout disabled"),
                            ("auto_execute_disabled", "Auto execute disabled"),
                            ("defensive_only", "Defensive only"),
                            ("mission_control_paused", "Mission control paused"),
                        ],
                        default="normal",
                        max_length=40,
                    ),
                ),
                ("mission_control_paused", models.BooleanField(default=False)),
                ("auto_execution_enabled", models.BooleanField(default=True)),
                ("rollout_enabled", models.BooleanField(default=True)),
                ("degraded_modules", models.JSONField(blank=True, default=list)),
                ("disabled_actions", models.JSONField(blank=True, default=list)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="IncidentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("provider_failure", "Provider failure"),
                            ("stale_data", "Stale data"),
                            ("rollout_guardrail", "Rollout guardrail"),
                            ("mission_control_failure", "Mission control failure"),
                            ("execution_anomaly", "Execution anomaly"),
                            ("queue_pressure", "Queue pressure"),
                            ("memory_index_failure", "Memory index failure"),
                            ("llm_unavailable", "LLM unavailable"),
                            ("runtime_conflict", "Runtime conflict"),
                            ("safety_block", "Safety block"),
                            ("alerts_delivery_failure", "Alerts delivery failure"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=48,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("MITIGATING", "Mitigating"),
                            ("DEGRADED", "Degraded"),
                            ("RECOVERING", "Recovering"),
                            ("RESOLVED", "Resolved"),
                            ("ESCALATED", "Escalated"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("source_app", models.CharField(max_length=64)),
                (
                    "related_object_type",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "related_object_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("dedupe_key", models.CharField(blank=True, max_length=255, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-last_seen_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-last_seen_at"],
                        name="incident_co_status_5b191e_idx",
                    ),
                    models.Index(
                        fields=["severity", "-last_seen_at"],
                        name="incident_co_severit_2b8198_idx",
                    ),
                    models.Index(
                        fields=["incident_type", "-last_seen_at"],
                        name="incident_co_inciden_1d4fb6_idx",
                    ),
                    models.Index(
                        fields=["dedupe_key"], name="incident_co_dedupe__b25748_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IncidentAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_type", models.CharField(max_length=64)),
                (
                    "action_status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("APPLIED", "Applied"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PLANNED",
                        max_length=12,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="incident_commander.incidentrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="IncidentRecoveryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run_status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="STARTED",
                        max_length=12,
                    ),
                ),
                ("trigger", models.CharField(default="system", max_length=64)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_runs",
                        to="incident_commander.incidentrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
