from django.urls import path

from apps.autonomous_trader.views import (
    AutonomousDispatchRecordsView,
    AutonomousExecutionDecisionDetailView,
    AutonomousExecutionDecisionsView,
    AutonomousExecutionIntakeCandidateDetailView,
    AutonomousExecutionIntakeCandidatesView,
    AutonomousExecutionIntakeRunsView,
    AutonomousExecutionIntakeSummaryView,
    AutonomousExecutionRecommendationsView,
    AutonomousLearningHandoffsView,
    AutonomousFeedbackCandidateContextsView,
    AutonomousFeedbackInfluencesView,
    AutonomousFeedbackRecommendationsView,
    AutonomousFeedbackReuseRunsView,
    AutonomousFeedbackSummaryView,
    AutonomousOutcomeHandoffRecommendationsView,
    AutonomousPositionWatchSummaryView,
    AutonomousPositionWatchRecommendationsView,
    AutonomousPositionActionExecutionsView,
    AutonomousPositionActionDecisionsView,
    AutonomousPositionWatchCandidatesView,
    AutonomousPositionWatchRunsView,
    AutonomousPositionWatchRunView,
    AutonomousOutcomeHandoffRunsView,
    AutonomousOutcomeHandoffSummaryView,
    AutonomousPostmortemHandoffsView,
    AutonomousTradeCandidatesView,
    AutonomousTradeCycleDetailView,
    AutonomousTradeCyclesView,
    AutonomousTradeDecisionsView,
    AutonomousTradeExecutionsView,
    AutonomousTradeOutcomesView,
    AutonomousTradeRunCycleView,
    AutonomousTradeRunExecutionIntakeView,
    AutonomousTradeRunOutcomeHandoffView,
    AutonomousTradeRunFeedbackReuseView,
    AutonomousTradeRunSizingView,
    AutonomousTradeRunWatchCycleView,
    AutonomousSizingContextsView,
    AutonomousSizingDecisionsView,
    AutonomousSizingRecommendationsView,
    AutonomousSizingRunsView,
    AutonomousSizingSummaryView,
    AutonomousTradeSummaryView,
    AutonomousTradeWatchRecordsView,
)

app_name = 'autonomous_trader'

urlpatterns = [
    path('run-execution-intake/', AutonomousTradeRunExecutionIntakeView.as_view(), name='run-execution-intake'),
    path('run-cycle/', AutonomousTradeRunCycleView.as_view(), name='run-cycle'),
    path('run-watch-cycle/', AutonomousTradeRunWatchCycleView.as_view(), name='run-watch-cycle'),
    path('run-outcome-handoff/', AutonomousTradeRunOutcomeHandoffView.as_view(), name='run-outcome-handoff'),
    path('run-feedback-reuse/', AutonomousTradeRunFeedbackReuseView.as_view(), name='run-feedback-reuse'),
    path('run-sizing/', AutonomousTradeRunSizingView.as_view(), name='run-sizing'),
    path('run-position-watch/', AutonomousPositionWatchRunView.as_view(), name='run-position-watch'),
    path('position-watch-runs/', AutonomousPositionWatchRunsView.as_view(), name='position-watch-runs'),
    path('position-watch-candidates/', AutonomousPositionWatchCandidatesView.as_view(), name='position-watch-candidates'),
    path('position-action-decisions/', AutonomousPositionActionDecisionsView.as_view(), name='position-action-decisions'),
    path('position-action-executions/', AutonomousPositionActionExecutionsView.as_view(), name='position-action-executions'),
    path('position-watch-recommendations/', AutonomousPositionWatchRecommendationsView.as_view(), name='position-watch-recommendations'),
    path('position-watch-summary/', AutonomousPositionWatchSummaryView.as_view(), name='position-watch-summary'),
    path('cycles/', AutonomousTradeCyclesView.as_view(), name='cycles'),
    path('cycles/<int:cycle_id>/', AutonomousTradeCycleDetailView.as_view(), name='cycle-detail'),
    path('candidates/', AutonomousTradeCandidatesView.as_view(), name='candidates'),
    path('decisions/', AutonomousTradeDecisionsView.as_view(), name='decisions'),
    path('executions/', AutonomousTradeExecutionsView.as_view(), name='executions'),
    path('watch-records/', AutonomousTradeWatchRecordsView.as_view(), name='watch-records'),
    path('outcomes/', AutonomousTradeOutcomesView.as_view(), name='outcomes'),
    path('summary/', AutonomousTradeSummaryView.as_view(), name='summary'),
    path('execution-intake-runs/', AutonomousExecutionIntakeRunsView.as_view(), name='execution-intake-runs'),
    path('execution-intake-candidates/', AutonomousExecutionIntakeCandidatesView.as_view(), name='execution-intake-candidates'),
    path('execution-intake-candidates/<int:candidate_id>/', AutonomousExecutionIntakeCandidateDetailView.as_view(), name='execution-intake-candidate-detail'),
    path('execution-decisions/', AutonomousExecutionDecisionsView.as_view(), name='execution-decisions'),
    path('execution-decisions/<int:decision_id>/', AutonomousExecutionDecisionDetailView.as_view(), name='execution-decision-detail'),
    path('dispatch-records/', AutonomousDispatchRecordsView.as_view(), name='dispatch-records'),
    path('execution-intake-recommendations/', AutonomousExecutionRecommendationsView.as_view(), name='execution-intake-recommendations'),
    path('execution-intake-summary/', AutonomousExecutionIntakeSummaryView.as_view(), name='execution-intake-summary'),
    path('outcome-handoff-runs/', AutonomousOutcomeHandoffRunsView.as_view(), name='outcome-handoff-runs'),
    path('postmortem-handoffs/', AutonomousPostmortemHandoffsView.as_view(), name='postmortem-handoffs'),
    path('learning-handoffs/', AutonomousLearningHandoffsView.as_view(), name='learning-handoffs'),
    path('outcome-handoff-recommendations/', AutonomousOutcomeHandoffRecommendationsView.as_view(), name='outcome-handoff-recommendations'),
    path('outcome-handoff-summary/', AutonomousOutcomeHandoffSummaryView.as_view(), name='outcome-handoff-summary'),
    path('feedback-reuse-runs/', AutonomousFeedbackReuseRunsView.as_view(), name='feedback-reuse-runs'),
    path('feedback-candidate-contexts/', AutonomousFeedbackCandidateContextsView.as_view(), name='feedback-candidate-contexts'),
    path('feedback-influences/', AutonomousFeedbackInfluencesView.as_view(), name='feedback-influences'),
    path('feedback-recommendations/', AutonomousFeedbackRecommendationsView.as_view(), name='feedback-recommendations'),
    path('feedback-summary/', AutonomousFeedbackSummaryView.as_view(), name='feedback-summary'),
    path('sizing-runs/', AutonomousSizingRunsView.as_view(), name='sizing-runs'),
    path('sizing-contexts/', AutonomousSizingContextsView.as_view(), name='sizing-contexts'),
    path('sizing-decisions/', AutonomousSizingDecisionsView.as_view(), name='sizing-decisions'),
    path('sizing-recommendations/', AutonomousSizingRecommendationsView.as_view(), name='sizing-recommendations'),
    path('sizing-summary/', AutonomousSizingSummaryView.as_view(), name='sizing-summary'),
]
