# Generated by Django 5.1.4 on 2026-03-29 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autonomy_advisory", "0001_initial"),
        ("autonomy_backlog", "0001_initial"),
        ("autonomy_campaign", "0001_initial"),
        ("autonomy_insights", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntakeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("ready_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("emitted_count", models.PositiveIntegerField(default=0)),
                ("duplicate_skipped_count", models.PositiveIntegerField(default=0)),
                ("roadmap_proposal_count", models.PositiveIntegerField(default=0)),
                ("scenario_proposal_count", models.PositiveIntegerField(default=0)),
                ("program_proposal_count", models.PositiveIntegerField(default=0)),
                ("manager_proposal_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PlanningProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal_type",
                    models.CharField(
                        choices=[
                            ("ROADMAP_PROPOSAL", "Roadmap proposal"),
                            ("SCENARIO_PROPOSAL", "Scenario proposal"),
                            ("PROGRAM_REVIEW_PROPOSAL", "Program review proposal"),
                            ("MANAGER_REVIEW_PROPOSAL", "Manager review proposal"),
                            ("OPERATOR_REVIEW_PROPOSAL", "Operator review proposal"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "proposal_status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending review"),
                            ("READY", "Ready"),
                            ("EMITTED", "Emitted"),
                            ("BLOCKED", "Blocked"),
                            ("DUPLICATE_SKIPPED", "Duplicate skipped"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=24,
                    ),
                ),
                (
                    "target_scope",
                    models.CharField(
                        choices=[
                            ("roadmap", "Roadmap"),
                            ("scenario", "Scenario"),
                            ("program", "Program"),
                            ("manager", "Manager"),
                            ("operator_review", "Operator review"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("emitted_by", models.CharField(blank=True, max_length=120)),
                ("emitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "linked_target_artifact",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "advisory_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_proposals",
                        to="autonomy_advisory.advisoryartifact",
                    ),
                ),
                (
                    "backlog_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_proposals",
                        to="autonomy_backlog.governancebacklogitem",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_proposals",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "insight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_proposals",
                        to="autonomy_insights.campaigninsight",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="IntakeRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ROADMAP_PROPOSAL", "Roadmap proposal"),
                            ("SCENARIO_PROPOSAL", "Scenario proposal"),
                            ("PROGRAM_REVIEW_PROPOSAL", "Program review proposal"),
                            ("MANAGER_REVIEW_PROPOSAL", "Manager review proposal"),
                            ("OPERATOR_REVIEW_PROPOSAL", "Operator review proposal"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("EMIT_ROADMAP_PROPOSAL", "Emit roadmap proposal"),
                            ("EMIT_SCENARIO_PROPOSAL", "Emit scenario proposal"),
                            (
                                "EMIT_PROGRAM_REVIEW_PROPOSAL",
                                "Emit program review proposal",
                            ),
                            (
                                "EMIT_MANAGER_REVIEW_PROPOSAL",
                                "Emit manager review proposal",
                            ),
                            (
                                "EMIT_OPERATOR_REVIEW_PROPOSAL",
                                "Emit operator review proposal",
                            ),
                            ("SKIP_DUPLICATE_PROPOSAL", "Skip duplicate proposal"),
                            (
                                "REQUIRE_MANUAL_INTAKE_REVIEW",
                                "Require manual intake review",
                            ),
                            ("REORDER_INTAKE_PRIORITY", "Reorder intake priority"),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "backlog_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intake_recommendations",
                        to="autonomy_backlog.governancebacklogitem",
                    ),
                ),
                (
                    "intake_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_intake.intakerun",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intake_recommendations",
                        to="autonomy_intake.planningproposal",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="planningproposal",
            index=models.Index(
                fields=["backlog_item", "target_scope", "-updated_at"],
                name="autonomy_in_backlog_7a39bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="planningproposal",
            index=models.Index(
                fields=["proposal_status", "-updated_at"],
                name="autonomy_in_proposa_164be2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="planningproposal",
            index=models.Index(
                fields=["priority_level", "-updated_at"],
                name="autonomy_in_priorit_385b58_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="intakerecommendation",
            index=models.Index(
                fields=["recommendation_type", "-created_at"],
                name="autonomy_in_recomme_2d43ea_idx",
            ),
        ),
    ]
