# Generated by Django 5.1.4 on 2026-03-27 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChaosExperiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=128, unique=True)),
                (
                    "experiment_type",
                    models.CharField(
                        choices=[
                            ("provider_sync_failure", "Provider sync failure"),
                            ("llm_unavailable", "LLM unavailable"),
                            (
                                "mission_control_step_failure",
                                "Mission control step failure",
                            ),
                            ("rollout_guardrail_trigger", "Rollout guardrail trigger"),
                            ("queue_pressure_spike", "Queue pressure spike"),
                            (
                                "notification_delivery_failure",
                                "Notification delivery failure",
                            ),
                            ("stale_data_scenario", "Stale data scenario"),
                            ("execution_fill_anomaly", "Execution fill anomaly"),
                        ],
                        max_length=64,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("warning", "Warning"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=12,
                    ),
                ),
                ("target_module", models.CharField(max_length=64)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("config", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["name", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_enabled", "severity"],
                        name="chaos_lab_c_is_enab_805564_idx",
                    ),
                    models.Index(
                        fields=["target_module", "is_enabled"],
                        name="chaos_lab_c_target__c482a0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChaosRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                            ("ABORTED", "Aborted"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "trigger_mode",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("scheduled", "Scheduled"),
                            ("benchmark_suite", "Benchmark suite"),
                        ],
                        default="manual",
                        max_length=24,
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="chaos_lab.chaosexperiment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ChaosObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("message", models.CharField(max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=12,
                    ),
                ),
                ("observed_at", models.DateTimeField()),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="chaos_lab.chaosrun",
                    ),
                ),
            ],
            options={
                "ordering": ["observed_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ResilienceBenchmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "detection_time_seconds",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "mitigation_time_seconds",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "recovery_time_seconds",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("incidents_created", models.PositiveIntegerField(default=0)),
                ("degraded_mode_triggered", models.BooleanField(default=False)),
                ("rollback_triggered", models.BooleanField(default=False)),
                ("alerts_sent", models.PositiveIntegerField(default=0)),
                ("queue_items_created", models.PositiveIntegerField(default=0)),
                (
                    "recovery_success_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "resilience_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                ("metrics", models.JSONField(blank=True, default=dict)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benchmarks",
                        to="chaos_lab.chaosexperiment",
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benchmark",
                        to="chaos_lab.chaosrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="chaosrun",
            index=models.Index(
                fields=["status", "-created_at"], name="chaos_lab_c_status_08a7dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chaosrun",
            index=models.Index(
                fields=["experiment", "-created_at"],
                name="chaos_lab_c_experim_587e3b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chaosobservation",
            index=models.Index(
                fields=["run", "observed_at"], name="chaos_lab_c_run_id_337816_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chaosobservation",
            index=models.Index(
                fields=["code", "severity"], name="chaos_lab_c_code_6f5a33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resiliencebenchmark",
            index=models.Index(
                fields=["experiment", "-created_at"],
                name="chaos_lab_r_experim_37e950_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resiliencebenchmark",
            index=models.Index(
                fields=["resilience_score", "-created_at"],
                name="chaos_lab_r_resilie_9dda86_idx",
            ),
        ),
    ]
