from django.urls import path

from apps.promotion_committee.views import (
    CurrentPromotionRecommendationView,
    GovernedPromotionRunReviewView,
    GovernedPromotionSummaryView,
    PromotionAdoptionActionsView,
    PromotionAdoptionCandidatesView,
    PromotionAdoptionRecommendationsView,
    PromotionAdoptionRunReviewView,
    PromotionAdoptionSummaryView,
    PromotionApplyView,
    PromotionCasesView,
    PromotionDecisionRecommendationsView,
    PromotionEvidencePacksView,
    PromotionManualApplyCaseView,
    PromotionRollbackPlansView,
    PromotionRollbackActionView,
    PromotionRollbackExecutionsView,
    PromotionRunRolloutPrepView,
    PromotionRolloutCandidatesView,
    PromotionRolloutPlansView,
    PromotionCheckpointPlansView,
    PromotionRolloutRecommendationsView,
    PromotionRolloutSummaryView,
    PromotionPrepareRolloutView,
    PromotionRunDetailView,
    PromotionRunListView,
    PromotionRunReviewView,
    PromotionSummaryView,
)

app_name = 'promotion_committee'

urlpatterns = [
    path('run-review/', GovernedPromotionRunReviewView.as_view(), name='governed-run-review'),
    path('run-adoption-review/', PromotionAdoptionRunReviewView.as_view(), name='run-adoption-review'),
    path('cases/', PromotionCasesView.as_view(), name='cases'),
    path('adoption-candidates/', PromotionAdoptionCandidatesView.as_view(), name='adoption-candidates'),
    path('adoption-actions/', PromotionAdoptionActionsView.as_view(), name='adoption-actions'),
    path('rollback-plans/', PromotionRollbackPlansView.as_view(), name='rollback-plans'),
    path('adoption-recommendations/', PromotionAdoptionRecommendationsView.as_view(), name='adoption-recommendations'),
    path('adoption-summary/', PromotionAdoptionSummaryView.as_view(), name='adoption-summary'),
    path('run-rollout-prep/', PromotionRunRolloutPrepView.as_view(), name='run-rollout-prep'),
    path('rollout-candidates/', PromotionRolloutCandidatesView.as_view(), name='rollout-candidates'),
    path('rollout-plans/', PromotionRolloutPlansView.as_view(), name='rollout-plans'),
    path('checkpoint-plans/', PromotionCheckpointPlansView.as_view(), name='checkpoint-plans'),
    path('rollback-executions/', PromotionRollbackExecutionsView.as_view(), name='rollback-executions'),
    path('rollout-recommendations/', PromotionRolloutRecommendationsView.as_view(), name='rollout-recommendations'),
    path('rollout-summary/', PromotionRolloutSummaryView.as_view(), name='rollout-summary'),
    path('prepare-rollout/<int:case_id>/', PromotionPrepareRolloutView.as_view(), name='prepare-rollout'),
    path('rollback/<int:action_id>/', PromotionRollbackActionView.as_view(), name='rollback-action'),
    path('evidence-packs/', PromotionEvidencePacksView.as_view(), name='evidence-packs'),
    path('recommendations/', PromotionDecisionRecommendationsView.as_view(), name='recommendations'),
    path('summary/', GovernedPromotionSummaryView.as_view(), name='governed-summary'),
    path('legacy-run-review/', PromotionRunReviewView.as_view(), name='run-review'),
    path('runs/', PromotionRunListView.as_view(), name='runs'),
    path('runs/<int:pk>/', PromotionRunDetailView.as_view(), name='run-detail'),
    path('current-recommendation/', CurrentPromotionRecommendationView.as_view(), name='current-recommendation'),
    path('legacy-summary/', PromotionSummaryView.as_view(), name='summary'),
    path('legacy-apply/<int:pk>/', PromotionApplyView.as_view(), name='legacy-apply'),
    path('apply/<int:case_id>/', PromotionManualApplyCaseView.as_view(), name='apply'),
]
