# Generated by Django 5.1.4 on 2026-03-27 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("broker_bridge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapitalFirewallRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                ("block_live_transition", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["code", "id"],
            },
        ),
        migrations.CreateModel(
            name="GoLiveChecklistRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.CharField(default="local-operator", max_length=120),
                ),
                ("context", models.CharField(default="manual", max_length=64)),
                ("checklist_version", models.CharField(default="v1", max_length=24)),
                ("passed", models.BooleanField(default=False)),
                (
                    "gate_state",
                    models.CharField(
                        choices=[
                            ("PAPER_ONLY_LOCKED", "Paper only locked"),
                            ("PRELIVE_REHEARSAL_READY", "Pre-live rehearsal ready"),
                            ("MANUAL_APPROVAL_PENDING", "Manual approval pending"),
                            ("LIVE_DISABLED_BY_POLICY", "Live disabled by policy"),
                            ("REMEDIATION_REQUIRED", "Remediation required"),
                        ],
                        default="PAPER_ONLY_LOCKED",
                        max_length=40,
                    ),
                ),
                ("passed_items", models.JSONField(blank=True, default=list)),
                ("failed_items", models.JSONField(blank=True, default=list)),
                ("blocking_reasons", models.JSONField(blank=True, default=list)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GoLiveApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requested_by", models.CharField(max_length=120)),
                ("rationale", models.TextField(blank=True)),
                ("scope", models.CharField(default="global", max_length=120)),
                (
                    "requested_mode",
                    models.CharField(default="PRELIVE_REHEARSAL", max_length=48),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("blocking_reasons", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "checklist_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_requests",
                        to="go_live_gate.golivechecklistrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GoLiveRehearsalRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gate_state",
                    models.CharField(
                        choices=[
                            ("PAPER_ONLY_LOCKED", "Paper only locked"),
                            ("PRELIVE_REHEARSAL_READY", "Pre-live rehearsal ready"),
                            ("MANUAL_APPROVAL_PENDING", "Manual approval pending"),
                            ("LIVE_DISABLED_BY_POLICY", "Live disabled by policy"),
                            ("REMEDIATION_REQUIRED", "Remediation required"),
                        ],
                        default="PAPER_ONLY_LOCKED",
                        max_length=40,
                    ),
                ),
                ("allowed_to_proceed_in_rehearsal", models.BooleanField(default=False)),
                ("blocked_by_firewall", models.BooleanField(default=True)),
                ("missing_approvals", models.JSONField(blank=True, default=list)),
                ("missing_preconditions", models.JSONField(blank=True, default=list)),
                ("blocked_reasons", models.JSONField(blank=True, default=list)),
                (
                    "final_dry_run_disposition",
                    models.CharField(blank=True, max_length=32),
                ),
                (
                    "dry_run_reference_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "approval_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rehearsals",
                        to="go_live_gate.goliveapprovalrequest",
                    ),
                ),
                (
                    "checklist_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rehearsals",
                        to="go_live_gate.golivechecklistrun",
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="go_live_rehearsals",
                        to="broker_bridge.brokerorderintent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
