# Generated by Django 5.1.4 on 2026-03-26 23:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioExposureSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_equity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "available_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_exposure",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("open_positions", models.PositiveIntegerField(default=0)),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "recent_drawdown_pct",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "cash_reserve_ratio",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "concentration_market_ratio",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "concentration_provider_ratio",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("exposure_by_market", models.JSONField(blank=True, default=list)),
                ("exposure_by_provider", models.JSONField(blank=True, default=list)),
                ("exposure_by_category", models.JSONField(blank=True, default=list)),
                (
                    "created_at_snapshot",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-created_at_snapshot", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioThrottleDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCK_NEW_ENTRIES", "Block new entries"),
                            ("FORCE_REDUCE", "Force reduce"),
                        ],
                        default="NORMAL",
                        max_length=24,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "recommended_max_new_positions",
                    models.PositiveIntegerField(default=3),
                ),
                (
                    "recommended_max_size_multiplier",
                    models.DecimalField(decimal_places=4, default=1, max_digits=8),
                ),
                ("regime_signals", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at_decision",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-created_at_decision", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioGovernanceRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("profile_slug", models.CharField(blank=True, max_length=64)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "exposure_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="governance_runs",
                        to="portfolio_governor.portfolioexposuresnapshot",
                    ),
                ),
                (
                    "throttle_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="governance_runs",
                        to="portfolio_governor.portfoliothrottledecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
    ]
