# Generated by Django 5.1.4 on 2026-04-02 20:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "autonomous_trader",
            "0006_autonomousexecutiondecision_autonomousdispatchrecord_and_more",
        ),
        ("markets", "0002_event_source_type_market_source_type"),
        ("mission_control", "0010_autonomousglobalcapacitysnapshot_and_more"),
        ("portfolio_governor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioExposureCoordinationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_cluster_count", models.PositiveIntegerField(default=0)),
                ("concentration_alert_count", models.PositiveIntegerField(default=0)),
                ("conflict_alert_count", models.PositiveIntegerField(default=0)),
                ("throttle_count", models.PositiveIntegerField(default=0)),
                ("defer_count", models.PositiveIntegerField(default=0)),
                ("park_count", models.PositiveIntegerField(default=0)),
                ("manual_review_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioExposureClusterSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cluster_label", models.CharField(max_length=140)),
                (
                    "cluster_type",
                    models.CharField(
                        choices=[
                            ("MARKET", "Market"),
                            ("NARRATIVE", "Narrative"),
                            ("DIRECTIONAL", "Directional"),
                            ("THEMATIC", "Thematic"),
                            ("MIXED", "Mixed"),
                        ],
                        default="MIXED",
                        max_length=16,
                    ),
                ),
                (
                    "net_direction",
                    models.CharField(
                        choices=[
                            ("LONG_BIAS", "Long bias"),
                            ("SHORT_BIAS", "Short bias"),
                            ("MIXED", "Mixed"),
                            ("UNCLEAR", "Unclear"),
                        ],
                        default="UNCLEAR",
                        max_length=16,
                    ),
                ),
                ("session_count", models.PositiveIntegerField(default=0)),
                ("open_position_count", models.PositiveIntegerField(default=0)),
                ("pending_dispatch_count", models.PositiveIntegerField(default=0)),
                (
                    "aggregate_notional_pressure",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "aggregate_risk_pressure_state",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCK_NEW_EXPOSURE", "Block new exposure"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "concentration_status",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("ELEVATED", "Elevated"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="NORMAL",
                        max_length=16,
                    ),
                ),
                ("cluster_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at_snapshot",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "linked_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_exposure_clusters",
                        to="markets.market",
                    ),
                ),
                (
                    "linked_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_snapshots",
                        to="portfolio_governor.portfolioexposurecoordinationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at_snapshot", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioExposureConflictReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("CONCENTRATION_RISK", "Concentration risk"),
                            (
                                "REDUNDANT_SESSION_STACKING",
                                "Redundant session stacking",
                            ),
                            ("DIRECTIONAL_CONFLICT", "Directional conflict"),
                            ("PENDING_DISPATCH_OVERLOAD", "Pending dispatch overload"),
                            ("LOW_VALUE_CAPACITY_WASTE", "Low value capacity waste"),
                            (
                                "PORTFOLIO_PRESSURE_CONFLICT",
                                "Portfolio pressure conflict",
                            ),
                        ],
                        max_length=36,
                    ),
                ),
                (
                    "review_severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("CAUTION", "Caution"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=12,
                    ),
                ),
                ("review_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at_review",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "linked_cluster_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflict_reviews",
                        to="portfolio_governor.portfolioexposureclustersnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at_review", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioExposureDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("KEEP_EXPOSURE_AS_IS", "Keep exposure as is"),
                            ("THROTTLE_NEW_ENTRIES", "Throttle new entries"),
                            ("DEFER_PENDING_DISPATCH", "Defer pending dispatch"),
                            ("PARK_WEAKER_SESSION", "Park weaker session"),
                            ("PAUSE_CLUSTER_ACTIVITY", "Pause cluster activity"),
                            ("REDUCE_EXPOSURE_PRIORITY", "Reduce exposure priority"),
                            (
                                "REQUIRE_MANUAL_EXPOSURE_REVIEW",
                                "Require manual exposure review",
                            ),
                        ],
                        max_length=36,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=12,
                    ),
                ),
                ("auto_applicable", models.BooleanField(default=False)),
                ("decision_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at_decision",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "linked_cluster_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="portfolio_governor.portfolioexposureclustersnapshot",
                    ),
                ),
                (
                    "linked_conflict_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions",
                        to="portfolio_governor.portfolioexposureconflictreview",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at_decision", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioExposureRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("KEEP_CURRENT_EXPOSURE", "Keep current exposure"),
                            (
                                "THROTTLE_CLUSTER_FOR_CONCENTRATION",
                                "Throttle cluster for concentration",
                            ),
                            (
                                "DEFER_WEAKER_PENDING_DISPATCH",
                                "Defer weaker pending dispatch",
                            ),
                            ("PARK_REDUNDANT_SESSION", "Park redundant session"),
                            (
                                "PAUSE_CLUSTER_FOR_PORTFOLIO_PRESSURE",
                                "Pause cluster for portfolio pressure",
                            ),
                            (
                                "REQUIRE_MANUAL_EXPOSURE_REVIEW",
                                "Require manual exposure review",
                            ),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_cluster_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="portfolio_governor.portfolioexposureclustersnapshot",
                    ),
                ),
                (
                    "target_conflict_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="portfolio_governor.portfolioexposureconflictreview",
                    ),
                ),
                (
                    "target_exposure_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="portfolio_governor.portfolioexposuredecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SessionExposureContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contribution_role",
                    models.CharField(
                        choices=[
                            ("PRIMARY_DRIVER", "Primary driver"),
                            ("SUPPORTING", "Supporting"),
                            ("REDUNDANT", "Redundant"),
                            ("CONFLICTING", "Conflicting"),
                            ("LOW_VALUE", "Low value"),
                        ],
                        default="SUPPORTING",
                        max_length=20,
                    ),
                ),
                (
                    "contribution_direction",
                    models.CharField(
                        choices=[
                            ("LONG", "Long"),
                            ("SHORT", "Short"),
                            ("MIXED", "Mixed"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        default="NEUTRAL",
                        max_length=12,
                    ),
                ),
                (
                    "contribution_strength",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="LOW",
                        max_length=8,
                    ),
                ),
                ("contribution_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at_snapshot",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "linked_admission_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_exposure_contributions",
                        to="mission_control.autonomoussessionadmissiondecision",
                    ),
                ),
                (
                    "linked_cluster_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_contributions",
                        to="portfolio_governor.portfolioexposureclustersnapshot",
                    ),
                ),
                (
                    "linked_dispatch_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_exposure_contributions",
                        to="autonomous_trader.autonomousdispatchrecord",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_exposure_contributions",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "linked_trade_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_exposure_contributions",
                        to="autonomous_trader.autonomoustradeexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at_snapshot", "-id"],
            },
        ),
    ]
