# Generated by Django 5.1.4 on 2026-04-02 20:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "autonomous_trader",
            "0006_autonomousexecutiondecision_autonomousdispatchrecord_and_more",
        ),
        ("mission_control", "0010_autonomousglobalcapacitysnapshot_and_more"),
        ("portfolio_governor", "0002_portfolioexposurecoordinationrun_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioExposureApplyRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_decision_count", models.PositiveIntegerField(default=0)),
                ("applied_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                (
                    "deferred_dispatch_apply_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("parked_session_apply_count", models.PositiveIntegerField(default=0)),
                ("paused_cluster_apply_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioExposureApplyDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "apply_type",
                    models.CharField(
                        choices=[
                            (
                                "APPLY_THROTTLE_NEW_ENTRIES",
                                "Apply throttle new entries",
                            ),
                            (
                                "APPLY_DEFER_PENDING_DISPATCH",
                                "Apply defer pending dispatch",
                            ),
                            ("APPLY_PARK_SESSION", "Apply park session"),
                            (
                                "APPLY_PAUSE_CLUSTER_ACTIVITY",
                                "Apply pause cluster activity",
                            ),
                            ("APPLY_MANUAL_REVIEW_ONLY", "Apply manual review only"),
                            ("APPLY_NO_CHANGE", "Apply no change"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "apply_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                            ("FAILED", "Failed"),
                        ],
                        default="PROPOSED",
                        max_length=12,
                    ),
                ),
                ("auto_applicable", models.BooleanField(default=False)),
                ("apply_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at_decision",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "linked_exposure_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apply_decisions",
                        to="portfolio_governor.portfolioexposuredecision",
                    ),
                ),
                (
                    "linked_apply_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apply_decisions",
                        to="portfolio_governor.portfolioexposureapplyrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at_decision", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioExposureApplyRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            (
                                "APPLY_CLUSTER_THROTTLE_NOW",
                                "Apply cluster throttle now",
                            ),
                            (
                                "DEFER_PENDING_DISPATCH_SAFELY",
                                "Defer pending dispatch safely",
                            ),
                            (
                                "PARK_REDUNDANT_SESSION_NOW",
                                "Park redundant session now",
                            ),
                            (
                                "PAUSE_CLUSTER_ACTIVITY_CONSERVATIVELY",
                                "Pause cluster activity conservatively",
                            ),
                            (
                                "REQUIRE_MANUAL_EXPOSURE_APPLY_REVIEW",
                                "Require manual exposure apply review",
                            ),
                            (
                                "LEAVE_EXPOSURE_DECISION_AS_ADVISORY_ONLY",
                                "Leave exposure decision as advisory only",
                            ),
                        ],
                        max_length=56,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_apply_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="portfolio_governor.portfolioexposureapplydecision",
                    ),
                ),
                (
                    "target_exposure_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apply_recommendations",
                        to="portfolio_governor.portfolioexposuredecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioExposureApplyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record_status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "effect_type",
                    models.CharField(
                        choices=[
                            ("NEW_ENTRIES_THROTTLED", "New entries throttled"),
                            ("DISPATCH_DEFERRED", "Dispatch deferred"),
                            ("SESSION_PARKED", "Session parked"),
                            ("CLUSTER_ACTIVITY_PAUSED", "Cluster activity paused"),
                            ("MANUAL_REVIEW_ONLY", "Manual review only"),
                            ("NO_CHANGE", "No change"),
                        ],
                        max_length=32,
                    ),
                ),
                ("record_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at_record",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "linked_apply_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="portfolio_governor.portfolioexposureapplydecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at_record", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioExposureApplyTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("SESSION", "Session"),
                            ("PENDING_DISPATCH", "Pending dispatch"),
                            ("CLUSTER_GATE", "Cluster gate"),
                            ("ADMISSION_PATH", "Admission path"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "target_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="READY",
                        max_length=12,
                    ),
                ),
                ("target_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at_target",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "linked_apply_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="portfolio_governor.portfolioexposureapplyrun",
                    ),
                ),
                (
                    "linked_cluster_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apply_targets",
                        to="portfolio_governor.portfolioexposureclustersnapshot",
                    ),
                ),
                (
                    "linked_dispatch_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_exposure_apply_targets",
                        to="autonomous_trader.autonomousdispatchrecord",
                    ),
                ),
                (
                    "linked_exposure_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apply_targets",
                        to="portfolio_governor.portfolioexposuredecision",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_exposure_apply_targets",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at_target", "-id"],
            },
        ),
    ]
