# Generated by Django 5.1.4 on 2026-03-26 17:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0002_event_source_type_market_source_type"),
        ("paper_trading", "0001_initial"),
        ("prediction_agent", "0001_initial"),
        ("proposal_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionWatchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="READY",
                        max_length=12,
                    ),
                ),
                ("watched_positions", models.PositiveIntegerField(default=0)),
                ("generated_events", models.PositiveIntegerField(default=0)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PositionWatchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("monitor", "Monitor"),
                            ("caution", "Caution"),
                            ("review_required", "Review required"),
                            ("exit_consideration", "Exit consideration"),
                            ("blocked_context", "Blocked context"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("high", "High"),
                        ],
                        default="info",
                        max_length=12,
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("rationale", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "paper_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_watch_events",
                        to="paper_trading.paperposition",
                    ),
                ),
                (
                    "watch_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="risk_agent.positionwatchrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="READY",
                        max_length=12,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="MEDIUM",
                        max_length=12,
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("key_risk_factors", models.JSONField(blank=True, default=list)),
                ("narrative_risk_summary", models.TextField(blank=True)),
                (
                    "liquidity_risk",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "volatility_or_momentum_risk",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "confidence_risk",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "provider_risk",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "runtime_risk",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("safety_context", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_agent_assessments",
                        to="markets.market",
                    ),
                ),
                (
                    "prediction_score",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_agent_assessments",
                        to="prediction_agent.predictionscore",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_agent_assessments",
                        to="proposal_engine.tradeproposal",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RiskSizingDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base_quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "adjusted_quantity",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "sizing_mode",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("heuristic", "Heuristic"),
                            ("kelly_like", "Kelly-like"),
                            ("capped", "Capped"),
                        ],
                        default="heuristic",
                        max_length=16,
                    ),
                ),
                ("sizing_rationale", models.TextField(blank=True)),
                (
                    "max_exposure_allowed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "reserve_cash_considered",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "confidence_adjustment",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=8
                    ),
                ),
                (
                    "liquidity_adjustment",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=8
                    ),
                ),
                (
                    "safety_adjustment",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=8
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "risk_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizing_decisions",
                        to="risk_agent.riskassessment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
