# Generated by Django 5.1.4 on 2026-03-30 01:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0002_event_source_type_market_source_type"),
        (
            "prediction_agent",
            "0002_predictionruntimerun_predictionruntimecandidate_and_more",
        ),
        ("risk_agent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskRuntimeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("approved_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("reduced_size_count", models.PositiveIntegerField(default=0)),
                ("watch_required_count", models.PositiveIntegerField(default=0)),
                ("sent_to_execution_sim_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RiskRuntimeCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("market_provider", models.CharField(blank=True, max_length=64)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "calibrated_probability",
                    models.DecimalField(decimal_places=4, max_digits=7),
                ),
                ("adjusted_edge", models.DecimalField(decimal_places=4, max_digits=8)),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=4, max_digits=7),
                ),
                (
                    "uncertainty_score",
                    models.DecimalField(decimal_places=4, max_digits=7),
                ),
                (
                    "evidence_quality_score",
                    models.DecimalField(decimal_places=4, max_digits=7),
                ),
                (
                    "precedent_caution_score",
                    models.DecimalField(decimal_places=4, max_digits=7),
                ),
                (
                    "market_liquidity_context",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "time_to_resolution",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("predicted_status", models.CharField(blank=True, max_length=24)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_runtime_candidates",
                        to="markets.market",
                    ),
                ),
                (
                    "linked_prediction_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_runtime_candidates",
                        to="prediction_agent.predictionruntimeassessment",
                    ),
                ),
                (
                    "runtime_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="risk_agent.riskruntimerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RiskApprovalDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("APPROVED_REDUCED", "Approved reduced"),
                            ("BLOCKED", "Blocked"),
                            ("NEEDS_REVIEW", "Needs review"),
                        ],
                        max_length=24,
                    ),
                ),
                ("approval_rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                (
                    "risk_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=7
                    ),
                ),
                (
                    "max_allowed_exposure",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("watch_required", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_decision",
                        to="risk_agent.riskruntimecandidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RiskRuntimeRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            (
                                "APPROVE_FOR_PAPER_EXECUTION",
                                "Approve for paper execution",
                            ),
                            ("APPROVE_REDUCED_SIZE", "Approve reduced size"),
                            ("BLOCK_HIGH_RISK", "Block high risk"),
                            ("BLOCK_LOW_CONFIDENCE", "Block low confidence"),
                            ("BLOCK_POOR_LIQUIDITY", "Block poor liquidity"),
                            (
                                "REQUIRE_MANUAL_RISK_REVIEW",
                                "Require manual risk review",
                            ),
                            (
                                "SEND_TO_EXECUTION_SIMULATOR",
                                "Send to execution simulator",
                            ),
                            ("KEEP_ON_WATCH", "Keep on watch"),
                            ("REORDER_RISK_PRIORITY", "Reorder risk priority"),
                        ],
                        max_length=64,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="risk_agent.riskruntimecandidate",
                    ),
                ),
                (
                    "runtime_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="risk_agent.riskruntimerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RiskSizingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sizing_mode",
                    models.CharField(
                        choices=[
                            ("fixed_fraction", "Fixed fraction"),
                            ("bounded_kelly", "Bounded Kelly"),
                            ("capped_fractional_kelly", "Capped fractional Kelly"),
                            ("watch_only", "Watch only"),
                            ("no_trade", "No trade"),
                        ],
                        default="no_trade",
                        max_length=32,
                    ),
                ),
                (
                    "raw_size_fraction",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=8
                    ),
                ),
                (
                    "adjusted_size_fraction",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=8
                    ),
                ),
                ("cap_applied", models.BooleanField(default=False)),
                ("cap_reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "paper_notional_size",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("sizing_rationale", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_approval_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizing_plans",
                        to="risk_agent.riskapprovaldecision",
                    ),
                ),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizing_plans",
                        to="risk_agent.riskruntimecandidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PositionWatchPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "watch_status",
                    models.CharField(
                        choices=[
                            ("REQUIRED", "Required"),
                            ("OPTIONAL", "Optional"),
                            ("NOT_NEEDED", "Not needed"),
                        ],
                        default="OPTIONAL",
                        max_length=16,
                    ),
                ),
                ("watch_triggers", models.JSONField(blank=True, default=dict)),
                ("review_interval_hint", models.CharField(blank=True, max_length=64)),
                ("escalation_path", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_plans",
                        to="risk_agent.riskruntimecandidate",
                    ),
                ),
                (
                    "linked_sizing_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_plans",
                        to="risk_agent.risksizingplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="riskapprovaldecision",
            index=models.Index(
                fields=["approval_status", "-created_at"],
                name="risk_agent__approva_8d3c2c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="riskruntimecandidate",
            index=models.Index(
                fields=["runtime_run", "-created_at"],
                name="risk_agent__runtime_f73724_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="riskruntimecandidate",
            index=models.Index(
                fields=["linked_market", "-created_at"],
                name="risk_agent__linked__76e52c_idx",
            ),
        ),
    ]
