# Generated by Django 5.1.4 on 2026-04-01 23:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0002_event_source_type_market_source_type"),
        (
            "prediction_agent",
            "0003_predictionintakerun_predictionintakecandidate_and_more",
        ),
        ("risk_agent", "0002_riskruntimerun_riskruntimecandidate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskapprovaldecision",
            name="approval_confidence",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=7
            ),
        ),
        migrations.AddField(
            model_name="riskapprovaldecision",
            name="approval_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="riskruntimecandidate",
            name="context_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="riskruntimecandidate",
            name="conviction_bucket",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="riskruntimecandidate",
            name="intake_status",
            field=models.CharField(
                choices=[
                    ("READY_FOR_RISK_RUNTIME", "Ready for risk runtime"),
                    ("REDUCED_CONTEXT", "Reduced context"),
                    ("BLOCKED", "Blocked"),
                    ("INSUFFICIENT_CONTEXT", "Insufficient context"),
                ],
                default="INSUFFICIENT_CONTEXT",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="riskruntimecandidate",
            name="linked_feedback_context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="riskruntimecandidate",
            name="linked_portfolio_context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="riskruntimecandidate",
            name="linked_prediction_conviction_review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="risk_runtime_candidates",
                to="prediction_agent.predictionconvictionreview",
            ),
        ),
        migrations.AddField(
            model_name="riskruntimecandidate",
            name="linked_prediction_intake_candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="risk_runtime_candidates",
                to="prediction_agent.predictionintakecandidate",
            ),
        ),
        migrations.AddField(
            model_name="riskruntimecandidate",
            name="linked_risk_ready_prediction_handoff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="risk_runtime_candidates",
                to="prediction_agent.riskreadypredictionhandoff",
            ),
        ),
        migrations.AddField(
            model_name="riskruntimecandidate",
            name="market_probability",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=7
            ),
        ),
        migrations.AddField(
            model_name="riskruntimecandidate",
            name="portfolio_pressure_state",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="riskruntimecandidate",
            name="reason_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="riskruntimerun",
            name="considered_handoff_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="riskruntimerun",
            name="execution_ready_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="riskruntimerun",
            name="needs_review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="riskruntimecandidate",
            name="linked_prediction_assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_runtime_candidates",
                to="prediction_agent.predictionruntimeassessment",
            ),
        ),
        migrations.CreateModel(
            name="AutonomousExecutionReadiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "readiness_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("READY_REDUCED", "Ready reduced"),
                            ("WATCH_ONLY", "Watch only"),
                            ("BLOCKED", "Blocked"),
                            ("DEFERRED", "Deferred"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "readiness_confidence",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=7
                    ),
                ),
                ("readiness_summary", models.TextField(blank=True)),
                ("readiness_reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_approval_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_readiness",
                        to="risk_agent.riskapprovaldecision",
                    ),
                ),
                (
                    "linked_market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autonomous_execution_readiness",
                        to="markets.market",
                    ),
                ),
                (
                    "linked_sizing_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_readiness",
                        to="risk_agent.risksizingplan",
                    ),
                ),
                (
                    "linked_watch_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_readiness",
                        to="risk_agent.positionwatchplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RiskIntakeRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            (
                                "APPROVE_FOR_AUTONOMOUS_EXECUTION",
                                "Approve for autonomous execution",
                            ),
                            ("APPROVE_WITH_REDUCED_SIZE", "Approve with reduced size"),
                            ("BLOCK_FOR_RISK_POSTURE", "Block for risk posture"),
                            (
                                "BLOCK_FOR_PORTFOLIO_PRESSURE",
                                "Block for portfolio pressure",
                            ),
                            ("KEEP_ON_WATCH_ONLY", "Keep on watch only"),
                            (
                                "REQUIRE_MANUAL_RISK_REVIEW",
                                "Require manual risk review",
                            ),
                        ],
                        max_length=80,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "runtime_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_recommendations",
                        to="risk_agent.riskruntimerun",
                    ),
                ),
                (
                    "target_approval_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intake_recommendations",
                        to="risk_agent.riskapprovaldecision",
                    ),
                ),
                (
                    "target_intake_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intake_recommendations",
                        to="risk_agent.riskruntimecandidate",
                    ),
                ),
                (
                    "target_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_intake_recommendations",
                        to="markets.market",
                    ),
                ),
                (
                    "target_readiness",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intake_recommendations",
                        to="risk_agent.autonomousexecutionreadiness",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
