<<<<<<< HEAD
# Generated by Django 5.1.4 on 2026-03-29 05:09
=======
# Generated by Django 5.1.4 on 2026-03-29 04:58
>>>>>>> origin/main

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approval_center", "0001_initial"),
        ("autonomy_campaign", "0001_initial"),
        ("autonomy_operations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterventionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_campaign_count", models.PositiveIntegerField(default=0)),
                ("open_request_count", models.PositiveIntegerField(default=0)),
                ("approval_required_count", models.PositiveIntegerField(default=0)),
                ("ready_request_count", models.PositiveIntegerField(default=0)),
                ("blocked_request_count", models.PositiveIntegerField(default=0)),
                ("executed_recent_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CampaignInterventionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("operations_recommendation", "Operations recommendation"),
                            ("attention_signal", "Attention signal"),
                            ("manual", "Manual"),
                            ("incident_response", "Incident response"),
                        ],
<<<<<<< HEAD
                        max_length=32,
=======
                        max_length=40,
>>>>>>> origin/main
                    ),
                ),
                (
                    "requested_action",
                    models.CharField(
                        choices=[
                            ("PAUSE_CAMPAIGN", "Pause campaign"),
                            ("RESUME_CAMPAIGN", "Resume campaign"),
                            ("ESCALATE_TO_APPROVAL", "Escalate to approval"),
                            ("REVIEW_FOR_ABORT", "Review for abort"),
                            ("CLEAR_TO_CONTINUE", "Clear to continue"),
                        ],
<<<<<<< HEAD
                        max_length=32,
=======
                        max_length=40,
>>>>>>> origin/main
                    ),
                ),
                (
                    "request_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("APPROVAL_REQUIRED", "Approval required"),
                            ("READY", "Ready"),
                            ("EXECUTED", "Executed"),
                            ("REJECTED", "Rejected"),
                            ("BLOCKED", "Blocked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("severity", models.CharField(default="MEDIUM", max_length=12)),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("requested_by", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "approval_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intervention_requests",
                        to="approval_center.approvalrequest",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention_requests",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "linked_recommendation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intervention_requests",
                        to="autonomy_operations.operationsrecommendation",
                    ),
                ),
                (
                    "linked_signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intervention_requests",
                        to="autonomy_operations.campaignattentionsignal",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CampaignInterventionAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("pause", "Pause"),
                            ("resume", "Resume"),
                            ("escalate", "Escalate"),
                            ("abort_review", "Abort review"),
                            ("continue_clearance", "Continue clearance"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "action_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("EXECUTING", "Executing"),
                            ("EXECUTED", "Executed"),
                            ("BLOCKED", "Blocked"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("executed_by", models.CharField(blank=True, max_length=120)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_message", models.CharField(blank=True, max_length=255)),
                ("result_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention_actions",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "intervention_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="autonomy_intervention.campaigninterventionrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InterventionOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outcome_type",
                    models.CharField(
                        choices=[
                            ("CAMPAIGN_PAUSED", "Campaign paused"),
                            ("CAMPAIGN_RESUMED", "Campaign resumed"),
                            ("APPROVAL_OPENED", "Approval opened"),
                            ("ABORT_REVIEW_OPENED", "Abort review opened"),
                            ("CONTINUE_CONFIRMED", "Continue confirmed"),
                            ("NO_STATE_CHANGE", "No state change"),
                            ("ACTION_BLOCKED", "Action blocked"),
                            ("ACTION_FAILED", "Action failed"),
                        ],
                        max_length=32,
                    ),
                ),
<<<<<<< HEAD
                ("campaign_state_before", models.CharField(blank=True, max_length=24)),
                ("campaign_state_after", models.CharField(blank=True, max_length=24)),
=======
                ("campaign_state_before", models.CharField(blank=True, max_length=16)),
                ("campaign_state_after", models.CharField(blank=True, max_length=16)),
>>>>>>> origin/main
                ("summary", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="autonomy_intervention.campaigninterventionaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="campaigninterventionrequest",
            index=models.Index(
                fields=["request_status", "-created_at"],
                name="autonomy_in_request_b523e0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaigninterventionrequest",
            index=models.Index(
                fields=["campaign", "-created_at"],
                name="autonomy_in_campaig_dd78fa_idx",
            ),
        ),
        migrations.AddIndex(
<<<<<<< HEAD
            model_name="campaigninterventionrequest",
            index=models.Index(
                fields=["requested_action", "-created_at"],
                name="autonomy_in_request_d39b86_idx",
            ),
        ),
        migrations.AddIndex(
=======
>>>>>>> origin/main
            model_name="campaigninterventionaction",
            index=models.Index(
                fields=["action_status", "-created_at"],
                name="autonomy_in_action__9b1de2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaigninterventionaction",
            index=models.Index(
                fields=["campaign", "-created_at"],
                name="autonomy_in_campaig_f4f92f_idx",
            ),
        ),
<<<<<<< HEAD
        migrations.AddIndex(
            model_name="interventionoutcome",
            index=models.Index(
                fields=["outcome_type", "-created_at"],
                name="autonomy_in_outcome_1d4160_idx",
            ),
        ),
=======
>>>>>>> origin/main
    ]
