# Generated by Django 5.1.4 on 2026-03-29 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autonomy_campaign", "0001_initial"),
        ("memory_retrieval", "0002_agentprecedentuse"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloseoutRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("ready_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("requires_postmortem_count", models.PositiveIntegerField(default=0)),
                ("requires_memory_index_count", models.PositiveIntegerField(default=0)),
                (
                    "requires_roadmap_feedback_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("completed_closeout_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CampaignCloseoutReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("disposition_type", models.CharField(max_length=32)),
                (
                    "closeout_status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending review"),
                            ("READY", "Ready"),
                            ("APPROVAL_REQUIRED", "Approval required"),
                            ("COMPLETED", "Completed"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=24,
                    ),
                ),
                ("executive_summary", models.CharField(max_length=255)),
                ("lifecycle_summary", models.JSONField(blank=True, default=dict)),
                ("major_blockers", models.JSONField(blank=True, default=list)),
                ("incident_summary", models.JSONField(blank=True, default=dict)),
                ("intervention_summary", models.JSONField(blank=True, default=dict)),
                ("recovery_summary", models.JSONField(blank=True, default=dict)),
                ("final_outcome_summary", models.CharField(max_length=255)),
                ("requires_postmortem", models.BooleanField(default=False)),
                ("requires_memory_index", models.BooleanField(default=False)),
                ("requires_roadmap_feedback", models.BooleanField(default=False)),
                (
                    "linked_postmortem_request",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "linked_feedback_artifact",
                    models.CharField(blank=True, max_length=120),
                ),
                ("closed_out_by", models.CharField(blank=True, max_length=120)),
                ("closed_out_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closeout_report",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "linked_memory_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomy_closeout_reports",
                        to="memory_retrieval.memorydocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CloseoutFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "finding_type",
                    models.CharField(
                        choices=[
                            ("success_factor", "Success factor"),
                            ("failure_mode", "Failure mode"),
                            ("blocker_pattern", "Blocker pattern"),
                            ("approval_friction", "Approval friction"),
                            ("rollout_lesson", "Rollout lesson"),
                            ("incident_lesson", "Incident lesson"),
                            ("recovery_lesson", "Recovery lesson"),
                            ("disposition_lesson", "Disposition lesson"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "severity_or_weight",
                    models.CharField(default="MEDIUM", max_length=16),
                ),
                ("summary", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("recommended_followup", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "closeout_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="autonomy_closeout.campaigncloseoutreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CloseoutRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("COMPLETE_CLOSEOUT", "Complete closeout"),
                            ("SEND_TO_POSTMORTEM", "Send to postmortem"),
                            ("INDEX_IN_MEMORY", "Index in memory"),
                            ("PREPARE_ROADMAP_FEEDBACK", "Prepare roadmap feedback"),
                            (
                                "REQUIRE_MANUAL_CLOSEOUT_REVIEW",
                                "Require manual closeout review",
                            ),
                            ("KEEP_OPEN_FOR_FOLLOWUP", "Keep open for follow up"),
                            ("REORDER_CLOSEOUT_PRIORITY", "Reorder closeout priority"),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("impacted_domains", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closeout_recommendations",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "closeout_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_closeout.closeoutrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="campaigncloseoutreport",
            index=models.Index(
                fields=["closeout_status", "-updated_at"],
                name="autonomy_cl_closeou_c49f47_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="closeoutfinding",
            index=models.Index(
                fields=["finding_type", "-created_at"],
                name="autonomy_cl_finding_805f90_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="closeoutrecommendation",
            index=models.Index(
                fields=["recommendation_type", "-created_at"],
                name="autonomy_cl_recomme_950442_idx",
            ),
        ),
    ]
