# Generated by Django 5.1.4 on 2026-03-24 16:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0001_initial"),
        ("paper_trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("STALE", "Stale"),
                            ("SUPERSEDED", "Superseded"),
                            ("REJECTED", "Rejected"),
                            ("EXECUTED", "Executed"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("BUY_YES", "Buy YES"),
                            ("BUY_NO", "Buy NO"),
                            ("HOLD", "Hold"),
                            ("AVOID", "Avoid"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "proposal_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                ("headline", models.CharField(max_length=255)),
                ("thesis", models.TextField()),
                ("rationale", models.TextField(blank=True)),
                (
                    "suggested_trade_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell"), ("HOLD", "Hold")], max_length=8
                    ),
                ),
                (
                    "suggested_side",
                    models.CharField(
                        blank=True,
                        choices=[("YES", "Yes"), ("NO", "No")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "suggested_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "suggested_price_reference",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "risk_decision",
                    models.CharField(
                        choices=[
                            ("APPROVE", "Approve"),
                            ("CAUTION", "Caution"),
                            ("BLOCK", "Block"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "policy_decision",
                    models.CharField(
                        choices=[
                            ("AUTO_APPROVE", "Auto approve"),
                            ("APPROVAL_REQUIRED", "Approval required"),
                            ("HARD_BLOCK", "Hard block"),
                        ],
                        max_length=24,
                    ),
                ),
                ("approval_required", models.BooleanField(default=False)),
                ("is_actionable", models.BooleanField(default=False)),
                ("recommendation", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_proposals",
                        to="markets.market",
                    ),
                ),
                (
                    "paper_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trade_proposals",
                        to="paper_trading.paperaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["market", "-created_at"],
                        name="proposal_en_market__0c93a4_idx",
                    ),
                    models.Index(
                        fields=["proposal_status", "-created_at"],
                        name="proposal_en_proposa_6710c4_idx",
                    ),
                    models.Index(
                        fields=["direction", "is_actionable"],
                        name="proposal_en_directi_dfe6fe_idx",
                    ),
                    models.Index(
                        fields=["policy_decision", "risk_decision"],
                        name="proposal_en_policy__42c62b_idx",
                    ),
                ],
            },
        ),
    ]
