# Generated by Django 5.1.4 on 2026-04-01 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0002_event_source_type_market_source_type"),
        ("opportunity_supervisor", "0002_opportunitycycleruntimerun_and_more"),
        ("paper_trading", "0001_initial"),
        (
            "prediction_agent",
            "0002_predictionruntimerun_predictionruntimecandidate_and_more",
        ),
        ("research_agent", "0006_marketuniverserun_marketresearchcandidate_and_more"),
        ("risk_agent", "0002_riskruntimerun_riskruntimecandidate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousTradeCycleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cycle_mode",
                    models.CharField(
                        choices=[
                            ("SCAN_TO_WATCH", "Scan to watch"),
                            ("SCAN_TO_PAPER_EXECUTION", "Scan to paper execution"),
                            ("WATCH_ONLY", "Watch only"),
                            (
                                "FULL_AUTONOMOUS_PAPER_LOOP",
                                "Full autonomous paper loop",
                            ),
                        ],
                        default="FULL_AUTONOMOUS_PAPER_LOOP",
                        max_length=40,
                    ),
                ),
                ("considered_candidate_count", models.PositiveIntegerField(default=0)),
                ("watchlist_count", models.PositiveIntegerField(default=0)),
                (
                    "approved_for_execution_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("executed_paper_trade_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("closed_position_count", models.PositiveIntegerField(default=0)),
                ("postmortem_handoff_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousTradeCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate_status",
                    models.CharField(
                        choices=[
                            ("WATCH", "Watch"),
                            ("EXECUTION_READY", "Execution ready"),
                            ("BLOCKED", "Blocked"),
                            ("LOW_CONVICTION", "Low conviction"),
                            ("NEEDS_REVIEW", "Needs review"),
                        ],
                        default="NEEDS_REVIEW",
                        max_length=24,
                    ),
                ),
                (
                    "system_probability",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "market_probability",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "adjusted_edge",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                ("risk_posture", models.CharField(blank=True, max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autonomous_trade_candidates",
                        to="markets.market",
                    ),
                ),
                (
                    "linked_opportunity_signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_trade_candidates",
                        to="opportunity_supervisor.opportunityrecommendation",
                    ),
                ),
                (
                    "linked_prediction_recommendation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_trade_candidates",
                        to="prediction_agent.predictionruntimerecommendation",
                    ),
                ),
                (
                    "linked_research_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_trade_candidates",
                        to="research_agent.marketresearchcandidate",
                    ),
                ),
                (
                    "linked_risk_recommendation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_trade_candidates",
                        to="risk_agent.riskruntimerecommendation",
                    ),
                ),
                (
                    "linked_scan_signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_trade_candidates",
                        to="research_agent.narrativesignal",
                    ),
                ),
                (
                    "cycle_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="autonomous_trader.autonomoustradecyclerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousTradeDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("KEEP_ON_WATCH", "Keep on watch"),
                            ("EXECUTE_PAPER_TRADE", "Execute paper trade"),
                            ("BLOCK_BY_RISK", "Block by risk"),
                            ("BLOCK_BY_POLICY", "Block by policy"),
                            ("BLOCK_BY_RUNTIME", "Block by runtime"),
                            ("SKIP_LOW_EDGE", "Skip low edge"),
                            ("SKIP_LOW_CONFIDENCE", "Skip low confidence"),
                            (
                                "SEND_TO_POSTMORTEM_ON_CLOSE",
                                "Send to postmortem on close",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("EXECUTED", "Executed"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=16,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="autonomous_trader.autonomoustradecandidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousTradeExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SUBMITTED", "Submitted"),
                            ("FILLED", "Filled"),
                            ("PARTIAL", "Partial"),
                            ("NO_FILL", "No fill"),
                            ("CANCELLED", "Cancelled"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("sizing_summary", models.CharField(blank=True, max_length=255)),
                ("watch_plan_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="autonomous_trader.autonomoustradecandidate",
                    ),
                ),
                (
                    "linked_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="autonomous_trader.autonomoustradedecision",
                    ),
                ),
                (
                    "linked_paper_trade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_trade_executions",
                        to="paper_trading.papertrade",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousTradeWatchRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "watch_status",
                    models.CharField(
                        choices=[
                            ("OPEN_MONITORING", "Open monitoring"),
                            ("REDUCE_SIGNAL", "Reduce signal"),
                            ("CLOSE_SIGNAL", "Close signal"),
                            ("HOLD_SIGNAL", "Hold signal"),
                            ("EXIT_REVIEW_REQUIRED", "Exit review required"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN_MONITORING",
                        max_length=24,
                    ),
                ),
                ("sentiment_shift_detected", models.BooleanField(default=False)),
                ("market_move_detected", models.BooleanField(default=False)),
                ("risk_change_detected", models.BooleanField(default=False)),
                ("watch_notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_records",
                        to="autonomous_trader.autonomoustradeexecution",
                    ),
                ),
                (
                    "linked_position_watch_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_trade_watch_records",
                        to="risk_agent.positionwatchplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousTradeOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outcome_type",
                    models.CharField(
                        choices=[
                            ("PROFITABLE_EXIT", "Profitable exit"),
                            ("LOSS_EXIT", "Loss exit"),
                            ("MANUAL_STOP", "Manual stop"),
                            ("NO_ACTION", "No action"),
                            ("EXPIRED_NO_TRADE", "Expired no trade"),
                            ("BLOCKED_PRE_TRADE", "Blocked pre trade"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "outcome_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("DEFERRED", "Deferred"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("outcome_summary", models.CharField(blank=True, max_length=255)),
                ("send_to_postmortem", models.BooleanField(default=False)),
                ("send_to_learning", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="autonomous_trader.autonomoustradeexecution",
                    ),
                ),
                (
                    "linked_watch_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outcomes",
                        to="autonomous_trader.autonomoustradewatchrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
