# Generated by Django 5.1.4 on 2026-04-01 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autonomous_trader", "0001_initial"),
        (
            "learning_memory",
            "0003_failurepattern_postmortemlearningadjustment_and_more",
        ),
        ("postmortem_agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousOutcomeHandoffRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_outcome_count", models.PositiveIntegerField(default=0)),
                ("eligible_postmortem_count", models.PositiveIntegerField(default=0)),
                ("eligible_learning_count", models.PositiveIntegerField(default=0)),
                (
                    "postmortem_handoff_created_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "learning_handoff_created_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("duplicate_skipped_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousLearningHandoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "handoff_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("EMITTED", "Emitted"),
                            ("DUPLICATE_SKIPPED", "Duplicate skipped"),
                            ("BLOCKED", "Blocked"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                (
                    "trigger_reason",
                    models.CharField(
                        choices=[
                            ("LOSS_REVIEW_COMPLETED", "Loss review completed"),
                            (
                                "PROFITABLE_PATTERN_CAPTURE",
                                "Profitable pattern capture",
                            ),
                            ("MONITORING_LESSON", "Monitoring lesson"),
                            ("NO_ACTION_LESSON", "No action lesson"),
                        ],
                        max_length=40,
                    ),
                ),
                ("handoff_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_learning_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_handoffs",
                        to="learning_memory.postmortemlearningrun",
                    ),
                ),
                (
                    "linked_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_handoffs",
                        to="autonomous_trader.autonomoustradeoutcome",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousPostmortemHandoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "handoff_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("EMITTED", "Emitted"),
                            ("DUPLICATE_SKIPPED", "Duplicate skipped"),
                            ("BLOCKED", "Blocked"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                (
                    "trigger_reason",
                    models.CharField(
                        choices=[
                            ("LOSS_EXIT", "Loss exit"),
                            ("EXIT_REVIEW_REQUIRED", "Exit review required"),
                            ("RISK_DRIFT", "Risk drift"),
                            ("SENTIMENT_REVERSAL", "Sentiment reversal"),
                            ("MANUAL_STOP", "Manual stop"),
                        ],
                        max_length=32,
                    ),
                ),
                ("handoff_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="postmortem_handoffs",
                        to="autonomous_trader.autonomoustradecandidate",
                    ),
                ),
                (
                    "linked_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="postmortem_handoffs",
                        to="autonomous_trader.autonomoustradeexecution",
                    ),
                ),
                (
                    "linked_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postmortem_handoffs",
                        to="autonomous_trader.autonomoustradeoutcome",
                    ),
                ),
                (
                    "linked_postmortem_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_handoffs",
                        to="postmortem_agents.postmortemboardrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousOutcomeHandoffRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("SEND_TO_POSTMORTEM_NOW", "Send to postmortem now"),
                            ("WAIT_FOR_OUTCOME_CLOSURE", "Wait for outcome closure"),
                            ("SEND_TO_LEARNING_CAPTURE", "Send to learning capture"),
                            ("BLOCK_DUPLICATE_HANDOFF", "Block duplicate handoff"),
                            (
                                "REQUIRE_MANUAL_REVIEW_BEFORE_HANDOFF",
                                "Require manual review before handoff",
                            ),
                            ("CLOSE_FEEDBACK_LOOP", "Close feedback loop"),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0.5, max_digits=5),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_learning_handoff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomous_trader.autonomouslearninghandoff",
                    ),
                ),
                (
                    "target_outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handoff_recommendations",
                        to="autonomous_trader.autonomoustradeoutcome",
                    ),
                ),
                (
                    "target_postmortem_handoff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomous_trader.autonomouspostmortemhandoff",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="autonomouslearninghandoff",
            name="linked_postmortem_handoff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learning_handoffs",
                to="autonomous_trader.autonomouspostmortemhandoff",
            ),
        ),
        migrations.AddConstraint(
            model_name="autonomouspostmortemhandoff",
            constraint=models.UniqueConstraint(
                fields=("linked_outcome", "trigger_reason"),
                name="autonomous_unique_postmortem_handoff",
            ),
        ),
        migrations.AddConstraint(
            model_name="autonomouslearninghandoff",
            constraint=models.UniqueConstraint(
                fields=("linked_outcome", "trigger_reason"),
                name="autonomous_unique_learning_handoff",
            ),
        ),
    ]
