# Generated by Django 5.1.4 on 2026-04-01 19:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autonomous_trader", "0002_autonomousoutcomehandoffrun_and_more"),
        ("markets", "0002_event_source_type_market_source_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousFeedbackReuseRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_candidate_count", models.PositiveIntegerField(default=0)),
                ("retrieval_attempt_count", models.PositiveIntegerField(default=0)),
                ("retrieval_hit_count", models.PositiveIntegerField(default=0)),
                ("influence_applied_count", models.PositiveIntegerField(default=0)),
                ("watch_caution_count", models.PositiveIntegerField(default=0)),
                ("blocked_or_reduced_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousFeedbackCandidateContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "retrieval_status",
                    models.CharField(
                        choices=[
                            ("NO_RETRIEVAL", "No retrieval"),
                            ("NO_HITS", "No hits"),
                            ("HITS_FOUND", "Hits found"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="NO_RETRIEVAL",
                        max_length=20,
                    ),
                ),
                ("top_precedent_count", models.PositiveIntegerField(default=0)),
                ("top_failure_modes", models.JSONField(blank=True, default=list)),
                ("top_lessons", models.JSONField(blank=True, default=list)),
                ("context_summary", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_contexts",
                        to="autonomous_trader.autonomoustradecandidate",
                    ),
                ),
                (
                    "linked_cycle_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_candidate_contexts",
                        to="autonomous_trader.autonomoustradecyclerun",
                    ),
                ),
                (
                    "linked_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_contexts",
                        to="autonomous_trader.autonomoustradeexecution",
                    ),
                ),
                (
                    "linked_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_feedback_contexts",
                        to="markets.market",
                    ),
                ),
                (
                    "linked_reuse_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_contexts",
                        to="autonomous_trader.autonomousfeedbackreuserun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousFeedbackInfluenceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "influence_type",
                    models.CharField(
                        choices=[
                            ("CONTEXT_ONLY", "Context only"),
                            ("CAUTION_BOOST", "Caution boost"),
                            ("CONFIDENCE_REDUCTION", "Confidence reduction"),
                            ("WATCH_PRIORITY_UP", "Watch priority up"),
                            ("BLOCK_REPEAT_PATTERN", "Block repeat pattern"),
                            ("RATIONALE_ENRICHMENT", "Rationale enrichment"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "influence_status",
                    models.CharField(
                        choices=[
                            ("SUGGESTED", "Suggested"),
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="SUGGESTED",
                        max_length=16,
                    ),
                ),
                ("influence_reason_codes", models.JSONField(blank=True, default=list)),
                ("influence_summary", models.TextField(blank=True)),
                (
                    "pre_adjust_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "post_adjust_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_influence_records",
                        to="autonomous_trader.autonomoustradecandidate",
                    ),
                ),
                (
                    "linked_candidate_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="influence_records",
                        to="autonomous_trader.autonomousfeedbackcandidatecontext",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousFeedbackRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("APPLY_CAUTION_BOOST", "Apply caution boost"),
                            (
                                "REDUCE_CONFIDENCE_FOR_REPEAT_PATTERN",
                                "Reduce confidence for repeat pattern",
                            ),
                            (
                                "KEEP_ON_WATCH_WITH_MEMORY_CONTEXT",
                                "Keep on watch with memory context",
                            ),
                            ("BLOCK_REPEAT_LOSS_PATTERN", "Block repeat loss pattern"),
                            (
                                "REQUIRE_MANUAL_REVIEW_FOR_MEMORY_CONFLICT",
                                "Require manual review for memory conflict",
                            ),
                            (
                                "NO_RELEVANT_LEARNING_FOUND",
                                "No relevant learning found",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0.5, max_digits=5),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_recommendations",
                        to="autonomous_trader.autonomoustradecandidate",
                    ),
                ),
                (
                    "target_context",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomous_trader.autonomousfeedbackcandidatecontext",
                    ),
                ),
                (
                    "target_influence_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomous_trader.autonomousfeedbackinfluencerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
