# Generated by Django 5.1.4 on 2026-04-01 20:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocation_engine", "0001_initial"),
        ("autonomous_trader", "0003_autonomousfeedbackreuserun_and_more"),
        ("portfolio_governor", "0001_initial"),
        (
            "prediction_agent",
            "0002_predictionruntimerun_predictionruntimecandidate_and_more",
        ),
        ("risk_agent", "0002_riskruntimerun_riskruntimecandidate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousSizingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_candidate_count", models.PositiveIntegerField(default=0)),
                ("approved_for_sizing_count", models.PositiveIntegerField(default=0)),
                ("reduced_by_portfolio_count", models.PositiveIntegerField(default=0)),
                ("reduced_by_risk_count", models.PositiveIntegerField(default=0)),
                ("blocked_for_sizing_count", models.PositiveIntegerField(default=0)),
                ("sized_for_execution_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousSizingContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system_probability",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "market_probability",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "adjusted_edge",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "uncertainty",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("risk_posture", models.CharField(blank=True, max_length=32)),
                ("portfolio_posture", models.CharField(blank=True, max_length=32)),
                (
                    "context_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("REDUCED", "Reduced"),
                            ("BLOCKED", "Blocked"),
                            ("INSUFFICIENT_CONTEXT", "Insufficient context"),
                        ],
                        default="INSUFFICIENT_CONTEXT",
                        max_length=32,
                    ),
                ),
                ("context_summary", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_allocation_context",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_sizing_contexts",
                        to="allocation_engine.allocationdecision",
                    ),
                ),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizing_contexts",
                        to="autonomous_trader.autonomoustradecandidate",
                    ),
                ),
                (
                    "linked_cycle_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizing_contexts",
                        to="autonomous_trader.autonomoustradecyclerun",
                    ),
                ),
                (
                    "linked_feedback_influence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sizing_contexts",
                        to="autonomous_trader.autonomousfeedbackinfluencerecord",
                    ),
                ),
                (
                    "linked_portfolio_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_sizing_contexts",
                        to="portfolio_governor.portfolioexposuresnapshot",
                    ),
                ),
                (
                    "linked_prediction_recommendation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_sizing_contexts",
                        to="prediction_agent.predictionruntimerecommendation",
                    ),
                ),
                (
                    "linked_risk_recommendation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_sizing_contexts",
                        to="risk_agent.riskruntimerecommendation",
                    ),
                ),
                (
                    "linked_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contexts",
                        to="autonomous_trader.autonomoussizingrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousSizingDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sizing_method",
                    models.CharField(
                        choices=[
                            ("FIXED_NOTIONAL", "Fixed notional"),
                            ("FRACTIONAL_KELLY", "Fractional Kelly"),
                            ("KELLY_CAPPED", "Kelly capped"),
                            ("RISK_REDUCED_FRACTIONAL", "Risk reduced fractional"),
                            ("PORTFOLIO_THROTTLED", "Portfolio throttled"),
                        ],
                        default="FIXED_NOTIONAL",
                        max_length=40,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPLIED", "Applied"),
                            ("REDUCED", "Reduced"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=16,
                    ),
                ),
                (
                    "base_kelly_fraction",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=8, null=True
                    ),
                ),
                (
                    "applied_fraction",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=8, null=True
                    ),
                ),
                (
                    "notional_before_adjustment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "notional_after_adjustment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "final_paper_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("adjustment_reason_codes", models.JSONField(blank=True, default=list)),
                ("decision_summary", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizing_decisions",
                        to="autonomous_trader.autonomoustradecandidate",
                    ),
                ),
                (
                    "linked_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizing_decisions",
                        to="autonomous_trader.autonomoussizingcontext",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="autonomoustradeexecution",
            name="linked_sizing_decision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executions",
                to="autonomous_trader.autonomoussizingdecision",
            ),
        ),
        migrations.CreateModel(
            name="AutonomousSizingRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            (
                                "APPLY_CAPPED_FRACTIONAL_KELLY",
                                "Apply capped fractional Kelly",
                            ),
                            (
                                "REDUCE_SIZE_FOR_LOW_CONFIDENCE",
                                "Reduce size for low confidence",
                            ),
                            (
                                "REDUCE_SIZE_FOR_PORTFOLIO_PRESSURE",
                                "Reduce size for portfolio pressure",
                            ),
                            (
                                "BLOCK_SIZE_FOR_RISK_POSTURE",
                                "Block size for risk posture",
                            ),
                            (
                                "USE_MINIMAL_FIXED_NOTIONAL",
                                "Use minimal fixed notional",
                            ),
                            (
                                "REQUIRE_MANUAL_REVIEW_FOR_SIZING_CONFLICT",
                                "Require manual review for sizing conflict",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0.5, max_digits=5),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sizing_recommendations",
                        to="autonomous_trader.autonomoustradecandidate",
                    ),
                ),
                (
                    "target_context",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomous_trader.autonomoussizingcontext",
                    ),
                ),
                (
                    "target_sizing_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomous_trader.autonomoussizingdecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
