# Generated by Django 5.1.4 on 2026-04-01 20:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "autonomous_trader",
            "0004_autonomoussizingrun_autonomoussizingcontext_and_more",
        ),
        ("markets", "0002_event_source_type_market_source_type"),
        ("paper_trading", "0001_initial"),
        ("research_agent", "0006_marketuniverserun_marketresearchcandidate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousPositionActionDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("HOLD_POSITION", "Hold position"),
                            ("REDUCE_POSITION", "Reduce position"),
                            ("CLOSE_POSITION", "Close position"),
                            ("REVIEW_REQUIRED", "Review required"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=16,
                    ),
                ),
                (
                    "decision_confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "reduction_fraction",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousPositionWatchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_position_count", models.PositiveIntegerField(default=0)),
                ("hold_count", models.PositiveIntegerField(default=0)),
                ("reduce_count", models.PositiveIntegerField(default=0)),
                ("close_count", models.PositiveIntegerField(default=0)),
                ("review_required_count", models.PositiveIntegerField(default=0)),
                ("executed_reduce_count", models.PositiveIntegerField(default=0)),
                ("executed_close_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousPositionActionExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "execution_type",
                    models.CharField(
                        choices=[
                            ("REDUCE_EXECUTION", "Reduce execution"),
                            ("CLOSE_EXECUTION", "Close execution"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SUBMITTED", "Submitted"),
                            ("FILLED", "Filled"),
                            ("PARTIAL", "Partial"),
                            ("NO_FILL", "No fill"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="QUEUED",
                        max_length=12,
                    ),
                ),
                (
                    "quantity_before",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "quantity_after",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "notional_before",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "notional_after",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_action_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="autonomous_trader.autonomouspositionactiondecision",
                    ),
                ),
                (
                    "linked_paper_trade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_action_executions",
                        to="paper_trading.papertrade",
                    ),
                ),
                (
                    "linked_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_action_executions",
                        to="paper_trading.paperposition",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousPositionWatchCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE_MONITORING", "Active monitoring"),
                            ("REDUCE_ELIGIBLE", "Reduce eligible"),
                            ("CLOSE_ELIGIBLE", "Close eligible"),
                            ("REVIEW_REQUIRED", "Review required"),
                            ("NO_ACTION", "No action"),
                        ],
                        default="ACTIVE_MONITORING",
                        max_length=24,
                    ),
                ),
                (
                    "entry_probability",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "current_probability",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "entry_edge",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "current_edge",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "sentiment_state",
                    models.CharField(
                        choices=[
                            ("IMPROVING", "Improving"),
                            ("STABLE", "Stable"),
                            ("WEAKENING", "Weakening"),
                            ("REVERSING", "Reversing"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                (
                    "risk_state",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("ELEVATED", "Elevated"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="NORMAL",
                        max_length=16,
                    ),
                ),
                (
                    "portfolio_pressure_state",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCK_NEW_ENTRIES", "Block new entries"),
                        ],
                        default="NORMAL",
                        max_length=24,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_autonomous_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="position_watch_candidates",
                        to="autonomous_trader.autonomoustradeexecution",
                    ),
                ),
                (
                    "linked_latest_research_context",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_watch_candidates",
                        to="research_agent.marketresearchcandidate",
                    ),
                ),
                (
                    "linked_latest_scan_signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_watch_candidates",
                        to="research_agent.narrativesignal",
                    ),
                ),
                (
                    "linked_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_watch_candidates",
                        to="markets.market",
                    ),
                ),
                (
                    "linked_paper_trade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_watch_candidates",
                        to="paper_trading.papertrade",
                    ),
                ),
                (
                    "linked_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_watch_candidates",
                        to="paper_trading.paperposition",
                    ),
                ),
                (
                    "linked_watch_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="autonomous_trader.autonomouspositionwatchrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="autonomouspositionactiondecision",
            name="linked_watch_candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_decisions",
                to="autonomous_trader.autonomouspositionwatchcandidate",
            ),
        ),
        migrations.CreateModel(
            name="AutonomousPositionWatchRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("KEEP_HOLDING_POSITION", "Keep holding position"),
                            (
                                "REDUCE_FOR_SENTIMENT_WEAKENING",
                                "Reduce for sentiment weakening",
                            ),
                            (
                                "CLOSE_FOR_NARRATIVE_REVERSAL",
                                "Close for narrative reversal",
                            ),
                            (
                                "REDUCE_FOR_PORTFOLIO_PRESSURE",
                                "Reduce for portfolio pressure",
                            ),
                            (
                                "CLOSE_FOR_RISK_DETERIORATION",
                                "Close for risk deterioration",
                            ),
                            (
                                "REQUIRE_MANUAL_REVIEW_FOR_SIGNAL_CONFLICT",
                                "Require manual review for signal conflict",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0.5, max_digits=5),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_action_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomous_trader.autonomouspositionactiondecision",
                    ),
                ),
                (
                    "target_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_watch_recommendations",
                        to="paper_trading.paperposition",
                    ),
                ),
                (
                    "target_watch_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomous_trader.autonomouspositionwatchcandidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
