# Generated by Django 5.1.4 on 2026-04-01 23:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autonomous_trader", "0005_autonomouspositionactiondecision_and_more"),
        ("markets", "0002_event_source_type_market_source_type"),
        ("paper_trading", "0001_initial"),
        ("risk_agent", "0003_riskapprovaldecision_approval_confidence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousExecutionDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("EXECUTE_NOW", "Execute now"),
                            ("EXECUTE_REDUCED", "Execute reduced"),
                            ("KEEP_ON_WATCH", "Keep on watch"),
                            ("DEFER", "Defer"),
                            ("BLOCK", "Block"),
                            ("REQUIRE_MANUAL_REVIEW", "Require manual review"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=16,
                    ),
                ),
                (
                    "decision_confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousDispatchRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dispatch_status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("DISPATCHED", "Dispatched"),
                            ("FILLED", "Filled"),
                            ("PARTIAL", "Partial"),
                            ("NO_FILL", "No fill"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                (
                    "dispatch_mode",
                    models.CharField(
                        choices=[
                            ("PAPER_EXECUTION", "Paper execution"),
                            ("PAPER_REDUCED_EXECUTION", "Paper reduced execution"),
                        ],
                        default="PAPER_EXECUTION",
                        max_length=32,
                    ),
                ),
                (
                    "dispatched_notional",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "dispatched_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("dispatch_summary", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_paper_trade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_dispatch_records",
                        to="paper_trading.papertrade",
                    ),
                ),
                (
                    "linked_trade_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_records",
                        to="autonomous_trader.autonomoustradeexecution",
                    ),
                ),
                (
                    "linked_execution_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_records",
                        to="autonomous_trader.autonomousexecutiondecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousExecutionIntakeCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_prediction_context",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "linked_portfolio_context",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "intake_status",
                    models.CharField(
                        choices=[
                            (
                                "READY_FOR_AUTONOMOUS_EXECUTION",
                                "Ready for autonomous execution",
                            ),
                            ("READY_REDUCED", "Ready reduced"),
                            ("WATCH_ONLY", "Watch only"),
                            ("DEFERRED", "Deferred"),
                            ("BLOCKED", "Blocked"),
                            ("INSUFFICIENT_CONTEXT", "Insufficient context"),
                        ],
                        default="INSUFFICIENT_CONTEXT",
                        max_length=40,
                    ),
                ),
                (
                    "readiness_confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                ("approval_status", models.CharField(blank=True, max_length=24)),
                ("sizing_method", models.CharField(blank=True, max_length=48)),
                ("execution_context_summary", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_approval_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_intake_candidates",
                        to="risk_agent.riskapprovaldecision",
                    ),
                ),
                (
                    "linked_execution_readiness",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_intake_candidates",
                        to="risk_agent.autonomousexecutionreadiness",
                    ),
                ),
                (
                    "linked_market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autonomous_execution_intake_candidates",
                        to="markets.market",
                    ),
                ),
                (
                    "linked_sizing_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_intake_candidates",
                        to="risk_agent.risksizingplan",
                    ),
                ),
                (
                    "linked_watch_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_intake_candidates",
                        to="risk_agent.positionwatchplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="autonomousexecutiondecision",
            name="linked_intake_candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="execution_decisions",
                to="autonomous_trader.autonomousexecutionintakecandidate",
            ),
        ),
        migrations.CreateModel(
            name="AutonomousExecutionIntakeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_readiness_count", models.PositiveIntegerField(default=0)),
                ("execute_now_count", models.PositiveIntegerField(default=0)),
                ("execute_reduced_count", models.PositiveIntegerField(default=0)),
                ("watch_count", models.PositiveIntegerField(default=0)),
                ("defer_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("manual_review_count", models.PositiveIntegerField(default=0)),
                ("dispatch_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_cycle_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_intake_runs",
                        to="autonomous_trader.autonomoustradecyclerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="autonomousexecutionintakecandidate",
            name="intake_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intake_candidates",
                to="autonomous_trader.autonomousexecutionintakerun",
            ),
        ),
        migrations.CreateModel(
            name="AutonomousExecutionRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("AUTO_EXECUTE_NOW", "Auto execute now"),
                            ("AUTO_EXECUTE_REDUCED", "Auto execute reduced"),
                            ("KEEP_ON_AUTONOMOUS_WATCH", "Keep on autonomous watch"),
                            (
                                "DEFER_FOR_WEAKER_READINESS",
                                "Defer for weaker readiness",
                            ),
                            (
                                "BLOCK_FOR_POLICY_OR_RUNTIME",
                                "Block for policy or runtime",
                            ),
                            (
                                "REQUIRE_MANUAL_REVIEW_FOR_EXECUTION_CONFLICT",
                                "Require manual review for execution conflict",
                            ),
                        ],
                        max_length=72,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_intake_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="autonomous_trader.autonomousexecutionintakerun",
                    ),
                ),
                (
                    "target_dispatch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomous_trader.autonomousdispatchrecord",
                    ),
                ),
                (
                    "target_execution_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomous_trader.autonomousexecutiondecision",
                    ),
                ),
                (
                    "target_intake_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomous_trader.autonomousexecutionintakecandidate",
                    ),
                ),
                (
                    "target_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomous_execution_recommendations",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
