# Generated by Django 5.1.4 on 2026-03-29 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approval_center", "0001_initial"),
        ("autonomy_campaign", "0001_initial"),
        ("autonomy_closeout", "0001_initial"),
        ("memory_retrieval", "0002_agentprecedentuse"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowupRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("ready_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("emitted_count", models.PositiveIntegerField(default=0)),
                ("duplicate_skipped_count", models.PositiveIntegerField(default=0)),
                ("memory_followup_count", models.PositiveIntegerField(default=0)),
                ("postmortem_followup_count", models.PositiveIntegerField(default=0)),
                ("roadmap_feedback_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CampaignFollowup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "followup_type",
                    models.CharField(
                        choices=[
                            ("MEMORY_INDEX", "Memory index"),
                            ("POSTMORTEM_REQUEST", "Postmortem request"),
                            ("ROADMAP_FEEDBACK", "Roadmap feedback"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "followup_status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending review"),
                            ("READY", "Ready"),
                            ("EMITTED", "Emitted"),
                            ("BLOCKED", "Blocked"),
                            ("DUPLICATE_SKIPPED", "Duplicate skipped"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=24,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("emitted_by", models.CharField(blank=True, max_length=120)),
                ("emitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "linked_feedback_artifact",
                    models.CharField(blank=True, max_length=120),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "closeout_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="autonomy_closeout.campaigncloseoutreport",
                    ),
                ),
                (
                    "linked_memory_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomy_followups",
                        to="memory_retrieval.memorydocument",
                    ),
                ),
                (
                    "linked_postmortem_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomy_followups",
                        to="approval_center.approvalrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["followup_status", "-updated_at"],
                        name="autonomy_fo_followu_b47c57_idx",
                    ),
                    models.Index(
                        fields=["followup_type", "-updated_at"],
                        name="autonomy_fo_followu_940aa6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FollowupRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("EMIT_MEMORY_INDEX", "Emit memory index"),
                            ("EMIT_POSTMORTEM_REQUEST", "Emit postmortem request"),
                            ("EMIT_ROADMAP_FEEDBACK", "Emit roadmap feedback"),
                            ("SKIP_DUPLICATE_FOLLOWUP", "Skip duplicate followup"),
                            ("REQUIRE_MANUAL_REVIEW", "Require manual review"),
                            ("KEEP_PENDING", "Keep pending"),
                            ("REORDER_FOLLOWUP_PRIORITY", "Reorder followup priority"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "followup_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MEMORY_INDEX", "Memory index"),
                            ("POSTMORTEM_REQUEST", "Postmortem request"),
                            ("ROADMAP_FEEDBACK", "Roadmap feedback"),
                        ],
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="followup_recommendations",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "followup_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_followup.followuprun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recommendation_type", "-created_at"],
                        name="autonomy_fo_recomme_2d1072_idx",
                    )
                ],
            },
        ),
    ]
