# Generated by Django 5.1.4 on 2026-03-27 00:25

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0002_event_source_type_market_source_type"),
        ("paper_trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperOrderLifecycleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("orders_reviewed", models.PositiveIntegerField(default=0)),
                ("orders_open", models.PositiveIntegerField(default=0)),
                ("orders_filled", models.PositiveIntegerField(default=0)),
                ("orders_partial", models.PositiveIntegerField(default=0)),
                ("orders_cancelled", models.PositiveIntegerField(default=0)),
                ("orders_expired", models.PositiveIntegerField(default=0)),
                ("no_fill_attempts", models.PositiveIntegerField(default=0)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaperOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "side",
                    models.CharField(
                        choices=[
                            ("BUY_YES", "Buy Yes"),
                            ("BUY_NO", "Buy No"),
                            ("SELL_YES", "Sell Yes"),
                            ("SELL_NO", "Sell No"),
                            ("REDUCE", "Reduce"),
                            ("CLOSE", "Close"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "requested_quantity",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "remaining_quantity",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("market_like", "Market-like"),
                            ("limit_like", "Limit-like"),
                            ("close_order", "Close order"),
                        ],
                        default="market_like",
                        max_length=16,
                    ),
                ),
                (
                    "requested_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "created_from",
                    models.CharField(
                        choices=[
                            ("opportunity_supervisor", "Opportunity supervisor"),
                            ("position_manager", "Position manager"),
                            ("operator_queue", "Operator queue"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("PARTIALLY_FILLED", "Partially filled"),
                            ("FILLED", "Filled"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "effective_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("wait_cycles", models.PositiveIntegerField(default=0)),
                ("max_wait_cycles", models.PositiveIntegerField(default=3)),
                ("cancel_after_n_cycles", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paper_orders",
                        to="markets.market",
                    ),
                ),
                (
                    "paper_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_orders",
                        to="paper_trading.paperaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaperFill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fill_quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                ("fill_price", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "fill_type",
                    models.CharField(
                        choices=[("full", "Full"), ("partial", "Partial")],
                        max_length=12,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "paper_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fills",
                        to="execution_simulator.paperorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaperExecutionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt_status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("NO_FILL", "No fill"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "market_price_snapshot",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "effective_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "filled_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                (
                    "slippage_bps",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "paper_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="execution_simulator.paperorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="paperorder",
            index=models.Index(
                fields=["paper_account", "status"],
                name="execution_s_paper_a_1c2e18_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paperorder",
            index=models.Index(
                fields=["market", "status"], name="execution_s_market__e3c8cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paperorder",
            index=models.Index(
                fields=["created_from", "status"], name="execution_s_created_e5cdd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paperfill",
            index=models.Index(
                fields=["paper_order", "created_at"],
                name="execution_s_paper_o_d15028_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paperexecutionattempt",
            index=models.Index(
                fields=["paper_order", "attempt_status"],
                name="execution_s_paper_o_ae3fba_idx",
            ),
        ),
    ]
