# Generated by Django 5.1.4 on 2026-03-25 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("operator_alerts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("ui_only", "UI only"),
                            ("email", "Email"),
                            ("webhook", "Webhook"),
                            ("telegram", "Telegram"),
                            ("discord", "Discord"),
                            ("slack", "Slack"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="NotificationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("is_enabled", models.BooleanField(default=True)),
                ("match_criteria", models.JSONField(blank=True, default=dict)),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("digest", "Digest"),
                            ("escalation", "Escalation"),
                            ("escalation_only", "Escalation only"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                (
                    "severity_threshold",
                    models.CharField(default="warning", max_length=12),
                ),
                ("cooldown_seconds", models.PositiveIntegerField(default=900)),
                ("dedupe_window_seconds", models.PositiveIntegerField(default=600)),
                (
                    "channels",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rules",
                        to="notification_center.notificationchannel",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                            ("SUPPRESSED", "Suppressed"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("digest", "Digest"),
                            ("escalation", "Escalation"),
                            ("escalation_only", "Escalation only"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("payload_preview", models.JSONField(blank=True, default=dict)),
                ("response_metadata", models.JSONField(blank=True, default=dict)),
                ("fingerprint", models.CharField(blank=True, max_length=255)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="notification_center.notificationchannel",
                    ),
                ),
                (
                    "related_alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_deliveries",
                        to="operator_alerts.operatoralert",
                    ),
                ),
                (
                    "related_digest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_deliveries",
                        to="operator_alerts.operatordigest",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="notification_center.notificationrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["delivery_status", "-created_at"],
                        name="notificatio_deliver_3c0163_idx",
                    ),
                    models.Index(
                        fields=["fingerprint", "-created_at"],
                        name="notificatio_fingerp_dce913_idx",
                    ),
                    models.Index(
                        fields=["related_alert", "-created_at"],
                        name="notificatio_related_edef4b_idx",
                    ),
                    models.Index(
                        fields=["related_digest", "-created_at"],
                        name="notificatio_related_e58806_idx",
                    ),
                ],
            },
        ),
    ]
