# Generated by Django 5.1.4 on 2026-03-25 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification_center", "0001_initial"),
        ("operator_alerts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationAutomationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("automatic_dispatch_enabled", models.BooleanField(default=True)),
                ("automatic_digest_enabled", models.BooleanField(default=True)),
                ("escalation_enabled", models.BooleanField(default=True)),
                ("suppress_info_alerts_by_default", models.BooleanField(default=True)),
                ("digest_interval_minutes", models.PositiveIntegerField(default=60)),
                ("escalation_after_minutes", models.PositiveIntegerField(default=30)),
                (
                    "max_auto_notifications_per_window",
                    models.PositiveIntegerField(default=40),
                ),
                ("automation_window_minutes", models.PositiveIntegerField(default=60)),
                (
                    "last_automatic_dispatch_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_digest_cycle_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_escalation_cycle_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationEscalationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("severity", models.CharField(max_length=12)),
                ("reason", models.CharField(max_length=255)),
                ("status", models.CharField(default="TRIGGERED", max_length=16)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="trigger_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("automatic", "Automatic"),
                    ("digest_automation", "Digest automation"),
                    ("escalation", "Escalation"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["trigger_source", "-created_at"],
                name="notificatio_trigger_306be9_idx",
            ),
        ),
        migrations.AddField(
            model_name="notificationescalationevent",
            name="alert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_escalations",
                to="operator_alerts.operatoralert",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationescalationevent",
            index=models.Index(
                fields=["status", "-created_at"], name="notificatio_status_b435c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationescalationevent",
            index=models.Index(
                fields=["severity", "-created_at"],
                name="notificatio_severit_4bd382_idx",
            ),
        ),
    ]
