# Generated by Django 5.1.4 on 2026-03-29 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autonomy_campaign", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("UPCOMING", "Upcoming"),
                            ("CLOSED", "Closed"),
                            ("FROZEN", "Frozen"),
                        ],
                        default="UPCOMING",
                        max_length=12,
                    ),
                ),
                (
                    "window_type",
                    models.CharField(
                        choices=[
                            ("normal_change", "Normal change"),
                            ("cautious_change", "Cautious change"),
                            ("observation_only", "Observation only"),
                            ("freeze_window", "Freeze window"),
                        ],
                        default="normal_change",
                        max_length=24,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("max_new_admissions", models.PositiveIntegerField(default=1)),
                ("allowed_postures", models.JSONField(blank=True, default=list)),
                ("blocked_domains", models.JSONField(blank=True, default=list)),
                ("rationale", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "starts_at"],
                        name="autonomy_sc_status_6e3347_idx",
                    ),
                    models.Index(
                        fields=["window_type", "-created_at"],
                        name="autonomy_sc_window__841009_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SchedulerRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("queue_counts", models.JSONField(blank=True, default=dict)),
                ("ready_campaigns", models.JSONField(blank=True, default=list)),
                ("blocked_campaigns", models.JSONField(blank=True, default=list)),
                ("deferred_campaigns", models.JSONField(blank=True, default=list)),
                (
                    "current_program_posture",
                    models.CharField(blank=True, max_length=20),
                ),
                ("max_admissible_starts", models.PositiveIntegerField(default=0)),
                ("recommendations_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "active_window",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduler_runs",
                        to="autonomy_scheduler.changewindow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CampaignAdmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("READY", "Ready"),
                            ("DEFERRED", "Deferred"),
                            ("BLOCKED", "Blocked"),
                            ("ADMITTED", "Admitted"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("roadmap_plan", "Roadmap plan"),
                            ("scenario_run", "Scenario run"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("priority_score", models.PositiveIntegerField(default=0)),
                ("readiness_score", models.PositiveIntegerField(default=0)),
                ("blocked_reasons", models.JSONField(blank=True, default=list)),
                ("admitted_at", models.DateTimeField(blank=True, null=True)),
                ("deferred_until", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission_record",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "requested_window",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_admissions",
                        to="autonomy_scheduler.changewindow",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority_score", "-readiness_score", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="autonomy_sc_status_ecf95f_idx",
                    ),
                    models.Index(
                        fields=["source_type", "-priority_score"],
                        name="autonomy_sc_source__93576e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdmissionRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("ADMIT_CAMPAIGN", "Admit campaign"),
                            ("DEFER_CAMPAIGN", "Defer campaign"),
                            ("HOLD_QUEUE", "Hold queue"),
                            ("WAIT_FOR_WINDOW", "Wait for window"),
                            ("REORDER_ADMISSION_QUEUE", "Reorder admission queue"),
                            ("SAFE_TO_ADMIT_NEXT", "Safe to admit next"),
                            ("BLOCK_ADMISSION", "Block admission"),
                            ("REQUIRE_APPROVAL_TO_ADMIT", "Require approval to admit"),
                        ],
                        max_length=36,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("impacted_domains", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admission_recommendations",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "recommended_window",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_scheduler.changewindow",
                    ),
                ),
                (
                    "scheduler_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_scheduler.schedulerrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recommendation_type", "-created_at"],
                        name="autonomy_sc_recomme_7fe9ba_idx",
                    )
                ],
            },
        ),
    ]
