# Generated by Django 5.1.4 on 2026-03-30 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certification_board", "0001_initial"),
        (
            "promotion_committee",
            "0004_rolloutexecutionrecord_postrolloutstatus_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificationCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_component", models.CharField(max_length=32)),
                ("target_scope", models.CharField(max_length=24)),
                ("rollout_status", models.CharField(max_length=24)),
                (
                    "stabilization_readiness",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("NEEDS_OBSERVATION", "Needs observation"),
                            ("REVIEW_REQUIRED", "Review required"),
                            ("ROLLBACK_RECOMMENDED", "Rollback recommended"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="NEEDS_OBSERVATION",
                        max_length=24,
                    ),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_post_rollout_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certification_candidates",
                        to="promotion_committee.postrolloutstatus",
                    ),
                ),
                (
                    "linked_promotion_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certification_candidates",
                        to="promotion_committee.promotioncase",
                    ),
                ),
                (
                    "linked_rollout_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certification_candidates",
                        to="promotion_committee.rolloutexecutionrecord",
                    ),
                ),
                (
                    "linked_rollout_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certification_candidates",
                        to="promotion_committee.manualrolloutplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CertificationEvidencePack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("summary", models.CharField(max_length=255)),
                (
                    "linked_checkpoint_outcomes",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "linked_post_rollout_statuses",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "linked_evaluation_metrics",
                    models.JSONField(blank=True, default=dict),
                ),
                ("sample_count", models.PositiveIntegerField(default=0)),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "stability_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "regression_risk_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "evidence_status",
                    models.CharField(
                        choices=[
                            ("STRONG", "Strong"),
                            ("MIXED", "Mixed"),
                            ("WEAK", "Weak"),
                            ("INSUFFICIENT", "Insufficient"),
                        ],
                        default="INSUFFICIENT",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_pack",
                        to="certification_board.certificationcandidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CertificationDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            (
                                "CERTIFIED_FOR_PAPER_BASELINE",
                                "Certified for paper baseline",
                            ),
                            ("KEEP_UNDER_OBSERVATION", "Keep under observation"),
                            ("REQUIRE_MANUAL_REVIEW", "Require manual review"),
                            ("RECOMMEND_ROLLBACK", "Recommend rollback"),
                            ("REJECT_CERTIFICATION", "Reject certification"),
                        ],
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("decided_by", models.CharField(blank=True, max_length=120)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision",
                        to="certification_board.certificationcandidate",
                    ),
                ),
                (
                    "linked_evidence_pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="certification_board.certificationevidencepack",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RolloutCertificationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("certified_count", models.PositiveIntegerField(default=0)),
                ("observation_count", models.PositiveIntegerField(default=0)),
                ("review_required_count", models.PositiveIntegerField(default=0)),
                ("rollback_recommended_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_rollout_execution_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certification_runs",
                        to="promotion_committee.rolloutexecutionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CertificationRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            (
                                "CERTIFY_FOR_PAPER_BASELINE",
                                "Certify for paper baseline",
                            ),
                            ("KEEP_UNDER_OBSERVATION", "Keep under observation"),
                            ("REQUIRE_MORE_OBSERVATION", "Require more observation"),
                            (
                                "REQUIRE_MANUAL_CERTIFICATION_REVIEW",
                                "Require manual certification review",
                            ),
                            ("RECOMMEND_MANUAL_ROLLBACK", "Recommend manual rollback"),
                            ("REJECT_CERTIFICATION", "Reject certification"),
                            (
                                "REORDER_CERTIFICATION_PRIORITY",
                                "Reorder certification priority",
                            ),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="certification_board.certificationcandidate",
                    ),
                ),
                (
                    "review_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="certification_board.rolloutcertificationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="certificationcandidate",
            name="review_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="certification_board.rolloutcertificationrun",
            ),
        ),
        migrations.AddIndex(
            model_name="certificationevidencepack",
            index=models.Index(
                fields=["evidence_status", "-created_at"],
                name="certificati_evidenc_7b05c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="certificationdecision",
            index=models.Index(
                fields=["decision_status", "-created_at"],
                name="certificati_decisio_9c9d3e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="certificationrecommendation",
            index=models.Index(
                fields=["recommendation_type", "-created_at"],
                name="certificati_recomme_9f6e89_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="certificationcandidate",
            index=models.Index(
                fields=["stabilization_readiness", "-created_at"],
                name="certificati_stabili_b9c329_idx",
            ),
        ),
    ]
