# Generated by Django 5.1.4 on 2026-03-30 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "certification_board",
            "0002_certificationcandidate_certificationevidencepack_and_more",
        ),
        (
            "promotion_committee",
            "0004_rolloutexecutionrecord_postrolloutstatus_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BaselineConfirmationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("ready_to_confirm_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("confirmed_count", models.PositiveIntegerField(default=0)),
                ("rollback_ready_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_certification_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_confirmation_runs",
                        to="certification_board.rolloutcertificationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BaselineConfirmationCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_component", models.CharField(max_length=32)),
                ("target_scope", models.CharField(max_length=24)),
                (
                    "certification_status",
                    models.CharField(
                        choices=[
                            (
                                "CERTIFIED_FOR_PAPER_BASELINE",
                                "Certified for paper baseline",
                            ),
                            ("KEEP_UNDER_OBSERVATION", "Keep under observation"),
                            ("REQUIRE_MANUAL_REVIEW", "Require manual review"),
                            ("RECOMMEND_ROLLBACK", "Recommend rollback"),
                            ("REJECT_CERTIFICATION", "Reject certification"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "previous_baseline_reference",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "proposed_baseline_reference",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "binding_resolution_status",
                    models.CharField(
                        choices=[
                            ("RESOLVED", "Resolved"),
                            ("PARTIAL", "Partial"),
                            ("BLOCKED", "Blocked"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                ("ready_for_confirmation", models.BooleanField(default=False)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_certification_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baseline_confirmation_candidates",
                        to="certification_board.certificationcandidate",
                    ),
                ),
                (
                    "linked_certification_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baseline_confirmation_candidates",
                        to="certification_board.certificationdecision",
                    ),
                ),
                (
                    "linked_rollout_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_confirmation_candidates",
                        to="promotion_committee.rolloutexecutionrecord",
                    ),
                ),
                (
                    "review_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="certification_board.baselineconfirmationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaperBaselineConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmation_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("READY_TO_CONFIRM", "Ready to confirm"),
                            ("CONFIRMED", "Confirmed"),
                            ("BLOCKED", "Blocked"),
                            ("DEFERRED", "Deferred"),
                            ("ROLLBACK_AVAILABLE", "Rollback available"),
                        ],
                        default="PROPOSED",
                        max_length=24,
                    ),
                ),
                ("target_component", models.CharField(max_length=32)),
                ("target_scope", models.CharField(max_length=24)),
                (
                    "previous_baseline_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "confirmed_baseline_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                ("confirmed_by", models.CharField(blank=True, max_length=120)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                (
                    "linked_binding_artifact",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baseline_confirmation",
                        to="certification_board.baselineconfirmationcandidate",
                    ),
                ),
                (
                    "linked_certification_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_baseline_confirmations",
                        to="certification_board.certificationdecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BaselineConfirmationRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("CONFIRM_PAPER_BASELINE", "Confirm paper baseline"),
                            ("REQUIRE_BINDING_REVIEW", "Require binding review"),
                            (
                                "DEFER_BASELINE_CONFIRMATION",
                                "Defer baseline confirmation",
                            ),
                            ("PREPARE_BASELINE_ROLLBACK", "Prepare baseline rollback"),
                            ("REQUIRE_COMMITTEE_RECHECK", "Require committee recheck"),
                            ("REORDER_BASELINE_PRIORITY", "Reorder baseline priority"),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "review_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="certification_board.baselineconfirmationrun",
                    ),
                ),
                (
                    "target_confirmation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="certification_board.paperbaselineconfirmation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BaselineBindingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "binding_type",
                    models.CharField(
                        choices=[
                            ("champion_reference", "Champion reference"),
                            ("stack_profile_binding", "Stack profile binding"),
                            ("trust_calibration_binding", "Trust calibration binding"),
                            ("policy_tuning_binding", "Policy tuning binding"),
                            ("rollout_reference", "Rollout reference"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "binding_status",
                    models.CharField(
                        choices=[
                            ("PREVIOUS", "Previous"),
                            ("PROPOSED", "Proposed"),
                            ("CONFIRMED", "Confirmed"),
                            ("REVERTED", "Reverted"),
                        ],
                        max_length=16,
                    ),
                ),
                ("binding_snapshot", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_confirmation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="binding_snapshots",
                        to="certification_board.paperbaselineconfirmation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="baselineconfirmationcandidate",
            index=models.Index(
                fields=["binding_resolution_status", "-created_at"],
                name="certificati_binding_2dcaf3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paperbaselineconfirmation",
            index=models.Index(
                fields=["confirmation_status", "-created_at"],
                name="certificati_confirm_83efb0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="baselineconfirmationrecommendation",
            index=models.Index(
                fields=["recommendation_type", "-created_at"],
                name="certificati_recomme_bc2dad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="baselinebindingsnapshot",
            index=models.Index(
                fields=["binding_type", "binding_status", "-created_at"],
                name="certificati_binding_77aaea_idx",
            ),
        ),
    ]
