# Generated by Django 5.1.4 on 2026-03-30 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certification_board", "0003_baselineconfirmationrun_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaselineActivationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("ready_to_activate_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("activated_count", models.PositiveIntegerField(default=0)),
                ("rollback_ready_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_baseline_confirmation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_activation_runs",
                        to="certification_board.baselineconfirmationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BaselineActivationCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_component", models.CharField(max_length=32)),
                ("target_scope", models.CharField(max_length=24)),
                (
                    "previous_active_reference",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "proposed_active_reference",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "activation_resolution_status",
                    models.CharField(
                        choices=[
                            ("RESOLVED", "Resolved"),
                            ("PARTIAL", "Partial"),
                            ("BLOCKED", "Blocked"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                ("ready_for_activation", models.BooleanField(default=False)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_certification_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_activation_candidates",
                        to="certification_board.certificationdecision",
                    ),
                ),
                (
                    "linked_paper_baseline_confirmation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activation_candidates",
                        to="certification_board.paperbaselineconfirmation",
                    ),
                ),
                (
                    "review_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="certification_board.baselineactivationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaperBaselineActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activation_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("READY_TO_ACTIVATE", "Ready to activate"),
                            ("ACTIVATED", "Activated"),
                            ("BLOCKED", "Blocked"),
                            ("DEFERRED", "Deferred"),
                            ("ROLLBACK_AVAILABLE", "Rollback available"),
                        ],
                        default="PROPOSED",
                        max_length=24,
                    ),
                ),
                ("target_component", models.CharField(max_length=32)),
                ("target_scope", models.CharField(max_length=24)),
                (
                    "previous_active_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                ("activated_snapshot", models.JSONField(blank=True, default=dict)),
                ("activated_by", models.CharField(blank=True, max_length=120)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                (
                    "linked_binding_artifact",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activations",
                        to="certification_board.baselineactivationcandidate",
                    ),
                ),
                (
                    "linked_confirmation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activations",
                        to="certification_board.paperbaselineconfirmation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BaselineActivationRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("ACTIVATE_PAPER_BASELINE", "Activate paper baseline"),
                            ("REQUIRE_BINDING_RECHECK", "Require binding recheck"),
                            ("DEFER_ACTIVATION", "Defer activation"),
                            (
                                "PREPARE_ACTIVATION_ROLLBACK",
                                "Prepare activation rollback",
                            ),
                            ("REQUIRE_COMMITTEE_RECHECK", "Require committee recheck"),
                            (
                                "REORDER_ACTIVATION_PRIORITY",
                                "Reorder activation priority",
                            ),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "review_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="certification_board.baselineactivationrun",
                    ),
                ),
                (
                    "target_activation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="certification_board.paperbaselineactivation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ActivePaperBindingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_component", models.CharField(max_length=32)),
                ("target_scope", models.CharField(max_length=24)),
                (
                    "active_binding_type",
                    models.CharField(
                        choices=[
                            ("champion_reference", "Champion reference"),
                            ("stack_profile_binding", "Stack profile binding"),
                            ("trust_calibration_binding", "Trust calibration binding"),
                            ("policy_tuning_binding", "Policy tuning binding"),
                            ("rollout_reference", "Rollout reference"),
                        ],
                        max_length=40,
                    ),
                ),
                ("active_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUPERSEDED", "Superseded"),
                            ("REVERTED", "Reverted"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "source_activation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_binding_records",
                        to="certification_board.paperbaselineactivation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="baselineactivationcandidate",
            index=models.Index(
                fields=["activation_resolution_status", "-created_at"],
                name="certificati_activat_ccd98e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paperbaselineactivation",
            index=models.Index(
                fields=["activation_status", "-created_at"],
                name="certificati_activat_15ffdd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="baselineactivationrecommendation",
            index=models.Index(
                fields=["recommendation_type", "-created_at"],
                name="certificati_recomme_791612_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activepaperbindingrecord",
            index=models.Index(
                fields=["target_component", "target_scope", "status", "-created_at"],
                name="certificati_target__e56a5c_idx",
            ),
        ),
    ]
