# Generated by Django 5.1.4 on 2026-03-30 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "certification_board",
            "0004_baselineactivationrun_baselineactivationcandidate_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BaselineHealthRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("active_binding_count", models.PositiveIntegerField(default=0)),
                ("healthy_count", models.PositiveIntegerField(default=0)),
                ("watch_count", models.PositiveIntegerField(default=0)),
                ("degraded_count", models.PositiveIntegerField(default=0)),
                ("review_required_count", models.PositiveIntegerField(default=0)),
                ("rollback_review_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_baseline_activation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_health_runs",
                        to="certification_board.baselineactivationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BaselineHealthCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_component", models.CharField(max_length=32)),
                ("target_scope", models.CharField(max_length=24)),
                (
                    "active_binding_type",
                    models.CharField(
                        choices=[
                            ("champion_reference", "Champion reference"),
                            ("stack_profile_binding", "Stack profile binding"),
                            ("trust_calibration_binding", "Trust calibration binding"),
                            ("policy_tuning_binding", "Policy tuning binding"),
                            ("rollout_reference", "Rollout reference"),
                        ],
                        max_length=40,
                    ),
                ),
                ("current_health_inputs", models.JSONField(blank=True, default=dict)),
                (
                    "readiness_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("NEEDS_MORE_DATA", "Needs more data"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="NEEDS_MORE_DATA",
                        max_length=20,
                    ),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_active_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baseline_health_candidates",
                        to="certification_board.activepaperbindingrecord",
                    ),
                ),
                (
                    "linked_baseline_activation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_health_candidates",
                        to="certification_board.paperbaselineactivation",
                    ),
                ),
                (
                    "review_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="certification_board.baselinehealthrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BaselineHealthStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("UNDER_WATCH", "Under watch"),
                            ("DEGRADED", "Degraded"),
                            ("REVIEW_REQUIRED", "Review required"),
                            (
                                "ROLLBACK_REVIEW_RECOMMENDED",
                                "Rollback review recommended",
                            ),
                            ("INSUFFICIENT_DATA", "Insufficient data"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "calibration_health_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "risk_gate_health_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "opportunity_quality_health_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "drift_risk_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "regression_risk_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_statuses",
                        to="certification_board.baselinehealthcandidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BaselineHealthSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("calibration_drift", "Calibration drift"),
                            ("risk_precision_drop", "Risk precision drop"),
                            ("shortlist_quality_drop", "Shortlist quality drop"),
                            (
                                "opportunity_conviction_drop",
                                "Opportunity conviction drop",
                            ),
                            (
                                "provider_bias_reappearance",
                                "Provider bias reappearance",
                            ),
                            (
                                "category_bias_reappearance",
                                "Category bias reappearance",
                            ),
                            ("watchlist_noise_increase", "Watchlist noise increase"),
                            ("rollback_pressure", "Rollback pressure"),
                            ("insufficient_observation", "Insufficient observation"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "signal_severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "signal_direction",
                    models.CharField(
                        choices=[
                            ("improving", "Improving"),
                            ("stable", "Stable"),
                            ("degrading", "Degrading"),
                        ],
                        max_length=16,
                    ),
                ),
                ("evidence_summary", models.JSONField(blank=True, default=dict)),
                ("rationale", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="certification_board.baselinehealthstatus",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BaselineHealthRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("KEEP_BASELINE_ACTIVE", "Keep baseline active"),
                            ("KEEP_UNDER_WATCH", "Keep under watch"),
                            ("REQUIRE_REEVALUATION", "Require re-evaluation"),
                            ("OPEN_TUNING_REVIEW", "Open tuning review"),
                            (
                                "REQUIRE_MANUAL_BASELINE_REVIEW",
                                "Require manual baseline review",
                            ),
                            ("PREPARE_ROLLBACK_REVIEW", "Prepare rollback review"),
                            (
                                "REORDER_BASELINE_HEALTH_PRIORITY",
                                "Reorder baseline health priority",
                            ),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "review_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="certification_board.baselinehealthrun",
                    ),
                ),
                (
                    "target_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="certification_board.baselinehealthstatus",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="baselinehealthcandidate",
            index=models.Index(
                fields=["readiness_status", "-created_at"],
                name="certificati_readine_bd6bad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="baselinehealthstatus",
            index=models.Index(
                fields=["health_status", "-created_at"],
                name="certificati_health__9fac9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="baselinehealthsignal",
            index=models.Index(
                fields=["signal_type", "signal_severity", "-created_at"],
                name="certificati_signal__107878_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="baselinehealthrecommendation",
            index=models.Index(
                fields=["recommendation_type", "-created_at"],
                name="certificati_recomme_423a9b_idx",
            ),
        ),
    ]
