# Generated by Django 5.1.4 on 2026-03-30 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "certification_board",
            "0005_baselinehealthrun_baselinehealthcandidate_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BaselineResponseRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("opened_case_count", models.PositiveIntegerField(default=0)),
                ("watch_case_count", models.PositiveIntegerField(default=0)),
                ("reevaluation_case_count", models.PositiveIntegerField(default=0)),
                ("tuning_case_count", models.PositiveIntegerField(default=0)),
                ("rollback_review_case_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_baseline_health_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_response_runs",
                        to="certification_board.baselinehealthrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BaselineResponseCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("linked_health_signals", models.JSONField(blank=True, default=list)),
                ("target_component", models.CharField(max_length=32)),
                ("target_scope", models.CharField(max_length=24)),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("KEEP_UNDER_WATCH", "Keep under watch"),
                            ("OPEN_REEVALUATION", "Open re-evaluation"),
                            ("OPEN_TUNING_REVIEW", "Open tuning review"),
                            (
                                "REQUIRE_MANUAL_BASELINE_REVIEW",
                                "Require manual baseline review",
                            ),
                            ("PREPARE_ROLLBACK_REVIEW", "Prepare rollback review"),
                            ("REQUIRE_COMMITTEE_RECHECK", "Require committee recheck"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                (
                    "case_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("UNDER_REVIEW", "Under review"),
                            ("ROUTED", "Routed"),
                            ("DEFERRED", "Deferred"),
                            ("CLOSED_NO_ACTION", "Closed with no action"),
                            ("ESCALATED", "Escalated"),
                        ],
                        default="OPEN",
                        max_length=24,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_active_binding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_response_cases",
                        to="certification_board.activepaperbindingrecord",
                    ),
                ),
                (
                    "linked_baseline_health_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="response_cases",
                        to="certification_board.baselinehealthstatus",
                    ),
                ),
                (
                    "review_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="certification_board.baselineresponserun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ResponseEvidencePack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("summary", models.CharField(max_length=255)),
                ("linked_health_signals", models.JSONField(blank=True, default=list)),
                (
                    "linked_evaluation_metrics",
                    models.JSONField(blank=True, default=dict),
                ),
                ("linked_risk_context", models.JSONField(blank=True, default=dict)),
                (
                    "linked_opportunity_context",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "severity_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "urgency_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "evidence_status",
                    models.CharField(
                        choices=[
                            ("STRONG", "Strong"),
                            ("MIXED", "Mixed"),
                            ("WEAK", "Weak"),
                            ("INSUFFICIENT", "Insufficient"),
                        ],
                        default="INSUFFICIENT",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_health_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="response_evidence_packs",
                        to="certification_board.baselinehealthstatus",
                    ),
                ),
                (
                    "linked_response_case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_pack",
                        to="certification_board.baselineresponsecase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ResponseRoutingDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "routing_target",
                    models.CharField(
                        choices=[
                            ("evaluation_lab", "Evaluation lab"),
                            ("tuning_board", "Tuning board"),
                            ("promotion_committee", "Promotion committee"),
                            ("certification_board", "Certification board"),
                            ("rollback_review", "Rollback review"),
                            ("monitoring_only", "Monitoring only"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "routing_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("READY", "Ready"),
                            ("SENT", "Sent"),
                            ("DEFERRED", "Deferred"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=16,
                    ),
                ),
                ("routing_rationale", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_response_case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_decision",
                        to="certification_board.baselineresponsecase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BaselineResponseRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("KEEP_UNDER_WATCH", "Keep under watch"),
                            ("OPEN_REEVALUATION", "Open re-evaluation"),
                            ("OPEN_TUNING_REVIEW", "Open tuning review"),
                            (
                                "REQUIRE_MANUAL_BASELINE_REVIEW",
                                "Require manual baseline review",
                            ),
                            ("PREPARE_ROLLBACK_REVIEW", "Prepare rollback review"),
                            ("REQUIRE_MORE_EVIDENCE", "Require more evidence"),
                            ("REORDER_RESPONSE_PRIORITY", "Reorder response priority"),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="certification_board.baselineresponsecase",
                    ),
                ),
                (
                    "review_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="certification_board.baselineresponserun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recommendation_type", "-created_at"],
                        name="certificati_recomme_74cc70_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="baselineresponsecase",
            index=models.Index(
                fields=[
                    "response_type",
                    "priority_level",
                    "case_status",
                    "-created_at",
                ],
                name="certificati_respons_e8cf78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="responseevidencepack",
            index=models.Index(
                fields=["evidence_status", "-created_at"],
                name="certificati_evidenc_1fb8e8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="responseroutingdecision",
            index=models.Index(
                fields=["routing_target", "routing_status", "-created_at"],
                name="certificati_routing_7b7953_idx",
            ),
        ),
    ]
