# Generated by Django 5.1.4 on 2026-03-30 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "certification_board",
            "0006_baselineresponserun_baselineresponsecase_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BaselineResponseActionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("ready_to_route_count", models.PositiveIntegerField(default=0)),
                ("routed_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("under_review_count", models.PositiveIntegerField(default=0)),
                ("closed_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_baseline_response_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_runs",
                        to="certification_board.baselineresponserun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ResponseActionCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_component", models.CharField(max_length=32)),
                ("target_scope", models.CharField(max_length=24)),
                (
                    "intended_routing_target",
                    models.CharField(blank=True, max_length=32),
                ),
                (
                    "routing_resolution_status",
                    models.CharField(
                        choices=[
                            ("RESOLVED", "Resolved"),
                            ("PARTIAL", "Partial"),
                            ("BLOCKED", "Blocked"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                ("ready_for_action", models.BooleanField(default=False)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "action_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="certification_board.baselineresponseactionrun",
                    ),
                ),
                (
                    "linked_response_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_candidates",
                        to="certification_board.baselineresponsecase",
                    ),
                ),
                (
                    "linked_routing_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_candidates",
                        to="certification_board.responseroutingdecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ResponseRoutingAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("SEND_TO_EVALUATION_REVIEW", "Send to evaluation review"),
                            ("SEND_TO_TUNING_REVIEW", "Send to tuning review"),
                            (
                                "SEND_TO_CERTIFICATION_REVIEW",
                                "Send to certification review",
                            ),
                            ("SEND_TO_PROMOTION_RECHECK", "Send to promotion recheck"),
                            ("SEND_TO_ROLLBACK_REVIEW", "Send to rollback review"),
                            ("KEEP_IN_MONITORING", "Keep in monitoring"),
                            ("REQUIRE_ROUTING_RECHECK", "Require routing recheck"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "action_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("READY_TO_ROUTE", "Ready to route"),
                            ("ROUTED", "Routed"),
                            ("BLOCKED", "Blocked"),
                            ("DEFERRED", "Deferred"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PROPOSED",
                        max_length=20,
                    ),
                ),
                ("routed_by", models.CharField(blank=True, max_length=120)),
                ("routed_at", models.DateTimeField(blank=True, null=True)),
                ("routing_target", models.CharField(blank=True, max_length=32)),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                (
                    "linked_target_artifact",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routing_actions",
                        to="certification_board.responseactioncandidate",
                    ),
                ),
                (
                    "linked_response_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_actions",
                        to="certification_board.baselineresponsecase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ResponseCaseTrackingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "downstream_status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("UNDER_REVIEW", "Under review"),
                            ("WAITING_EVIDENCE", "Waiting evidence"),
                            ("COMPLETED", "Completed"),
                            ("CLOSED_NO_ACTION", "Closed without action"),
                            ("ESCALATED", "Escalated"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=24,
                    ),
                ),
                ("tracking_notes", models.CharField(blank=True, max_length=255)),
                ("tracked_by", models.CharField(blank=True, max_length=120)),
                ("tracked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "linked_downstream_reference",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_response_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_records",
                        to="certification_board.baselineresponsecase",
                    ),
                ),
                (
                    "linked_routing_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracking_records",
                        to="certification_board.responseroutingaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ResponseActionRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("ROUTE_CASE_NOW", "Route case now"),
                            ("REQUIRE_ROUTING_RECHECK", "Require routing recheck"),
                            ("KEEP_CASE_IN_MONITORING", "Keep case in monitoring"),
                            ("ESCALATE_CASE_PRIORITY", "Escalate case priority"),
                            ("CLOSE_CASE_NO_ACTION", "Close case with no action"),
                            (
                                "REQUIRE_DOWNSTREAM_STATUS_UPDATE",
                                "Require downstream status update",
                            ),
                            (
                                "REORDER_RESPONSE_ACTION_PRIORITY",
                                "Reorder response action priority",
                            ),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "action_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="certification_board.baselineresponseactionrun",
                    ),
                ),
                (
                    "target_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="certification_board.responseroutingaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="responseactioncandidate",
            index=models.Index(
                fields=["routing_resolution_status", "ready_for_action", "-created_at"],
                name="certificati_routing_d00a2e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="responseroutingaction",
            index=models.Index(
                fields=["action_type", "action_status", "-created_at"],
                name="certificati_action__0a60f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="responsecasetrackingrecord",
            index=models.Index(
                fields=["downstream_status", "-created_at"],
                name="certificati_downstr_c8525b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="responseactionrecommendation",
            index=models.Index(
                fields=["recommendation_type", "-created_at"],
                name="certificati_recomme_676344_idx",
            ),
        ),
    ]
