# Generated by Django 5.1.4 on 2026-03-30 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "certification_board",
            "0007_baselineresponseactionrun_responseactioncandidate_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BaselineResponseLifecycleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("routed_action_count", models.PositiveIntegerField(default=0)),
                ("acknowledged_count", models.PositiveIntegerField(default=0)),
                ("accepted_for_review_count", models.PositiveIntegerField(default=0)),
                ("waiting_evidence_count", models.PositiveIntegerField(default=0)),
                ("resolved_downstream_count", models.PositiveIntegerField(default=0)),
                ("rejected_downstream_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_baseline_response_action_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lifecycle_runs",
                        to="certification_board.baselineresponseactionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DownstreamAcknowledgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("routing_target", models.CharField(blank=True, max_length=64)),
                (
                    "acknowledgement_status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("ACCEPTED_FOR_REVIEW", "Accepted for review"),
                            ("REJECTED_BY_TARGET", "Rejected by target"),
                            ("WAITING_MORE_EVIDENCE", "Waiting more evidence"),
                            ("NO_RESPONSE", "No response"),
                        ],
                        max_length=32,
                    ),
                ),
                ("acknowledged_by", models.CharField(blank=True, max_length=120)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledgement_notes", models.CharField(blank=True, max_length=255)),
                (
                    "linked_target_reference",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_response_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downstream_acknowledgements",
                        to="certification_board.baselineresponsecase",
                    ),
                ),
                (
                    "linked_response_routing_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="downstream_acknowledgements",
                        to="certification_board.responseroutingaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ResponseLifecycleRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            (
                                "REQUEST_ACKNOWLEDGEMENT_UPDATE",
                                "Request acknowledgement update",
                            ),
                            ("MARK_ACCEPTED_FOR_REVIEW", "Mark accepted for review"),
                            ("RECORD_WAITING_EVIDENCE", "Record waiting evidence"),
                            ("RECORD_REJECTED_BY_TARGET", "Record rejected by target"),
                            ("ESCALATE_FOR_FOLLOWUP", "Escalate for follow-up"),
                            ("PREPARE_CASE_RESOLUTION", "Prepare case resolution"),
                            (
                                "REORDER_LIFECYCLE_PRIORITY",
                                "Reorder lifecycle priority",
                            ),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "lifecycle_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="certification_board.baselineresponselifecyclerun",
                    ),
                ),
                (
                    "target_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lifecycle_recommendations",
                        to="certification_board.baselineresponsecase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ResponseReviewStageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage_type",
                    models.CharField(
                        choices=[
                            ("intake_review", "Intake review"),
                            ("evidence_collection", "Evidence collection"),
                            ("board_review", "Board review"),
                            ("manual_followup", "Manual follow-up"),
                            ("downstream_resolution", "Downstream resolution"),
                            ("rejection_review", "Rejection review"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "stage_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("BLOCKED", "Blocked"),
                            ("SKIPPED", "Skipped"),
                        ],
                        max_length=16,
                    ),
                ),
                ("stage_notes", models.CharField(blank=True, max_length=255)),
                ("stage_actor", models.CharField(blank=True, max_length=120)),
                ("stage_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_acknowledgement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stage_records",
                        to="certification_board.downstreamacknowledgement",
                    ),
                ),
                (
                    "linked_response_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_stage_records",
                        to="certification_board.baselineresponsecase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DownstreamLifecycleOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outcome_type",
                    models.CharField(
                        choices=[
                            ("RESOLVED_BY_TARGET", "Resolved by target"),
                            ("REJECTED_BY_TARGET", "Rejected by target"),
                            ("WAITING_EVIDENCE", "Waiting evidence"),
                            ("NO_ACTION_TAKEN", "No action taken"),
                            ("ESCALATED_BACK", "Escalated back"),
                            ("STILL_UNDER_REVIEW", "Still under review"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "outcome_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("CONFIRMED", "Confirmed"),
                            ("DEFERRED", "Deferred"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=16,
                    ),
                ),
                ("outcome_rationale", models.CharField(max_length=255)),
                (
                    "linked_target_reference",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_acknowledgement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="downstream_lifecycle_outcomes",
                        to="certification_board.downstreamacknowledgement",
                    ),
                ),
                (
                    "linked_response_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downstream_lifecycle_outcomes",
                        to="certification_board.baselineresponsecase",
                    ),
                ),
                (
                    "linked_latest_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="downstream_lifecycle_outcomes",
                        to="certification_board.responsereviewstagerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="downstreamacknowledgement",
            index=models.Index(
                fields=["acknowledgement_status", "-created_at"],
                name="certificati_acknowl_8a74e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="responselifecyclerecommendation",
            index=models.Index(
                fields=["recommendation_type", "-created_at"],
                name="certificati_recomme_3a9271_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="responsereviewstagerecord",
            index=models.Index(
                fields=["stage_type", "stage_status", "-created_at"],
                name="certificati_stage_t_1e9fb0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="downstreamlifecycleoutcome",
            index=models.Index(
                fields=["outcome_type", "outcome_status", "-created_at"],
                name="certificati_outcome_476cba_idx",
            ),
        ),
    ]
