# Generated by Django 5.1.4 on 2026-04-01 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certification_board", "0008_baselineresponselifecyclerun_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaselineResponseResolutionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("ready_to_close_count", models.PositiveIntegerField(default=0)),
                ("resolved_count", models.PositiveIntegerField(default=0)),
                ("waiting_evidence_count", models.PositiveIntegerField(default=0)),
                ("closed_no_action_count", models.PositiveIntegerField(default=0)),
                ("escalated_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_baseline_response_lifecycle_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolution_runs",
                        to="certification_board.baselineresponselifecyclerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ResponseResolutionCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_component", models.CharField(max_length=32)),
                ("target_scope", models.CharField(max_length=24)),
                (
                    "downstream_progress_status",
                    models.CharField(
                        choices=[
                            ("READY_TO_RESOLVE", "Ready to resolve"),
                            ("WAITING_EVIDENCE", "Waiting evidence"),
                            ("IN_PROGRESS", "In progress"),
                            ("FOLLOWUP_REQUIRED", "Follow-up required"),
                            ("BLOCKED", "Blocked"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=24,
                    ),
                ),
                ("ready_for_resolution", models.BooleanField(default=False)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "latest_acknowledgement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolution_candidates",
                        to="certification_board.downstreamacknowledgement",
                    ),
                ),
                (
                    "latest_lifecycle_outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolution_candidates",
                        to="certification_board.downstreamlifecycleoutcome",
                    ),
                ),
                (
                    "latest_tracking_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolution_candidates",
                        to="certification_board.responsecasetrackingrecord",
                    ),
                ),
                (
                    "linked_response_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolution_candidates",
                        to="certification_board.baselineresponsecase",
                    ),
                ),
                (
                    "linked_routing_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolution_candidates",
                        to="certification_board.responseroutingaction",
                    ),
                ),
                (
                    "resolution_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="certification_board.baselineresponseresolutionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ResponseCaseResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolution_type",
                    models.CharField(
                        choices=[
                            ("RESOLVED_BY_REEVALUATION", "Resolved by reevaluation"),
                            ("RESOLVED_BY_TUNING_REVIEW", "Resolved by tuning review"),
                            (
                                "RESOLVED_BY_ROLLBACK_REVIEW",
                                "Resolved by rollback review",
                            ),
                            (
                                "RESOLVED_BY_MONITORING_ONLY",
                                "Resolved by monitoring only",
                            ),
                            ("CLOSED_NO_ACTION", "Closed with no action"),
                            ("DEFERRED_WAITING_EVIDENCE", "Deferred waiting evidence"),
                            (
                                "ESCALATED_FOR_MANUAL_REVIEW",
                                "Escalated for manual review",
                            ),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("READY_TO_CLOSE", "Ready to close"),
                            ("RESOLVED", "Resolved"),
                            ("DEFERRED", "Deferred"),
                            ("BLOCKED", "Blocked"),
                            ("ESCALATED", "Escalated"),
                        ],
                        default="PROPOSED",
                        max_length=20,
                    ),
                ),
                ("rationale", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("resolved_by", models.CharField(blank=True, max_length=120)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_response_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_resolutions",
                        to="certification_board.baselineresponsecase",
                    ),
                ),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolutions",
                        to="certification_board.responseresolutioncandidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ResponseResolutionRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("CLOSE_CASE_AS_RESOLVED", "Close case as resolved"),
                            ("KEEP_WAITING_FOR_EVIDENCE", "Keep waiting for evidence"),
                            (
                                "ESCALATE_FOR_MANUAL_REVIEW",
                                "Escalate for manual review",
                            ),
                            ("CLOSE_CASE_NO_ACTION", "Close case no action"),
                            (
                                "REQUIRE_DOWNSTREAM_REFERENCE",
                                "Require downstream reference",
                            ),
                            (
                                "REORDER_CASE_RESOLUTION_PRIORITY",
                                "Reorder case resolution priority",
                            ),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "resolution_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="certification_board.baselineresponseresolutionrun",
                    ),
                ),
                (
                    "target_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolution_recommendations",
                        to="certification_board.baselineresponsecase",
                    ),
                ),
                (
                    "target_resolution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="certification_board.responsecaseresolution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DownstreamOutcomeReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("evaluation_review", "Evaluation review"),
                            ("tuning_review", "Tuning review"),
                            ("experiment_review", "Experiment review"),
                            ("promotion_recheck", "Promotion recheck"),
                            ("rollback_review", "Rollback review"),
                            ("monitoring_decision", "Monitoring decision"),
                            ("manual_note", "Manual note"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "reference_status",
                    models.CharField(
                        choices=[
                            ("LINKED", "Linked"),
                            ("PARTIAL", "Partial"),
                            ("MISSING", "Missing"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "downstream_reference_id",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "downstream_reference_label",
                    models.CharField(blank=True, max_length=255),
                ),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_resolution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downstream_references",
                        to="certification_board.responsecaseresolution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["reference_type", "reference_status", "-created_at"],
                        name="certificati_referen_3a27b5_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="responseresolutioncandidate",
            index=models.Index(
                fields=[
                    "downstream_progress_status",
                    "ready_for_resolution",
                    "-created_at",
                ],
                name="certificati_downstr_8bd893_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="responsecaseresolution",
            index=models.Index(
                fields=["resolution_type", "resolution_status", "-created_at"],
                name="certificati_resolut_9376e8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="responseresolutionrecommendation",
            index=models.Index(
                fields=["recommendation_type", "-created_at"],
                name="certificati_recomme_1477a3_idx",
            ),
        ),
    ]
