# Generated by Django 5.1.4 on 2026-03-29 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approval_center", "0001_initial"),
        ("autonomy_campaign", "0001_initial"),
        ("autonomy_scheduler", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaunchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("ready_count", models.PositiveIntegerField(default=0)),
                ("waiting_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("approval_required_count", models.PositiveIntegerField(default=0)),
                ("program_posture", models.CharField(max_length=20)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "active_window",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="launch_runs",
                        to="autonomy_scheduler.changewindow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LaunchAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authorization_status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending review"),
                            ("AUTHORIZED", "Authorized"),
                            ("HOLD", "Hold"),
                            ("BLOCKED", "Blocked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=16,
                    ),
                ),
                (
                    "authorization_type",
                    models.CharField(
                        choices=[
                            ("normal_start", "Normal start"),
                            ("approval_required_start", "Approval required start"),
                            ("blocked_start", "Blocked start"),
                        ],
                        default="normal_start",
                        max_length=32,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("requires_approval", models.BooleanField(default=False)),
                ("authorized_by", models.CharField(blank=True, max_length=120)),
                ("authorized_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "approved_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="launch_authorizations",
                        to="approval_center.approvalrequest",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="launch_authorizations",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["campaign", "-created_at"],
                        name="autonomy_la_campaig_0c5918_idx",
                    ),
                    models.Index(
                        fields=["authorization_status", "-created_at"],
                        name="autonomy_la_authori_1a20c0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LaunchRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("START_NOW", "Start now"),
                            ("AUTHORIZE_START", "Authorize start"),
                            ("HOLD_START", "Hold start"),
                            ("WAIT_FOR_WINDOW", "Wait for window"),
                            ("REQUIRE_APPROVAL_TO_START", "Require approval to start"),
                            ("BLOCK_START", "Block start"),
                            ("REORDER_START_PRIORITY", "Reorder start priority"),
                        ],
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("impacted_domains", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="launch_recommendations",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "launch_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_launch.launchrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recommendation_type", "-created_at"],
                        name="autonomy_la_recomme_94ea97_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LaunchReadinessSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("admission_status", models.CharField(max_length=16)),
                ("program_posture", models.CharField(max_length=20)),
                ("active_window_status", models.CharField(max_length=12)),
                (
                    "unresolved_checkpoints_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("unresolved_approvals_count", models.PositiveIntegerField(default=0)),
                ("dependency_blocked", models.BooleanField(default=False)),
                ("domain_conflict", models.BooleanField(default=False)),
                ("incident_impact", models.PositiveIntegerField(default=0)),
                ("degraded_impact", models.PositiveIntegerField(default=0)),
                ("rollout_observation_impact", models.PositiveIntegerField(default=0)),
                ("readiness_score", models.PositiveIntegerField(default=0)),
                (
                    "readiness_status",
                    models.CharField(
                        choices=[
                            ("READY_TO_START", "Ready to start"),
                            ("CAUTION", "Caution"),
                            ("WAITING", "Waiting"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="WAITING",
                        max_length=24,
                    ),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="launch_readiness_snapshots",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "launch_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="readiness_snapshots",
                        to="autonomy_launch.launchrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["campaign", "-created_at"],
                        name="autonomy_la_campaig_34b90e_idx",
                    ),
                    models.Index(
                        fields=["readiness_status", "-created_at"],
                        name="autonomy_la_readine_280ec9_idx",
                    ),
                ],
            },
        ),
    ]
