from __future__ import annotations

from apps.autonomous_trader.models import AutonomousTradeExecution, AutonomousTradeWatchRecord, AutonomousWatchStatus


def create_watch_record(*, execution: AutonomousTradeExecution) -> AutonomousTradeWatchRecord:
    trade = execution.linked_paper_trade
    sentiment_shift = bool(execution.linked_candidate.adjusted_edge < 0)
    risk_change = execution.linked_candidate.risk_posture in {'BLOCKED', 'NEEDS_REVIEW'}
    market_move = bool(trade and trade.position and trade.position.unrealized_pnl < 0)

    if trade and trade.position and trade.position.status == 'CLOSED':
        status = AutonomousWatchStatus.CLOSED
    elif risk_change:
        status = AutonomousWatchStatus.EXIT_REVIEW_REQUIRED
    elif market_move:
        status = AutonomousWatchStatus.CLOSE_SIGNAL
    else:
        status = AutonomousWatchStatus.OPEN_MONITORING

    return AutonomousTradeWatchRecord.objects.create(
        linked_execution=execution,
        watch_status=status,
        sentiment_shift_detected=sentiment_shift,
        market_move_detected=market_move,
        risk_change_detected=risk_change,
        watch_notes='Automated watch record generated by autonomous paper loop.',
        metadata={'paper_only': True},
    )
