from django.urls import path

from apps.runtime_governor.views import (
    ApplyOperatingModeDecisionView,
    OperatingModeDecisionDetailView,
    OperatingModeDecisionListView,
    RunModeEnforcementReviewView,
    ModeEnforcementRunListView,
    ModeModuleImpactListView,
    ModeEnforcementDecisionListView,
    ModeEnforcementDecisionDetailView,
    ModeEnforcementRecommendationListView,
    ModeEnforcementSummaryView,
    ApplyRuntimeFeedbackDecisionView,
    OperatingModeRecommendationListView,
    OperatingModeSummaryView,
    OperatingModeSwitchRecordListView,
    RunOperatingModeReviewView,
    RuntimeCapabilitiesView,
    RuntimeModesView,
    RuntimePostureRunListView,
    RuntimePostureSnapshotListView,
    RuntimeSetModeView,
    RuntimeStatusView,
    RuntimeFeedbackDecisionDetailView,
    RuntimeFeedbackDecisionListView,
    RuntimeFeedbackRecommendationListView,
    RuntimeFeedbackRunListView,
    RuntimeDiagnosticReviewListView,
    RuntimeFeedbackSummaryView,
    RuntimePerformanceSnapshotListView,
    RuntimeTransitionListView,
    RunRuntimeFeedbackReviewView,
)

urlpatterns = [
    path('status/', RuntimeStatusView.as_view(), name='status'),
    path('modes/', RuntimeModesView.as_view(), name='modes'),
    path('set-mode/', RuntimeSetModeView.as_view(), name='set_mode'),
    path('transitions/', RuntimeTransitionListView.as_view(), name='transitions'),
    path('capabilities/', RuntimeCapabilitiesView.as_view(), name='capabilities'),
    path('run-operating-mode-review/', RunOperatingModeReviewView.as_view(), name='run_operating_mode_review'),
    path('runtime-posture-runs/', RuntimePostureRunListView.as_view(), name='runtime_posture_runs'),
    path('runtime-posture-snapshots/', RuntimePostureSnapshotListView.as_view(), name='runtime_posture_snapshots'),
    path('operating-mode-decisions/', OperatingModeDecisionListView.as_view(), name='operating_mode_decisions'),
    path('operating-mode-decisions/<int:decision_id>/', OperatingModeDecisionDetailView.as_view(), name='operating_mode_decision_detail'),
    path('operating-mode-switch-records/', OperatingModeSwitchRecordListView.as_view(), name='operating_mode_switch_records'),
    path('operating-mode-recommendations/', OperatingModeRecommendationListView.as_view(), name='operating_mode_recommendations'),
    path('operating-mode-summary/', OperatingModeSummaryView.as_view(), name='operating_mode_summary'),
    path('apply-operating-mode/<int:decision_id>/', ApplyOperatingModeDecisionView.as_view(), name='apply_operating_mode'),
    path('run-mode-enforcement-review/', RunModeEnforcementReviewView.as_view(), name='run_mode_enforcement_review'),
    path('mode-enforcement-runs/', ModeEnforcementRunListView.as_view(), name='mode_enforcement_runs'),
    path('mode-module-impacts/', ModeModuleImpactListView.as_view(), name='mode_module_impacts'),
    path('mode-enforcement-decisions/', ModeEnforcementDecisionListView.as_view(), name='mode_enforcement_decisions'),
    path('mode-enforcement-decisions/<int:enforcement_decision_id>/', ModeEnforcementDecisionDetailView.as_view(), name='mode_enforcement_decision_detail'),
    path('mode-enforcement-recommendations/', ModeEnforcementRecommendationListView.as_view(), name='mode_enforcement_recommendations'),
    path('mode-enforcement-summary/', ModeEnforcementSummaryView.as_view(), name='mode_enforcement_summary'),
    path('run-runtime-feedback-review/', RunRuntimeFeedbackReviewView.as_view(), name='run_runtime_feedback_review'),
    path('runtime-feedback-runs/', RuntimeFeedbackRunListView.as_view(), name='runtime_feedback_runs'),
    path('runtime-performance-snapshots/', RuntimePerformanceSnapshotListView.as_view(), name='runtime_performance_snapshots'),
    path('runtime-diagnostic-reviews/', RuntimeDiagnosticReviewListView.as_view(), name='runtime_diagnostic_reviews'),
    path('runtime-feedback-decisions/', RuntimeFeedbackDecisionListView.as_view(), name='runtime_feedback_decisions'),
    path('runtime-feedback-decisions/<int:feedback_decision_id>/', RuntimeFeedbackDecisionDetailView.as_view(), name='runtime_feedback_decision_detail'),
    path('runtime-feedback-recommendations/', RuntimeFeedbackRecommendationListView.as_view(), name='runtime_feedback_recommendations'),
    path('runtime-feedback-summary/', RuntimeFeedbackSummaryView.as_view(), name='runtime_feedback_summary'),
    path('apply-runtime-feedback-decision/<int:decision_id>/', ApplyRuntimeFeedbackDecisionView.as_view(), name='apply_runtime_feedback_decision'),
]
