from django.urls import path

from apps.runtime_governor.views import (
    ApplyOperatingModeDecisionView,
    OperatingModeDecisionDetailView,
    OperatingModeDecisionListView,
    RunModeEnforcementReviewView,
    ModeEnforcementRunListView,
    ModeModuleImpactListView,
    ModeEnforcementDecisionListView,
    ModeEnforcementDecisionDetailView,
    ModeEnforcementRecommendationListView,
    ModeEnforcementSummaryView,
    ApplyRuntimeFeedbackDecisionView,
    OperatingModeRecommendationListView,
    OperatingModeSummaryView,
    OperatingModeSwitchRecordListView,
    RunOperatingModeReviewView,
    RuntimeCapabilitiesView,
    RuntimeModesView,
    RuntimePostureRunListView,
    RuntimePostureSnapshotListView,
    RuntimeSetModeView,
    RuntimeStatusView,
    RuntimeFeedbackDecisionDetailView,
    RuntimeFeedbackDecisionListView,
    RuntimeFeedbackRecommendationListView,
    RuntimeFeedbackRunListView,
    RuntimeDiagnosticReviewListView,
    RuntimeFeedbackSummaryView,
    RunRuntimeFeedbackApplyReviewView,
    RuntimeFeedbackApplyRunListView,
    RuntimeFeedbackApplyDecisionListView,
    RuntimeFeedbackApplyRecordListView,
    RuntimeFeedbackApplyRecommendationListView,
    RuntimeFeedbackApplySummaryView,
    ApplyStabilizedModeTransitionView,
    RunModeStabilizationReviewView,
    ModeStabilizationRunListView,
    ModeTransitionSnapshotListView,
    ModeStabilityReviewListView,
    ModeTransitionDecisionListView,
    ModeTransitionApplyRecordListView,
    ModeStabilizationRecommendationListView,
    ModeStabilizationSummaryView,
    RuntimePerformanceSnapshotListView,
    RuntimeTransitionListView,
    RuntimeTuningProfileSummaryView,
    RuntimeTuningProfileValuesView,
    RuntimeTuningContextSnapshotListView,
    RuntimeTuningContextDriftSummaryView,
    RuntimeTuningContextDiffListView,
    RuntimeTuningContextDiffDetailView,
    RuntimeTuningRunCorrelationListView,
    RuntimeTuningScopeDigestListView,
    RuntimeTuningChangeAlertListView,
    RuntimeTuningChangeAlertSummaryView,
    RuntimeTuningReviewBoardListView,
    RuntimeTuningReviewBoardDetailView,
    RuntimeTuningInvestigationDetailView,
    RuntimeTuningCockpitPanelListView,
    RuntimeTuningCockpitPanelDetailView,
    RunRuntimeFeedbackReviewView,
)

urlpatterns = [
    path('status/', RuntimeStatusView.as_view(), name='status'),
    path('modes/', RuntimeModesView.as_view(), name='modes'),
    path('set-mode/', RuntimeSetModeView.as_view(), name='set_mode'),
    path('transitions/', RuntimeTransitionListView.as_view(), name='transitions'),
    path('capabilities/', RuntimeCapabilitiesView.as_view(), name='capabilities'),
    path('tuning-profile-summary/', RuntimeTuningProfileSummaryView.as_view(), name='tuning_profile_summary'),
    path('tuning-profile-values/', RuntimeTuningProfileValuesView.as_view(), name='tuning_profile_values'),
    path('tuning-context-snapshots/', RuntimeTuningContextSnapshotListView.as_view(), name='tuning_context_snapshots'),
    path('tuning-context-drift-summary/', RuntimeTuningContextDriftSummaryView.as_view(), name='tuning_context_drift_summary'),
    path('tuning-context-diffs/', RuntimeTuningContextDiffListView.as_view(), name='tuning_context_diffs'),
    path('tuning-context-diffs/<int:snapshot_id>/', RuntimeTuningContextDiffDetailView.as_view(), name='tuning_context_diff_detail'),
    path('tuning-run-correlations/', RuntimeTuningRunCorrelationListView.as_view(), name='tuning_run_correlations'),
    path('tuning-scope-digest/', RuntimeTuningScopeDigestListView.as_view(), name='tuning_scope_digest'),
    path('tuning-change-alerts/', RuntimeTuningChangeAlertListView.as_view(), name='tuning_change_alerts'),
    path('tuning-change-alert-summary/', RuntimeTuningChangeAlertSummaryView.as_view(), name='tuning_change_alert_summary'),
    path('tuning-review-board/', RuntimeTuningReviewBoardListView.as_view(), name='tuning_review_board'),
    path('tuning-review-board/<str:source_scope>/', RuntimeTuningReviewBoardDetailView.as_view(), name='tuning_review_board_detail'),
    path('tuning-investigation/<str:source_scope>/', RuntimeTuningInvestigationDetailView.as_view(), name='tuning_investigation_detail'),
    path('tuning-cockpit-panel/', RuntimeTuningCockpitPanelListView.as_view(), name='tuning_cockpit_panel'),
    path('tuning-cockpit-panel/<str:source_scope>/', RuntimeTuningCockpitPanelDetailView.as_view(), name='tuning_cockpit_panel_detail'),
    path('run-operating-mode-review/', RunOperatingModeReviewView.as_view(), name='run_operating_mode_review'),
    path('runtime-posture-runs/', RuntimePostureRunListView.as_view(), name='runtime_posture_runs'),
    path('runtime-posture-snapshots/', RuntimePostureSnapshotListView.as_view(), name='runtime_posture_snapshots'),
    path('operating-mode-decisions/', OperatingModeDecisionListView.as_view(), name='operating_mode_decisions'),
    path('operating-mode-decisions/<int:decision_id>/', OperatingModeDecisionDetailView.as_view(), name='operating_mode_decision_detail'),
    path('operating-mode-switch-records/', OperatingModeSwitchRecordListView.as_view(), name='operating_mode_switch_records'),
    path('operating-mode-recommendations/', OperatingModeRecommendationListView.as_view(), name='operating_mode_recommendations'),
    path('operating-mode-summary/', OperatingModeSummaryView.as_view(), name='operating_mode_summary'),
    path('apply-operating-mode/<int:decision_id>/', ApplyOperatingModeDecisionView.as_view(), name='apply_operating_mode'),
    path('run-mode-enforcement-review/', RunModeEnforcementReviewView.as_view(), name='run_mode_enforcement_review'),
    path('mode-enforcement-runs/', ModeEnforcementRunListView.as_view(), name='mode_enforcement_runs'),
    path('mode-module-impacts/', ModeModuleImpactListView.as_view(), name='mode_module_impacts'),
    path('mode-enforcement-decisions/', ModeEnforcementDecisionListView.as_view(), name='mode_enforcement_decisions'),
    path('mode-enforcement-decisions/<int:enforcement_decision_id>/', ModeEnforcementDecisionDetailView.as_view(), name='mode_enforcement_decision_detail'),
    path('mode-enforcement-recommendations/', ModeEnforcementRecommendationListView.as_view(), name='mode_enforcement_recommendations'),
    path('mode-enforcement-summary/', ModeEnforcementSummaryView.as_view(), name='mode_enforcement_summary'),
    path('run-runtime-feedback-review/', RunRuntimeFeedbackReviewView.as_view(), name='run_runtime_feedback_review'),
    path('runtime-feedback-runs/', RuntimeFeedbackRunListView.as_view(), name='runtime_feedback_runs'),
    path('runtime-performance-snapshots/', RuntimePerformanceSnapshotListView.as_view(), name='runtime_performance_snapshots'),
    path('runtime-diagnostic-reviews/', RuntimeDiagnosticReviewListView.as_view(), name='runtime_diagnostic_reviews'),
    path('runtime-feedback-decisions/', RuntimeFeedbackDecisionListView.as_view(), name='runtime_feedback_decisions'),
    path('runtime-feedback-decisions/<int:feedback_decision_id>/', RuntimeFeedbackDecisionDetailView.as_view(), name='runtime_feedback_decision_detail'),
    path('runtime-feedback-recommendations/', RuntimeFeedbackRecommendationListView.as_view(), name='runtime_feedback_recommendations'),
    path('runtime-feedback-summary/', RuntimeFeedbackSummaryView.as_view(), name='runtime_feedback_summary'),
    path('apply-runtime-feedback-decision/<int:decision_id>/', ApplyRuntimeFeedbackDecisionView.as_view(), name='apply_runtime_feedback_decision'),
    path('run-runtime-feedback-apply-review/', RunRuntimeFeedbackApplyReviewView.as_view(), name='run_runtime_feedback_apply_review'),
    path('runtime-feedback-apply-runs/', RuntimeFeedbackApplyRunListView.as_view(), name='runtime_feedback_apply_runs'),
    path('runtime-feedback-apply-decisions/', RuntimeFeedbackApplyDecisionListView.as_view(), name='runtime_feedback_apply_decisions'),
    path('runtime-feedback-apply-records/', RuntimeFeedbackApplyRecordListView.as_view(), name='runtime_feedback_apply_records'),
    path('runtime-feedback-apply-recommendations/', RuntimeFeedbackApplyRecommendationListView.as_view(), name='runtime_feedback_apply_recommendations'),
    path('runtime-feedback-apply-summary/', RuntimeFeedbackApplySummaryView.as_view(), name='runtime_feedback_apply_summary'),
    path('run-mode-stabilization-review/', RunModeStabilizationReviewView.as_view(), name='run_mode_stabilization_review'),
    path('mode-stabilization-runs/', ModeStabilizationRunListView.as_view(), name='mode_stabilization_runs'),
    path('mode-transition-snapshots/', ModeTransitionSnapshotListView.as_view(), name='mode_transition_snapshots'),
    path('mode-stability-reviews/', ModeStabilityReviewListView.as_view(), name='mode_stability_reviews'),
    path('mode-transition-decisions/', ModeTransitionDecisionListView.as_view(), name='mode_transition_decisions'),
    path('apply-stabilized-mode-transition/<int:decision_id>/', ApplyStabilizedModeTransitionView.as_view(), name='apply_stabilized_mode_transition'),
    path('mode-transition-apply-records/', ModeTransitionApplyRecordListView.as_view(), name='mode_transition_apply_records'),
    path('mode-stabilization-recommendations/', ModeStabilizationRecommendationListView.as_view(), name='mode_stabilization_recommendations'),
    path('mode-stabilization-summary/', ModeStabilizationSummaryView.as_view(), name='mode_stabilization_summary'),
]
