# Generated by Django 5.1.4 on 2026-03-26 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("agent_type", models.CharField(max_length=50)),
                ("is_enabled", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("input_schema_version", models.CharField(default="v1", max_length=40)),
                (
                    "output_schema_version",
                    models.CharField(default="v1", max_length=40),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AgentPipelineRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pipeline_type",
                    models.CharField(
                        choices=[
                            ("research_to_prediction", "Research to Prediction"),
                            ("postmortem_to_learning", "Postmortem to Learning"),
                            ("real_market_agent_cycle", "Real-market Agent Cycle"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="READY",
                        max_length=12,
                    ),
                ),
                (
                    "triggered_from",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("automation", "Automation"),
                            ("continuous_demo", "Continuous Demo"),
                            ("real_ops", "Real Ops"),
                            ("replay", "Replay"),
                            ("experiment", "Experiment"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("agents_run_count", models.PositiveIntegerField(default=0)),
                ("handoffs_count", models.PositiveIntegerField(default=0)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="READY",
                        max_length=12,
                    ),
                ),
                (
                    "triggered_from",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("automation", "Automation"),
                            ("continuous_demo", "Continuous Demo"),
                            ("real_ops", "Real Ops"),
                            ("replay", "Replay"),
                            ("experiment", "Experiment"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "agent_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="agents.agentdefinition",
                    ),
                ),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to="agents.agentpipelinerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AgentHandoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("handoff_type", models.CharField(max_length=120)),
                ("payload_summary", models.CharField(blank=True, max_length=255)),
                ("payload_ref", models.JSONField(blank=True, default=dict)),
                (
                    "to_agent_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_handoffs",
                        to="agents.agentdefinition",
                    ),
                ),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handoffs",
                        to="agents.agentpipelinerun",
                    ),
                ),
                (
                    "from_agent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handoffs",
                        to="agents.agentrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
