# Generated by Django 5.1.4 on 2026-03-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentpipelinerun",
            name="pipeline_type",
            field=models.CharField(
                choices=[
                    ("research_to_prediction", "Research to Prediction"),
                    ("postmortem_to_learning", "Postmortem to Learning"),
                    ("real_market_agent_cycle", "Real-market Agent Cycle"),
                    ("postmortem_board_cycle", "Postmortem Board Cycle"),
                ],
                max_length=64,
            ),
        ),
    ]
