# Generated by Django 5.1.4 on 2026-03-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_alter_agentpipelinerun_pipeline_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentpipelinerun",
            name="pipeline_type",
            field=models.CharField(
                choices=[
                    ("research_universe_scan_cycle", "Research Universe Scan Cycle"),
                    ("research_triage_to_prediction", "Research Triage to Prediction"),
                    ("research_to_prediction", "Research to Prediction"),
                    (
                        "research_prediction_risk_signal_cycle",
                        "Research Prediction Risk Signal Cycle",
                    ),
                    ("signal_to_proposal_cycle", "Signal to Proposal Cycle"),
                    ("postmortem_to_learning", "Postmortem to Learning"),
                    ("real_market_agent_cycle", "Real-market Agent Cycle"),
                    ("postmortem_board_cycle", "Postmortem Board Cycle"),
                    ("opportunity_cycle_pipeline", "Opportunity Cycle Pipeline"),
                    (
                        "signal_to_proposal_execution_cycle",
                        "Signal to Proposal Execution Cycle",
                    ),
                ],
                max_length=64,
            ),
        ),
    ]
