# Generated by Django 5.1.4 on 2026-03-29 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autonomy_campaign", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsightRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("lifecycle_closed_count", models.PositiveIntegerField(default=0)),
                ("insight_count", models.PositiveIntegerField(default=0)),
                ("success_pattern_count", models.PositiveIntegerField(default=0)),
                ("failure_pattern_count", models.PositiveIntegerField(default=0)),
                ("blocker_pattern_count", models.PositiveIntegerField(default=0)),
                ("governance_pattern_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CampaignInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("success_pattern", "Success pattern"),
                            ("failure_pattern", "Failure pattern"),
                            ("blocker_pattern", "Blocker pattern"),
                            ("approval_pattern", "Approval pattern"),
                            ("incident_pattern", "Incident pattern"),
                            ("recovery_pattern", "Recovery pattern"),
                            ("rollout_pattern", "Rollout pattern"),
                            ("governance_pattern", "Governance pattern"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("campaign", "Campaign"),
                            ("domain", "Domain"),
                            ("cross_campaign", "Cross campaign"),
                        ],
                        default="campaign",
                        max_length=24,
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("evidence_summary", models.JSONField(blank=True, default=dict)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("recommended_followup", models.CharField(blank=True, max_length=255)),
                (
                    "recommendation_target",
                    models.CharField(
                        choices=[
                            ("memory", "Memory"),
                            ("roadmap", "Roadmap"),
                            ("scenario", "Scenario"),
                            ("program", "Program"),
                            ("manager", "Manager"),
                            ("operator_review", "Operator review"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("reviewed", models.BooleanField(default=False)),
                ("reviewed_by", models.CharField(blank=True, max_length=120)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insights",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InsightRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("REGISTER_MEMORY_PRECEDENT", "Register memory precedent"),
                            (
                                "PREPARE_ROADMAP_GOVERNANCE_NOTE",
                                "Prepare roadmap governance note",
                            ),
                            ("PREPARE_SCENARIO_CAUTION", "Prepare scenario caution"),
                            (
                                "PREPARE_PROGRAM_POLICY_NOTE",
                                "Prepare program policy note",
                            ),
                            ("REQUIRE_OPERATOR_REVIEW", "Require operator review"),
                            ("REORDER_INSIGHT_PRIORITY", "Reorder insight priority"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("success_pattern", "Success pattern"),
                            ("failure_pattern", "Failure pattern"),
                            ("blocker_pattern", "Blocker pattern"),
                            ("approval_pattern", "Approval pattern"),
                            ("incident_pattern", "Incident pattern"),
                            ("recovery_pattern", "Recovery pattern"),
                            ("rollout_pattern", "Rollout pattern"),
                            ("governance_pattern", "Governance pattern"),
                        ],
                        max_length=32,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign_insight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_insights.campaigninsight",
                    ),
                ),
                (
                    "target_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insight_recommendations",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "insight_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_insights.insightrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="campaigninsight",
            index=models.Index(
                fields=["insight_type", "-created_at"],
                name="autonomy_in_insight_6aa8a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaigninsight",
            index=models.Index(
                fields=["reviewed", "-created_at"],
                name="autonomy_in_reviewe_4e464f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="insightrecommendation",
            index=models.Index(
                fields=["recommendation_type", "-created_at"],
                name="autonomy_in_recomme_d6db8d_idx",
            ),
        ),
    ]
