# Generated by Django 5.1.4 on 2026-03-27 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("champion_challenger", "0001_initial"),
        ("promotion_committee", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="StackRolloutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("SHADOW_ONLY", "Shadow only"),
                            ("CANARY", "Canary"),
                            ("STAGED", "Staged"),
                        ],
                        default="CANARY",
                        max_length=16,
                    ),
                ),
                ("canary_percentage", models.PositiveSmallIntegerField(default=10)),
                (
                    "sampling_rule",
                    models.CharField(default="MARKET_HASH", max_length=32),
                ),
                ("profile_scope", models.CharField(blank=True, max_length=64)),
                ("guardrails", models.JSONField(blank=True, default=dict)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "candidate_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rollout_plans_as_candidate",
                        to="champion_challenger.stackprofilebinding",
                    ),
                ),
                (
                    "champion_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rollout_plans_as_champion",
                        to="champion_challenger.stackprofilebinding",
                    ),
                ),
                (
                    "source_review_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rollout_plans",
                        to="promotion_committee.promotionreviewrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StackRolloutRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("PAUSED", "Paused"),
                            ("COMPLETED", "Completed"),
                            ("ROLLED_BACK", "Rolled back"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                (
                    "current_phase",
                    models.CharField(default="INITIAL_CANARY", max_length=48),
                ),
                ("routed_opportunities_count", models.PositiveIntegerField(default=0)),
                ("champion_count", models.PositiveIntegerField(default=0)),
                ("challenger_count", models.PositiveIntegerField(default=0)),
                ("canary_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="rollout_manager.stackrolloutplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RolloutGuardrailEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("severity", models.CharField(default="WARNING", max_length=16)),
                ("reason", models.TextField(blank=True)),
                (
                    "metric_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardrail_events",
                        to="rollout_manager.stackrolloutrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RolloutDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("CONTINUE_ROLLOUT", "Continue rollout"),
                            ("PAUSE_ROLLOUT", "Pause rollout"),
                            ("ROLLBACK_NOW", "Rollback now"),
                            ("COMPLETE_PROMOTION", "Complete promotion"),
                            ("EXTEND_CANARY", "Extend canary"),
                        ],
                        max_length=32,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("recommendation_payload", models.JSONField(blank=True, default=dict)),
                ("actor", models.CharField(default="rollout_manager", max_length=64)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="rollout_manager.stackrolloutrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
