# Generated by Django 5.1.4 on 2026-03-26 23:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProfileGovernanceRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                (
                    "regime",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("STRESSED", "Stressed"),
                            ("CONCENTRATED", "Concentrated"),
                            ("DRAWDOWN_MODE", "Drawdown mode"),
                            ("DEFENSIVE", "Defensive"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="NORMAL",
                        max_length=24,
                    ),
                ),
                ("runtime_mode", models.CharField(blank=True, max_length=32)),
                ("readiness_status", models.CharField(blank=True, max_length=24)),
                ("safety_status", models.CharField(blank=True, max_length=24)),
                ("triggered_by", models.CharField(default="manual_api", max_length=64)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ManagedProfileBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("module_key", models.CharField(max_length=64)),
                (
                    "operating_mode",
                    models.CharField(
                        help_text="conservative, balanced, aggressive_light",
                        max_length=24,
                    ),
                ),
                ("profile_slug", models.CharField(max_length=96)),
                ("profile_label", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["module_key", "operating_mode", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("module_key", "operating_mode"),
                        name="profile_binding_unique_module_mode",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProfileDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_mode",
                    models.CharField(
                        choices=[
                            ("RECOMMEND_ONLY", "Recommend only"),
                            ("APPLY_SAFE", "Apply safe"),
                            ("APPLY_FORCED", "Apply forced"),
                        ],
                        default="RECOMMEND_ONLY",
                        max_length=20,
                    ),
                ),
                ("target_research_profile", models.CharField(max_length=96)),
                ("target_signal_profile", models.CharField(max_length=96)),
                (
                    "target_opportunity_supervisor_profile",
                    models.CharField(max_length=96),
                ),
                ("target_mission_control_profile", models.CharField(max_length=96)),
                ("target_portfolio_governor_profile", models.CharField(max_length=96)),
                (
                    "target_prediction_profile",
                    models.CharField(blank=True, max_length=96),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blocking_constraints", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_applied", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision",
                        to="profile_manager.profilegovernancerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
