# Generated by Django 5.1.4 on 2026-03-28 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autonomy_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomyCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("roadmap_plan", "Roadmap plan"),
                            ("scenario_run", "Scenario run"),
                            ("manual_bundle", "Manual bundle"),
                        ],
                        max_length=24,
                    ),
                ),
                ("source_object_id", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("PAUSED", "Paused"),
                            ("BLOCKED", "Blocked"),
                            ("COMPLETED", "Completed"),
                            ("ABORTED", "Aborted"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("current_wave", models.PositiveIntegerField(default=1)),
                ("total_steps", models.PositiveIntegerField(default=0)),
                ("completed_steps", models.PositiveIntegerField(default=0)),
                ("blocked_steps", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="autonomy_ca_status_847aae_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AutonomyCampaignStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_order", models.PositiveIntegerField()),
                ("wave", models.PositiveIntegerField(default=1)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("APPLY_TRANSITION", "Apply domain stage transition"),
                            ("START_ROLLOUT", "Start rollout observation"),
                            ("EVALUATE_ROLLOUT", "Evaluate rollout observation"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("WAITING_APPROVAL", "Waiting approval"),
                            ("OBSERVING", "Observing"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                            ("ABORTED", "Aborted"),
                        ],
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                ("rationale", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_steps",
                        to="autonomy_manager.autonomydomain",
                    ),
                ),
            ],
            options={
                "ordering": ["campaign_id", "step_order"],
            },
        ),
        migrations.CreateModel(
            name="AutonomyCampaignCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checkpoint_type",
                    models.CharField(
                        choices=[
                            ("APPROVAL_REQUIRED", "Approval required"),
                            ("ROLLOUT_OBSERVATION", "Rollout observation"),
                            ("DEPENDENCY_CONFLICT", "Dependency conflict"),
                            ("INCIDENT_BLOCK", "Incident/degraded block"),
                            ("MANUAL_REVIEW_REQUIRED", "Manual review required"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("SATISFIED", "Satisfied"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="autonomy_campaign.autonomycampaignstep",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="autonomycampaignstep",
            index=models.Index(
                fields=["campaign", "wave", "status"],
                name="autonomy_ca_campaig_824c4f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="autonomycampaignstep",
            unique_together={("campaign", "step_order")},
        ),
        migrations.AddIndex(
            model_name="autonomycampaigncheckpoint",
            index=models.Index(
                fields=["campaign", "status"], name="autonomy_ca_campaig_fada56_idx"
            ),
        ),
    ]
