# Generated by Django 5.1.4 on 2026-03-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemoAutomationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("simulate_tick", "Simulate tick"),
                            ("generate_signals", "Generate signals"),
                            ("revalue_portfolio", "Revalue portfolio"),
                            ("generate_trade_reviews", "Generate trade reviews"),
                            ("sync_demo_state", "Sync demo state"),
                            ("run_demo_cycle", "Run demo cycle"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "triggered_from",
                    models.CharField(
                        choices=[
                            ("automation_page", "Automation page"),
                            ("dashboard", "Dashboard"),
                            ("system", "System"),
                            ("api", "API"),
                        ],
                        default="api",
                        max_length=32,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
    ]
