# Generated by Django 5.1.4 on 2026-03-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation_demo", "0002_alter_demoautomationrun_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demoautomationrun",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("simulate_tick", "Simulate tick"),
                    ("generate_signals", "Generate signals"),
                    ("revalue_portfolio", "Revalue portfolio"),
                    ("generate_trade_reviews", "Generate trade reviews"),
                    ("sync_demo_state", "Sync demo state"),
                    ("run_demo_cycle", "Run demo cycle"),
                    ("rebuild_learning_memory", "Rebuild learning memory"),
                    ("run_full_learning_cycle", "Run full learning cycle"),
                    ("sync_real_data", "Sync real data (read-only)"),
                ],
                max_length=64,
            ),
        ),
    ]
