# Generated by Django 5.1.4 on 2026-03-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OperatorAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("approval_required", "Approval required"),
                            ("safety", "Safety"),
                            ("runtime", "Runtime"),
                            ("sync", "Sync"),
                            ("readiness", "Readiness"),
                            ("queue", "Queue"),
                            ("portfolio", "Portfolio"),
                            ("anomaly", "Anomaly"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                            ("SUPPRESSED", "Suppressed"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("operator_queue", "Operator queue"),
                            ("safety", "Safety"),
                            ("runtime", "Runtime"),
                            ("real_sync", "Real sync"),
                            ("continuous_demo", "Continuous demo"),
                            ("evaluation", "Evaluation"),
                            ("readiness", "Readiness"),
                            ("manual", "Manual"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "related_object_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("dedupe_key", models.CharField(blank=True, max_length=255, null=True)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-last_seen_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-last_seen_at"],
                        name="operator_al_status_52eead_idx",
                    ),
                    models.Index(
                        fields=["severity", "-last_seen_at"],
                        name="operator_al_severit_f07272_idx",
                    ),
                    models.Index(
                        fields=["source", "alert_type"],
                        name="operator_al_source_e9a219_idx",
                    ),
                    models.Index(
                        fields=["dedupe_key"], name="operator_al_dedupe__990ddd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OperatorDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "digest_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("session", "Session"),
                            ("manual", "Manual"),
                            ("cycle_window", "Cycle window"),
                        ],
                        default="session",
                        max_length=20,
                    ),
                ),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("summary", models.TextField(blank=True)),
                ("alerts_count", models.PositiveIntegerField(default=0)),
                ("critical_count", models.PositiveIntegerField(default=0)),
                ("approvals_pending_count", models.PositiveIntegerField(default=0)),
                ("safety_events_count", models.PositiveIntegerField(default=0)),
                ("runtime_changes_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-window_end", "-id"],
                "indexes": [
                    models.Index(
                        fields=["digest_type", "-window_end"],
                        name="operator_al_digest__99429e_idx",
                    )
                ],
            },
        ),
    ]
