# Generated by Django 5.1.4 on 2026-03-29 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autonomy_campaign", "0001_initial"),
        ("autonomy_launch", "0001_initial"),
        ("autonomy_scheduler", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("ready_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("expired_count", models.PositiveIntegerField(default=0)),
                ("dispatched_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("current_program_posture", models.CharField(max_length=20)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "active_window",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activation_runs",
                        to="autonomy_scheduler.changewindow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ActivationRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("DISPATCH_NOW", "Dispatch now"),
                            (
                                "REVALIDATE_BEFORE_DISPATCH",
                                "Revalidate before dispatch",
                            ),
                            ("HOLD_DISPATCH", "Hold dispatch"),
                            ("BLOCK_DISPATCH", "Block dispatch"),
                            ("WAIT_FOR_WINDOW", "Wait for window"),
                            ("EXPIRE_AUTHORIZATION", "Expire authorization"),
                            ("REORDER_DISPATCH_PRIORITY", "Reorder dispatch priority"),
                        ],
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("impacted_domains", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activation_recommendations",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "activation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_activation.activationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recommendation_type", "-created_at"],
                        name="autonomy_ac_recomme_0bfec6_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CampaignActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DISPATCHING", "Dispatching"),
                            ("STARTED", "Started"),
                            ("BLOCKED", "Blocked"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "trigger_source",
                    models.CharField(
                        choices=[
                            ("manual_ui", "Manual UI"),
                            ("manual_api", "Manual API"),
                            ("approval_resume", "Approval resume"),
                        ],
                        default="manual_api",
                        max_length=20,
                    ),
                ),
                ("dispatch_rationale", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("started_campaign_state", models.CharField(blank=True, max_length=24)),
                ("failure_message", models.CharField(blank=True, max_length=255)),
                ("activated_by", models.CharField(blank=True, max_length=120)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activations",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "launch_authorization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_activations",
                        to="autonomy_launch.launchauthorization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["campaign", "-created_at"],
                        name="autonomy_ac_campaig_cf7ab4_idx",
                    ),
                    models.Index(
                        fields=["activation_status", "-created_at"],
                        name="autonomy_ac_activat_397eba_idx",
                    ),
                ],
            },
        ),
    ]
