# Generated by Django 5.2.5 on 2026-03-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autonomy_campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('ready_to_resume_count', models.PositiveIntegerField(default=0)),
                ('keep_paused_count', models.PositiveIntegerField(default=0)),
                ('blocked_count', models.PositiveIntegerField(default=0)),
                ('review_abort_count', models.PositiveIntegerField(default=0)),
                ('close_candidate_count', models.PositiveIntegerField(default=0)),
                ('approval_required_count', models.PositiveIntegerField(default=0)),
                ('recommendation_summary', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.CreateModel(
            name='RecoverySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_campaign_status', models.CharField(max_length=24)),
                ('last_progress_at', models.DateTimeField(blank=True, null=True)),
                ('paused_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('blocker_count', models.PositiveIntegerField(default=0)),
                ('blocker_types', models.JSONField(blank=True, default=dict)),
                ('approvals_pending', models.BooleanField(default=False)),
                ('checkpoints_pending', models.BooleanField(default=False)),
                ('incident_pressure_level', models.PositiveIntegerField(default=0)),
                ('recovery_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('recovery_priority', models.PositiveIntegerField(default=0)),
                ('resume_readiness', models.CharField(choices=[('READY', 'Ready'), ('CAUTION', 'Caution'), ('NOT_READY', 'Not ready')], default='NOT_READY', max_length=16)),
                ('recovery_status', models.CharField(choices=[('READY_TO_RESUME', 'Ready to resume'), ('RECOVERY_IN_PROGRESS', 'Recovery in progress'), ('KEEP_PAUSED', 'Keep paused'), ('BLOCKED', 'Blocked'), ('REVIEW_ABORT', 'Review abort'), ('CLOSE_CANDIDATE', 'Close candidate')], default='KEEP_PAUSED', max_length=24)),
                ('rationale', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_snapshots', to='autonomy_campaign.autonomycampaign')),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.CreateModel(
            name='RecoveryRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation_type', models.CharField(choices=[('RESUME_CAMPAIGN', 'Resume campaign'), ('KEEP_PAUSED', 'Keep paused'), ('REQUIRE_MORE_RECOVERY', 'Require more recovery'), ('ESCALATE_TO_APPROVAL', 'Escalate to approval'), ('REVIEW_FOR_ABORT', 'Review for abort'), ('CLOSE_CAMPAIGN', 'Close campaign'), ('REORDER_RECOVERY_PRIORITY', 'Reorder recovery priority')], max_length=40)),
                ('rationale', models.CharField(max_length=255)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('impacted_domains', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recovery_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='autonomy_recovery.recoveryrun')),
                ('target_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_recommendations', to='autonomy_campaign.autonomycampaign')),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddIndex(model_name='recoverysnapshot', index=models.Index(fields=['campaign', '-created_at'], name='autonomy_rec_campaig_322dcf_idx')),
        migrations.AddIndex(model_name='recoverysnapshot', index=models.Index(fields=['recovery_status', '-created_at'], name='autonomy_rec_recover_83a4a5_idx')),
        migrations.AddIndex(model_name='recoveryrecommendation', index=models.Index(fields=['recommendation_type', '-created_at'], name='autonomy_rec_recomme_1af46d_idx')),
    ]
