# Generated by Django 5.1.4 on 2026-03-27 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("execution_simulator", "0001_initial"),
        ("markets", "0002_event_source_type_market_source_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerBridgeValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("VALID", "Valid"),
                            ("INVALID", "Invalid"),
                            ("MANUAL_REVIEW", "Manual review"),
                        ],
                        max_length=24,
                    ),
                ),
                ("is_valid", models.BooleanField(default=False)),
                ("requires_manual_review", models.BooleanField(default=False)),
                ("blocking_reasons", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("missing_fields", models.JSONField(blank=True, default=list)),
                ("checks", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BrokerOrderIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(default="paper_order", max_length=40)),
                ("source_id", models.CharField(blank=True, max_length=64)),
                ("source_ref", models.CharField(blank=True, max_length=128)),
                ("market_ref", models.CharField(blank=True, max_length=128)),
                ("symbol", models.CharField(blank=True, max_length=64)),
                ("side", models.CharField(max_length=24)),
                ("order_type", models.CharField(default="market", max_length=32)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "limit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("time_in_force", models.CharField(default="GTC", max_length=16)),
                (
                    "mapping_profile",
                    models.CharField(
                        default="generic_prediction_market", max_length=64
                    ),
                ),
                ("created_from", models.CharField(default="manual", max_length=48)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("VALIDATED", "Validated"),
                            ("REJECTED", "Rejected"),
                            ("DRY_RUN_READY", "Dry-run ready"),
                            ("DRY_RUN_EXECUTED", "Dry-run executed"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broker_intents",
                        to="markets.market",
                    ),
                ),
                (
                    "related_paper_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broker_intents",
                        to="execution_simulator.paperorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BrokerDryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "simulated_response",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("hold", "Hold"),
                            ("needs_manual_review", "Needs manual review"),
                        ],
                        max_length=32,
                    ),
                ),
                ("dry_run_summary", models.CharField(blank=True, max_length=255)),
                ("simulated_payload", models.JSONField(blank=True, default=dict)),
                (
                    "simulated_broker_response",
                    models.JSONField(blank=True, default=dict),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "validation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dry_runs",
                        to="broker_bridge.brokerbridgevalidation",
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dry_runs",
                        to="broker_bridge.brokerorderintent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="brokerbridgevalidation",
            name="intent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validations",
                to="broker_bridge.brokerorderintent",
            ),
        ),
        migrations.AddIndex(
            model_name="brokerorderintent",
            index=models.Index(
                fields=["status", "-created_at"], name="broker_brid_status_3b9d27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokerorderintent",
            index=models.Index(
                fields=["source_type", "source_id"],
                name="broker_brid_source__e51583_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brokerorderintent",
            index=models.Index(
                fields=["mapping_profile", "-created_at"],
                name="broker_brid_mapping_c12701_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brokerdryrun",
            index=models.Index(
                fields=["simulated_response", "-created_at"],
                name="broker_brid_simulat_329fbb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brokerbridgevalidation",
            index=models.Index(
                fields=["outcome", "-created_at"], name="broker_brid_outcome_8e601b_idx"
            ),
        ),
    ]
