# Generated by Django 5.1.2 on 2026-03-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('champion_challenger', '0001_initial'),
        ('readiness_lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionReviewRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=16)),
                ('decision_mode', models.CharField(choices=[('RECOMMENDATION_ONLY', 'Recommendation only'), ('MANUAL_APPLY', 'Manual apply')], default='RECOMMENDATION_ONLY', max_length=24)),
                ('readiness_status', models.CharField(blank=True, choices=[('READY', 'Ready'), ('CAUTION', 'Caution'), ('NOT_READY', 'Not ready')], max_length=24)),
                ('recommendation_code', models.CharField(choices=[('KEEP_CURRENT_CHAMPION', 'Keep current champion'), ('PROMOTE_CHALLENGER', 'Promote challenger'), ('EXTEND_SHADOW_TEST', 'Extend shadow test'), ('REVERT_TO_CONSERVATIVE_STACK', 'Revert to conservative stack'), ('MANUAL_REVIEW_REQUIRED', 'Manual review required')], max_length=40)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('rationale', models.TextField(blank=True)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('blocking_constraints', models.JSONField(blank=True, default=list)),
                ('evidence_summary', models.JSONField(blank=True, default=dict)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.CreateModel(
            name='PromotionDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(default='RECOMMENDATION_ISSUED', max_length=32)),
                ('actor', models.CharField(default='system', max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('review_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='promotion_committee.promotionreviewrun')),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.CreateModel(
            name='StackEvidenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('champion_challenger_summary', models.JSONField(blank=True, default=dict)),
                ('execution_aware_metrics', models.JSONField(blank=True, default=dict)),
                ('readiness_summary', models.JSONField(blank=True, default=dict)),
                ('profile_governance_context', models.JSONField(blank=True, default=dict)),
                ('portfolio_governor_context', models.JSONField(blank=True, default=dict)),
                ('model_governance_summary', models.JSONField(blank=True, default=dict)),
                ('precedent_warnings', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('challenger_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_challenger_evidence', to='champion_challenger.stackprofilebinding')),
                ('champion_binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_champion_evidence', to='champion_challenger.stackprofilebinding')),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='promotionreviewrun',
            name='evidence_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_review_runs', to='promotion_committee.stackevidencesnapshot'),
        ),
    ]
