# Generated by Django 5.1.4 on 2026-03-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("champion_challenger", "0001_initial"),
        ("experiment_lab", "0002_experimentcandidate_tuningexperimentrun_and_more"),
        ("tuning_board", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionReviewRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "Completed"), ("FAILED", "Failed")],
                        default="COMPLETED",
                        max_length=16,
                    ),
                ),
                (
                    "decision_mode",
                    models.CharField(
                        choices=[
                            ("RECOMMENDATION_ONLY", "Recommendation only"),
                            ("MANUAL_APPLY", "Manual apply"),
                        ],
                        default="RECOMMENDATION_ONLY",
                        max_length=24,
                    ),
                ),
                (
                    "readiness_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("READY", "Ready"),
                            ("CAUTION", "Caution"),
                            ("NOT_READY", "Not ready"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "recommendation_code",
                    models.CharField(
                        choices=[
                            ("KEEP_CURRENT_CHAMPION", "Keep current champion"),
                            ("PROMOTE_CHALLENGER", "Promote challenger"),
                            ("EXTEND_SHADOW_TEST", "Extend shadow test"),
                            (
                                "REVERT_TO_CONSERVATIVE_STACK",
                                "Revert to conservative stack",
                            ),
                            ("MANUAL_REVIEW_REQUIRED", "Manual review required"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blocking_constraints", models.JSONField(blank=True, default=list)),
                ("evidence_summary", models.JSONField(blank=True, default=dict)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PromotionReviewCycleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("ready_for_review_count", models.PositiveIntegerField(default=0)),
                ("needs_more_data_count", models.PositiveIntegerField(default=0)),
                ("deferred_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("high_priority_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_experiment_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_review_runs",
                        to="experiment_lab.tuningexperimentrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PromotionCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_component",
                    models.CharField(
                        choices=[
                            ("prediction", "Prediction"),
                            ("risk", "Risk"),
                            ("research", "Research"),
                            ("opportunity_cycle", "Opportunity cycle"),
                            ("calibration", "Calibration"),
                            ("learning", "Learning"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "target_scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("provider", "Provider"),
                            ("category", "Category"),
                            ("horizon_band", "Horizon band"),
                            ("model_mode", "Model mode"),
                            ("source_type", "Source type"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("threshold_update", "Threshold update"),
                            ("calibration_update", "Calibration update"),
                            ("risk_gate_update", "Risk gate update"),
                            ("size_cap_update", "Size cap update"),
                            ("shortlist_update", "Shortlist update"),
                            ("conviction_update", "Conviction update"),
                            ("caution_weight_update", "Caution weight update"),
                            ("review_rule_update", "Review rule update"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "case_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("READY_FOR_REVIEW", "Ready for review"),
                            ("NEEDS_MORE_DATA", "Needs more data"),
                            ("DEFERRED", "Deferred"),
                            ("REJECTED", "Rejected"),
                            (
                                "APPROVED_FOR_MANUAL_ADOPTION",
                                "Approved for manual adoption",
                            ),
                        ],
                        default="PROPOSED",
                        max_length=40,
                    ),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                ("current_value", models.CharField(blank=True, max_length=128)),
                ("proposed_value", models.CharField(blank=True, max_length=128)),
                ("rationale", models.CharField(max_length=255)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_cases",
                        to="tuning_board.tuningproposalbundle",
                    ),
                ),
                (
                    "linked_comparison",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_cases",
                        to="experiment_lab.tuningchampionchallengercomparison",
                    ),
                ),
                (
                    "linked_experiment_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_cases",
                        to="experiment_lab.experimentcandidate",
                    ),
                ),
                (
                    "linked_tuning_proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_cases",
                        to="tuning_board.tuningproposal",
                    ),
                ),
                (
                    "review_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="promotion_committee.promotionreviewcyclerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PromotionDecisionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(default="RECOMMENDATION_ISSUED", max_length=32),
                ),
                ("actor", models.CharField(default="system", max_length=64)),
                ("notes", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "review_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_logs",
                        to="promotion_committee.promotionreviewrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StackEvidenceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "champion_challenger_summary",
                    models.JSONField(blank=True, default=dict),
                ),
                ("execution_aware_metrics", models.JSONField(blank=True, default=dict)),
                ("readiness_summary", models.JSONField(blank=True, default=dict)),
                (
                    "profile_governance_context",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "portfolio_governor_context",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "model_governance_summary",
                    models.JSONField(blank=True, default=dict),
                ),
                ("precedent_warnings", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "challenger_binding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_challenger_evidence",
                        to="champion_challenger.stackprofilebinding",
                    ),
                ),
                (
                    "champion_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_champion_evidence",
                        to="champion_challenger.stackprofilebinding",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="promotionreviewrun",
            name="evidence_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="promotion_review_runs",
                to="promotion_committee.stackevidencesnapshot",
            ),
        ),
        migrations.CreateModel(
            name="PromotionEvidencePack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("summary", models.CharField(max_length=255)),
                ("linked_metrics", models.JSONField(blank=True, default=dict)),
                ("linked_comparisons", models.JSONField(blank=True, default=dict)),
                ("linked_recommendations", models.JSONField(blank=True, default=dict)),
                ("sample_count", models.PositiveIntegerField(default=0)),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "risk_of_adoption_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "expected_benefit_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "evidence_status",
                    models.CharField(
                        choices=[
                            ("STRONG", "Strong"),
                            ("MIXED", "Mixed"),
                            ("WEAK", "Weak"),
                            ("INSUFFICIENT", "Insufficient"),
                        ],
                        default="INSUFFICIENT",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_promotion_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_packs",
                        to="promotion_committee.promotioncase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["evidence_status", "-created_at"],
                        name="promotion_c_evidenc_8fce8d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PromotionDecisionRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            (
                                "APPROVE_FOR_MANUAL_ADOPTION",
                                "Approve for manual adoption",
                            ),
                            ("DEFER_FOR_MORE_EVIDENCE", "Defer for more evidence"),
                            ("REJECT_CHANGE", "Reject change"),
                            ("REQUIRE_COMMITTEE_REVIEW", "Require committee review"),
                            ("SPLIT_SCOPE_AND_RETEST", "Split scope and retest"),
                            (
                                "GROUP_WITH_RELATED_CHANGES",
                                "Group with related changes",
                            ),
                            (
                                "REORDER_PROMOTION_PRIORITY",
                                "Reorder promotion priority",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decision_recommendations",
                        to="promotion_committee.promotioncase",
                    ),
                ),
                (
                    "review_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_recommendations",
                        to="promotion_committee.promotionreviewcyclerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recommendation_type", "-created_at"],
                        name="promotion_c_recomme_b653e3_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="promotioncase",
            index=models.Index(
                fields=["case_status", "-created_at"],
                name="promotion_c_case_st_6c8749_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promotioncase",
            index=models.Index(
                fields=["priority_level", "-created_at"],
                name="promotion_c_priorit_1af4b4_idx",
            ),
        ),
    ]
