# Generated by Django 5.1.4 on 2026-03-30 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotion_committee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdoptionActionCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_component",
                    models.CharField(
                        choices=[
                            ("prediction", "Prediction"),
                            ("risk", "Risk"),
                            ("research", "Research"),
                            ("opportunity_cycle", "Opportunity cycle"),
                            ("calibration", "Calibration"),
                            ("learning", "Learning"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "target_scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("provider", "Provider"),
                            ("category", "Category"),
                            ("horizon_band", "Horizon band"),
                            ("model_mode", "Model mode"),
                            ("source_type", "Source type"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("threshold_update", "Threshold update"),
                            ("calibration_update", "Calibration update"),
                            ("risk_gate_update", "Risk gate update"),
                            ("size_cap_update", "Size cap update"),
                            ("shortlist_update", "Shortlist update"),
                            ("conviction_update", "Conviction update"),
                            ("caution_weight_update", "Caution weight update"),
                            ("review_rule_update", "Review rule update"),
                        ],
                        max_length=32,
                    ),
                ),
                ("current_value", models.CharField(blank=True, max_length=128)),
                ("proposed_value", models.CharField(blank=True, max_length=128)),
                (
                    "target_resolution_status",
                    models.CharField(
                        choices=[
                            ("RESOLVED", "Resolved"),
                            ("PARTIAL", "Partial"),
                            ("BLOCKED", "Blocked"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                ("ready_for_action", models.BooleanField(default=False)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_promotion_case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adoption_candidate",
                        to="promotion_committee.promotioncase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ManualAdoptionAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            (
                                "APPLY_POLICY_TUNING_CHANGE",
                                "Apply policy tuning change",
                            ),
                            (
                                "APPLY_TRUST_CALIBRATION_CHANGE",
                                "Apply trust calibration change",
                            ),
                            (
                                "APPLY_STACK_BINDING_CHANGE",
                                "Apply stack binding change",
                            ),
                            ("PREPARE_ROLLOUT_PLAN", "Prepare rollout plan"),
                            ("RECORD_MANUAL_ADOPTION", "Record manual adoption"),
                            ("REQUIRE_TARGET_MAPPING", "Require target mapping"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "action_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("READY_TO_APPLY", "Ready to apply"),
                            ("APPLIED", "Applied"),
                            ("BLOCKED", "Blocked"),
                            ("DEFERRED", "Deferred"),
                            ("ROLLBACK_AVAILABLE", "Rollback available"),
                        ],
                        default="PROPOSED",
                        max_length=24,
                    ),
                ),
                (
                    "target_component",
                    models.CharField(
                        choices=[
                            ("prediction", "Prediction"),
                            ("risk", "Risk"),
                            ("research", "Research"),
                            ("opportunity_cycle", "Opportunity cycle"),
                            ("calibration", "Calibration"),
                            ("learning", "Learning"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "target_scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("provider", "Provider"),
                            ("category", "Category"),
                            ("horizon_band", "Horizon band"),
                            ("model_mode", "Model mode"),
                            ("source_type", "Source type"),
                        ],
                        max_length=24,
                    ),
                ),
                ("current_value_snapshot", models.JSONField(blank=True, default=dict)),
                ("proposed_value_snapshot", models.JSONField(blank=True, default=dict)),
                ("applied_by", models.CharField(blank=True, max_length=64)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                (
                    "linked_target_artifact",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="promotion_committee.adoptionactioncandidate",
                    ),
                ),
                (
                    "linked_promotion_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adoption_actions",
                        to="promotion_committee.promotioncase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AdoptionRollbackPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rollback_type",
                    models.CharField(
                        choices=[
                            ("REVERT_VALUE", "Revert value"),
                            ("RESTORE_BINDING", "Restore binding"),
                            ("CANCEL_ROLLOUT_PLAN", "Cancel rollout plan"),
                            ("RETURN_TO_BASELINE", "Return to baseline"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "rollback_status",
                    models.CharField(
                        choices=[
                            ("PREPARED", "Prepared"),
                            ("AVAILABLE", "Available"),
                            ("EXECUTED", "Executed"),
                            ("NOT_NEEDED", "Not needed"),
                        ],
                        default="PREPARED",
                        max_length=16,
                    ),
                ),
                (
                    "rollback_target_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_manual_action",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollback_plan",
                        to="promotion_committee.manualadoptionaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PromotionAdoptionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("ready_to_apply_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("applied_count", models.PositiveIntegerField(default=0)),
                ("rollback_plan_count", models.PositiveIntegerField(default=0)),
                ("rollout_handoff_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_promotion_review_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adoption_runs",
                        to="promotion_committee.promotionreviewcyclerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="manualadoptionaction",
            name="adoption_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="promotion_committee.promotionadoptionrun",
            ),
        ),
        migrations.CreateModel(
            name="AdoptionActionRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("APPLY_CHANGE_MANUALLY", "Apply change manually"),
                            ("PREPARE_ROLLOUT_PLAN", "Prepare rollout plan"),
                            ("REQUIRE_TARGET_MAPPING", "Require target mapping"),
                            ("DEFER_ADOPTION", "Defer adoption"),
                            ("PREPARE_ROLLBACK", "Prepare rollback"),
                            ("REQUIRE_COMMITTEE_RECHECK", "Require committee recheck"),
                            ("REORDER_ADOPTION_PRIORITY", "Reorder adoption priority"),
                        ],
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_promotion_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adoption_recommendations",
                        to="promotion_committee.promotioncase",
                    ),
                ),
                (
                    "target_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="promotion_committee.manualadoptionaction",
                    ),
                ),
                (
                    "adoption_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adoption_recommendations",
                        to="promotion_committee.promotionadoptionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="adoptionactioncandidate",
            name="adoption_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="promotion_committee.promotionadoptionrun",
            ),
        ),
        migrations.AddIndex(
            model_name="manualadoptionaction",
            index=models.Index(
                fields=["action_status", "-created_at"],
                name="promotion_c_action__283c47_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adoptionactioncandidate",
            index=models.Index(
                fields=["target_resolution_status", "-created_at"],
                name="promotion_c_target__84c932_idx",
            ),
        ),
    ]
