# Generated by Django 5.1.4 on 2026-03-30 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "promotion_committee",
            "0002_adoptionactioncandidate_manualadoptionaction_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualRolloutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rollout_plan_type",
                    models.CharField(
                        choices=[
                            ("DIRECT_CONFIG_APPLY", "Direct config apply"),
                            ("STAGED_BINDING_ROLLOUT", "Staged binding rollout"),
                            ("SHADOW_CONFIG_ROLLOUT", "Shadow config rollout"),
                            ("TRUST_CALIBRATION_ROLLOUT", "Trust calibration rollout"),
                            ("POLICY_TUNING_ROLLOUT", "Policy tuning rollout"),
                        ],
                        default="DIRECT_CONFIG_APPLY",
                        max_length=36,
                    ),
                ),
                (
                    "rollout_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("READY", "Ready"),
                            ("EXECUTED", "Executed"),
                            ("BLOCKED", "Blocked"),
                            ("DEFERRED", "Deferred"),
                            ("ROLLBACK_AVAILABLE", "Rollback available"),
                        ],
                        default="PROPOSED",
                        max_length=20,
                    ),
                ),
                (
                    "target_component",
                    models.CharField(
                        choices=[
                            ("prediction", "Prediction"),
                            ("risk", "Risk"),
                            ("research", "Research"),
                            ("opportunity_cycle", "Opportunity cycle"),
                            ("calibration", "Calibration"),
                            ("learning", "Learning"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "target_scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("provider", "Provider"),
                            ("category", "Category"),
                            ("horizon_band", "Horizon band"),
                            ("model_mode", "Model mode"),
                            ("source_type", "Source type"),
                        ],
                        max_length=24,
                    ),
                ),
                ("rollout_rationale", models.CharField(max_length=255)),
                ("staged_steps", models.JSONField(blank=True, default=list)),
                ("monitoring_intent", models.JSONField(blank=True, default=dict)),
                (
                    "linked_rollout_artifact",
                    models.CharField(blank=True, max_length=255),
                ),
                ("executed_by", models.CharField(blank=True, max_length=64)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_manual_adoption_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollout_plans",
                        to="promotion_committee.manualadoptionaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ManualRollbackExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("EXECUTED", "Executed"),
                            ("BLOCKED", "Blocked"),
                            ("NOT_NEEDED", "Not needed"),
                        ],
                        default="READY",
                        max_length=16,
                    ),
                ),
                (
                    "rollback_type",
                    models.CharField(
                        choices=[
                            ("REVERT_VALUE", "Revert value"),
                            ("RESTORE_BINDING", "Restore binding"),
                            ("CANCEL_ROLLOUT_PLAN", "Cancel rollout plan"),
                            ("RETURN_TO_BASELINE", "Return to baseline"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "rollback_target_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                ("executed_by", models.CharField(blank=True, max_length=64)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("rationale", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_manual_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollback_executions",
                        to="promotion_committee.manualadoptionaction",
                    ),
                ),
                (
                    "linked_rollback_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_executions",
                        to="promotion_committee.adoptionrollbackplan",
                    ),
                ),
                (
                    "linked_rollout_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rollback_executions",
                        to="promotion_committee.manualrolloutplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RolloutActionCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_component",
                    models.CharField(
                        choices=[
                            ("prediction", "Prediction"),
                            ("risk", "Risk"),
                            ("research", "Research"),
                            ("opportunity_cycle", "Opportunity cycle"),
                            ("calibration", "Calibration"),
                            ("learning", "Learning"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "target_scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("provider", "Provider"),
                            ("category", "Category"),
                            ("horizon_band", "Horizon band"),
                            ("model_mode", "Model mode"),
                            ("source_type", "Source type"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            (
                                "APPLY_POLICY_TUNING_CHANGE",
                                "Apply policy tuning change",
                            ),
                            (
                                "APPLY_TRUST_CALIBRATION_CHANGE",
                                "Apply trust calibration change",
                            ),
                            (
                                "APPLY_STACK_BINDING_CHANGE",
                                "Apply stack binding change",
                            ),
                            ("PREPARE_ROLLOUT_PLAN", "Prepare rollout plan"),
                            ("RECORD_MANUAL_ADOPTION", "Record manual adoption"),
                            ("REQUIRE_TARGET_MAPPING", "Require target mapping"),
                        ],
                        max_length=40,
                    ),
                ),
                ("current_value_snapshot", models.JSONField(blank=True, default=dict)),
                ("proposed_value_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "rollout_need_level",
                    models.CharField(
                        choices=[
                            ("DIRECT_APPLY_OK", "Direct apply ok"),
                            ("ROLLOUT_RECOMMENDED", "Rollout recommended"),
                            ("ROLLOUT_REQUIRED", "Rollout required"),
                        ],
                        default="ROLLOUT_RECOMMENDED",
                        max_length=24,
                    ),
                ),
                (
                    "target_resolution_status",
                    models.CharField(
                        choices=[
                            ("RESOLVED", "Resolved"),
                            ("PARTIAL", "Partial"),
                            ("BLOCKED", "Blocked"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                ("ready_for_rollout", models.BooleanField(default=False)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_manual_adoption_action",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollout_candidate",
                        to="promotion_committee.manualadoptionaction",
                    ),
                ),
                (
                    "linked_promotion_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollout_candidates",
                        to="promotion_committee.promotioncase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="manualrolloutplan",
            name="linked_candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rollout_plans",
                to="promotion_committee.rolloutactioncandidate",
            ),
        ),
        migrations.CreateModel(
            name="RolloutCheckpointPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checkpoint_type",
                    models.CharField(
                        choices=[
                            ("pre_apply_check", "Pre apply check"),
                            ("post_apply_check", "Post apply check"),
                            ("metric_drift_check", "Metric drift check"),
                            ("calibration_check", "Calibration check"),
                            ("risk_gate_check", "Risk gate check"),
                            ("proposal_quality_check", "Proposal quality check"),
                            ("rollback_readiness_check", "Rollback readiness check"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "checkpoint_status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PLANNED",
                        max_length=16,
                    ),
                ),
                ("checkpoint_rationale", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_rollout_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoint_plans",
                        to="promotion_committee.manualrolloutplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RolloutPreparationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("rollout_ready_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("checkpoint_count", models.PositiveIntegerField(default=0)),
                ("rollback_ready_count", models.PositiveIntegerField(default=0)),
                ("rollback_executed_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_adoption_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rollout_preparation_runs",
                        to="promotion_committee.promotionadoptionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RolloutPreparationRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("PREPARE_MANUAL_ROLLOUT", "Prepare manual rollout"),
                            ("DIRECT_APPLY_OK", "Direct apply ok"),
                            (
                                "REQUIRE_ROLLOUT_CHECKPOINTS",
                                "Require rollout checkpoints",
                            ),
                            ("ROLLBACK_READY", "Rollback ready"),
                            ("EXECUTE_ROLLBACK_MANUALLY", "Execute rollback manually"),
                            ("REQUIRE_TARGET_RECHECK", "Require target recheck"),
                            ("DEFER_ROLLOUT", "Defer rollout"),
                            ("REORDER_ROLLOUT_PRIORITY", "Reorder rollout priority"),
                        ],
                        max_length=36,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="promotion_committee.rolloutactioncandidate",
                    ),
                ),
                (
                    "target_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="promotion_committee.manualrolloutplan",
                    ),
                ),
                (
                    "preparation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollout_recommendations",
                        to="promotion_committee.rolloutpreparationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="rolloutactioncandidate",
            name="preparation_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="promotion_committee.rolloutpreparationrun",
            ),
        ),
    ]
