# Generated by Django 5.1.4 on 2026-03-30 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "promotion_committee",
            "0003_manualrolloutplan_manualrollbackexecution_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RolloutExecutionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("EXECUTING", "Executing"),
                            ("EXECUTED", "Executed"),
                            ("PAUSED", "Paused"),
                            ("FAILED", "Failed"),
                            ("ROLLBACK_RECOMMENDED", "Rollback recommended"),
                            ("REVERTED", "Reverted"),
                        ],
                        default="READY",
                        max_length=24,
                    ),
                ),
                ("executed_step_count", models.PositiveIntegerField(default=0)),
                ("executed_by", models.CharField(blank=True, max_length=64)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_notes", models.TextField(blank=True)),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_rollout_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_record",
                        to="promotion_committee.manualrolloutplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PostRolloutStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("CAUTION", "Caution"),
                            ("REVIEW_REQUIRED", "Review required"),
                            ("ROLLBACK_RECOMMENDED", "Rollback recommended"),
                            ("REVERTED", "Reverted"),
                            ("INCOMPLETE", "Incomplete"),
                        ],
                        max_length=24,
                    ),
                ),
                ("status_rationale", models.CharField(max_length=255)),
                (
                    "linked_checkpoint_outcomes",
                    models.JSONField(blank=True, default=list),
                ),
                ("observed_drift_flags", models.JSONField(blank=True, default=list)),
                ("observed_risk_flags", models.JSONField(blank=True, default=list)),
                (
                    "observed_calibration_flags",
                    models.JSONField(blank=True, default=list),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_rollout_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_rollout_statuses",
                        to="promotion_committee.rolloutexecutionrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CheckpointOutcomeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outcome_status",
                    models.CharField(
                        choices=[
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("WARNING", "Warning"),
                            ("SKIPPED", "Skipped"),
                        ],
                        max_length=16,
                    ),
                ),
                ("observed_metrics", models.JSONField(blank=True, default=dict)),
                ("outcome_rationale", models.CharField(max_length=255)),
                (
                    "triggered_action",
                    models.CharField(
                        choices=[
                            ("CONTINUE", "Continue"),
                            ("PAUSE", "Pause"),
                            ("REQUIRE_REVIEW", "Require review"),
                            ("RECOMMEND_ROLLBACK", "Recommend rollback"),
                        ],
                        max_length=24,
                    ),
                ),
                ("recorded_by", models.CharField(blank=True, max_length=64)),
                ("recorded_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_checkpoint_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcome_records",
                        to="promotion_committee.rolloutcheckpointplan",
                    ),
                ),
                (
                    "linked_rollout_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoint_outcomes",
                        to="promotion_committee.rolloutexecutionrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RolloutExecutionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("plan_count", models.PositiveIntegerField(default=0)),
                ("executed_count", models.PositiveIntegerField(default=0)),
                ("paused_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("rollback_recommended_count", models.PositiveIntegerField(default=0)),
                ("rollback_executed_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_rollout_preparation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_runs",
                        to="promotion_committee.rolloutpreparationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="rolloutexecutionrecord",
            name="execution_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="execution_records",
                to="promotion_committee.rolloutexecutionrun",
            ),
        ),
        migrations.CreateModel(
            name="RolloutExecutionRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("EXECUTE_NEXT_STAGE", "Execute next stage"),
                            ("PAUSE_AND_REVIEW", "Pause and review"),
                            ("MARK_ROLLOUT_HEALTHY", "Mark rollout healthy"),
                            ("RECOMMEND_MANUAL_ROLLBACK", "Recommend manual rollback"),
                            ("REQUIRE_MORE_OBSERVATION", "Require more observation"),
                            ("CLOSE_ROLLOUT", "Close rollout"),
                            (
                                "REORDER_ROLLOUT_EXECUTION_PRIORITY",
                                "Reorder rollout execution priority",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="promotion_committee.rolloutexecutionrecord",
                    ),
                ),
                (
                    "execution_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_recommendations",
                        to="promotion_committee.rolloutexecutionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
