# Generated by Django 5.1.4 on 2026-03-27 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("broker_bridge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VenueCapabilityProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adapter_name",
                    models.CharField(
                        default="null_sandbox", max_length=64, unique=True
                    ),
                ),
                (
                    "venue_name",
                    models.CharField(default="sandbox_venue", max_length=64),
                ),
                ("supports_market_like", models.BooleanField(default=True)),
                ("supports_limit_like", models.BooleanField(default=True)),
                ("supports_reduce_only", models.BooleanField(default=True)),
                ("supports_close_order", models.BooleanField(default=True)),
                ("supports_partial_updates", models.BooleanField(default=False)),
                ("requires_symbol_mapping", models.BooleanField(default=True)),
                ("requires_manual_confirmation", models.BooleanField(default=False)),
                ("paper_only_supported", models.BooleanField(default=True)),
                ("live_supported", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["adapter_name", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VenueOrderPayload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("venue_name", models.CharField(max_length=64)),
                ("external_market_id", models.CharField(blank=True, max_length=128)),
                ("side", models.CharField(max_length=32)),
                ("order_type", models.CharField(max_length=32)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "limit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("tif", models.CharField(blank=True, max_length=16)),
                ("reduce_only", models.BooleanField(default=False)),
                ("close_flag", models.BooleanField(default=False)),
                ("source_intent_id", models.PositiveIntegerField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venue_payloads",
                        to="broker_bridge.brokerorderintent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VenueOrderResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_order_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "normalized_status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("HOLD", "Hold"),
                            ("REQUIRES_CONFIRMATION", "Requires confirmation"),
                            ("UNSUPPORTED", "Unsupported"),
                            ("INVALID_PAYLOAD", "Invalid payload"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venue_responses",
                        to="broker_bridge.brokerorderintent",
                    ),
                ),
                (
                    "payload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="execution_venue.venueorderpayload",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VenueParityRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parity_status",
                    models.CharField(
                        choices=[
                            ("PARITY_OK", "Parity ok"),
                            ("PARITY_GAP", "Parity gap"),
                        ],
                        max_length=24,
                    ),
                ),
                ("issues", models.JSONField(blank=True, default=list)),
                ("missing_fields", models.JSONField(blank=True, default=list)),
                ("unsupported_actions", models.JSONField(blank=True, default=list)),
                ("readiness_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "bridge_dry_run_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "simulator_order_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venue_parity_runs",
                        to="broker_bridge.brokerorderintent",
                    ),
                ),
                (
                    "payload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parity_runs",
                        to="execution_venue.venueorderpayload",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parity_runs",
                        to="execution_venue.venueorderresponse",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="venueorderpayload",
            index=models.Index(
                fields=["venue_name", "-created_at"],
                name="execution_v_venue_n_bd6a8e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="venueorderpayload",
            index=models.Index(
                fields=["source_intent_id", "-created_at"],
                name="execution_v_source__b69f88_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="venueorderresponse",
            index=models.Index(
                fields=["normalized_status", "-created_at"],
                name="execution_v_normali_7983c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="venueparityrun",
            index=models.Index(
                fields=["parity_status", "-created_at"],
                name="execution_v_parity__06d506_idx",
            ),
        ),
    ]
