# Generated by Django 5.1.4 on 2026-03-27 20:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("broker_bridge", "0001_initial"),
        ("execution_simulator", "0001_initial"),
        ("paper_trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VenueAccountSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "venue_name",
                    models.CharField(default="sandbox_venue", max_length=64),
                ),
                (
                    "account_reference",
                    models.CharField(default="sandbox-account-001", max_length=128),
                ),
                (
                    "account_mode",
                    models.CharField(
                        choices=[("SANDBOX_ONLY", "Sandbox only")],
                        default="SANDBOX_ONLY",
                        max_length=24,
                    ),
                ),
                (
                    "equity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "cash_available",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "reserved_cash",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("open_positions_count", models.PositiveIntegerField(default=0)),
                ("open_orders_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VenueReconciliationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PARITY_OK", "Parity ok"),
                            ("PARITY_GAP", "Parity gap"),
                        ],
                        default="PARITY_OK",
                        max_length=24,
                    ),
                ),
                ("positions_compared", models.PositiveIntegerField(default=0)),
                ("orders_compared", models.PositiveIntegerField(default=0)),
                ("balances_compared", models.PositiveIntegerField(default=0)),
                ("mismatches_count", models.PositiveIntegerField(default=0)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VenueBalanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "available",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "reserved",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "account_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="venue_account.venueaccountsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VenueOrderSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_intent_ref_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("external_order_id", models.CharField(max_length=128, unique=True)),
                ("instrument_ref", models.CharField(max_length=128)),
                ("side", models.CharField(max_length=24)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                (
                    "filled_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                (
                    "remaining_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("OPEN", "Open"),
                            ("PARTIALLY_FILLED", "Partially filled"),
                            ("FILLED", "Filled"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("last_response_status", models.CharField(blank=True, max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "source_intent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="venue_order_snapshots",
                        to="broker_bridge.brokerorderintent",
                    ),
                ),
                (
                    "source_paper_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="venue_order_snapshots",
                        to="execution_simulator.paperorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-updated_at"],
                        name="venue_accou_status_9cacb9_idx",
                    ),
                    models.Index(
                        fields=["source_intent_ref_id", "-updated_at"],
                        name="venue_accou_source__8cfe14_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VenuePositionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_instrument_ref", models.CharField(max_length=128)),
                ("side", models.CharField(max_length=24)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                (
                    "avg_entry_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=12
                    ),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "source_internal_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="venue_position_snapshots",
                        to="paper_trading.paperposition",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-updated_at"],
                        name="venue_accou_status_a51445_idx",
                    ),
                    models.Index(
                        fields=["external_instrument_ref", "side"],
                        name="venue_accou_externa_2217fe_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VenueReconciliationIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("missing_external_order", "Missing external order"),
                            ("missing_internal_order", "Missing internal order"),
                            ("fill_quantity_mismatch", "Fill quantity mismatch"),
                            ("status_mismatch", "Status mismatch"),
                            ("balance_drift", "Balance drift"),
                            (
                                "position_quantity_mismatch",
                                "Position quantity mismatch",
                            ),
                            ("unsupported_mapping", "Unsupported mapping"),
                            ("stale_snapshot", "Stale snapshot"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("HIGH", "High"),
                        ],
                        default="WARNING",
                        max_length=12,
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("source_refs", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "reconciliation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="venue_account.venuereconciliationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["issue_type", "-created_at"],
                        name="venue_accou_issue_t_9b8738_idx",
                    )
                ],
            },
        ),
    ]
