# Generated by Django 5.1.4 on 2026-03-27 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomationPolicyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("recommendation_mode", models.BooleanField(default=False)),
                ("allow_runbook_auto_advance", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="AutomationPolicyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_type", models.CharField(max_length=80)),
                ("source_context_type", models.CharField(blank=True, max_length=80)),
                (
                    "trust_tier",
                    models.CharField(
                        choices=[
                            ("MANUAL_ONLY", "Manual only"),
                            ("APPROVAL_REQUIRED", "Approval required"),
                            ("SAFE_AUTOMATION", "Safe automation"),
                            ("AUTO_BLOCKED", "Auto blocked"),
                        ],
                        max_length=32,
                    ),
                ),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("rationale", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="automation_policy.automationpolicyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["profile_id", "action_type", "source_context_type", "id"],
            },
        ),
        migrations.CreateModel(
            name="AutomationDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_type", models.CharField(max_length=80)),
                ("source_context_type", models.CharField(blank=True, max_length=80)),
                (
                    "runbook_instance_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("runbook_step_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "trust_tier",
                    models.CharField(
                        choices=[
                            ("MANUAL_ONLY", "Manual only"),
                            ("APPROVAL_REQUIRED", "Approval required"),
                            ("SAFE_AUTOMATION", "Safe automation"),
                            ("AUTO_BLOCKED", "Auto blocked"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "effective_trust_tier",
                    models.CharField(
                        choices=[
                            ("MANUAL_ONLY", "Manual only"),
                            ("APPROVAL_REQUIRED", "Approval required"),
                            ("SAFE_AUTOMATION", "Safe automation"),
                            ("AUTO_BLOCKED", "Auto blocked"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("ALLOWED", "Allowed"),
                            ("APPROVAL_REQUIRED", "Approval required"),
                            ("MANUAL_ONLY", "Manual only"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("rationale", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions",
                        to="automation_policy.automationpolicyprofile",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions",
                        to="automation_policy.automationpolicyrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutomationActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_runbook_instance_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "source_runbook_step_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("action_name", models.CharField(max_length=120)),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("EXECUTED", "Executed"),
                            ("SKIPPED", "Skipped"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("result_summary", models.CharField(blank=True, max_length=255)),
                ("output_refs", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="automation_policy.automationdecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["execution_status", "-created_at"],
                        name="automation__executi_b77a81_idx",
                    ),
                    models.Index(
                        fields=["action_name", "-created_at"],
                        name="automation__action__af63b0_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="automationpolicyrule",
            constraint=models.UniqueConstraint(
                fields=("profile", "action_type", "source_context_type"),
                name="automation_policy_rule_unique_profile_action_context",
            ),
        ),
        migrations.AddIndex(
            model_name="automationdecision",
            index=models.Index(
                fields=["action_type", "-created_at"],
                name="automation__action__77e7a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationdecision",
            index=models.Index(
                fields=["outcome", "-created_at"], name="automation__outcome_6de7e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationdecision",
            index=models.Index(
                fields=["effective_trust_tier", "-created_at"],
                name="automation__effecti_7248ab_idx",
            ),
        ),
    ]
