# Generated by Django 5.1.4 on 2026-03-27 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdapterQualificationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("adapter_name", models.CharField(max_length=64)),
                ("adapter_type", models.CharField(default="sandbox", max_length=64)),
                (
                    "qualification_status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("capability_checks_run", models.PositiveIntegerField(default=0)),
                ("payload_checks_run", models.PositiveIntegerField(default=0)),
                ("response_checks_run", models.PositiveIntegerField(default=0)),
                ("account_mirror_checks_run", models.PositiveIntegerField(default=0)),
                ("reconciliation_checks_run", models.PositiveIntegerField(default=0)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ConnectorFixtureProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=96)),
                ("description", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="AdapterReadinessRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("SANDBOX_CERTIFIED", "Sandbox certified"),
                            ("READ_ONLY_PREPARED", "Read-only prepared"),
                            ("INCOMPLETE_MAPPING", "Incomplete mapping"),
                            ("RECONCILIATION_GAPS", "Reconciliation gaps"),
                            ("MANUAL_REVIEW_REQUIRED", "Manual review required"),
                            ("NOT_READY", "Not ready"),
                        ],
                        default="NOT_READY",
                        max_length=32,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("missing_capabilities", models.JSONField(blank=True, default=list)),
                ("unsupported_paths", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "qualification_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readiness_recommendation",
                        to="connector_lab.adapterqualificationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="adapterqualificationrun",
            name="fixture_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qualification_runs",
                to="connector_lab.connectorfixtureprofile",
            ),
        ),
        migrations.CreateModel(
            name="AdapterQualificationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("case_code", models.CharField(max_length=64)),
                ("case_group", models.CharField(max_length=32)),
                (
                    "result_status",
                    models.CharField(
                        choices=[
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("UNSUPPORTED", "Unsupported"),
                            ("WARNING", "Warning"),
                        ],
                        max_length=16,
                    ),
                ),
                ("issues", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "qualification_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="connector_lab.adapterqualificationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["case_code", "result_status"],
                        name="connector_l_case_co_3cd573_idx",
                    )
                ],
            },
        ),
    ]
