# Generated by Django 5.1.4 on 2026-03-28 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("runbook_checkpoint", "Runbook checkpoint"),
                            ("go_live_request", "Go-live request"),
                            ("operator_queue_item", "Operator queue item"),
                            ("rollout_decision", "Rollout decision"),
                            ("promotion_review", "Promotion review"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("source_object_id", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("ESCALATED", "Escalated"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("requested_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-requested_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-requested_at"],
                        name="approval_ce_status_8ffb59_idx",
                    ),
                    models.Index(
                        fields=["priority", "-requested_at"],
                        name="approval_ce_priorit_2b688b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_type", "source_object_id"),
                        name="approval_request_unique_source_binding",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ApprovalDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("EXPIRE", "Expire"),
                            ("ESCALATE", "Escalate"),
                        ],
                        max_length=16,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                (
                    "decided_by",
                    models.CharField(default="local-operator", max_length=120),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "approval_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="approval_center.approvalrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["approval_request", "-created_at"],
                        name="approval_ce_approva_394dbc_idx",
                    )
                ],
            },
        ),
    ]
