# Generated by Django 5.1.4 on 2026-03-26 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("paper_trading", "0001_initial"),
        ("risk_agent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionLifecycleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="READY",
                        max_length=12,
                    ),
                ),
                ("watched_positions", models.PositiveIntegerField(default=0)),
                ("decisions_count", models.PositiveIntegerField(default=0)),
                ("hold_count", models.PositiveIntegerField(default=0)),
                ("reduce_count", models.PositiveIntegerField(default=0)),
                ("close_count", models.PositiveIntegerField(default=0)),
                ("review_required_count", models.PositiveIntegerField(default=0)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PositionLifecycleDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HOLD", "Hold"),
                            ("REDUCE", "Reduce"),
                            ("CLOSE", "Close"),
                            ("REVIEW_REQUIRED", "Review required"),
                            ("BLOCK_ADD", "Block add"),
                            ("EXPIRED", "Expired"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "decision_confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("risk_context", models.JSONField(blank=True, default=dict)),
                ("prediction_context", models.JSONField(blank=True, default=dict)),
                ("narrative_context", models.JSONField(blank=True, default=dict)),
                ("position_snapshot", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "latest_watch_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lifecycle_decisions",
                        to="risk_agent.positionwatchevent",
                    ),
                ),
                (
                    "paper_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lifecycle_decisions",
                        to="paper_trading.paperposition",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="position_manager.positionlifecyclerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PositionExitPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("HOLD", "Hold"),
                            ("REDUCE", "Reduce"),
                            ("CLOSE", "Close"),
                            ("REVIEW_REQUIRED", "Review required"),
                            ("BLOCK_ADD", "Block add"),
                            ("EXPIRED", "Expired"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "target_quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "quantity_delta",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "execution_mode",
                    models.CharField(default="paper_only", max_length=24),
                ),
                ("queue_required", models.BooleanField(default=False)),
                ("auto_execute_allowed", models.BooleanField(default=False)),
                (
                    "final_recommended_action",
                    models.CharField(
                        choices=[
                            ("HOLD", "Hold"),
                            ("REDUCE", "Reduce"),
                            ("CLOSE", "Close"),
                            ("REVIEW_REQUIRED", "Review required"),
                            ("BLOCK_ADD", "Block add"),
                            ("EXPIRED", "Expired"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "execution_path",
                    models.CharField(default="record_only", max_length=48),
                ),
                ("explanation", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "paper_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exit_plans",
                        to="paper_trading.paperposition",
                    ),
                ),
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exit_plan",
                        to="position_manager.positionlifecycledecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
