from django.urls import path

from apps.certification_board.views import (
    BaselineBindingSnapshotListView,
    BaselineConfirmationCandidateListView,
    BaselineConfirmationRecommendationListView,
    BaselineConfirmationSummaryView,
    ConfirmPaperBaselineView,
    CertificationCandidateListView,
    CertificationDecisionListView,
    CertificationEvidencePackListView,
    CertificationApplyView,
    CertificationRecommendationListView,
    CertificationRunDetailView,
    CertificationRunListView,
    CertificationRunReviewView,
    CertificationSummaryView,
    CurrentCertificationView,
    PostRolloutCertificationSummaryView,
    PaperBaselineConfirmationListView,
    RollbackPaperBaselineView,
    RunBaselineConfirmationReviewView,
    RunPostRolloutCertificationReviewView,
)

urlpatterns = [
    path('run-review/', CertificationRunReviewView.as_view(), name='run-review'),
    path('runs/', CertificationRunListView.as_view(), name='runs'),
    path('runs/<int:pk>/', CertificationRunDetailView.as_view(), name='run-detail'),
    path('current/', CurrentCertificationView.as_view(), name='current'),
    path('summary/', CertificationSummaryView.as_view(), name='summary'),
    path('apply/<int:pk>/', CertificationApplyView.as_view(), name='apply'),
    path('run-post-rollout-review/', RunPostRolloutCertificationReviewView.as_view(), name='run-post-rollout-review'),
    path('candidates/', CertificationCandidateListView.as_view(), name='candidates'),
    path('evidence-packs/', CertificationEvidencePackListView.as_view(), name='evidence-packs'),
    path('decisions/', CertificationDecisionListView.as_view(), name='decisions'),
    path('recommendations/', CertificationRecommendationListView.as_view(), name='recommendations'),
    path('post-rollout-summary/', PostRolloutCertificationSummaryView.as_view(), name='post-rollout-summary'),
    path('run-baseline-confirmation/', RunBaselineConfirmationReviewView.as_view(), name='run-baseline-confirmation'),
    path('baseline-candidates/', BaselineConfirmationCandidateListView.as_view(), name='baseline-candidates'),
    path('baseline-confirmations/', PaperBaselineConfirmationListView.as_view(), name='baseline-confirmations'),
    path('binding-snapshots/', BaselineBindingSnapshotListView.as_view(), name='binding-snapshots'),
    path('baseline-recommendations/', BaselineConfirmationRecommendationListView.as_view(), name='baseline-recommendations'),
    path('baseline-summary/', BaselineConfirmationSummaryView.as_view(), name='baseline-summary'),
    path('confirm-baseline/<int:decision_id>/', ConfirmPaperBaselineView.as_view(), name='confirm-baseline'),
    path('rollback-baseline/<int:confirmation_id>/', RollbackPaperBaselineView.as_view(), name='rollback-baseline'),
]
