from django.urls import path

from apps.certification_board.views import (
    ActivePaperBindingRecordListView,
    ActivatePaperBaselineView,
    BaselineActivationCandidateListView,
    BaselineActivationRecommendationListView,
    BaselineActivationSummaryView,
    BaselineHealthCandidateListView,
    BaselineHealthRecommendationListView,
    BaselineHealthSignalListView,
    BaselineHealthStatusListView,
    BaselineHealthSummaryView,
    BaselineResponseCaseListView,
    BaselineResponseRecommendationListView,
    BaselineResponseSummaryView,
    BaselineBindingSnapshotListView,
    BaselineConfirmationCandidateListView,
    BaselineConfirmationRecommendationListView,
    BaselineConfirmationSummaryView,
    ConfirmPaperBaselineView,
    CertificationCandidateListView,
    CertificationDecisionListView,
    CertificationEvidencePackListView,
    CertificationApplyView,
    CertificationRecommendationListView,
    CertificationRunDetailView,
    CertificationRunListView,
    CertificationRunReviewView,
    CertificationSummaryView,
    CurrentCertificationView,
    PaperBaselineActivationListView,
    PostRolloutCertificationSummaryView,
    PaperBaselineConfirmationListView,
    RollbackBaselineActivationView,
    RollbackPaperBaselineView,
    RunBaselineActivationReviewView,
    RunBaselineHealthReviewView,
    RunBaselineResponseReviewView,
    RunBaselineConfirmationReviewView,
    RunPostRolloutCertificationReviewView,
    ResponseEvidencePackListView,
    ResponseRoutingDecisionListView,
)

urlpatterns = [
    path('run-review/', CertificationRunReviewView.as_view(), name='run-review'),
    path('runs/', CertificationRunListView.as_view(), name='runs'),
    path('runs/<int:pk>/', CertificationRunDetailView.as_view(), name='run-detail'),
    path('current/', CurrentCertificationView.as_view(), name='current'),
    path('summary/', CertificationSummaryView.as_view(), name='summary'),
    path('apply/<int:pk>/', CertificationApplyView.as_view(), name='apply'),
    path('run-post-rollout-review/', RunPostRolloutCertificationReviewView.as_view(), name='run-post-rollout-review'),
    path('candidates/', CertificationCandidateListView.as_view(), name='candidates'),
    path('evidence-packs/', CertificationEvidencePackListView.as_view(), name='evidence-packs'),
    path('decisions/', CertificationDecisionListView.as_view(), name='decisions'),
    path('recommendations/', CertificationRecommendationListView.as_view(), name='recommendations'),
    path('post-rollout-summary/', PostRolloutCertificationSummaryView.as_view(), name='post-rollout-summary'),
    path('run-baseline-confirmation/', RunBaselineConfirmationReviewView.as_view(), name='run-baseline-confirmation'),
    path('baseline-candidates/', BaselineConfirmationCandidateListView.as_view(), name='baseline-candidates'),
    path('baseline-confirmations/', PaperBaselineConfirmationListView.as_view(), name='baseline-confirmations'),
    path('binding-snapshots/', BaselineBindingSnapshotListView.as_view(), name='binding-snapshots'),
    path('baseline-recommendations/', BaselineConfirmationRecommendationListView.as_view(), name='baseline-recommendations'),
    path('baseline-summary/', BaselineConfirmationSummaryView.as_view(), name='baseline-summary'),
    path('confirm-baseline/<int:decision_id>/', ConfirmPaperBaselineView.as_view(), name='confirm-baseline'),
    path('rollback-baseline/<int:confirmation_id>/', RollbackPaperBaselineView.as_view(), name='rollback-baseline'),
    path('run-baseline-activation/', RunBaselineActivationReviewView.as_view(), name='run-baseline-activation'),
    path('activation-candidates/', BaselineActivationCandidateListView.as_view(), name='activation-candidates'),
    path('baseline-activations/', PaperBaselineActivationListView.as_view(), name='baseline-activations'),
    path('active-bindings/', ActivePaperBindingRecordListView.as_view(), name='active-bindings'),
    path('activation-recommendations/', BaselineActivationRecommendationListView.as_view(), name='activation-recommendations'),
    path('activation-summary/', BaselineActivationSummaryView.as_view(), name='activation-summary'),
    path('run-baseline-health-review/', RunBaselineHealthReviewView.as_view(), name='run-baseline-health-review'),
    path('health-candidates/', BaselineHealthCandidateListView.as_view(), name='health-candidates'),
    path('health-status/', BaselineHealthStatusListView.as_view(), name='health-status'),
    path('health-signals/', BaselineHealthSignalListView.as_view(), name='health-signals'),
    path('health-recommendations/', BaselineHealthRecommendationListView.as_view(), name='health-recommendations'),
    path('health-summary/', BaselineHealthSummaryView.as_view(), name='health-summary'),
    path('run-baseline-response-review/', RunBaselineResponseReviewView.as_view(), name='run-baseline-response-review'),
    path('response-cases/', BaselineResponseCaseListView.as_view(), name='response-cases'),
    path('response-evidence-packs/', ResponseEvidencePackListView.as_view(), name='response-evidence-packs'),
    path('response-routing-decisions/', ResponseRoutingDecisionListView.as_view(), name='response-routing-decisions'),
    path('response-recommendations/', BaselineResponseRecommendationListView.as_view(), name='response-recommendations'),
    path('response-summary/', BaselineResponseSummaryView.as_view(), name='response-summary'),
    path('activate-baseline/<int:confirmation_id>/', ActivatePaperBaselineView.as_view(), name='activate-baseline'),
    path('rollback-activation/<int:activation_id>/', RollbackBaselineActivationView.as_view(), name='rollback-activation'),
]
