# Generated by Django 5.1.4 on 2026-03-24 19:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContinuousDemoSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_status",
                    models.CharField(
                        choices=[
                            ("IDLE", "Idle"),
                            ("RUNNING", "Running"),
                            ("PAUSED", "Paused"),
                            ("STOPPED", "Stopped"),
                            ("FAILED", "Failed"),
                        ],
                        default="IDLE",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("last_cycle_at", models.DateTimeField(blank=True, null=True)),
                ("total_cycles", models.PositiveIntegerField(default=0)),
                ("total_auto_executed", models.PositiveIntegerField(default=0)),
                ("total_pending_approvals", models.PositiveIntegerField(default=0)),
                ("total_blocked", models.PositiveIntegerField(default=0)),
                ("total_errors", models.PositiveIntegerField(default=0)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("settings_snapshot", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LoopRuntimeControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "runtime_status",
                    models.CharField(
                        choices=[
                            ("IDLE", "Idle"),
                            ("RUNNING", "Running"),
                            ("PAUSED", "Paused"),
                            ("STOPPED", "Stopped"),
                        ],
                        default="IDLE",
                        max_length=12,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("kill_switch", models.BooleanField(default=False)),
                ("stop_requested", models.BooleanField(default=False)),
                ("pause_requested", models.BooleanField(default=False)),
                ("cycle_in_progress", models.BooleanField(default=False)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("default_settings", models.JSONField(blank=True, default=dict)),
                (
                    "active_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_records",
                        to="continuous_demo.continuousdemosession",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ContinuousDemoCycleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cycle_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="SUCCESS",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("actions_run", models.JSONField(blank=True, default=list)),
                ("markets_evaluated", models.PositiveIntegerField(default=0)),
                ("proposals_generated", models.PositiveIntegerField(default=0)),
                ("auto_executed_count", models.PositiveIntegerField(default=0)),
                ("approval_required_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycles",
                        to="continuous_demo.continuousdemosession",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "cycle_number"),
                        name="continuous_demo_session_cycle_number_uniq",
                    )
                ],
            },
        ),
    ]
