# Generated by Django 5.1.4 on 2026-03-27 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RunbookInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_object_type", models.CharField(max_length=80)),
                ("source_object_id", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In progress"),
                            ("BLOCKED", "Blocked"),
                            ("COMPLETED", "Completed"),
                            ("ABORTED", "Aborted"),
                            ("ESCALATED", "Escalated"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=12,
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RunbookTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("trigger_type", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                ("severity_hint", models.CharField(blank=True, max_length=24)),
                ("is_enabled", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="RunbookStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_order", models.PositiveIntegerField()),
                ("step_type", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=160)),
                ("instructions", models.TextField(blank=True)),
                (
                    "action_kind",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("api_action", "API action"),
                            ("review", "Review"),
                            ("confirm", "Confirm"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "runbook_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="runbook_engine.runbookinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["step_order", "id"],
                "unique_together": {("runbook_instance", "step_order")},
            },
        ),
        migrations.CreateModel(
            name="RunbookActionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_name", models.CharField(max_length=120)),
                (
                    "action_status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("result_summary", models.CharField(blank=True, max_length=255)),
                ("output_refs", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "runbook_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_results",
                        to="runbook_engine.runbookstep",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="runbookinstance",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instances",
                to="runbook_engine.runbooktemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="runbookinstance",
            index=models.Index(
                fields=["status", "-updated_at"], name="runbook_eng_status_0b1d5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="runbookinstance",
            index=models.Index(
                fields=["source_object_type", "source_object_id"],
                name="runbook_eng_source__7b09bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="runbookinstance",
            index=models.Index(
                fields=["priority", "-updated_at"],
                name="runbook_eng_priorit_d44dea_idx",
            ),
        ),
    ]
