# Generated by Django 5.1.4 on 2026-03-27 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runbook_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunbookAutopilotRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("PAUSED_FOR_APPROVAL", "Paused for approval"),
                            ("BLOCKED", "Blocked"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("ABORTED", "Aborted"),
                        ],
                        default="RUNNING",
                        max_length=32,
                    ),
                ),
                ("steps_evaluated", models.PositiveIntegerField(default=0)),
                ("steps_auto_executed", models.PositiveIntegerField(default=0)),
                ("steps_waiting_manual", models.PositiveIntegerField(default=0)),
                ("steps_blocked", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "runbook_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autopilot_runs",
                        to="runbook_engine.runbookinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RunbookApprovalCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approval_reason", models.CharField(max_length=255)),
                ("blocking_constraints", models.JSONField(blank=True, default=list)),
                ("context_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by", models.CharField(blank=True, max_length=120)),
                (
                    "runbook_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_checkpoints",
                        to="runbook_engine.runbookinstance",
                    ),
                ),
                (
                    "runbook_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_checkpoints",
                        to="runbook_engine.runbookstep",
                    ),
                ),
                (
                    "autopilot_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_checkpoints",
                        to="runbook_engine.runbookautopilotrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RunbookAutopilotStepResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt", models.PositiveIntegerField(default=1)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("AUTO_EXECUTED", "Auto executed"),
                            ("APPROVAL_REQUIRED", "Approval required"),
                            ("MANUAL_ONLY", "Manual only"),
                            ("BLOCKED", "Blocked"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "automation_decision_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "automation_action_log_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("rationale", models.CharField(blank=True, max_length=255)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "autopilot_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_results",
                        to="runbook_engine.runbookautopilotrun",
                    ),
                ),
                (
                    "runbook_action_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="runbook_engine.runbookactionresult",
                    ),
                ),
                (
                    "runbook_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autopilot_results",
                        to="runbook_engine.runbookstep",
                    ),
                ),
            ],
            options={
                "ordering": ["runbook_step__step_order", "attempt", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="runbookautopilotrun",
            index=models.Index(
                fields=["status", "-created_at"], name="runbook_eng_status_a86225_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="runbookapprovalcheckpoint",
            index=models.Index(
                fields=["status", "-created_at"], name="runbook_eng_status_ac92d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="runbookautopilotstepresult",
            index=models.Index(
                fields=["autopilot_run", "runbook_step", "attempt"],
                name="runbook_eng_autopil_b52d18_idx",
            ),
        ),
    ]
