# Generated by Django 5.1.4 on 2026-03-29 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autonomy_advisory", "0001_initial"),
        ("autonomy_backlog", "0001_initial"),
        ("autonomy_campaign", "0001_initial"),
        ("autonomy_insights", "0001_initial"),
        ("autonomy_intake", "0001_initial"),
        ("autonomy_planning_review", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("ready_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("registered_count", models.PositiveIntegerField(default=0)),
                ("duplicate_skipped_count", models.PositiveIntegerField(default=0)),
                ("roadmap_decision_count", models.PositiveIntegerField(default=0)),
                ("scenario_decision_count", models.PositiveIntegerField(default=0)),
                ("program_decision_count", models.PositiveIntegerField(default=0)),
                ("manager_decision_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("ROADMAP_DECISION_PACKAGE", "Roadmap decision package"),
                            ("SCENARIO_DECISION_PACKAGE", "Scenario decision package"),
                            ("PROGRAM_DECISION_PACKAGE", "Program decision package"),
                            ("MANAGER_DECISION_NOTE", "Manager decision note"),
                            ("OPERATOR_DECISION_NOTE", "Operator decision note"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending review"),
                            ("READY", "Ready"),
                            ("REGISTERED", "Registered"),
                            ("BLOCKED", "Blocked"),
                            ("DUPLICATE_SKIPPED", "Duplicate skipped"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=24,
                    ),
                ),
                (
                    "target_scope",
                    models.CharField(
                        choices=[
                            ("roadmap", "Roadmap"),
                            ("scenario", "Scenario"),
                            ("program", "Program"),
                            ("manager", "Manager"),
                            ("operator_review", "Operator review"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("registered_by", models.CharField(blank=True, max_length=120)),
                ("registered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "linked_target_artifact",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "advisory_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="governance_decisions",
                        to="autonomy_advisory.advisoryartifact",
                    ),
                ),
                (
                    "backlog_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="governance_decisions",
                        to="autonomy_backlog.governancebacklogitem",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="governance_decisions",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "insight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="governance_decisions",
                        to="autonomy_insights.campaigninsight",
                    ),
                ),
                (
                    "planning_proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="governance_decisions",
                        to="autonomy_intake.planningproposal",
                    ),
                ),
                (
                    "planning_resolution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="governance_decisions",
                        to="autonomy_planning_review.planningproposalresolution",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DecisionRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ROADMAP_DECISION_PACKAGE", "Roadmap decision package"),
                            ("SCENARIO_DECISION_PACKAGE", "Scenario decision package"),
                            ("PROGRAM_DECISION_PACKAGE", "Program decision package"),
                            ("MANAGER_DECISION_NOTE", "Manager decision note"),
                            ("OPERATOR_DECISION_NOTE", "Operator decision note"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("REGISTER_ROADMAP_DECISION", "Register roadmap decision"),
                            (
                                "REGISTER_SCENARIO_DECISION",
                                "Register scenario decision",
                            ),
                            ("REGISTER_PROGRAM_DECISION", "Register program decision"),
                            ("REGISTER_MANAGER_DECISION", "Register manager decision"),
                            ("SKIP_DUPLICATE_DECISION", "Skip duplicate decision"),
                            (
                                "REQUIRE_MANUAL_DECISION_REVIEW",
                                "Require manual decision review",
                            ),
                            ("REORDER_DECISION_PRIORITY", "Reorder decision priority"),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "planning_proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decision_recommendations",
                        to="autonomy_intake.planningproposal",
                    ),
                ),
                (
                    "decision_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_decision.decisionrun",
                    ),
                ),
                (
                    "governance_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_decision.governancedecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="governancedecision",
            index=models.Index(
                fields=["planning_proposal", "target_scope", "-updated_at"],
                name="autonomy_de_plannin_9626b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="governancedecision",
            index=models.Index(
                fields=["decision_status", "-updated_at"],
                name="autonomy_de_decisio_2e0689_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="governancedecision",
            index=models.Index(
                fields=["target_scope", "priority_level", "-updated_at"],
                name="autonomy_de_target__0f7ebb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="decisionrecommendation",
            index=models.Index(
                fields=["recommendation_type", "-created_at"],
                name="autonomy_de_recomme_a4b042_idx",
            ),
        ),
    ]
