# Generated by Django 5.1.4 on 2026-03-26 20:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0002_event_source_type_market_source_type"),
        ("operator_queue", "0001_initial"),
        ("paper_trading", "0001_initial"),
        ("proposal_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityCycleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("profile_slug", models.CharField(blank=True, max_length=64)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("markets_scanned", models.PositiveIntegerField(default=0)),
                ("opportunities_built", models.PositiveIntegerField(default=0)),
                ("proposals_generated", models.PositiveIntegerField(default=0)),
                ("allocation_ready_count", models.PositiveIntegerField(default=0)),
                ("queued_count", models.PositiveIntegerField(default=0)),
                ("auto_executed_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityCycleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_provider", models.CharField(blank=True, max_length=64)),
                ("research_context", models.JSONField(blank=True, default=dict)),
                ("prediction_context", models.JSONField(blank=True, default=dict)),
                ("risk_context", models.JSONField(blank=True, default=dict)),
                ("signal_context", models.JSONField(blank=True, default=dict)),
                ("proposal_status", models.CharField(blank=True, max_length=32)),
                ("allocation_status", models.CharField(blank=True, max_length=32)),
                (
                    "allocation_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "execution_path",
                    models.CharField(
                        choices=[
                            ("WATCH", "Watch"),
                            ("PROPOSAL_ONLY", "Proposal only"),
                            ("QUEUE", "Queue"),
                            ("AUTO_EXECUTE_PAPER", "Auto execute paper"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="WATCH",
                        max_length=24,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_cycle_items",
                        to="markets.market",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunity_cycle_items",
                        to="proposal_engine.tradeproposal",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="opportunity_supervisor.opportunitycyclerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityExecutionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("runtime_mode", models.CharField(blank=True, max_length=24)),
                ("policy_decision", models.CharField(blank=True, max_length=24)),
                ("safety_status", models.CharField(blank=True, max_length=24)),
                ("queue_required", models.BooleanField(default=False)),
                ("auto_execute_allowed", models.BooleanField(default=False)),
                (
                    "final_recommended_action",
                    models.CharField(
                        choices=[
                            ("WATCH", "Watch"),
                            ("PROPOSAL_ONLY", "Proposal only"),
                            ("QUEUE", "Queue"),
                            ("AUTO_EXECUTE_PAPER", "Auto execute paper"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=24,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_plan",
                        to="opportunity_supervisor.opportunitycycleitem",
                    ),
                ),
                (
                    "paper_trade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_plans",
                        to="paper_trading.papertrade",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_plans",
                        to="proposal_engine.tradeproposal",
                    ),
                ),
                (
                    "queue_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_plans",
                        to="operator_queue.operatorqueueitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
