# Generated by Django 5.1.4 on 2026-03-30 02:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0002_event_source_type_market_source_type"),
        ("opportunity_supervisor", "0001_initial"),
        (
            "prediction_agent",
            "0002_predictionruntimerun_predictionruntimecandidate_and_more",
        ),
        ("proposal_engine", "0001_initial"),
        ("research_agent", "0006_marketuniverserun_marketresearchcandidate_and_more"),
        ("risk_agent", "0002_riskruntimerun_riskruntimecandidate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityCycleRuntimeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("fused_count", models.PositiveIntegerField(default=0)),
                ("ready_for_proposal_count", models.PositiveIntegerField(default=0)),
                ("watch_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("sent_to_proposal_count", models.PositiveIntegerField(default=0)),
                (
                    "sent_to_execution_sim_context_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityFusionCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("linked_scan_signals", models.JSONField(blank=True, default=list)),
                (
                    "linked_learning_adjustments",
                    models.JSONField(blank=True, default=list),
                ),
                ("provider", models.CharField(blank=True, max_length=64)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "market_probability",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "narrative_support_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "pursue_worthiness_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "adjusted_edge",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "opportunity_quality_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_fusion_candidates",
                        to="markets.market",
                    ),
                ),
                (
                    "linked_prediction_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunity_fusion_candidates",
                        to="prediction_agent.predictionruntimeassessment",
                    ),
                ),
                (
                    "linked_research_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunity_fusion_candidates",
                        to="research_agent.marketresearchcandidate",
                    ),
                ),
                (
                    "linked_risk_approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunity_fusion_candidates",
                        to="risk_agent.riskapprovaldecision",
                    ),
                ),
                (
                    "linked_risk_sizing_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunity_fusion_candidates",
                        to="risk_agent.risksizingplan",
                    ),
                ),
                (
                    "linked_watch_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunity_fusion_candidates",
                        to="risk_agent.positionwatchplan",
                    ),
                ),
                (
                    "runtime_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="opportunity_supervisor.opportunitycycleruntimerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-opportunity_quality_score", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityFusionAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fusion_status",
                    models.CharField(
                        choices=[
                            ("READY_FOR_PROPOSAL", "Ready for proposal"),
                            ("WATCH_ONLY", "Watch only"),
                            ("BLOCKED_BY_RISK", "Blocked by risk"),
                            ("BLOCKED_BY_LEARNING", "Blocked by learning"),
                            ("LOW_CONVICTION", "Low conviction"),
                            ("NEEDS_REVIEW", "Needs review"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "conviction_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "execution_feasibility_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "learning_drag_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "portfolio_fit_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "final_opportunity_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at_assessment",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "runtime_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="opportunity_supervisor.opportunitycycleruntimerun",
                    ),
                ),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="opportunity_supervisor.opportunityfusioncandidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-final_opportunity_score", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("SEND_TO_PROPOSAL_ENGINE", "Send to proposal engine"),
                            (
                                "SEND_TO_EXECUTION_SIMULATOR",
                                "Send to execution simulator",
                            ),
                            ("KEEP_ON_WATCH", "Keep on watch"),
                            ("BLOCK_BY_RISK", "Block by risk"),
                            ("BLOCK_BY_LEARNING", "Block by learning"),
                            ("BLOCK_LOW_CONVICTION", "Block low conviction"),
                            (
                                "REQUIRE_MANUAL_OPPORTUNITY_REVIEW",
                                "Require manual opportunity review",
                            ),
                            (
                                "REORDER_OPPORTUNITY_PRIORITY",
                                "Reorder opportunity priority",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                (
                    "created_at_recommendation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "runtime_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="opportunity_supervisor.opportunitycycleruntimerun",
                    ),
                ),
                (
                    "target_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="opportunity_supervisor.opportunityfusionassessment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaperOpportunityProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("READY", "Ready"),
                            ("WATCH", "Watch"),
                            ("BLOCKED", "Blocked"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PROPOSED",
                        max_length=16,
                    ),
                ),
                ("recommended_direction", models.CharField(blank=True, max_length=12)),
                (
                    "calibrated_probability",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "adjusted_edge",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "approved_size_fraction",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=8, null=True
                    ),
                ),
                (
                    "paper_notional_size",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("watch_required", models.BooleanField(default=False)),
                ("execution_sim_recommended", models.BooleanField(default=False)),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at_proposal",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "linked_assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_proposal",
                        to="opportunity_supervisor.opportunityfusionassessment",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunity_cycle_proposals",
                        to="proposal_engine.tradeproposal",
                    ),
                ),
                (
                    "runtime_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_proposals",
                        to="opportunity_supervisor.opportunitycycleruntimerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
