# Generated by Django 5.1.4 on 2026-03-25 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RuntimeModeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("OBSERVE_ONLY", "Observe only"),
                            ("PAPER_ASSIST", "Paper assist"),
                            ("PAPER_SEMI_AUTO", "Paper semi auto"),
                            ("PAPER_AUTO", "Paper auto"),
                        ],
                        max_length=24,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=48)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("allow_signal_generation", models.BooleanField(default=True)),
                ("allow_proposals", models.BooleanField(default=True)),
                ("allow_allocation", models.BooleanField(default=True)),
                ("allow_real_market_ops", models.BooleanField(default=False)),
                ("allow_auto_execution", models.BooleanField(default=False)),
                ("allow_continuous_loop", models.BooleanField(default=False)),
                ("require_operator_for_all_trades", models.BooleanField(default=True)),
                ("allow_pending_approvals", models.BooleanField(default=True)),
                ("allow_replay", models.BooleanField(default=True)),
                ("allow_experiments", models.BooleanField(default=True)),
                ("max_auto_trades_per_cycle", models.PositiveIntegerField(default=0)),
                ("max_auto_trades_per_session", models.PositiveIntegerField(default=0)),
                (
                    "stricter_safety_overrides",
                    models.JSONField(blank=True, default=dict),
                ),
            ],
            options={
                "ordering": ["mode"],
            },
        ),
        migrations.CreateModel(
            name="RuntimeModeState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_mode",
                    models.CharField(
                        choices=[
                            ("OBSERVE_ONLY", "Observe only"),
                            ("PAPER_ASSIST", "Paper assist"),
                            ("PAPER_SEMI_AUTO", "Paper semi auto"),
                            ("PAPER_AUTO", "Paper auto"),
                        ],
                        default="OBSERVE_ONLY",
                        max_length=24,
                    ),
                ),
                (
                    "desired_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OBSERVE_ONLY", "Observe only"),
                            ("PAPER_ASSIST", "Paper assist"),
                            ("PAPER_SEMI_AUTO", "Paper semi auto"),
                            ("PAPER_AUTO", "Paper auto"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DEGRADED", "Degraded"),
                            ("PAUSED", "Paused"),
                            ("STOPPED", "Stopped"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                (
                    "set_by",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("operator", "Operator"),
                            ("readiness", "Readiness"),
                            ("safety", "Safety"),
                            ("system", "System"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("rationale", models.CharField(blank=True, max_length=255)),
                (
                    "effective_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RuntimeTransitionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OBSERVE_ONLY", "Observe only"),
                            ("PAPER_ASSIST", "Paper assist"),
                            ("PAPER_SEMI_AUTO", "Paper semi auto"),
                            ("PAPER_AUTO", "Paper auto"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "to_mode",
                    models.CharField(
                        choices=[
                            ("OBSERVE_ONLY", "Observe only"),
                            ("PAPER_ASSIST", "Paper assist"),
                            ("PAPER_SEMI_AUTO", "Paper semi auto"),
                            ("PAPER_AUTO", "Paper auto"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DEGRADED", "Degraded"),
                            ("PAUSED", "Paused"),
                            ("STOPPED", "Stopped"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DEGRADED", "Degraded"),
                            ("PAUSED", "Paused"),
                            ("STOPPED", "Stopped"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                (
                    "trigger_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("operator", "Operator"),
                            ("readiness", "Readiness"),
                            ("safety", "Safety"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=32,
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["trigger_source", "-created_at"],
                        name="runtime_gov_trigger_592716_idx",
                    ),
                    models.Index(
                        fields=["to_mode", "-created_at"],
                        name="runtime_gov_to_mode_124de2_idx",
                    ),
                ],
            },
        ),
    ]
