# Generated by Django 5.1.4 on 2026-04-02 21:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runtime_governor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalOperatingModeDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BALANCED", "Balanced"),
                            ("CAUTION", "Caution"),
                            ("MONITOR_ONLY", "Monitor only"),
                            ("RECOVERY_MODE", "Recovery mode"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "target_mode",
                    models.CharField(
                        choices=[
                            ("BALANCED", "Balanced"),
                            ("CAUTION", "Caution"),
                            ("MONITOR_ONLY", "Monitor only"),
                            ("RECOVERY_MODE", "Recovery mode"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("KEEP_CURRENT_MODE", "Keep current mode"),
                            ("SWITCH_TO_CAUTION", "Switch to caution"),
                            ("SWITCH_TO_MONITOR_ONLY", "Switch to monitor only"),
                            ("SWITCH_TO_RECOVERY_MODE", "Switch to recovery mode"),
                            ("SWITCH_TO_THROTTLED", "Switch to throttled"),
                            ("SWITCH_TO_BLOCKED", "Switch to blocked"),
                            (
                                "REQUIRE_MANUAL_MODE_REVIEW",
                                "Require manual mode review",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=12,
                    ),
                ),
                ("auto_applicable", models.BooleanField(default=False)),
                ("decision_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at_decision",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-created_at_decision", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GlobalRuntimePostureRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_signal_count", models.PositiveIntegerField(default=0)),
                ("mode_kept_count", models.PositiveIntegerField(default=0)),
                ("mode_switch_count", models.PositiveIntegerField(default=0)),
                ("caution_count", models.PositiveIntegerField(default=0)),
                ("monitor_only_count", models.PositiveIntegerField(default=0)),
                ("recovery_mode_count", models.PositiveIntegerField(default=0)),
                ("throttled_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GlobalOperatingModeSwitchRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "previous_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BALANCED", "Balanced"),
                            ("CAUTION", "Caution"),
                            ("MONITOR_ONLY", "Monitor only"),
                            ("RECOVERY_MODE", "Recovery mode"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "applied_mode",
                    models.CharField(
                        choices=[
                            ("BALANCED", "Balanced"),
                            ("CAUTION", "Caution"),
                            ("MONITOR_ONLY", "Monitor only"),
                            ("RECOVERY_MODE", "Recovery mode"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "switch_status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("switch_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at_switch",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "linked_mode_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="switch_records",
                        to="runtime_governor.globaloperatingmodedecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at_switch", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GlobalRuntimePostureSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exposure_pressure_state",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCK_NEW_ACTIVITY", "Block new activity"),
                        ],
                        default="NORMAL",
                        max_length=24,
                    ),
                ),
                (
                    "admission_pressure_state",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="NORMAL",
                        max_length=24,
                    ),
                ),
                (
                    "session_health_state",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("CAUTION", "Caution"),
                            ("DEGRADED", "Degraded"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="HEALTHY",
                        max_length=12,
                    ),
                ),
                (
                    "recent_loss_state",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("RECENT_LOSS", "Recent loss"),
                            ("REPEATED_LOSS", "Repeated loss"),
                        ],
                        default="NONE",
                        max_length=16,
                    ),
                ),
                (
                    "signal_quality_state",
                    models.CharField(
                        choices=[
                            ("STRONG", "Strong"),
                            ("NORMAL", "Normal"),
                            ("WEAK", "Weak"),
                            ("QUIET", "Quiet"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                (
                    "runtime_posture",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                (
                    "safety_posture",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("HARD_BLOCK", "Hard block"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                (
                    "incident_pressure_state",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("CAUTION", "Caution"),
                            ("HIGH", "High"),
                        ],
                        default="NONE",
                        max_length=12,
                    ),
                ),
                (
                    "portfolio_pressure_state",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCK_NEW_ENTRIES", "Block new entries"),
                        ],
                        default="NORMAL",
                        max_length=24,
                    ),
                ),
                ("snapshot_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at_snapshot",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "linked_posture_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posture_snapshots",
                        to="runtime_governor.globalruntimeposturerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at_snapshot", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GlobalOperatingModeRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("KEEP_BALANCED_MODE", "Keep balanced mode"),
                            ("SHIFT_TO_CAUTION_MODE", "Shift to caution mode"),
                            (
                                "SHIFT_TO_MONITOR_ONLY_MODE",
                                "Shift to monitor only mode",
                            ),
                            ("ENTER_RECOVERY_MODE", "Enter recovery mode"),
                            ("THROTTLE_GLOBAL_ACTIVITY", "Throttle global activity"),
                            (
                                "BLOCK_NEW_ACTIVITY_GLOBALLY",
                                "Block new activity globally",
                            ),
                            (
                                "REQUIRE_MANUAL_MODE_REVIEW",
                                "Require manual mode review",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_mode_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="runtime_governor.globaloperatingmodedecision",
                    ),
                ),
                (
                    "target_posture_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="runtime_governor.globalruntimeposturesnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="globaloperatingmodedecision",
            name="linked_posture_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mode_decisions",
                to="runtime_governor.globalruntimeposturesnapshot",
            ),
        ),
    ]
