# Generated by Django 5.1.4 on 2026-04-02 22:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "runtime_governor",
            "0002_globaloperatingmodedecision_globalruntimeposturerun_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalModeEnforcementRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_mode",
                    models.CharField(
                        choices=[
                            ("BALANCED", "Balanced"),
                            ("CAUTION", "Caution"),
                            ("MONITOR_ONLY", "Monitor only"),
                            ("RECOVERY_MODE", "Recovery mode"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="BALANCED",
                        max_length=24,
                    ),
                ),
                ("considered_module_count", models.PositiveIntegerField(default=0)),
                ("affected_module_count", models.PositiveIntegerField(default=0)),
                ("restricted_module_count", models.PositiveIntegerField(default=0)),
                ("throttled_module_count", models.PositiveIntegerField(default=0)),
                ("blocked_module_count", models.PositiveIntegerField(default=0)),
                ("monitor_only_module_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GlobalModeEnforcementDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("module_name", models.CharField(max_length=64)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("KEEP_DEFAULT_BEHAVIOR", "Keep default behavior"),
                            ("REDUCE_CADENCE", "Reduce cadence"),
                            ("REDUCE_ADMISSION_CAPACITY", "Reduce admission capacity"),
                            ("THROTTLE_EXPOSURE", "Throttle exposure"),
                            ("BLOCK_NEW_EXECUTION", "Block new execution"),
                            ("FORCE_MONITOR_ONLY", "Force monitor only"),
                            (
                                "REQUIRE_MANUAL_REVIEW_BIAS",
                                "Require manual review bias",
                            ),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=12,
                    ),
                ),
                ("auto_applicable", models.BooleanField(default=True)),
                ("decision_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_enforcement_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enforcement_decisions",
                        to="runtime_governor.globalmodeenforcementrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GlobalModeModuleImpact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_mode",
                    models.CharField(
                        choices=[
                            ("BALANCED", "Balanced"),
                            ("CAUTION", "Caution"),
                            ("MONITOR_ONLY", "Monitor only"),
                            ("RECOVERY_MODE", "Recovery mode"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=24,
                    ),
                ),
                ("module_name", models.CharField(max_length=64)),
                (
                    "impact_status",
                    models.CharField(
                        choices=[
                            ("UNCHANGED", "Unchanged"),
                            ("REDUCED", "Reduced"),
                            ("THROTTLED", "Throttled"),
                            ("MONITOR_ONLY", "Monitor only"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="UNCHANGED",
                        max_length=24,
                    ),
                ),
                (
                    "effective_behavior_summary",
                    models.CharField(blank=True, max_length=255),
                ),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_enforcement_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_impacts",
                        to="runtime_governor.globalmodeenforcementrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GlobalModeEnforcementRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("KEEP_BALANCED_ENFORCEMENT", "Keep balanced enforcement"),
                            ("REDUCE_RUNTIME_INTENSITY", "Reduce runtime intensity"),
                            (
                                "ENTER_MONITOR_ONLY_BEHAVIOR",
                                "Enter monitor only behavior",
                            ),
                            (
                                "THROTTLE_GLOBAL_NEW_ACTIVITY",
                                "Throttle global new activity",
                            ),
                            ("BLOCK_NEW_EXECUTION_PATHS", "Block new execution paths"),
                            ("BIAS_TOWARD_MANUAL_REVIEW", "Bias toward manual review"),
                            (
                                "REQUIRE_MANUAL_MODE_ENFORCEMENT_REVIEW",
                                "Require manual mode enforcement review",
                            ),
                        ],
                        max_length=56,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "target_enforcement_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="runtime_governor.globalmodeenforcementdecision",
                    ),
                ),
                (
                    "target_enforcement_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="runtime_governor.globalmodeenforcementrun",
                    ),
                ),
                (
                    "target_module_impact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="runtime_governor.globalmodemoduleimpact",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
