# Generated by Django 5.1.4 on 2026-04-02 22:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runtime_governor", "0003_globalmodeenforcementrun_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeDiagnosticReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "diagnostic_type",
                    models.CharField(
                        choices=[
                            ("HEALTHY_RUNTIME", "Healthy runtime"),
                            ("OVERTRADING_PRESSURE", "Overtrading pressure"),
                            ("QUIET_RUNTIME", "Quiet runtime"),
                            ("LOSS_RECOVERY_PRESSURE", "Loss recovery pressure"),
                            (
                                "BLOCKED_RUNTIME_SATURATION",
                                "Blocked runtime saturation",
                            ),
                            (
                                "LOW_QUALITY_OPPORTUNITY_FLOW",
                                "Low quality opportunity flow",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "diagnostic_severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("CAUTION", "Caution"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=12,
                    ),
                ),
                ("diagnostic_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RuntimeFeedbackRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_metric_count", models.PositiveIntegerField(default=0)),
                ("healthy_runtime_count", models.PositiveIntegerField(default=0)),
                ("overtrading_alert_count", models.PositiveIntegerField(default=0)),
                ("quiet_runtime_alert_count", models.PositiveIntegerField(default=0)),
                ("loss_pressure_alert_count", models.PositiveIntegerField(default=0)),
                ("blocked_runtime_alert_count", models.PositiveIntegerField(default=0)),
                ("feedback_decision_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RuntimeFeedbackDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("KEEP_CURRENT_GLOBAL_MODE", "Keep current global mode"),
                            (
                                "SHIFT_TO_MORE_CONSERVATIVE_MODE",
                                "Shift to more conservative mode",
                            ),
                            ("SHIFT_TO_MONITOR_ONLY", "Shift to monitor only"),
                            ("ENTER_RECOVERY_MODE", "Enter recovery mode"),
                            ("RELAX_TO_CAUTION", "Relax to caution"),
                            (
                                "REDUCE_ADMISSION_AND_CADENCE",
                                "Reduce admission and cadence",
                            ),
                            (
                                "REQUIRE_MANUAL_RUNTIME_REVIEW",
                                "Require manual runtime review",
                            ),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=12,
                    ),
                ),
                ("auto_applicable", models.BooleanField(default=False)),
                ("decision_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_diagnostic_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_decisions",
                        to="runtime_governor.runtimediagnosticreview",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RuntimeFeedbackRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("KEEP_RUNTIME_STABLE", "Keep runtime stable"),
                            (
                                "SHIFT_TO_CONSERVATIVE_BEHAVIOR",
                                "Shift to conservative behavior",
                            ),
                            (
                                "ENTER_MONITOR_ONLY_TEMPORARILY",
                                "Enter monitor only temporarily",
                            ),
                            (
                                "ENTER_RECOVERY_MODE_FOR_LOSS_PRESSURE",
                                "Enter recovery mode for loss pressure",
                            ),
                            (
                                "REDUCE_ADMISSION_AND_CADENCE_NOW",
                                "Reduce admission and cadence now",
                            ),
                            (
                                "REQUIRE_MANUAL_RUNTIME_REVIEW",
                                "Require manual runtime review",
                            ),
                        ],
                        max_length=56,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "target_diagnostic_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="runtime_governor.runtimediagnosticreview",
                    ),
                ),
                (
                    "target_feedback_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="runtime_governor.runtimefeedbackdecision",
                    ),
                ),
                (
                    "target_feedback_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="runtime_governor.runtimefeedbackrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RuntimePerformanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_global_mode",
                    models.CharField(
                        choices=[
                            ("BALANCED", "Balanced"),
                            ("CAUTION", "Caution"),
                            ("MONITOR_ONLY", "Monitor only"),
                            ("RECOVERY_MODE", "Recovery mode"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="BALANCED",
                        max_length=24,
                    ),
                ),
                ("recent_dispatch_count", models.PositiveIntegerField(default=0)),
                ("recent_closed_outcome_count", models.PositiveIntegerField(default=0)),
                ("recent_loss_count", models.PositiveIntegerField(default=0)),
                ("recent_no_action_tick_count", models.PositiveIntegerField(default=0)),
                ("recent_blocked_tick_count", models.PositiveIntegerField(default=0)),
                (
                    "recent_deferred_dispatch_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("recent_parked_session_count", models.PositiveIntegerField(default=0)),
                (
                    "recent_exposure_throttle_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "recent_recovery_resume_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "signal_quality_state",
                    models.CharField(
                        choices=[
                            ("STRONG", "Strong"),
                            ("NORMAL", "Normal"),
                            ("WEAK", "Weak"),
                            ("QUIET", "Quiet"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                (
                    "runtime_pressure_state",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                ("snapshot_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_feedback_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_snapshots",
                        to="runtime_governor.runtimefeedbackrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="runtimefeedbackdecision",
            name="linked_performance_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_decisions",
                to="runtime_governor.runtimeperformancesnapshot",
            ),
        ),
        migrations.AddField(
            model_name="runtimediagnosticreview",
            name="linked_performance_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnostic_reviews",
                to="runtime_governor.runtimeperformancesnapshot",
            ),
        ),
    ]
