# Generated by Django 5.1.4 on 2026-04-02 23:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "runtime_governor",
            "0004_runtimediagnosticreview_runtimefeedbackrun_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeFeedbackApplyRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "considered_feedback_decision_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("applied_count", models.PositiveIntegerField(default=0)),
                ("manual_review_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("mode_switch_count", models.PositiveIntegerField(default=0)),
                ("enforcement_refresh_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RuntimeFeedbackApplyDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BALANCED", "Balanced"),
                            ("CAUTION", "Caution"),
                            ("MONITOR_ONLY", "Monitor only"),
                            ("RECOVERY_MODE", "Recovery mode"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "target_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BALANCED", "Balanced"),
                            ("CAUTION", "Caution"),
                            ("MONITOR_ONLY", "Monitor only"),
                            ("RECOVERY_MODE", "Recovery mode"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "apply_type",
                    models.CharField(
                        choices=[
                            ("APPLY_KEEP_CURRENT_MODE", "Apply keep current mode"),
                            ("APPLY_SHIFT_TO_CAUTION", "Apply shift to caution"),
                            (
                                "APPLY_SHIFT_TO_MONITOR_ONLY",
                                "Apply shift to monitor only",
                            ),
                            ("APPLY_ENTER_RECOVERY_MODE", "Apply enter recovery mode"),
                            ("APPLY_RELAX_TO_CAUTION", "Apply relax to caution"),
                            ("APPLY_MANUAL_REVIEW_ONLY", "Apply manual review only"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "apply_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=12,
                    ),
                ),
                ("auto_applicable", models.BooleanField(default=False)),
                ("apply_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_feedback_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apply_decisions",
                        to="runtime_governor.runtimefeedbackdecision",
                    ),
                ),
                (
                    "linked_apply_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apply_decisions",
                        to="runtime_governor.runtimefeedbackapplyrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RuntimeFeedbackApplyRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("APPLY_FEEDBACK_NOW", "Apply feedback now"),
                            ("KEEP_AS_ADVISORY_ONLY", "Keep as advisory only"),
                            (
                                "REFRESH_ENFORCEMENT_AFTER_MODE_SWITCH",
                                "Refresh enforcement after mode switch",
                            ),
                            (
                                "BLOCK_AUTOMATIC_FEEDBACK_APPLY",
                                "Block automatic feedback apply",
                            ),
                            (
                                "REQUIRE_MANUAL_FEEDBACK_APPLY_REVIEW",
                                "Require manual feedback apply review",
                            ),
                        ],
                        max_length=56,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "target_apply_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="runtime_governor.runtimefeedbackapplydecision",
                    ),
                ),
                (
                    "target_feedback_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apply_recommendations",
                        to="runtime_governor.runtimefeedbackdecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RuntimeFeedbackApplyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record_status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "previous_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BALANCED", "Balanced"),
                            ("CAUTION", "Caution"),
                            ("MONITOR_ONLY", "Monitor only"),
                            ("RECOVERY_MODE", "Recovery mode"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "applied_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BALANCED", "Balanced"),
                            ("CAUTION", "Caution"),
                            ("MONITOR_ONLY", "Monitor only"),
                            ("RECOVERY_MODE", "Recovery mode"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                ("enforcement_refreshed", models.BooleanField(default=False)),
                ("record_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_apply_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apply_records",
                        to="runtime_governor.runtimefeedbackapplydecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
