# Generated by Django 5.1.4 on 2026-04-03 03:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "runtime_governor",
            "0005_runtimefeedbackapplyrun_runtimefeedbackapplydecision_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeModeStabilityReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("STABLE_TRANSITION", "Stable transition"),
                            ("EARLY_RELAX_ATTEMPT", "Early relax attempt"),
                            ("FLAPPING_RISK", "Flapping risk"),
                            ("INSUFFICIENT_DWELL_TIME", "Insufficient dwell time"),
                            ("SAFE_RECOVERY_ENTRY", "Safe recovery entry"),
                            ("SAFE_RELAXATION_WINDOW", "Safe relaxation window"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "review_severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("CAUTION", "Caution"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=12,
                    ),
                ),
                ("review_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RuntimeModeStabilizationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_transition_count", models.PositiveIntegerField(default=0)),
                ("allowed_count", models.PositiveIntegerField(default=0)),
                ("deferred_count", models.PositiveIntegerField(default=0)),
                ("dwell_hold_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("manual_review_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RuntimeModeTransitionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_mode",
                    models.CharField(
                        choices=[
                            ("BALANCED", "Balanced"),
                            ("CAUTION", "Caution"),
                            ("MONITOR_ONLY", "Monitor only"),
                            ("RECOVERY_MODE", "Recovery mode"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "target_mode",
                    models.CharField(
                        choices=[
                            ("BALANCED", "Balanced"),
                            ("CAUTION", "Caution"),
                            ("MONITOR_ONLY", "Monitor only"),
                            ("RECOVERY_MODE", "Recovery mode"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "current_mode_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "time_in_current_mode_seconds",
                    models.PositiveIntegerField(default=0),
                ),
                ("recent_switch_count", models.PositiveIntegerField(default=0)),
                (
                    "recent_switch_window_seconds",
                    models.PositiveIntegerField(default=0),
                ),
                ("last_switch_at", models.DateTimeField(blank=True, null=True)),
                (
                    "feedback_pressure_state",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                (
                    "transition_risk_state",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("CAUTION", "Caution"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=12,
                    ),
                ),
                ("snapshot_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_feedback_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mode_transition_snapshots",
                        to="runtime_governor.runtimefeedbackdecision",
                    ),
                ),
                (
                    "linked_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transition_snapshots",
                        to="runtime_governor.runtimemodestabilizationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RuntimeModeTransitionDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("ALLOW_MODE_SWITCH", "Allow mode switch"),
                            ("DEFER_MODE_SWITCH", "Defer mode switch"),
                            (
                                "KEEP_CURRENT_MODE_FOR_DWELL",
                                "Keep current mode for dwell",
                            ),
                            (
                                "REQUIRE_MANUAL_STABILITY_REVIEW",
                                "Require manual stability review",
                            ),
                            ("BLOCK_MODE_SWITCH", "Block mode switch"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=12,
                    ),
                ),
                ("auto_applicable", models.BooleanField(default=False)),
                ("decision_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_stability_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transition_decisions",
                        to="runtime_governor.runtimemodestabilityreview",
                    ),
                ),
                (
                    "linked_transition_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transition_decisions",
                        to="runtime_governor.runtimemodetransitionsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RuntimeModeStabilizationRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("ALLOW_TRANSITION_NOW", "Allow transition now"),
                            ("HOLD_CURRENT_MODE_LONGER", "Hold current mode longer"),
                            ("DEFER_RELAXATION", "Defer relaxation"),
                            ("BLOCK_FLAPPING_TRANSITION", "Block flapping transition"),
                            (
                                "REQUIRE_MANUAL_STABILITY_REVIEW",
                                "Require manual stability review",
                            ),
                            (
                                "KEEP_RECOVERY_MODE_UNTIL_STABLE",
                                "Keep recovery mode until stable",
                            ),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_stability_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="runtime_governor.runtimemodestabilityreview",
                    ),
                ),
                (
                    "target_transition_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="runtime_governor.runtimemodetransitiondecision",
                    ),
                ),
                (
                    "target_transition_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="runtime_governor.runtimemodetransitionsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="runtimemodestabilityreview",
            name="linked_transition_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stability_reviews",
                to="runtime_governor.runtimemodetransitionsnapshot",
            ),
        ),
    ]
