# Generated by Django 5.1.4 on 2026-04-03 03:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runtime_governor", "0006_runtimemodestabilityreview_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeModeTransitionApplyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "apply_status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "previous_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BALANCED", "Balanced"),
                            ("CAUTION", "Caution"),
                            ("MONITOR_ONLY", "Monitor only"),
                            ("RECOVERY_MODE", "Recovery mode"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "applied_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BALANCED", "Balanced"),
                            ("CAUTION", "Caution"),
                            ("MONITOR_ONLY", "Monitor only"),
                            ("RECOVERY_MODE", "Recovery mode"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                ("enforcement_refreshed", models.BooleanField(default=False)),
                ("apply_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_transition_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apply_records",
                        to="runtime_governor.runtimemodetransitiondecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
