# Generated by Django 5.1.4 on 2026-04-04 03:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runtime_governor", "0007_runtimemodetransitionapplyrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeTuningContextSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_scope",
                    models.CharField(
                        choices=[
                            ("runtime_feedback", "Runtime feedback"),
                            ("operating_mode", "Operating mode"),
                            ("mode_stabilization", "Mode stabilization"),
                            ("mode_enforcement", "Mode enforcement"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_run_id", models.PositiveIntegerField(blank=True, null=True)),
                ("tuning_profile_name", models.CharField(max_length=64)),
                ("tuning_profile_fingerprint", models.CharField(max_length=64)),
                (
                    "tuning_profile_summary",
                    models.CharField(blank=True, max_length=255),
                ),
                ("effective_values", models.JSONField(blank=True, default=dict)),
                (
                    "drift_status",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Initial"),
                            ("NO_CHANGE", "No change"),
                            ("MINOR_CONTEXT_CHANGE", "Minor context change"),
                            ("PROFILE_CHANGE", "Profile change"),
                        ],
                        max_length=24,
                    ),
                ),
                ("drift_summary", models.CharField(blank=True, max_length=255)),
                (
                    "created_at_snapshot",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-created_at_snapshot", "-id"],
                "indexes": [
                    models.Index(
                        fields=["source_scope", "-created_at_snapshot"],
                        name="runtime_gov_source__4bc461_idx",
                    ),
                    models.Index(
                        fields=["source_scope", "drift_status"],
                        name="runtime_gov_source__55f7a9_idx",
                    ),
                ],
            },
        ),
    ]
