# Generated by Django 5.1.4 on 2026-04-04 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runtime_governor", "0008_runtimetuningcontextsnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeTuningReviewState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_scope",
                    models.CharField(
                        choices=[
                            ("runtime_feedback", "Runtime feedback"),
                            ("operating_mode", "Operating mode"),
                            ("mode_stabilization", "Mode stabilization"),
                            ("mode_enforcement", "Mode enforcement"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "last_reviewed_snapshot_id_value",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("UNREVIEWED", "Unreviewed"),
                            ("ACKNOWLEDGED_CURRENT", "Acknowledged current"),
                            ("FOLLOWUP_REQUIRED", "Follow-up required"),
                            ("STALE_REVIEW", "Stale review"),
                        ],
                        default="UNREVIEWED",
                        max_length=32,
                    ),
                ),
                (
                    "last_action_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACKNOWLEDGE_CURRENT", "Acknowledge current"),
                            ("MARK_FOLLOWUP_REQUIRED", "Mark follow-up required"),
                            ("CLEAR_REVIEW_STATE", "Clear review state"),
                        ],
                        max_length=40,
                    ),
                ),
                ("last_action_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_reviewed_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_review_states",
                        to="runtime_governor.runtimetuningcontextsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["source_scope"],
            },
        ),
        migrations.CreateModel(
            name="RuntimeTuningReviewAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_scope",
                    models.CharField(
                        choices=[
                            ("runtime_feedback", "Runtime feedback"),
                            ("operating_mode", "Operating mode"),
                            ("mode_stabilization", "Mode stabilization"),
                            ("mode_enforcement", "Mode enforcement"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("ACKNOWLEDGE_CURRENT", "Acknowledge current"),
                            ("MARK_FOLLOWUP_REQUIRED", "Mark follow-up required"),
                            ("CLEAR_REVIEW_STATE", "Clear review state"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "snapshot_id_value",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "resulting_review_status",
                    models.CharField(
                        choices=[
                            ("UNREVIEWED", "Unreviewed"),
                            ("ACKNOWLEDGED_CURRENT", "Acknowledged current"),
                            ("FOLLOWUP_REQUIRED", "Follow-up required"),
                            ("STALE_REVIEW", "Stale review"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_review_actions",
                        to="runtime_governor.runtimetuningcontextsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["source_scope", "-created_at"],
                        name="runtime_gov_source__b12e7a_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="runtime_gov_action__45971d_idx",
                    ),
                ],
            },
        ),
    ]
