# Generated by Django 5.1.4 on 2026-03-28 17:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrustCalibrationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("IN_PROGRESS", "In progress"),
                            ("FAILED", "Failed"),
                        ],
                        default="IN_PROGRESS",
                        max_length=16,
                    ),
                ),
                ("window_days", models.PositiveIntegerField(default=30)),
                ("source_type", models.CharField(blank=True, max_length=80)),
                ("runbook_template_slug", models.CharField(blank=True, max_length=120)),
                ("profile_slug", models.CharField(blank=True, max_length=80)),
                ("include_degraded", models.BooleanField(default=True)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-started_at"],
                        name="trust_calib_status_921b27_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AutomationFeedbackSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_type", models.CharField(max_length=80)),
                ("source_type", models.CharField(blank=True, max_length=80)),
                ("runbook_template_slug", models.CharField(blank=True, max_length=120)),
                ("profile_slug", models.CharField(blank=True, max_length=80)),
                ("current_trust_tier", models.CharField(blank=True, max_length=32)),
                ("approvals_granted", models.PositiveIntegerField(default=0)),
                ("approvals_rejected", models.PositiveIntegerField(default=0)),
                ("approvals_expired", models.PositiveIntegerField(default=0)),
                ("approvals_escalated", models.PositiveIntegerField(default=0)),
                ("auto_actions_executed", models.PositiveIntegerField(default=0)),
                ("auto_actions_failed", models.PositiveIntegerField(default=0)),
                ("blocked_decisions", models.PositiveIntegerField(default=0)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("operator_overrides", models.PositiveIntegerField(default=0)),
                ("incidents_after_auto", models.PositiveIntegerField(default=0)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_snapshots",
                        to="trust_calibration.trustcalibrationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="TrustCalibrationRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            (
                                "PROMOTE_TO_SAFE_AUTOMATION",
                                "Promote to safe automation",
                            ),
                            ("KEEP_APPROVAL_REQUIRED", "Keep approval required"),
                            ("DOWNGRADE_TO_MANUAL_ONLY", "Downgrade to manual only"),
                            (
                                "BLOCK_AUTOMATION_FOR_ACTION",
                                "Block automation for action",
                            ),
                            ("REQUIRE_MORE_DATA", "Require more data"),
                            ("REVIEW_RULE_CONDITIONS", "Review rule conditions"),
                        ],
                        max_length=48,
                    ),
                ),
                ("action_type", models.CharField(max_length=80)),
                ("current_trust_tier", models.CharField(blank=True, max_length=32)),
                ("recommended_trust_tier", models.CharField(blank=True, max_length=32)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("supporting_metrics", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="trust_calibration.automationfeedbacksnapshot",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="trust_calibration.trustcalibrationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence", "-id"],
                "indexes": [
                    models.Index(
                        fields=["run", "recommendation_type"],
                        name="trust_calib_run_id_a08356_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="automationfeedbacksnapshot",
            index=models.Index(
                fields=["run", "action_type"], name="trust_calib_run_id_b649ca_idx"
            ),
        ),
    ]
