# Generated by Django 5.1.4 on 2026-03-29 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autonomy_advisory", "0001_initial"),
        ("autonomy_campaign", "0001_initial"),
        ("autonomy_insights", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryResolutionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("pending_count", models.PositiveIntegerField(default=0)),
                ("acknowledged_count", models.PositiveIntegerField(default=0)),
                ("adopted_count", models.PositiveIntegerField(default=0)),
                ("deferred_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("closed_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AdvisoryResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("ADOPTED", "Adopted"),
                            ("DEFERRED", "Deferred"),
                            ("REJECTED", "Rejected"),
                            ("BLOCKED", "Blocked"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                (
                    "resolution_type",
                    models.CharField(
                        choices=[
                            ("MEMORY_NOTE_ACKNOWLEDGED", "Memory note acknowledged"),
                            ("ROADMAP_NOTE_ACKNOWLEDGED", "Roadmap note acknowledged"),
                            (
                                "SCENARIO_NOTE_ACKNOWLEDGED",
                                "Scenario note acknowledged",
                            ),
                            ("PROGRAM_NOTE_ACKNOWLEDGED", "Program note acknowledged"),
                            ("MANAGER_NOTE_ACKNOWLEDGED", "Manager note acknowledged"),
                            ("MANUAL_REVIEW_REQUIRED", "Manual review required"),
                        ],
                        default="MANUAL_REVIEW_REQUIRED",
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("resolved_by", models.CharField(blank=True, max_length=120)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("linked_artifact", models.CharField(blank=True, max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "advisory_artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolution_events",
                        to="autonomy_advisory.advisoryartifact",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advisory_resolutions",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "insight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advisory_resolutions",
                        to="autonomy_insights.campaigninsight",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["advisory_artifact", "-updated_at"],
                        name="autonomy_ad_advisor_5aba2c_idx",
                    ),
                    models.Index(
                        fields=["resolution_status", "-updated_at"],
                        name="autonomy_ad_resolut_8c99d6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdvisoryResolutionRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("ACKNOWLEDGE_ADVISORY", "Acknowledge advisory"),
                            ("MARK_ADOPTED", "Mark adopted"),
                            ("MARK_DEFERRED", "Mark deferred"),
                            ("MARK_REJECTED", "Mark rejected"),
                            ("REQUIRE_MANUAL_REVIEW", "Require manual review"),
                            ("KEEP_PENDING", "Keep pending"),
                            (
                                "REORDER_ADVISORY_RESOLUTION_PRIORITY",
                                "Reorder advisory resolution priority",
                            ),
                        ],
                        max_length=56,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "advisory_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolution_recommendations",
                        to="autonomy_advisory.advisoryartifact",
                    ),
                ),
                (
                    "insight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advisory_resolution_recommendations",
                        to="autonomy_insights.campaigninsight",
                    ),
                ),
                (
                    "resolution_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_advisory_resolution.advisoryresolutionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recommendation_type", "-created_at"],
                        name="autonomy_ad_recomme_993556_idx",
                    )
                ],
            },
        ),
    ]
