# Generated by Django 5.1.4 on 2026-03-25 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0002_event_source_type_market_source_type"),
        ("paper_trading", "0001_initial"),
        ("proposal_engine", "0001_initial"),
        ("semi_auto_demo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorQueueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SNOOZED", "Snoozed"),
                            ("EXPIRED", "Expired"),
                            ("EXECUTED", "Executed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("policy", "Policy"),
                            ("safety", "Safety"),
                            ("allocation", "Allocation"),
                            ("semi_auto", "Semi-auto"),
                            ("continuous_demo", "Continuous demo"),
                            ("real_ops", "Real ops"),
                        ],
                        default="semi_auto",
                        max_length=24,
                    ),
                ),
                (
                    "queue_type",
                    models.CharField(
                        choices=[
                            ("approval_required", "Approval required"),
                            ("escalation", "Escalation"),
                            ("safety_review", "Safety review"),
                            ("blocked_review", "Blocked review"),
                        ],
                        default="approval_required",
                        max_length=24,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                ("headline", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("rationale", models.TextField(blank=True)),
                ("suggested_action", models.CharField(blank=True, max_length=16)),
                (
                    "suggested_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("snoozed_until", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "related_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operator_queue_items",
                        to="markets.market",
                    ),
                ),
                (
                    "related_pending_approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operator_queue_items",
                        to="semi_auto_demo.pendingapproval",
                    ),
                ),
                (
                    "related_proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operator_queue_items",
                        to="proposal_engine.tradeproposal",
                    ),
                ),
                (
                    "related_trade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operator_queue_items",
                        to="paper_trading.papertrade",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OperatorDecisionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("SNOOZE", "Snooze"),
                            ("CANCEL", "Cancel"),
                            ("FORCE_BLOCK", "Force block"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "decided_by",
                    models.CharField(default="local-operator", max_length=120),
                ),
                ("decision_note", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "queue_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_logs",
                        to="operator_queue.operatorqueueitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="operatorqueueitem",
            index=models.Index(
                fields=["status", "-created_at"], name="operator_qu_status_c85930_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operatorqueueitem",
            index=models.Index(
                fields=["priority", "-created_at"],
                name="operator_qu_priorit_dbc95d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="operatorqueueitem",
            index=models.Index(
                fields=["source", "queue_type"], name="operator_qu_source_e2403c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operatordecisionlog",
            index=models.Index(
                fields=["queue_item", "-created_at"],
                name="operator_qu_queue_i_1aa4d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="operatordecisionlog",
            index=models.Index(
                fields=["decision", "-created_at"],
                name="operator_qu_decisio_63a72a_idx",
            ),
        ),
    ]
