# Generated by Django 5.1.4 on 2026-03-28 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policy_tuning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyRolloutRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rollout_status",
                    models.CharField(
                        choices=[
                            ("OBSERVING", "Observing"),
                            ("STABLE", "Stable"),
                            ("CAUTION", "Caution"),
                            ("ROLLBACK_RECOMMENDED", "Rollback recommended"),
                            ("COMPLETED", "Completed"),
                            ("ABORTED", "Aborted"),
                        ],
                        default="OBSERVING",
                        max_length=32,
                    ),
                ),
                ("observation_window_days", models.PositiveIntegerField(default=14)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "application_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollout_runs",
                        to="policy_tuning.policytuningapplicationlog",
                    ),
                ),
                (
                    "policy_tuning_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollout_runs",
                        to="policy_tuning.policytuningcandidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PolicyRolloutRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("KEEP_CHANGE", "Keep change"),
                            ("REQUIRE_MORE_DATA", "Require more data"),
                            ("ROLLBACK_CHANGE", "Rollback change"),
                            ("REVIEW_MANUALLY", "Review manually"),
                            ("STABILIZE_AND_MONITOR", "Stabilize and monitor"),
                        ],
                        max_length=32,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("supporting_deltas", models.JSONField(blank=True, default=dict)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="policy_rollout.policyrolloutrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PolicyPostChangeSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("counts", models.JSONField(blank=True, default=dict)),
                ("deltas", models.JSONField(blank=True, default=dict)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("sample_size", models.PositiveIntegerField(default=0)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_change_snapshot",
                        to="policy_rollout.policyrolloutrun",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PolicyBaselineSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("counts", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baseline_snapshot",
                        to="policy_rollout.policyrolloutrun",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="policyrolloutrun",
            index=models.Index(
                fields=["rollout_status", "-created_at"],
                name="policy_roll_rollout_70acd8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="policyrolloutrecommendation",
            index=models.Index(
                fields=["recommendation", "-created_at"],
                name="policy_roll_recomme_b0ccde_idx",
            ),
        ),
    ]
