# Generated by Django 5.1.4 on 2026-03-23 20:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MockAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("SCAN", "Scan"),
                            ("RESEARCH", "Research"),
                            ("PREDICTION", "Prediction"),
                            ("RISK", "Risk"),
                            ("POSTMORTEM", "Postmortem"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SignalRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run_type", models.CharField(default="DEMO_SCAN", max_length=40)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("markets_evaluated", models.PositiveIntegerField(default=0)),
                ("signals_created", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MarketSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("MOMENTUM", "Momentum"),
                            ("MEAN_REVERSION", "Mean reversion"),
                            ("EXTREME", "Extreme probability"),
                            ("OPPORTUNITY", "Opportunity"),
                            ("RISK", "Risk review"),
                            ("DORMANT", "Dormant market"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("MONITOR", "Monitor"),
                            ("EXPIRED", "Expired"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("BULLISH", "Bullish"),
                            ("BEARISH", "Bearish"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        default="NEUTRAL",
                        max_length=12,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                ("headline", models.CharField(max_length=255)),
                ("thesis", models.TextField()),
                ("rationale", models.TextField(blank=True)),
                (
                    "signal_probability",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "market_probability_at_signal",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "edge_estimate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("is_actionable", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="markets.market",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signals",
                        to="signals.mockagent",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signals",
                        to="signals.signalrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["market", "-created_at"],
                        name="signals_mar_market__7eb751_idx",
                    ),
                    models.Index(
                        fields=["agent", "status"],
                        name="signals_mar_agent_i_0786c9_idx",
                    ),
                    models.Index(
                        fields=["signal_type", "status"],
                        name="signals_mar_signal__6948a3_idx",
                    ),
                    models.Index(
                        fields=["direction", "is_actionable"],
                        name="signals_mar_directi_a3a515_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["ACTIVE", "MONITOR"])),
                        fields=("market", "agent", "signal_type", "status"),
                        name="signals_unique_live_signal_per_market_agent_type",
                    )
                ],
            },
        ),
    ]
