# Generated by Django 5.1.4 on 2026-03-26 19:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0002_event_source_type_market_source_type"),
        ("signals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignalFusionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                (
                    "profile_slug",
                    models.CharField(default="balanced_signal", max_length=40),
                ),
                ("triggered_by", models.CharField(default="manual_api", max_length=40)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("markets_evaluated", models.PositiveIntegerField(default=0)),
                ("signals_created", models.PositiveIntegerField(default=0)),
                ("proposal_ready_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OpportunitySignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider_slug", models.CharField(blank=True, max_length=64)),
                (
                    "research_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "triage_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                ("narrative_direction", models.CharField(blank=True, max_length=20)),
                (
                    "narrative_confidence",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=7
                    ),
                ),
                ("source_mix", models.CharField(default="none", max_length=24)),
                (
                    "prediction_system_probability",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "prediction_market_probability",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "edge",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=8
                    ),
                ),
                (
                    "prediction_confidence",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=7
                    ),
                ),
                ("risk_level", models.CharField(default="MEDIUM", max_length=12)),
                (
                    "adjusted_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("runtime_constraints", models.JSONField(blank=True, default=dict)),
                (
                    "opportunity_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "opportunity_status",
                    models.CharField(
                        choices=[
                            ("WATCH", "Watch"),
                            ("CANDIDATE", "Candidate"),
                            ("PROPOSAL_READY", "Proposal ready"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="WATCH",
                        max_length=20,
                    ),
                ),
                ("rank", models.PositiveIntegerField(default=0)),
                ("rationale", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_signals",
                        to="markets.market",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="signals.signalfusionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "-opportunity_score", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProposalGateDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("should_generate_proposal", models.BooleanField(default=False)),
                ("proposal_priority", models.PositiveIntegerField(default=0)),
                ("proposal_reason", models.CharField(blank=True, max_length=255)),
                ("blocked_reason", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "opportunity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal_gate",
                        to="signals.opportunitysignal",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="opportunitysignal",
            index=models.Index(
                fields=["opportunity_status", "-opportunity_score"],
                name="signals_opp_opportu_f4744f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="opportunitysignal",
            index=models.Index(
                fields=["market", "-created_at"], name="signals_opp_market__b8d9e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunitysignal",
            index=models.Index(
                fields=["run", "rank"], name="signals_opp_run_id_9c76f4_idx"
            ),
        ),
    ]
