# Generated by Django 5.1.4 on 2026-03-28 18:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approval_center", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomyDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("owner_app", models.CharField(blank=True, max_length=80)),
                ("action_types", models.JSONField(blank=True, default=list)),
                ("source_apps", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="AutonomyEnvelope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("max_auto_actions_per_cycle", models.PositiveIntegerField(default=1)),
                (
                    "approval_override_behavior",
                    models.CharField(
                        default="REQUIRE_OPERATOR_APPROVAL", max_length=80
                    ),
                ),
                ("blocked_contexts", models.JSONField(blank=True, default=list)),
                (
                    "degraded_mode_handling",
                    models.CharField(default="DOWNGRADE_TO_MANUAL", max_length=80),
                ),
                (
                    "certification_dependencies",
                    models.JSONField(blank=True, default=list),
                ),
                ("runtime_dependencies", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "domain",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envelope",
                        to="autonomy_manager.autonomydomain",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AutonomyStageState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("ASSISTED", "Assisted"),
                            ("SUPERVISED_AUTOPILOT", "Supervised autopilot"),
                            ("FROZEN", "Frozen"),
                            ("ROLLBACK_RECOMMENDED", "Rollback recommended"),
                        ],
                        default="MANUAL",
                        max_length=32,
                    ),
                ),
                (
                    "effective_stage",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("ASSISTED", "Assisted"),
                            ("SUPERVISED_AUTOPILOT", "Supervised autopilot"),
                            ("FROZEN", "Frozen"),
                            ("ROLLBACK_RECOMMENDED", "Rollback recommended"),
                        ],
                        default="MANUAL",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("OBSERVING", "Observing"),
                            ("DEGRADED", "Degraded"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("rationale", models.CharField(blank=True, max_length=255)),
                ("linked_policy_profiles", models.JSONField(blank=True, default=list)),
                ("linked_action_types", models.JSONField(blank=True, default=list)),
                (
                    "last_changed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "domain",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_state",
                        to="autonomy_manager.autonomydomain",
                    ),
                ),
            ],
            options={
                "ordering": ["domain__slug"],
            },
        ),
        migrations.CreateModel(
            name="AutonomyStageRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_code",
                    models.CharField(
                        choices=[
                            ("PROMOTE_TO_ASSISTED", "Promote to assisted"),
                            (
                                "PROMOTE_TO_SUPERVISED_AUTOPILOT",
                                "Promote to supervised autopilot",
                            ),
                            ("KEEP_CURRENT_STAGE", "Keep current stage"),
                            ("DOWNGRADE_TO_MANUAL", "Downgrade to manual"),
                            ("FREEZE_DOMAIN", "Freeze domain"),
                            ("REQUIRE_MORE_DATA", "Require more data"),
                            ("ROLLBACK_STAGE", "Rollback stage"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("ASSISTED", "Assisted"),
                            ("SUPERVISED_AUTOPILOT", "Supervised autopilot"),
                            ("FROZEN", "Frozen"),
                            ("ROLLBACK_RECOMMENDED", "Rollback recommended"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "proposed_stage",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("ASSISTED", "Assisted"),
                            ("SUPERVISED_AUTOPILOT", "Supervised autopilot"),
                            ("FROZEN", "Frozen"),
                            ("ROLLBACK_RECOMMENDED", "Rollback recommended"),
                        ],
                        max_length=32,
                    ),
                ),
                ("rationale", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("evidence_refs", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="autonomy_manager.autonomydomain",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_manager.autonomystagestate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomyStageTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("READY_TO_APPLY", "Ready to apply"),
                            ("APPLIED", "Applied"),
                            ("ROLLED_BACK", "Rolled back"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                (
                    "previous_stage",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("ASSISTED", "Assisted"),
                            ("SUPERVISED_AUTOPILOT", "Supervised autopilot"),
                            ("FROZEN", "Frozen"),
                            ("ROLLBACK_RECOMMENDED", "Rollback recommended"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "requested_stage",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("ASSISTED", "Assisted"),
                            ("SUPERVISED_AUTOPILOT", "Supervised autopilot"),
                            ("FROZEN", "Frozen"),
                            ("ROLLBACK_RECOMMENDED", "Rollback recommended"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "applied_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MANUAL", "Manual"),
                            ("ASSISTED", "Assisted"),
                            ("SUPERVISED_AUTOPILOT", "Supervised autopilot"),
                            ("FROZEN", "Frozen"),
                            ("ROLLBACK_RECOMMENDED", "Rollback recommended"),
                        ],
                        max_length=32,
                    ),
                ),
                ("rationale", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("evidence_refs", models.JSONField(blank=True, default=list)),
                (
                    "requested_by",
                    models.CharField(default="autonomy-review", max_length=80),
                ),
                ("applied_by", models.CharField(blank=True, max_length=80)),
                ("rolled_back_by", models.CharField(blank=True, max_length=80)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "approval_request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autonomy_stage_transition",
                        to="approval_center.approvalrequest",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="autonomy_manager.autonomydomain",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transitions",
                        to="autonomy_manager.autonomystagerecommendation",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="autonomy_manager.autonomystagestate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="autonomystagerecommendation",
            index=models.Index(
                fields=["domain", "-created_at"], name="autonomy_ma_domain__26d4c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autonomystagerecommendation",
            index=models.Index(
                fields=["recommendation_code", "-created_at"],
                name="autonomy_ma_recomme_6787ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="autonomystagetransition",
            index=models.Index(
                fields=["status", "-created_at"], name="autonomy_ma_status_e9ea07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autonomystagetransition",
            index=models.Index(
                fields=["domain", "-created_at"], name="autonomy_ma_domain__f68648_idx"
            ),
        ),
    ]
