# Generated by Django 5.1.4 on 2026-03-28 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autonomy_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomyRoadmapPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("summary", models.CharField(max_length=255)),
                ("current_domain_posture", models.JSONField(blank=True, default=dict)),
                ("candidate_transitions", models.JSONField(blank=True, default=list)),
                ("blocked_domains", models.JSONField(blank=True, default=list)),
                ("frozen_domains", models.JSONField(blank=True, default=list)),
                ("recommended_sequence", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DomainRoadmapProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "domain",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_profile",
                        to="autonomy_manager.autonomydomain",
                    ),
                ),
            ],
            options={
                "ordering": ["domain__slug"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("domains", models.JSONField(blank=True, default=list)),
                ("sequence_order", models.JSONField(blank=True, default=list)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                ("requires_approval", models.BooleanField(default=False)),
                ("rationale", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundles",
                        to="autonomy_roadmap.autonomyroadmapplan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="DomainDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("requires_stable", "Requires stable target domain"),
                            (
                                "blocks_if_degraded",
                                "Blocks source if target is degraded/blocked",
                            ),
                            (
                                "recommended_before",
                                "Target should be promoted before source",
                            ),
                            (
                                "incompatible_parallel",
                                "Avoid promoting both in parallel",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "source_domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_dependencies_from",
                        to="autonomy_manager.autonomydomain",
                    ),
                ),
                (
                    "target_domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_dependencies_to",
                        to="autonomy_manager.autonomydomain",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "source_domain__slug",
                    "target_domain__slug",
                    "dependency_type",
                ],
                "indexes": [
                    models.Index(
                        fields=["dependency_type", "source_domain"],
                        name="autonomy_ro_depende_7b7be5_idx",
                    ),
                    models.Index(
                        fields=["source_domain", "target_domain"],
                        name="autonomy_ro_source__c2a8d7_idx",
                    ),
                ],
                "unique_together": {
                    ("source_domain", "target_domain", "dependency_type")
                },
            },
        ),
        migrations.CreateModel(
            name="RoadmapRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("ASSISTED", "Assisted"),
                            ("SUPERVISED_AUTOPILOT", "Supervised autopilot"),
                            ("FROZEN", "Frozen"),
                            ("ROLLBACK_RECOMMENDED", "Rollback recommended"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "proposed_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MANUAL", "Manual"),
                            ("ASSISTED", "Assisted"),
                            ("SUPERVISED_AUTOPILOT", "Supervised autopilot"),
                            ("FROZEN", "Frozen"),
                            ("ROLLBACK_RECOMMENDED", "Rollback recommended"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("PROMOTE_DOMAIN", "Promote domain"),
                            ("HOLD_DOMAIN", "Hold domain"),
                            ("FREEZE_DOMAIN", "Freeze domain"),
                            ("ROLLBACK_DOMAIN", "Rollback domain"),
                            ("SEQUENCE_BEFORE", "Sequence before"),
                            (
                                "DO_NOT_PROMOTE_IN_PARALLEL",
                                "Do not promote in parallel",
                            ),
                            (
                                "REQUIRE_STABILIZATION_FIRST",
                                "Require stabilization first",
                            ),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("evidence_refs", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_recommendations",
                        to="autonomy_manager.autonomydomain",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="autonomy_roadmap.autonomyroadmapplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"],
                        name="autonomy_ro_action_01dc75_idx",
                    ),
                    models.Index(
                        fields=["domain", "-created_at"],
                        name="autonomy_ro_domain__795642_idx",
                    ),
                ],
            },
        ),
    ]
