# Generated by Django 5.1.4 on 2026-03-30 04:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("evaluation_lab", "0002_effectivenessmetric_evaluationruntimerun_and_more"),
        ("policy_tuning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TuningProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal_type",
                    models.CharField(
                        choices=[
                            (
                                "prediction_confidence_threshold",
                                "Prediction confidence threshold",
                            ),
                            ("prediction_edge_threshold", "Prediction edge threshold"),
                            ("calibration_bias_offset", "Calibration bias offset"),
                            ("risk_gate_threshold", "Risk gate threshold"),
                            ("risk_size_cap", "Risk size cap"),
                            ("liquidity_floor", "Liquidity floor"),
                            ("shortlist_threshold", "Shortlist threshold"),
                            (
                                "opportunity_conviction_floor",
                                "Opportunity conviction floor",
                            ),
                            ("learning_caution_weight", "Learning caution weight"),
                            ("manual_review_rule", "Manual review rule"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "target_scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("provider", "Provider"),
                            ("category", "Category"),
                            ("horizon_band", "Horizon band"),
                            ("model_mode", "Model mode"),
                            ("source_type", "Source type"),
                        ],
                        default="global",
                        max_length=24,
                    ),
                ),
                (
                    "target_component",
                    models.CharField(
                        choices=[
                            ("research", "Research"),
                            ("prediction", "Prediction"),
                            ("risk", "Risk"),
                            ("opportunity_cycle", "Opportunity cycle"),
                            ("learning", "Learning"),
                            ("calibration", "Calibration"),
                        ],
                        max_length=24,
                    ),
                ),
                ("target_value", models.CharField(blank=True, max_length=120)),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "proposed_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "proposal_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("WATCH", "Watch"),
                            ("READY_FOR_REVIEW", "Ready for review"),
                            ("DEFERRED", "Deferred"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PROPOSED",
                        max_length=24,
                    ),
                ),
                (
                    "evidence_strength_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=16,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("linked_metrics", models.JSONField(blank=True, default=list)),
                ("linked_recommendations", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "policy_tuning_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="governed_tuning_proposals",
                        to="policy_tuning.policytuningcandidate",
                    ),
                ),
                (
                    "source_metric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tuning_proposals",
                        to="evaluation_lab.effectivenessmetric",
                    ),
                ),
                (
                    "source_recommendation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tuning_proposals",
                        to="evaluation_lab.evaluationrecommendation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TuningImpactHypothesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hypothesis_type",
                    models.CharField(
                        choices=[
                            ("improve_calibration", "Improve calibration"),
                            ("reduce_overconfidence", "Reduce overconfidence"),
                            ("reduce_false_positives", "Reduce false positives"),
                            ("reduce_false_negatives", "Reduce false negatives"),
                            ("tighten_risk_gate", "Tighten risk gate"),
                            ("relax_risk_gate", "Relax risk gate"),
                            ("reduce_provider_bias", "Reduce provider bias"),
                            ("reduce_category_bias", "Reduce category bias"),
                            ("improve_watch_precision", "Improve watch precision"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "expected_direction",
                    models.CharField(
                        choices=[
                            ("increase", "Increase"),
                            ("decrease", "Decrease"),
                            ("stabilize", "Stabilize"),
                        ],
                        max_length=16,
                    ),
                ),
                ("target_metric_type", models.CharField(max_length=64)),
                (
                    "expected_effect_size",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hypotheses",
                        to="tuning_board.tuningproposal",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TuningReviewRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metrics_reviewed_count", models.PositiveIntegerField(default=0)),
                ("poor_metric_count", models.PositiveIntegerField(default=0)),
                ("drift_flag_count", models.PositiveIntegerField(default=0)),
                ("proposal_count", models.PositiveIntegerField(default=0)),
                (
                    "high_priority_proposal_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_evaluation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tuning_review_runs",
                        to="evaluation_lab.evaluationruntimerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TuningRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            (
                                "REVIEW_PREDICTION_THRESHOLD",
                                "Review prediction threshold",
                            ),
                            ("REVIEW_CALIBRATION_OFFSET", "Review calibration offset"),
                            ("REVIEW_RISK_GATE", "Review risk gate"),
                            ("REVIEW_SIZE_CAP", "Review size cap"),
                            (
                                "REVIEW_SHORTLIST_THRESHOLD",
                                "Review shortlist threshold",
                            ),
                            ("REQUIRE_MORE_DATA", "Require more data"),
                            ("DEFER_TUNING_CHANGE", "Defer tuning change"),
                            ("GROUP_IN_BUNDLE", "Group in bundle"),
                            ("REORDER_TUNING_PRIORITY", "Reorder tuning priority"),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="tuning_board.tuningproposal",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="tuning_board.tuningreviewrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TuningProposalBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bundle_label", models.CharField(max_length=120)),
                ("bundle_scope", models.CharField(max_length=120)),
                (
                    "bundle_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("READY_FOR_REVIEW", "Ready for review"),
                            ("NEEDS_MORE_DATA", "Needs more data"),
                            ("DEFERRED", "Deferred"),
                        ],
                        default="PROPOSED",
                        max_length=24,
                    ),
                ),
                ("rationale", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_proposals",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bundles",
                        to="tuning_board.tuningproposal",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundles",
                        to="tuning_board.tuningreviewrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="tuningproposal",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to="tuning_board.tuningreviewrun",
            ),
        ),
        migrations.AddIndex(
            model_name="tuningproposal",
            index=models.Index(
                fields=["proposal_status", "-created_at"],
                name="tuning_boar_proposa_7f6d6b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tuningproposal",
            index=models.Index(
                fields=["priority_level", "-created_at"],
                name="tuning_boar_priorit_cef2a5_idx",
            ),
        ),
    ]
