# Generated by Django 5.2.7 on 2026-03-24

import decimal
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0002_event_source_type_market_source_type'),
        ('paper_trading', '0001_initial'),
        ('postmortem_demo', '0001_initial'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMemoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memory_type', models.CharField(choices=[('signal_pattern', 'Signal pattern'), ('market_pattern', 'Market pattern'), ('provider_pattern', 'Provider pattern'), ('trade_pattern', 'Trade pattern'), ('policy_pattern', 'Policy pattern')], max_length=32)),
                ('source_type', models.CharField(choices=[('demo', 'Demo'), ('real_read_only', 'Real read only'), ('mixed', 'Mixed')], default='mixed', max_length=24)),
                ('outcome', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=16)),
                ('score_delta', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=7)),
                ('confidence_delta', models.DecimalField(decimal_places=4, default=decimal.Decimal('0.0000'), max_digits=7)),
                ('quantity_bias_delta', models.DecimalField(decimal_places=4, default=decimal.Decimal('0.0000'), max_digits=7)),
                ('summary', models.CharField(max_length=255)),
                ('rationale', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_memory_entries', to='markets.market')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_memory_entries', to='markets.provider')),
                ('related_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_memory_entries', to='postmortem_demo.tradereview')),
                ('related_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_memory_entries', to='signals.marketsignal')),
                ('related_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_memory_entries', to='paper_trading.papertrade')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['memory_type', '-created_at'], name='learning_mem_memory__2ddf67_idx'), models.Index(fields=['outcome', '-created_at'], name='learning_mem_outcome_7f4ec0_idx'), models.Index(fields=['source_type', '-created_at'], name='learning_mem_source__88f3fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_type', models.CharField(choices=[('confidence_bias', 'Confidence bias'), ('quantity_bias', 'Quantity bias'), ('risk_caution_bias', 'Risk caution bias'), ('policy_caution_bias', 'Policy caution bias')], max_length=40)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('provider', 'Provider'), ('market', 'Market'), ('source_type', 'Source type'), ('signal_type', 'Signal type')], max_length=24)),
                ('scope_key', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('magnitude', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(decimal.Decimal('-1.0000')), django.core.validators.MaxValueValidator(decimal.Decimal('1.0000'))])),
                ('reason', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['adjustment_type', 'scope_type', 'scope_key'], name='learning_adj_adjustm_1e2f1f_idx'), models.Index(fields=['is_active', '-updated_at'], name='learning_adj_is_acti_22d932_idx')],
                'constraints': [models.UniqueConstraint(fields=('adjustment_type', 'scope_type', 'scope_key'), name='learning_memory_unique_adjustment_scope')],
            },
        ),
    ]
