# Generated by Django 5.1.4 on 2026-03-24 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("continuous_demo", "0001_initial"),
        ("learning_memory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningRebuildRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                        ],
                        default="SUCCESS",
                        max_length=12,
                    ),
                ),
                (
                    "triggered_from",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("automation", "Automation"),
                            ("continuous_demo", "Continuous demo"),
                            ("evaluation", "Evaluation"),
                            ("postmortem", "Postmortem"),
                        ],
                        default="manual",
                        max_length=24,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("memory_entries_processed", models.PositiveIntegerField(default=0)),
                ("adjustments_created", models.PositiveIntegerField(default=0)),
                ("adjustments_updated", models.PositiveIntegerField(default=0)),
                ("adjustments_deactivated", models.PositiveIntegerField(default=0)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.RenameIndex(
            model_name="learningadjustment",
            new_name="learning_me_adjustm_f27dfb_idx",
            old_name="learning_adj_adjustm_1e2f1f_idx",
        ),
        migrations.RenameIndex(
            model_name="learningadjustment",
            new_name="learning_me_is_acti_42e021_idx",
            old_name="learning_adj_is_acti_22d932_idx",
        ),
        migrations.RenameIndex(
            model_name="learningmemoryentry",
            new_name="learning_me_memory__1be00c_idx",
            old_name="learning_mem_memory__2ddf67_idx",
        ),
        migrations.RenameIndex(
            model_name="learningmemoryentry",
            new_name="learning_me_outcome_cb60c0_idx",
            old_name="learning_mem_outcome_7f4ec0_idx",
        ),
        migrations.RenameIndex(
            model_name="learningmemoryentry",
            new_name="learning_me_source__0a4da1_idx",
            old_name="learning_mem_source__88f3fd_idx",
        ),
        migrations.AddField(
            model_name="learningrebuildrun",
            name="related_cycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learning_rebuild_runs",
                to="continuous_demo.continuousdemocyclerun",
            ),
        ),
        migrations.AddField(
            model_name="learningrebuildrun",
            name="related_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learning_rebuild_runs",
                to="continuous_demo.continuousdemosession",
            ),
        ),
    ]
