# Generated by Django 5.1.4 on 2026-03-30 02:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_memory", "0002_learningrebuildrun_and_more"),
        ("postmortem_agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailurePattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("canonical_label", models.CharField(max_length=120)),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("narrative_miss", "Narrative miss"),
                            ("prediction_overconfidence", "Prediction overconfidence"),
                            ("weak_edge", "Weak edge"),
                            ("low_liquidity_trap", "Low liquidity trap"),
                            ("timing_decay", "Timing decay"),
                            ("runtime_guard_miss", "Runtime guard miss"),
                            ("risk_sizing_miss", "Risk sizing miss"),
                            ("execution_slippage_miss", "Execution slippage miss"),
                            ("precedent_ignored", "Precedent ignored"),
                            ("multi_factor_failure", "Multi factor failure"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("provider", "Provider"),
                            ("category", "Category"),
                            ("source_type", "Source type"),
                            ("signal_type", "Signal type"),
                            ("market", "Market"),
                        ],
                        default="global",
                        max_length=24,
                    ),
                ),
                ("scope_key", models.CharField(default="global", max_length=120)),
                (
                    "severity_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("recurrence_count", models.PositiveIntegerField(default=1)),
                ("evidence_summary", models.JSONField(blank=True, default=dict)),
                ("linked_postmortems", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("WATCH", "Watch"),
                            ("EXPIRED", "Expired"),
                            ("NEEDS_REVIEW", "Needs review"),
                        ],
                        default="WATCH",
                        max_length=24,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "canonical_label",
                            "pattern_type",
                            "scope",
                            "scope_key",
                        ),
                        name="learning_unique_failure_pattern_scope",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PostmortemLearningAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("confidence_penalty", "Confidence penalty"),
                            ("edge_penalty", "Edge penalty"),
                            ("liquidity_penalty", "Liquidity penalty"),
                            ("source_confidence_penalty", "Source confidence penalty"),
                            ("category_caution", "Category caution"),
                            ("provider_caution", "Provider caution"),
                            ("signal_type_caution", "Signal type caution"),
                            ("risk_size_cap", "Risk size cap"),
                            ("watch_escalation", "Watch escalation"),
                            ("manual_review_trigger", "Manual review trigger"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("provider", "Provider"),
                            ("category", "Category"),
                            ("source_type", "Source type"),
                            ("signal_type", "Signal type"),
                            ("market", "Market"),
                        ],
                        default="global",
                        max_length=24,
                    ),
                ),
                ("scope_key", models.CharField(default="global", max_length=120)),
                (
                    "adjustment_strength",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("EXPIRED", "Expired"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PROPOSED",
                        max_length=24,
                    ),
                ),
                ("expiration_hint", models.DateTimeField(blank=True, null=True)),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_failure_pattern",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustments",
                        to="learning_memory.failurepattern",
                    ),
                ),
                (
                    "linked_postmortem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_adjustments",
                        to="postmortem_agents.postmortemboardrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LearningRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("ACTIVATE_ADJUSTMENT", "Activate adjustment"),
                            ("KEEP_ADJUSTMENT_ON_WATCH", "Keep adjustment on watch"),
                            ("EXPIRE_ADJUSTMENT", "Expire adjustment"),
                            (
                                "REQUIRE_MANUAL_LEARNING_REVIEW",
                                "Require manual learning review",
                            ),
                            (
                                "ATTACH_CAUTION_TO_PREDICTION",
                                "Attach caution to prediction",
                            ),
                            ("ATTACH_CAUTION_TO_RISK", "Attach caution to risk"),
                            ("REORDER_LEARNING_PRIORITY", "Reorder learning priority"),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.5000"), max_digits=5
                    ),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_pattern",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="learning_memory.failurepattern",
                    ),
                ),
                (
                    "target_adjustment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="learning_memory.postmortemlearningadjustment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LearningApplicationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_component",
                    models.CharField(
                        choices=[
                            ("research", "Research"),
                            ("prediction", "Prediction"),
                            ("risk", "Risk"),
                            ("proposal", "Proposal"),
                            ("signal_fusion", "Signal fusion"),
                        ],
                        max_length=24,
                    ),
                ),
                ("target_entity_id", models.CharField(blank=True, max_length=120)),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("caution_attached", "Caution attached"),
                            ("score_penalty_applied", "Score penalty applied"),
                            ("manual_review_required", "Manual review required"),
                            ("size_cap_applied", "Size cap applied"),
                            ("watch_escalation_applied", "Watch escalation applied"),
                        ],
                        max_length=32,
                    ),
                ),
                ("before_value", models.CharField(blank=True, max_length=120)),
                ("after_value", models.CharField(blank=True, max_length=120)),
                ("rationale", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_adjustment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_records",
                        to="learning_memory.postmortemlearningadjustment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PostmortemLearningRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_position_count", models.PositiveIntegerField(default=0)),
                ("failure_pattern_count", models.PositiveIntegerField(default=0)),
                ("adjustment_count", models.PositiveIntegerField(default=0)),
                ("active_adjustment_count", models.PositiveIntegerField(default=0)),
                ("expired_adjustment_count", models.PositiveIntegerField(default=0)),
                (
                    "recommendation_summary",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_postmortem_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_runs",
                        to="postmortem_agents.postmortemboardrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="postmortemlearningadjustment",
            index=models.Index(
                fields=["status", "-updated_at"], name="learning_me_status_d4380c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postmortemlearningadjustment",
            index=models.Index(
                fields=["adjustment_type", "scope", "scope_key"],
                name="learning_me_adjustm_439033_idx",
            ),
        ),
    ]
