# Generated by Django 5.1.4 on 2026-03-25 23:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0002_event_source_type_market_source_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="NarrativeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("title", models.CharField(max_length=512)),
                ("url", models.URLField(max_length=1200)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("raw_text", models.TextField()),
                ("snippet", models.TextField(blank=True)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("source_name", models.CharField(blank=True, max_length=255)),
                ("dedupe_hash", models.CharField(max_length=64, unique=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-published_at", "-ingested_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NarrativeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("rss", "RSS"),
                            ("news_api", "News API"),
                            ("reddit", "Reddit"),
                            ("twitter", "Twitter/X"),
                            ("manual", "Manual"),
                        ],
                        default="rss",
                        max_length=20,
                    ),
                ),
                ("feed_url", models.URLField(blank=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("language", models.CharField(blank=True, max_length=12)),
                ("category", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResearchScanRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="success",
                        max_length=12,
                    ),
                ),
                ("triggered_by", models.CharField(default="manual", max_length=32)),
                ("sources_scanned", models.PositiveIntegerField(default=0)),
                ("items_created", models.PositiveIntegerField(default=0)),
                ("items_deduplicated", models.PositiveIntegerField(default=0)),
                ("analyses_generated", models.PositiveIntegerField(default=0)),
                ("candidates_generated", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NarrativeAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("summary", models.TextField(blank=True)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("neutral", "Neutral"),
                            ("mixed", "Mixed"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="uncertain",
                        max_length=16,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                ("entities", models.JSONField(blank=True, default=list)),
                ("topics", models.JSONField(blank=True, default=list)),
                (
                    "market_relevance_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000")),
                            django.core.validators.MaxValueValidator(Decimal("1.0000")),
                        ],
                    ),
                ),
                (
                    "analysis_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("complete", "Complete"),
                            ("degraded", "Degraded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "narrative_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="research_agent.narrativeitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="narrativeitem",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="research_agent.narrativesource",
            ),
        ),
        migrations.CreateModel(
            name="ResearchCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "narrative_pressure",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                (
                    "sentiment_direction",
                    models.CharField(
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("neutral", "Neutral"),
                            ("mixed", "Mixed"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="uncertain",
                        max_length=16,
                    ),
                ),
                (
                    "implied_probability_snapshot",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "market_implied_direction",
                    models.CharField(
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("neutral", "Neutral"),
                            ("mixed", "Mixed"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="uncertain",
                        max_length=16,
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("alignment", "Alignment"),
                            ("divergence", "Divergence"),
                            ("uncertainty", "Uncertainty"),
                        ],
                        default="uncertainty",
                        max_length=16,
                    ),
                ),
                (
                    "divergence_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                ("short_thesis", models.CharField(blank=True, max_length=255)),
                (
                    "priority",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_candidates",
                        to="markets.market",
                    ),
                ),
                (
                    "narrative_items",
                    models.ManyToManyField(
                        blank=True,
                        related_name="research_candidates",
                        to="research_agent.narrativeitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MarketNarrativeLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "link_strength",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0000")),
                            django.core.validators.MaxValueValidator(Decimal("1.0000")),
                        ],
                    ),
                ),
                ("rationale", models.CharField(blank=True, max_length=255)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="narrative_links",
                        to="markets.market",
                    ),
                ),
                (
                    "narrative_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_links",
                        to="research_agent.narrativeitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-link_strength", "-linked_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("narrative_item", "market"),
                        name="research_unique_item_market_link",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="narrativeitem",
            index=models.Index(
                fields=["source", "-ingested_at"], name="research_ag_source__510c6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="narrativeitem",
            index=models.Index(
                fields=["-published_at"], name="research_ag_publish_297f92_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="researchcandidate",
            constraint=models.UniqueConstraint(
                fields=("market",), name="research_unique_market_candidate"
            ),
        ),
    ]
