# Generated by Django 5.2.5 on 2026-03-26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_event_source_type_market_source_type'),
        ('research_agent', '0003_researchscanrun_twitter_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketUniverseScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=12)),
                ('triggered_by', models.CharField(default='manual', max_length=32)),
                ('filter_profile', models.CharField(choices=[('conservative_scan', 'Conservative scan'), ('balanced_scan', 'Balanced scan'), ('broad_scan', 'Broad scan')], default='balanced_scan', max_length=32)),
                ('provider_scope', models.JSONField(blank=True, default=list)),
                ('source_scope', models.JSONField(blank=True, default=list)),
                ('markets_considered', models.PositiveIntegerField(default=0)),
                ('markets_filtered_out', models.PositiveIntegerField(default=0)),
                ('markets_shortlisted', models.PositiveIntegerField(default=0)),
                ('markets_watchlist', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MarketTriageDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triage_status', models.CharField(choices=[('shortlisted', 'Shortlisted'), ('watch', 'Watch'), ('filtered_out', 'Filtered out')], max_length=16)),
                ('triage_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('exclusion_reasons', models.JSONField(blank=True, default=list)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('narrative_coverage', models.PositiveIntegerField(default=0)),
                ('narrative_relevance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('narrative_confidence', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('source_mix', models.CharField(default='none', max_length=24)),
                ('rationale', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_decisions', to='markets.market')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_decisions', to='research_agent.marketuniversescanrun')),
            ],
            options={
                'ordering': ['-triage_score', '-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('run', 'market'), name='research_unique_run_market_triage_decision')],
            },
        ),
        migrations.CreateModel(
            name='PursuitCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_slug', models.CharField(max_length=64)),
                ('liquidity', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('time_to_resolution_hours', models.IntegerField(blank=True, null=True)),
                ('market_probability', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('narrative_coverage', models.PositiveIntegerField(default=0)),
                ('narrative_direction', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral'), ('mixed', 'Mixed'), ('uncertain', 'Uncertain')], default='uncertain', max_length=16)),
                ('source_mix', models.CharField(default='none', max_length=24)),
                ('triage_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('triage_status', models.CharField(choices=[('shortlisted', 'Shortlisted'), ('watch', 'Watch'), ('filtered_out', 'Filtered out')], max_length=16)),
                ('rationale', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pursuit_candidates', to='markets.market')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pursuit_candidates', to='research_agent.marketuniversescanrun')),
                ('triage_decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pursuit_candidate', to='research_agent.markettriagedecision')),
            ],
            options={
                'ordering': ['-triage_score', '-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('run', 'market'), name='research_unique_run_market_pursuit_candidate')],
            },
        ),
    ]
