# Generated by Django 5.1.4 on 2026-03-30 00:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0002_event_source_type_market_source_type"),
        ("research_agent", "0004_universe_scan_triage_board"),
    ]

    operations = [
        migrations.CreateModel(
            name="NarrativeCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("canonical_topic", models.CharField(max_length=255)),
                ("representative_headline", models.CharField(max_length=512)),
                ("source_types", models.JSONField(blank=True, default=list)),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("first_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "combined_direction",
                    models.CharField(
                        choices=[
                            ("bullish_yes", "Bullish/Yes"),
                            ("bearish_yes", "Bearish/Yes"),
                            ("unclear", "Unclear"),
                            ("mixed", "Mixed"),
                        ],
                        default="unclear",
                        max_length=24,
                    ),
                ),
                (
                    "combined_sentiment",
                    models.CharField(
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("neutral", "Neutral"),
                            ("mixed", "Mixed"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="uncertain",
                        max_length=16,
                    ),
                ),
                (
                    "cluster_status",
                    models.CharField(
                        choices=[
                            ("emerging", "Emerging"),
                            ("confirmed_multi_source", "Confirmed multi-source"),
                            ("noisy", "Noisy"),
                            ("stale", "Stale"),
                        ],
                        default="emerging",
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-item_count", "-last_seen_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SourceScanRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("source_counts", models.JSONField(blank=True, default=dict)),
                ("raw_item_count", models.PositiveIntegerField(default=0)),
                ("deduped_item_count", models.PositiveIntegerField(default=0)),
                ("clustered_count", models.PositiveIntegerField(default=0)),
                ("signal_count", models.PositiveIntegerField(default=0)),
                ("ignored_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NarrativeSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("canonical_label", models.CharField(max_length=255)),
                ("topic", models.CharField(max_length=255)),
                ("source_mix", models.JSONField(blank=True, default=dict)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("bullish_yes", "Bullish/Yes"),
                            ("bearish_yes", "Bearish/Yes"),
                            ("unclear", "Unclear"),
                            ("mixed", "Mixed"),
                        ],
                        default="unclear",
                        max_length=24,
                    ),
                ),
                (
                    "sentiment_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                (
                    "novelty_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                (
                    "intensity_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                (
                    "source_confidence_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                (
                    "market_divergence_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                (
                    "total_signal_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("shortlisted", "Shortlisted"),
                            ("watch", "Watch"),
                            ("ignore", "Ignore"),
                        ],
                        default="candidate",
                        max_length=16,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("raw_source_refs", models.JSONField(blank=True, default=list)),
                ("created_at_scan", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signals",
                        to="research_agent.narrativecluster",
                    ),
                ),
                (
                    "linked_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_narrative_signals",
                        to="markets.market",
                    ),
                ),
                (
                    "target_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="narrative_signals",
                        to="markets.market",
                    ),
                ),
                (
                    "scan_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="research_agent.sourcescanrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-total_signal_score", "-created_at_scan", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ScanRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("send_to_research_triage", "Send to research triage"),
                            (
                                "send_to_prediction_context",
                                "Send to prediction context",
                            ),
                            ("keep_on_watchlist", "Keep on watchlist"),
                            ("ignore_noise", "Ignore noise"),
                            ("require_manual_review", "Require manual review"),
                            ("reorder_scan_priority", "Reorder scan priority"),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.TextField()),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("created_at_scan", models.DateTimeField(auto_now_add=True)),
                (
                    "target_signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="research_agent.narrativesignal",
                    ),
                ),
                (
                    "scan_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="research_agent.sourcescanrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at_scan", "-id"],
            },
        ),
        migrations.AddField(
            model_name="narrativecluster",
            name="scan_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clusters",
                to="research_agent.sourcescanrun",
            ),
        ),
    ]
