# Generated by Django 5.1.4 on 2026-03-30 01:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0002_event_source_type_market_source_type"),
        (
            "research_agent",
            "0005_narrativecluster_sourcescanrun_narrativesignal_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketUniverseRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_markets_seen", models.PositiveIntegerField(default=0)),
                ("open_markets_seen", models.PositiveIntegerField(default=0)),
                ("filtered_out_count", models.PositiveIntegerField(default=0)),
                ("shortlisted_count", models.PositiveIntegerField(default=0)),
                ("watchlist_count", models.PositiveIntegerField(default=0)),
                ("ignored_count", models.PositiveIntegerField(default=0)),
                ("source_provider_counts", models.JSONField(blank=True, default=dict)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MarketResearchCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("market_title", models.CharField(max_length=255)),
                ("market_provider", models.CharField(max_length=64)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "time_to_resolution_hours",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "liquidity_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                (
                    "volume_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                (
                    "freshness_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                (
                    "market_quality_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                (
                    "narrative_support_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                (
                    "divergence_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                (
                    "pursue_worthiness_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=7
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("shortlist", "Shortlist"),
                            ("watchlist", "Watchlist"),
                            ("ignore", "Ignore"),
                            ("needs_review", "Needs review"),
                        ],
                        default="needs_review",
                        max_length=24,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "linked_narrative_signals",
                    models.JSONField(blank=True, default=list),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_research_candidates",
                        to="markets.market",
                    ),
                ),
                (
                    "universe_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="research_agent.marketuniverserun",
                    ),
                ),
            ],
            options={
                "ordering": ["-pursue_worthiness_score", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MarketTriageDecisionV2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("send_to_prediction", "Send to prediction"),
                            ("keep_on_watchlist", "Keep on watchlist"),
                            ("ignore_market", "Ignore market"),
                            ("require_manual_review", "Require manual review"),
                            ("research_followup", "Research follow-up"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("reviewed", "Reviewed"),
                            ("confirmed", "Confirmed"),
                            ("skipped", "Skipped"),
                        ],
                        default="proposed",
                        max_length=24,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triage_decisions",
                        to="research_agent.marketresearchcandidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MarketResearchRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("send_to_prediction", "Send to prediction"),
                            ("research_followup", "Research follow-up"),
                            ("keep_on_watchlist", "Keep on watchlist"),
                            ("ignore_low_quality", "Ignore low quality"),
                            ("ignore_low_liquidity", "Ignore low liquidity"),
                            ("ignore_bad_time_horizon", "Ignore bad time horizon"),
                            ("require_manual_review", "Require manual review"),
                            ("reorder_research_priority", "Reorder research priority"),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="research_agent.marketresearchcandidate",
                    ),
                ),
                (
                    "target_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_recommendations",
                        to="markets.market",
                    ),
                ),
                (
                    "universe_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="research_agent.marketuniverserun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
