# Generated by Django 5.1.4 on 2026-04-01 21:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0002_event_source_type_market_source_type"),
        ("research_agent", "0006_marketuniverserun_marketresearchcandidate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NarrativeConsensusRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_signal_count", models.PositiveIntegerField(default=0)),
                ("considered_cluster_count", models.PositiveIntegerField(default=0)),
                ("consensus_detected_count", models.PositiveIntegerField(default=0)),
                ("conflict_detected_count", models.PositiveIntegerField(default=0)),
                ("divergence_detected_count", models.PositiveIntegerField(default=0)),
                ("priority_handoff_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NarrativeConsensusRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("topic_label", models.CharField(max_length=255)),
                ("source_mix", models.JSONField(blank=True, default=dict)),
                ("source_count", models.PositiveIntegerField(default=0)),
                (
                    "consensus_state",
                    models.CharField(
                        choices=[
                            ("strong_consensus", "Strong consensus"),
                            ("weak_consensus", "Weak consensus"),
                            ("mixed", "Mixed"),
                            ("conflicted", "Conflicted"),
                            ("insufficient_signal", "Insufficient signal"),
                        ],
                        default="insufficient_signal",
                        max_length=32,
                    ),
                ),
                (
                    "sentiment_direction",
                    models.CharField(
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("mixed", "Mixed"),
                            ("unclear", "Unclear"),
                        ],
                        default="unclear",
                        max_length=16,
                    ),
                ),
                (
                    "intensity_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                (
                    "novelty_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                (
                    "persistence_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consensus_records",
                        to="research_agent.narrativecluster",
                    ),
                ),
                (
                    "consensus_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="research_agent.narrativeconsensusrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence_score", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NarrativeMarketDivergenceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "market_probability",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "narrative_bias",
                    models.CharField(
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("mixed", "Mixed"),
                            ("unclear", "Unclear"),
                        ],
                        default="unclear",
                        max_length=16,
                    ),
                ),
                (
                    "divergence_state",
                    models.CharField(
                        choices=[
                            ("aligned", "Aligned"),
                            ("modest_divergence", "Modest divergence"),
                            ("high_divergence", "High divergence"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="uncertain",
                        max_length=32,
                    ),
                ),
                (
                    "divergence_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                ("market_context_summary", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consensus_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divergence_records",
                        to="research_agent.narrativeconsensusrun",
                    ),
                ),
                (
                    "linked_consensus_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divergence_records",
                        to="research_agent.narrativeconsensusrecord",
                    ),
                ),
                (
                    "linked_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="narrative_divergence_records",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "ordering": ["-divergence_score", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ResearchHandoffPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "priority_bucket",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("ignore", "Ignore"),
                        ],
                        default="low",
                        max_length=16,
                    ),
                ),
                (
                    "handoff_status",
                    models.CharField(
                        choices=[
                            ("ready_for_research", "Ready for research"),
                            ("watchlist", "Watchlist"),
                            ("blocked", "Blocked"),
                            ("deferred", "Deferred"),
                        ],
                        default="watchlist",
                        max_length=24,
                    ),
                ),
                ("priority_reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "priority_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                ("handoff_summary", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consensus_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handoff_priorities",
                        to="research_agent.narrativeconsensusrun",
                    ),
                ),
                (
                    "linked_consensus_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handoff_priorities",
                        to="research_agent.narrativeconsensusrecord",
                    ),
                ),
                (
                    "linked_divergence_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handoff_priorities",
                        to="research_agent.narrativemarketdivergencerecord",
                    ),
                ),
                (
                    "linked_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_handoff_priorities",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority_score", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NarrativeConsensusRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            (
                                "send_to_research_immediately",
                                "Send to research immediately",
                            ),
                            (
                                "keep_on_narrative_watchlist",
                                "Keep on narrative watchlist",
                            ),
                            (
                                "prioritize_for_market_divergence_review",
                                "Prioritize for market divergence review",
                            ),
                            ("defer_for_weaker_signal", "Defer for weaker signal"),
                            (
                                "block_for_conflicted_narrative",
                                "Block for conflicted narrative",
                            ),
                            (
                                "require_manual_review_for_source_conflict",
                                "Require manual review for source conflict",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                ("rationale", models.TextField()),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consensus_recommendations",
                        to="research_agent.narrativecluster",
                    ),
                ),
                (
                    "target_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consensus_recommendations",
                        to="markets.market",
                    ),
                ),
                (
                    "consensus_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="research_agent.narrativeconsensusrun",
                    ),
                ),
                (
                    "target_handoff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="research_agent.researchhandoffpriority",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
