# Generated by Django 5.1.4 on 2026-04-01 22:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0002_event_source_type_market_source_type"),
        (
            "research_agent",
            "0007_narrativeconsensusrun_narrativeconsensusrecord_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchPursuitRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_market_count", models.PositiveIntegerField(default=0)),
                ("considered_handoff_count", models.PositiveIntegerField(default=0)),
                ("prediction_ready_count", models.PositiveIntegerField(default=0)),
                ("research_watchlist_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("deferred_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ResearchPursuitScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pursuit_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                (
                    "priority_bucket",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("ignore", "Ignore"),
                        ],
                        default="low",
                        max_length=16,
                    ),
                ),
                ("score_components", models.JSONField(blank=True, default=dict)),
                (
                    "score_status",
                    models.CharField(
                        choices=[
                            ("ready_for_prediction", "Ready for prediction"),
                            (
                                "keep_on_research_watchlist",
                                "Keep on research watchlist",
                            ),
                            ("defer", "Defer"),
                            ("block", "Block"),
                        ],
                        default="defer",
                        max_length=32,
                    ),
                ),
                ("score_summary", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_pursuit_scores",
                        to="markets.market",
                    ),
                ),
                (
                    "pursuit_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="research_agent.researchpursuitrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-pursuit_score", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PredictionHandoffCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "handoff_status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("watch", "Watch"),
                            ("blocked", "Blocked"),
                            ("deferred", "Deferred"),
                        ],
                        default="watch",
                        max_length=16,
                    ),
                ),
                (
                    "handoff_confidence",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                ("handoff_summary", models.TextField(blank=True)),
                ("handoff_reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_consensus_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prediction_handoff_candidates",
                        to="research_agent.narrativeconsensusrecord",
                    ),
                ),
                (
                    "linked_divergence_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prediction_handoff_candidates",
                        to="research_agent.narrativemarketdivergencerecord",
                    ),
                ),
                (
                    "linked_market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction_handoff_candidates",
                        to="markets.market",
                    ),
                ),
                (
                    "pursuit_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction_handoffs",
                        to="research_agent.researchpursuitrun",
                    ),
                ),
                (
                    "linked_pursuit_score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handoff_candidates",
                        to="research_agent.researchpursuitscore",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ResearchStructuralAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "liquidity_state",
                    models.CharField(
                        choices=[
                            ("strong", "Strong"),
                            ("adequate", "Adequate"),
                            ("weak", "Weak"),
                            ("insufficient", "Insufficient"),
                        ],
                        default="insufficient",
                        max_length=16,
                    ),
                ),
                (
                    "volume_state",
                    models.CharField(
                        choices=[
                            ("strong", "Strong"),
                            ("adequate", "Adequate"),
                            ("weak", "Weak"),
                            ("insufficient", "Insufficient"),
                        ],
                        default="insufficient",
                        max_length=16,
                    ),
                ),
                (
                    "time_to_resolution_state",
                    models.CharField(
                        choices=[
                            ("good_window", "Good window"),
                            ("short_window", "Short window"),
                            ("too_close", "Too close"),
                            ("too_far", "Too far"),
                        ],
                        default="too_close",
                        max_length=16,
                    ),
                ),
                (
                    "market_activity_state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("moderate", "Moderate"),
                            ("stale", "Stale"),
                            ("closed_or_blocked", "Closed or blocked"),
                        ],
                        default="closed_or_blocked",
                        max_length=24,
                    ),
                ),
                (
                    "structural_status",
                    models.CharField(
                        choices=[
                            ("prediction_ready", "Prediction ready"),
                            ("watchlist_only", "Watchlist only"),
                            ("deferred", "Deferred"),
                            ("blocked", "Blocked"),
                        ],
                        default="deferred",
                        max_length=24,
                    ),
                ),
                ("assessment_summary", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_consensus_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="structural_assessments",
                        to="research_agent.narrativeconsensusrecord",
                    ),
                ),
                (
                    "linked_divergence_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="structural_assessments",
                        to="research_agent.narrativemarketdivergencerecord",
                    ),
                ),
                (
                    "linked_handoff_priority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="structural_assessments",
                        to="research_agent.researchhandoffpriority",
                    ),
                ),
                (
                    "linked_market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_structural_assessments",
                        to="markets.market",
                    ),
                ),
                (
                    "pursuit_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="research_agent.researchpursuitrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="researchpursuitscore",
            name="linked_assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="research_agent.researchstructuralassessment",
            ),
        ),
        migrations.CreateModel(
            name="ResearchPursuitRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            (
                                "send_to_prediction_immediately",
                                "Send to prediction immediately",
                            ),
                            (
                                "keep_on_research_watchlist",
                                "Keep on research watchlist",
                            ),
                            ("defer_for_low_liquidity", "Defer for low liquidity"),
                            (
                                "defer_for_poor_time_window",
                                "Defer for poor time window",
                            ),
                            ("block_for_stale_market", "Block for stale market"),
                            (
                                "prioritize_for_narrative_divergence",
                                "Prioritize for narrative divergence",
                            ),
                            (
                                "require_manual_review_for_structural_conflict",
                                "Require manual review for structural conflict",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_handoff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="research_agent.predictionhandoffcandidate",
                    ),
                ),
                (
                    "target_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_pursuit_recommendations",
                        to="markets.market",
                    ),
                ),
                (
                    "pursuit_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="research_agent.researchpursuitrun",
                    ),
                ),
                (
                    "target_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="research_agent.researchstructuralassessment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="predictionhandoffcandidate",
            name="linked_assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="handoff_candidates",
                to="research_agent.researchstructuralassessment",
            ),
        ),
    ]
