# Generated by Django 5.1.4 on 2026-03-25 15:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("paper_trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplayRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                        ],
                        default="READY",
                        max_length=16,
                    ),
                ),
                (
                    "source_scope",
                    models.CharField(
                        choices=[
                            ("real_only", "Real only"),
                            ("demo_only", "Demo only"),
                            ("mixed", "Mixed"),
                        ],
                        default="real_only",
                        max_length=16,
                    ),
                ),
                (
                    "provider_scope",
                    models.CharField(blank=True, default="all", max_length=64),
                ),
                ("replay_start_at", models.DateTimeField()),
                ("replay_end_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("snapshots_considered", models.PositiveIntegerField(default=0)),
                ("markets_considered", models.PositiveIntegerField(default=0)),
                ("proposals_generated", models.PositiveIntegerField(default=0)),
                ("trades_executed", models.PositiveIntegerField(default=0)),
                ("approvals_required", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                (
                    "total_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "ending_equity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "paper_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replay_runs",
                        to="paper_trading.paperaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ReplayStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_index", models.PositiveIntegerField()),
                ("step_timestamp", models.DateTimeField()),
                ("snapshots_used", models.PositiveIntegerField(default=0)),
                ("markets_considered", models.PositiveIntegerField(default=0)),
                ("proposals_generated", models.PositiveIntegerField(default=0)),
                ("trades_executed", models.PositiveIntegerField(default=0)),
                ("approvals_required", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                (
                    "estimated_equity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "replay_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="replay_lab.replayrun",
                    ),
                ),
            ],
            options={
                "ordering": ["step_index", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="replayrun",
            index=models.Index(
                fields=["status", "-created_at"], name="replay_lab__status_8d0ab8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="replayrun",
            index=models.Index(
                fields=["source_scope", "-created_at"],
                name="replay_lab__source__b3691f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="replayrun",
            index=models.Index(
                fields=["provider_scope", "-created_at"],
                name="replay_lab__provide_c9666e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="replaystep",
            index=models.Index(
                fields=["replay_run", "step_index"],
                name="replay_lab__replay__d54724_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="replaystep",
            index=models.Index(
                fields=["step_timestamp"], name="replay_lab__step_ti_a526df_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="replaystep",
            constraint=models.UniqueConstraint(
                fields=("replay_run", "step_index"), name="replay_step_run_index_uniq"
            ),
        ),
    ]
