# Generated by Django 5.2.5 on 2026-03-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='TraceRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('root_type', models.CharField(max_length=48)),
                ('root_object_id', models.CharField(max_length=128)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('current_status', models.CharField(blank=True, max_length=64)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.CreateModel(
            name='TraceQueryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_type', models.CharField(default='root_lookup', max_length=48)),
                ('query_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='SUCCESS', max_length=12)),
                ('partial', models.BooleanField(default=False)),
                ('node_count', models.PositiveIntegerField(default=0)),
                ('edge_count', models.PositiveIntegerField(default=0)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_runs', to='trace_explorer.traceroot')),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.CreateModel(
            name='TraceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_key', models.CharField(max_length=160)),
                ('node_type', models.CharField(max_length=64)),
                ('stage', models.CharField(blank=True, max_length=32)),
                ('ref_type', models.CharField(blank=True, max_length=64)),
                ('ref_id', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('summary', models.TextField(blank=True)),
                ('happened_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('trace_root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='trace_explorer.traceroot')),
            ],
            options={'ordering': ['happened_at', 'id']},
        ),
        migrations.CreateModel(
            name='TraceEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(max_length=48)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='trace_explorer.tracenode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='trace_explorer.tracenode')),
                ('trace_root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='trace_explorer.traceroot')),
            ],
            options={'ordering': ['id']},
        ),
        migrations.AddConstraint(
            model_name='traceroot',
            constraint=models.UniqueConstraint(fields=('root_type', 'root_object_id'), name='trace_root_type_object_unique'),
        ),
        migrations.AddConstraint(
            model_name='tracenode',
            constraint=models.UniqueConstraint(fields=('trace_root', 'node_key'), name='trace_node_unique_per_root_key'),
        ),
        migrations.AddIndex(model_name='traceroot', index=models.Index(fields=['root_type', '-updated_at'], name='trace_explo_root_ty_c906fe_idx')),
        migrations.AddIndex(model_name='tracequeryrun', index=models.Index(fields=['status', '-created_at'], name='trace_explo_status_5baccd_idx')),
        migrations.AddIndex(model_name='tracenode', index=models.Index(fields=['trace_root', 'stage'], name='trace_explo_trace_r_5b3bf9_idx')),
        migrations.AddIndex(model_name='tracenode', index=models.Index(fields=['ref_type', 'ref_id'], name='trace_explo_ref_typ_d77880_idx')),
        migrations.AddIndex(model_name='traceedge', index=models.Index(fields=['trace_root', 'relation'], name='trace_explo_trace_r_597177_idx')),
    ]
