# Generated by Django 5.1.4 on 2026-03-29 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approval_center", "0001_initial"),
        ("autonomy_campaign", "0001_initial"),
        ("autonomy_followup", "0001_initial"),
        (
            "memory_retrieval",
            "0002_agentprecedentuse",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("pending_count", models.PositiveIntegerField(default=0)),
                ("in_progress_count", models.PositiveIntegerField(default=0)),
                ("completed_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("closed_loop_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("REVIEW_MEMORY_RESOLUTION", "Review memory resolution"),
                            (
                                "REVIEW_POSTMORTEM_RESOLUTION",
                                "Review postmortem resolution",
                            ),
                            (
                                "REVIEW_ROADMAP_FEEDBACK_STATUS",
                                "Review roadmap feedback status",
                            ),
                            ("MARK_FOLLOWUP_COMPLETED", "Mark followup completed"),
                            ("REQUIRE_MANUAL_REVIEW", "Require manual review"),
                            ("KEEP_PENDING", "Keep pending"),
                            ("REORDER_FEEDBACK_PRIORITY", "Reorder feedback priority"),
                        ],
                        max_length=48,
                    ),
                ),
                ("followup_type", models.CharField(blank=True, max_length=40)),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "followup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_recommendations",
                        to="autonomy_followup.campaignfollowup",
                    ),
                ),
                (
                    "target_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_recommendations",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "feedback_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_feedback.feedbackrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recommendation_type", "-created_at"],
                        name="autonomy_fe_recomme_1335a6_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FollowupResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("BLOCKED", "Blocked"),
                            ("REJECTED", "Rejected"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                (
                    "downstream_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("BLOCKED", "Blocked"),
                            ("REJECTED", "Rejected"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=24,
                    ),
                ),
                (
                    "resolution_type",
                    models.CharField(
                        choices=[
                            ("MEMORY_RESOLVED", "Memory resolved"),
                            ("POSTMORTEM_RESOLVED", "Postmortem resolved"),
                            ("ROADMAP_FEEDBACK_REVIEWED", "Roadmap feedback reviewed"),
                            ("MANUAL_REVIEW_REQUIRED", "Manual review required"),
                        ],
                        default="MANUAL_REVIEW_REQUIRED",
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("resolved_by", models.CharField(blank=True, max_length=120)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "linked_feedback_artifact",
                    models.CharField(blank=True, max_length=120),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followup_resolutions",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "followup",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_resolution",
                        to="autonomy_followup.campaignfollowup",
                    ),
                ),
                (
                    "linked_memory_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_resolutions",
                        to="memory_retrieval.memorydocument",
                    ),
                ),
                (
                    "linked_postmortem_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_resolutions",
                        to="approval_center.approvalrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["resolution_status", "-updated_at"],
                        name="autonomy_fe_resolut_a7fdaa_idx",
                    ),
                    models.Index(
                        fields=["downstream_status", "-updated_at"],
                        name="autonomy_fe_downstr_0b4302_idx",
                    ),
                ],
            },
        ),
    ]
