# Generated by Django 5.1.4 on 2026-03-29 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autonomy_decision", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("ready_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("registered_count", models.PositiveIntegerField(default=0)),
                ("duplicate_skipped_count", models.PositiveIntegerField(default=0)),
                ("roadmap_package_count", models.PositiveIntegerField(default=0)),
                ("scenario_package_count", models.PositiveIntegerField(default=0)),
                ("program_package_count", models.PositiveIntegerField(default=0)),
                ("manager_package_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GovernancePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("ROADMAP_CHANGE_PACKAGE", "Roadmap change package"),
                            ("SCENARIO_CAUTION_PACKAGE", "Scenario caution package"),
                            (
                                "PROGRAM_GOVERNANCE_PACKAGE",
                                "Program governance package",
                            ),
                            ("MANAGER_REVIEW_PACKAGE", "Manager review package"),
                            ("OPERATOR_REVIEW_PACKAGE", "Operator review package"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "package_status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending review"),
                            ("READY", "Ready"),
                            ("REGISTERED", "Registered"),
                            ("BLOCKED", "Blocked"),
                            ("DUPLICATE_SKIPPED", "Duplicate skipped"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=24,
                    ),
                ),
                (
                    "target_scope",
                    models.CharField(
                        choices=[
                            ("roadmap", "Roadmap"),
                            ("scenario", "Scenario"),
                            ("program", "Program"),
                            ("manager", "Manager"),
                            ("operator_review", "Operator review"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.CharField(max_length=255)),
                ("rationale", models.CharField(max_length=255)),
                ("decision_count", models.PositiveIntegerField(default=0)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("grouping_key", models.CharField(max_length=120)),
                ("registered_by", models.CharField(blank=True, max_length=120)),
                ("registered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "linked_target_artifact",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_decisions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="governance_packages",
                        to="autonomy_decision.governancedecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PackageRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ROADMAP_CHANGE_PACKAGE", "Roadmap change package"),
                            ("SCENARIO_CAUTION_PACKAGE", "Scenario caution package"),
                            (
                                "PROGRAM_GOVERNANCE_PACKAGE",
                                "Program governance package",
                            ),
                            ("MANAGER_REVIEW_PACKAGE", "Manager review package"),
                            ("OPERATOR_REVIEW_PACKAGE", "Operator review package"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("REGISTER_ROADMAP_PACKAGE", "Register roadmap package"),
                            ("REGISTER_SCENARIO_PACKAGE", "Register scenario package"),
                            ("REGISTER_PROGRAM_PACKAGE", "Register program package"),
                            ("REGISTER_MANAGER_PACKAGE", "Register manager package"),
                            ("SKIP_DUPLICATE_PACKAGE", "Skip duplicate package"),
                            (
                                "REQUIRE_MANUAL_PACKAGE_REVIEW",
                                "Require manual package review",
                            ),
                            ("REORDER_PACKAGE_PRIORITY", "Reorder package priority"),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "governance_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="package_recommendations",
                        to="autonomy_decision.governancedecision",
                    ),
                ),
                (
                    "governance_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_package.governancepackage",
                    ),
                ),
                (
                    "package_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_package.packagerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="governancepackage",
            index=models.Index(
                fields=["grouping_key", "target_scope", "-updated_at"],
                name="autonomy_pa_groupin_9b2916_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="governancepackage",
            index=models.Index(
                fields=["package_status", "-updated_at"],
                name="autonomy_pa_package_9a2add_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="governancepackage",
            index=models.Index(
                fields=["target_scope", "priority_level", "-updated_at"],
                name="autonomy_pa_target__5c8049_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="packagerecommendation",
            index=models.Index(
                fields=["recommendation_type", "-created_at"],
                name="autonomy_pa_recomme_7d8b03_idx",
            ),
        ),
    ]
