# Generated by Django 5.1.4 on 2026-03-25 00:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proposal_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="SUCCESS",
                        max_length=12,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("real_only", "Real only"),
                            ("demo_only", "Demo only"),
                            ("mixed", "Mixed"),
                        ],
                        default="mixed",
                        max_length=16,
                    ),
                ),
                ("triggered_from", models.CharField(default="manual", max_length=64)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("proposals_considered", models.PositiveIntegerField(default=0)),
                ("proposals_ranked", models.PositiveIntegerField(default=0)),
                ("proposals_selected", models.PositiveIntegerField(default=0)),
                ("proposals_rejected", models.PositiveIntegerField(default=0)),
                (
                    "allocated_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "remaining_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AllocationDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rank", models.PositiveIntegerField(default=0)),
                (
                    "final_allocated_quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("SELECTED", "Selected"),
                            ("REDUCED", "Reduced"),
                            ("SKIPPED", "Skipped"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=12,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocation_decisions",
                        to="proposal_engine.tradeproposal",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="allocation_engine.allocationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "id"],
                "indexes": [
                    models.Index(
                        fields=["run", "rank"], name="allocation__run_id_f147e5_idx"
                    ),
                    models.Index(
                        fields=["decision", "-created_at"],
                        name="allocation__decisio_b87f8c_idx",
                    ),
                ],
            },
        ),
    ]
