# Generated by Django 5.1.4 on 2026-03-26 21:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MissionControlSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDLE", "Idle"),
                            ("RUNNING", "Running"),
                            ("PAUSED", "Paused"),
                            ("DEGRADED", "Degraded"),
                            ("STOPPED", "Stopped"),
                            ("FAILED", "Failed"),
                        ],
                        default="IDLE",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("cycle_count", models.PositiveIntegerField(default=0)),
                ("last_cycle_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MissionControlCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cycle_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="SUCCESS",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("steps_run_count", models.PositiveIntegerField(default=0)),
                ("opportunities_built", models.PositiveIntegerField(default=0)),
                ("proposals_generated", models.PositiveIntegerField(default=0)),
                ("queue_count", models.PositiveIntegerField(default=0)),
                ("auto_execute_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycles",
                        to="mission_control.missioncontrolsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MissionControlState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDLE", "Idle"),
                            ("RUNNING", "Running"),
                            ("PAUSED", "Paused"),
                            ("DEGRADED", "Degraded"),
                            ("STOPPED", "Stopped"),
                            ("FAILED", "Failed"),
                        ],
                        default="IDLE",
                        max_length=12,
                    ),
                ),
                ("pause_requested", models.BooleanField(default=False)),
                ("stop_requested", models.BooleanField(default=False)),
                ("cycle_in_progress", models.BooleanField(default=False)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "profile_slug",
                    models.CharField(default="balanced_mission_control", max_length=40),
                ),
                ("settings_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "active_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="state_records",
                        to="mission_control.missioncontrolsession",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MissionControlStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_type", models.CharField(max_length=48)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="SUCCESS",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="mission_control.missioncontrolcycle",
                    ),
                ),
            ],
            options={
                "ordering": ["started_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="missioncontrolcycle",
            constraint=models.UniqueConstraint(
                fields=("session", "cycle_number"),
                name="mission_control_session_cycle_unique",
            ),
        ),
    ]
