# Generated by Django 5.1.4 on 2026-04-01 23:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousMissionCycleExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("COMPLETED", "Completed"),
                            ("PARTIAL", "Partial"),
                            ("BLOCKED", "Blocked"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="STARTED",
                        max_length=12,
                    ),
                ),
                ("executed_steps", models.JSONField(blank=True, default=list)),
                ("skipped_steps", models.JSONField(blank=True, default=list)),
                ("blocked_steps", models.JSONField(blank=True, default=list)),
                ("linked_scan_run", models.CharField(blank=True, max_length=64)),
                ("linked_pursuit_run", models.CharField(blank=True, max_length=64)),
                (
                    "linked_prediction_intake_run",
                    models.CharField(blank=True, max_length=64),
                ),
                ("linked_risk_intake_run", models.CharField(blank=True, max_length=64)),
                (
                    "linked_execution_intake_run",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "linked_position_watch_run",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "linked_outcome_handoff_run",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "linked_feedback_reuse_run",
                    models.CharField(blank=True, max_length=64),
                ),
                ("execution_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousMissionCyclePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("planned_step_flags", models.JSONField(blank=True, default=dict)),
                (
                    "plan_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("REDUCED", "Reduced"),
                            ("BLOCKED", "Blocked"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="READY",
                        max_length=12,
                    ),
                ),
                ("runtime_mode", models.CharField(blank=True, max_length=32)),
                ("portfolio_posture", models.CharField(blank=True, max_length=32)),
                ("safety_posture", models.CharField(blank=True, max_length=32)),
                ("degraded_mode_state", models.CharField(blank=True, max_length=32)),
                ("plan_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousMissionRuntimeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "runtime_status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("PAUSED", "Paused"),
                            ("STOPPED", "Stopped"),
                            ("DEGRADED", "Degraded"),
                            ("BLOCKED", "Blocked"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="RUNNING",
                        max_length=12,
                    ),
                ),
                ("cycle_count", models.PositiveIntegerField(default=0)),
                ("executed_cycle_count", models.PositiveIntegerField(default=0)),
                ("blocked_cycle_count", models.PositiveIntegerField(default=0)),
                ("dispatch_count", models.PositiveIntegerField(default=0)),
                ("closed_outcome_count", models.PositiveIntegerField(default=0)),
                ("postmortem_handoff_count", models.PositiveIntegerField(default=0)),
                ("learning_handoff_count", models.PositiveIntegerField(default=0)),
                ("reuse_applied_count", models.PositiveIntegerField(default=0)),
                (
                    "recommendation_summary",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousMissionCycleOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outcome_status",
                    models.CharField(
                        choices=[
                            ("NO_ACTION", "No action"),
                            ("WATCH_ONLY", "Watch only"),
                            ("EXECUTION_OCCURRED", "Execution occurred"),
                            ("EXECUTION_REDUCED", "Execution reduced"),
                            ("POSITIONS_UPDATED", "Positions updated"),
                            ("OUTCOMES_CLOSED", "Outcomes closed"),
                            ("LEARNING_UPDATED", "Learning updated"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="NO_ACTION",
                        max_length=24,
                    ),
                ),
                ("dispatch_count", models.PositiveIntegerField(default=0)),
                ("watch_update_count", models.PositiveIntegerField(default=0)),
                ("close_action_count", models.PositiveIntegerField(default=0)),
                ("postmortem_count", models.PositiveIntegerField(default=0)),
                ("learning_count", models.PositiveIntegerField(default=0)),
                ("reuse_count", models.PositiveIntegerField(default=0)),
                ("outcome_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_cycle_execution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcome",
                        to="mission_control.autonomousmissioncycleexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="autonomousmissioncycleexecution",
            name="linked_cycle_plan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="execution",
                to="mission_control.autonomousmissioncycleplan",
            ),
        ),
        migrations.CreateModel(
            name="AutonomousMissionRuntimeRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("RUN_FULL_CYCLE", "Run full cycle"),
                            ("RUN_REDUCED_CYCLE", "Run reduced cycle"),
                            (
                                "SKIP_EXECUTION_AND_MONITOR_ONLY",
                                "Skip execution and monitor only",
                            ),
                            (
                                "PAUSE_FOR_PORTFOLIO_PRESSURE",
                                "Pause for portfolio pressure",
                            ),
                            (
                                "PAUSE_FOR_SAFETY_OR_RUNTIME_BLOCK",
                                "Pause for safety or runtime block",
                            ),
                            (
                                "REQUIRE_MANUAL_RUNTIME_REVIEW",
                                "Require manual runtime review",
                            ),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                (
                    "target_cycle_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomousmissioncycleexecution",
                    ),
                ),
                (
                    "target_cycle_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomousmissioncycleplan",
                    ),
                ),
                (
                    "target_runtime_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomousmissionruntimerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="autonomousmissioncycleplan",
            name="linked_runtime_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cycle_plans",
                to="mission_control.autonomousmissionruntimerun",
            ),
        ),
    ]
