# Generated by Django 5.1.4 on 2026-04-02 00:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0002_autonomousmissioncycleexecution_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousRuntimeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session_status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("PAUSED", "Paused"),
                            ("STOPPED", "Stopped"),
                            ("DEGRADED", "Degraded"),
                            ("BLOCKED", "Blocked"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="RUNNING",
                        max_length=12,
                    ),
                ),
                ("runtime_mode", models.CharField(blank=True, max_length=32)),
                ("profile_slug", models.CharField(blank=True, max_length=40)),
                ("tick_count", models.PositiveIntegerField(default=0)),
                ("executed_tick_count", models.PositiveIntegerField(default=0)),
                ("skipped_tick_count", models.PositiveIntegerField(default=0)),
                ("dispatch_count", models.PositiveIntegerField(default=0)),
                ("closed_outcome_count", models.PositiveIntegerField(default=0)),
                ("pause_reason_codes", models.JSONField(blank=True, default=list)),
                ("stop_reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousCooldownState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cooldown_type",
                    models.CharField(
                        choices=[
                            ("POST_DISPATCH_COOLDOWN", "Post dispatch cooldown"),
                            ("POST_LOSS_COOLDOWN", "Post loss cooldown"),
                            (
                                "PORTFOLIO_PRESSURE_COOLDOWN",
                                "Portfolio pressure cooldown",
                            ),
                            ("RUNTIME_CAUTION_COOLDOWN", "Runtime caution cooldown"),
                            ("QUIET_MARKET_COOLDOWN", "Quiet market cooldown"),
                        ],
                        max_length=36,
                    ),
                ),
                (
                    "cooldown_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("cooldown_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooldowns",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousRuntimeTick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tick_index", models.PositiveIntegerField()),
                (
                    "planned_tick_mode",
                    models.CharField(
                        choices=[
                            ("FULL_CYCLE", "Full cycle"),
                            ("REDUCED_CYCLE", "Reduced cycle"),
                            ("MONITOR_ONLY", "Monitor only"),
                            ("SKIP", "Skip"),
                        ],
                        default="FULL_CYCLE",
                        max_length=20,
                    ),
                ),
                (
                    "tick_status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("STARTED", "Started"),
                            ("COMPLETED", "Completed"),
                            ("PARTIAL", "Partial"),
                            ("BLOCKED", "Blocked"),
                            ("SKIPPED", "Skipped"),
                            ("FAILED", "Failed"),
                        ],
                        default="PLANNED",
                        max_length=12,
                    ),
                ),
                ("tick_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_cycle_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_ticks",
                        to="mission_control.autonomousmissioncycleexecution",
                    ),
                ),
                (
                    "linked_cycle_outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_ticks",
                        to="mission_control.autonomousmissioncycleoutcome",
                    ),
                ),
                (
                    "linked_cycle_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_ticks",
                        to="mission_control.autonomousmissioncycleplan",
                    ),
                ),
                (
                    "linked_runtime_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runtime_ticks",
                        to="mission_control.autonomousmissionruntimerun",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticks",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousCadenceDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cadence_mode",
                    models.CharField(
                        choices=[
                            ("RUN_NOW", "Run now"),
                            ("WAIT_SHORT", "Wait short"),
                            ("WAIT_LONG", "Wait long"),
                            ("MONITOR_ONLY_NEXT", "Monitor only next"),
                            ("PAUSE_SESSION", "Pause session"),
                            ("STOP_SESSION", "Stop session"),
                        ],
                        default="RUN_NOW",
                        max_length=20,
                    ),
                ),
                ("cadence_reason_codes", models.JSONField(blank=True, default=list)),
                ("portfolio_posture", models.CharField(blank=True, max_length=32)),
                ("runtime_posture", models.CharField(blank=True, max_length=32)),
                ("safety_posture", models.CharField(blank=True, max_length=32)),
                (
                    "signal_pressure_state",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("NORMAL", "Normal"),
                            ("LOW", "Low"),
                            ("QUIET", "Quiet"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                ("decision_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cadence_decisions",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "linked_previous_tick",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_cadence_decisions",
                        to="mission_control.autonomousruntimetick",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousSessionRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("CONTINUE_RUNNING", "Continue running"),
                            ("RUN_REDUCED_NEXT_TICK", "Run reduced next tick"),
                            (
                                "PAUSE_FOR_PORTFOLIO_PRESSURE",
                                "Pause for portfolio pressure",
                            ),
                            ("PAUSE_FOR_SAFETY_BLOCK", "Pause for safety block"),
                            (
                                "STOP_FOR_RUNTIME_HARD_BLOCK",
                                "Stop for runtime hard block",
                            ),
                            ("WAIT_FOR_SIGNAL_REFRESH", "Wait for signal refresh"),
                            (
                                "REQUIRE_MANUAL_SESSION_REVIEW",
                                "Require manual session review",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                (
                    "target_cadence_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomouscadencedecision",
                    ),
                ),
                (
                    "target_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "target_tick",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomousruntimetick",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="autonomousruntimetick",
            constraint=models.UniqueConstraint(
                fields=("linked_session", "tick_index"),
                name="autonomous_runtime_session_tick_unique",
            ),
        ),
    ]
