# Generated by Django 5.1.4 on 2026-04-02 02:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mission_control",
            "0003_autonomousruntimesession_autonomouscooldownstate_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousHeartbeatRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "runner_status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("IDLE", "Idle"),
                            ("PAUSED", "Paused"),
                            ("BLOCKED", "Blocked"),
                            ("FAILED", "Failed"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="RUNNING",
                        max_length=12,
                    ),
                ),
                ("considered_session_count", models.PositiveIntegerField(default=0)),
                ("due_tick_count", models.PositiveIntegerField(default=0)),
                ("executed_tick_count", models.PositiveIntegerField(default=0)),
                ("wait_count", models.PositiveIntegerField(default=0)),
                ("cooldown_skip_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("paused_count", models.PositiveIntegerField(default=0)),
                ("stopped_count", models.PositiveIntegerField(default=0)),
                (
                    "recommendation_summary",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousRunnerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("runner_name", models.CharField(max_length=64, unique=True)),
                (
                    "runner_status",
                    models.CharField(
                        choices=[
                            ("STOPPED", "Stopped"),
                            ("RUNNING", "Running"),
                            ("PAUSED", "Paused"),
                            ("ERROR", "Error"),
                        ],
                        default="STOPPED",
                        max_length=12,
                    ),
                ),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("last_successful_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("active_session_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousHeartbeatDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("RUN_DUE_TICK", "Run due tick"),
                            ("WAIT_FOR_NEXT_WINDOW", "Wait for next window"),
                            ("SKIP_FOR_COOLDOWN", "Skip for cooldown"),
                            ("PAUSE_SESSION", "Pause session"),
                            ("STOP_SESSION", "Stop session"),
                            ("BLOCK_SESSION", "Block session"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("EXECUTED", "Executed"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="READY",
                        max_length=12,
                    ),
                ),
                ("due_now", models.BooleanField(default=False)),
                ("next_due_at", models.DateTimeField(blank=True, null=True)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("decision_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_latest_tick",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="heartbeat_decisions",
                        to="mission_control.autonomousruntimetick",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heartbeat_decisions",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "linked_heartbeat_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="mission_control.autonomousheartbeatrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousHeartbeatRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("RUN_DUE_TICK_NOW", "Run due tick now"),
                            (
                                "WAIT_UNTIL_NEXT_DUE_WINDOW",
                                "Wait until next due window",
                            ),
                            ("SKIP_FOR_ACTIVE_COOLDOWN", "Skip for active cooldown"),
                            (
                                "PAUSE_FOR_RUNTIME_OR_SAFETY",
                                "Pause for runtime or safety",
                            ),
                            ("STOP_FOR_KILL_SWITCH", "Stop for kill switch"),
                            (
                                "REQUIRE_MANUAL_RUNNER_REVIEW",
                                "Require manual runner review",
                            ),
                        ],
                        max_length=36,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                (
                    "target_heartbeat_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomousheartbeatdecision",
                    ),
                ),
                (
                    "target_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="heartbeat_recommendations",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousTickDispatchAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dispatch_status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("STARTED", "Started"),
                            ("COMPLETED", "Completed"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=12,
                    ),
                ),
                ("automatic", models.BooleanField(default=True)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_heartbeat_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_attempts",
                        to="mission_control.autonomousheartbeatdecision",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tick_dispatch_attempts",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "linked_tick",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_attempts",
                        to="mission_control.autonomousruntimetick",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
