# Generated by Django 5.1.4 on 2026-04-02 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mission_control",
            "0004_autonomousheartbeatrun_autonomousrunnerstate_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousScheduleProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("base_interval_seconds", models.PositiveIntegerField(default=60)),
                ("reduced_interval_seconds", models.PositiveIntegerField(default=30)),
                (
                    "monitor_only_interval_seconds",
                    models.PositiveIntegerField(default=180),
                ),
                (
                    "cooldown_extension_seconds",
                    models.PositiveIntegerField(default=120),
                ),
                (
                    "max_no_action_ticks_before_pause",
                    models.PositiveIntegerField(default=5),
                ),
                (
                    "max_quiet_ticks_before_wait_long",
                    models.PositiveIntegerField(default=3),
                ),
                (
                    "max_consecutive_blocked_ticks_before_stop",
                    models.PositiveIntegerField(default=4),
                ),
                (
                    "enable_auto_pause_for_quiet_markets",
                    models.BooleanField(default=True),
                ),
                (
                    "enable_auto_stop_for_persistent_blocks",
                    models.BooleanField(default=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["slug", "-id"],
            },
        ),
        migrations.AddField(
            model_name="autonomousruntimesession",
            name="linked_schedule_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runtime_sessions",
                to="mission_control.autonomousscheduleprofile",
            ),
        ),
        migrations.CreateModel(
            name="AutonomousSessionTimingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_tick_at", models.DateTimeField(blank=True, null=True)),
                ("next_due_at", models.DateTimeField(blank=True, null=True)),
                ("active_cooldown_count", models.PositiveIntegerField(default=0)),
                ("consecutive_no_action_ticks", models.PositiveIntegerField(default=0)),
                ("consecutive_blocked_ticks", models.PositiveIntegerField(default=0)),
                ("recent_dispatch_count", models.PositiveIntegerField(default=0)),
                ("recent_loss_count", models.PositiveIntegerField(default=0)),
                (
                    "signal_pressure_state",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("NORMAL", "Normal"),
                            ("LOW", "Low"),
                            ("QUIET", "Quiet"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                (
                    "timing_status",
                    models.CharField(
                        choices=[
                            ("DUE_NOW", "Due now"),
                            ("WAIT_SHORT", "Wait short"),
                            ("WAIT_LONG", "Wait long"),
                            ("MONITOR_ONLY_WINDOW", "Monitor only window"),
                            ("PAUSE_RECOMMENDED", "Pause recommended"),
                            ("STOP_RECOMMENDED", "Stop recommended"),
                        ],
                        default="WAIT_SHORT",
                        max_length=24,
                    ),
                ),
                ("timing_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_schedule_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timing_snapshots",
                        to="mission_control.autonomousscheduleprofile",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timing_snapshots",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousStopConditionEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluation_type",
                    models.CharField(
                        choices=[
                            ("PERSISTENT_BLOCKS", "Persistent blocks"),
                            ("REPEATED_NO_ACTION", "Repeated no action"),
                            ("QUIET_MARKET", "Quiet market"),
                            ("POST_LOSS_COOLDOWN", "Post-loss cooldown"),
                            (
                                "PORTFOLIO_PRESSURE_PERSISTENT",
                                "Portfolio pressure persistent",
                            ),
                            ("RUNTIME_OR_SAFETY_STOP", "Runtime or safety stop"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "evaluation_status",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("CAUTION", "Caution"),
                            ("ACTIONABLE", "Actionable"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=12,
                    ),
                ),
                ("evaluation_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stop_condition_evaluations",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousTimingDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("RUN_NOW", "Run now"),
                            ("WAIT_SHORT", "Wait short"),
                            ("WAIT_LONG", "Wait long"),
                            ("MONITOR_ONLY_NEXT", "Monitor only next"),
                            ("PAUSE_SESSION", "Pause session"),
                            ("STOP_SESSION", "Stop session"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=12,
                    ),
                ),
                ("next_due_at", models.DateTimeField(blank=True, null=True)),
                ("decision_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timing_decisions",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "linked_timing_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timing_decisions",
                        to="mission_control.autonomoussessiontimingsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousTimingRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("RUN_NEXT_TICK_IMMEDIATELY", "Run next tick immediately"),
                            ("WAIT_FOR_SHORT_INTERVAL", "Wait for short interval"),
                            ("WAIT_FOR_LONG_INTERVAL", "Wait for long interval"),
                            ("ENTER_MONITOR_ONLY_WINDOW", "Enter monitor-only window"),
                            (
                                "PAUSE_SESSION_FOR_QUIET_MARKET",
                                "Pause session for quiet market",
                            ),
                            (
                                "STOP_SESSION_FOR_PERSISTENT_BLOCKS",
                                "Stop session for persistent blocks",
                            ),
                            (
                                "REQUIRE_MANUAL_TIMING_REVIEW",
                                "Require manual timing review",
                            ),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                (
                    "target_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timing_recommendations",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "target_timing_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomoustimingdecision",
                    ),
                ),
                (
                    "target_timing_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomoussessiontimingsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
