# Generated by Django 5.1.4 on 2026-04-02 04:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0005_autonomousscheduleprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousProfileSelectionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_session_count", models.PositiveIntegerField(default=0)),
                ("keep_current_profile_count", models.PositiveIntegerField(default=0)),
                ("switch_recommended_count", models.PositiveIntegerField(default=0)),
                ("switched_count", models.PositiveIntegerField(default=0)),
                ("blocked_switch_count", models.PositiveIntegerField(default=0)),
                (
                    "recommendation_summary",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousProfileSwitchDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("KEEP_CURRENT_PROFILE", "Keep current profile"),
                            (
                                "SWITCH_TO_CONSERVATIVE_QUIET",
                                "Switch to conservative quiet",
                            ),
                            ("SWITCH_TO_MONITOR_HEAVY", "Switch to monitor heavy"),
                            ("SWITCH_TO_BALANCED_LOCAL", "Switch to balanced local"),
                            (
                                "REQUIRE_MANUAL_PROFILE_REVIEW",
                                "Require manual profile review",
                            ),
                            ("BLOCK_PROFILE_SWITCH", "Block profile switch"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=12,
                    ),
                ),
                ("decision_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "from_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="switch_decisions_from",
                        to="mission_control.autonomousscheduleprofile",
                    ),
                ),
                (
                    "linked_selection_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="switch_decisions",
                        to="mission_control.autonomousprofileselectionrun",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_switch_decisions",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "to_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="switch_decisions_to",
                        to="mission_control.autonomousscheduleprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousProfileSwitchRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "switch_status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=12,
                    ),
                ),
                ("switch_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "applied_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="switch_records_to",
                        to="mission_control.autonomousscheduleprofile",
                    ),
                ),
                (
                    "linked_selection_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="switch_records",
                        to="mission_control.autonomousprofileselectionrun",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_switch_records",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "linked_switch_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="switch_records",
                        to="mission_control.autonomousprofileswitchdecision",
                    ),
                ),
                (
                    "previous_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="switch_records_from",
                        to="mission_control.autonomousscheduleprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousSessionContextReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio_pressure_state",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCK_NEW_ENTRIES", "Block new entries"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "runtime_posture",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                (
                    "safety_posture",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("HARD_BLOCK", "Hard block"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                (
                    "signal_pressure_state",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("NORMAL", "Normal"),
                            ("LOW", "Low"),
                            ("QUIET", "Quiet"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                (
                    "recent_loss_state",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("RECENT_LOSS", "Recent loss"),
                            ("REPEATED_LOSS", "Repeated loss"),
                        ],
                        default="NONE",
                        max_length=16,
                    ),
                ),
                (
                    "activity_state",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("LOW_ACTIVITY", "Low activity"),
                            ("REPEATED_NO_ACTION", "Repeated no action"),
                            ("REPEATED_BLOCKED", "Repeated blocked"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "context_status",
                    models.CharField(
                        choices=[
                            ("STABLE", "Stable"),
                            (
                                "NEEDS_MORE_CONSERVATIVE_PROFILE",
                                "Needs more conservative profile",
                            ),
                            ("NEEDS_MORE_ACTIVE_PROFILE", "Needs more active profile"),
                            ("HOLD_CURRENT", "Hold current"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="STABLE",
                        max_length=40,
                    ),
                ),
                ("context_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_current_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="context_reviews",
                        to="mission_control.autonomousscheduleprofile",
                    ),
                ),
                (
                    "linked_latest_timing_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="context_reviews",
                        to="mission_control.autonomoussessiontimingsnapshot",
                    ),
                ),
                (
                    "linked_selection_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="context_reviews",
                        to="mission_control.autonomousprofileselectionrun",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_reviews",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="autonomousprofileswitchdecision",
            name="linked_context_review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="switch_decisions",
                to="mission_control.autonomoussessioncontextreview",
            ),
        ),
        migrations.CreateModel(
            name="AutonomousProfileRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("KEEP_BALANCED_PROFILE", "Keep balanced profile"),
                            (
                                "SHIFT_TO_CONSERVATIVE_QUIET_PROFILE",
                                "Shift to conservative quiet profile",
                            ),
                            (
                                "SHIFT_TO_MONITOR_HEAVY_PROFILE",
                                "Shift to monitor heavy profile",
                            ),
                            ("RESTORE_BALANCED_PROFILE", "Restore balanced profile"),
                            (
                                "REQUIRE_MANUAL_PROFILE_REVIEW",
                                "Require manual profile review",
                            ),
                            (
                                "BLOCK_AUTOMATIC_PROFILE_SWITCH",
                                "Block automatic profile switch",
                            ),
                        ],
                        max_length=44,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                (
                    "target_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_recommendations",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "target_switch_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomousprofileswitchdecision",
                    ),
                ),
                (
                    "target_context_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomoussessioncontextreview",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
