# Generated by Django 5.1.4 on 2026-04-02 05:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0006_autonomousprofileselectionrun_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousSessionHealthRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_session_count", models.PositiveIntegerField(default=0)),
                ("healthy_count", models.PositiveIntegerField(default=0)),
                ("anomaly_count", models.PositiveIntegerField(default=0)),
                ("pause_recommended_count", models.PositiveIntegerField(default=0)),
                ("stop_recommended_count", models.PositiveIntegerField(default=0)),
                ("resume_recommended_count", models.PositiveIntegerField(default=0)),
                ("manual_review_count", models.PositiveIntegerField(default=0)),
                ("intervention_applied_count", models.PositiveIntegerField(default=0)),
                (
                    "recommendation_summary",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousSessionHealthSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_health_status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("CAUTION", "Caution"),
                            ("DEGRADED", "Degraded"),
                            ("BLOCKED", "Blocked"),
                            ("STALLED", "Stalled"),
                        ],
                        default="HEALTHY",
                        max_length=12,
                    ),
                ),
                ("consecutive_failed_ticks", models.PositiveIntegerField(default=0)),
                ("consecutive_blocked_ticks", models.PositiveIntegerField(default=0)),
                (
                    "consecutive_no_progress_ticks",
                    models.PositiveIntegerField(default=0),
                ),
                ("has_active_cooldown", models.BooleanField(default=False)),
                ("runner_session_mismatch", models.BooleanField(default=False)),
                ("recent_dispatch_count", models.PositiveIntegerField(default=0)),
                ("recent_outcome_close_count", models.PositiveIntegerField(default=0)),
                ("recent_loss_count", models.PositiveIntegerField(default=0)),
                (
                    "incident_pressure_state",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("CAUTION", "Caution"),
                            ("HIGH", "High"),
                        ],
                        default="NONE",
                        max_length=12,
                    ),
                ),
                ("health_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_health_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="mission_control.autonomoussessionhealthrun",
                    ),
                ),
                (
                    "linked_latest_heartbeat_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_snapshots",
                        to="mission_control.autonomousheartbeatdecision",
                    ),
                ),
                (
                    "linked_latest_tick",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_snapshots",
                        to="mission_control.autonomousruntimetick",
                    ),
                ),
                (
                    "linked_latest_timing_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_snapshots",
                        to="mission_control.autonomoussessiontimingsnapshot",
                    ),
                ),
                (
                    "linked_runner_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_snapshots",
                        to="mission_control.autonomousrunnerstate",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_snapshots",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousSessionAnomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("REPEATED_FAILED_TICKS", "Repeated failed ticks"),
                            ("REPEATED_BLOCKED_TICKS", "Repeated blocked ticks"),
                            ("RUNNER_SESSION_MISMATCH", "Runner/session mismatch"),
                            ("STALE_SESSION_NO_PROGRESS", "Stale session no progress"),
                            ("PERSISTENT_PAUSE", "Persistent pause"),
                            (
                                "SAFETY_OR_RUNTIME_PRESSURE",
                                "Safety or runtime pressure",
                            ),
                            (
                                "INCIDENT_ESCALATION_PRESSURE",
                                "Incident escalation pressure",
                            ),
                            (
                                "POST_LOSS_STABILIZATION_REQUIRED",
                                "Post-loss stabilization required",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "anomaly_severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("CAUTION", "Caution"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=12,
                    ),
                ),
                ("anomaly_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_anomalies",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "linked_health_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="mission_control.autonomoussessionhealthsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousSessionInterventionDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("KEEP_RUNNING", "Keep running"),
                            ("PAUSE_SESSION", "Pause session"),
                            ("RESUME_SESSION", "Resume session"),
                            ("STOP_SESSION", "Stop session"),
                            ("REQUIRE_MANUAL_REVIEW", "Require manual review"),
                            (
                                "ESCALATE_TO_INCIDENT_REVIEW",
                                "Escalate to incident review",
                            ),
                        ],
                        max_length=36,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=12,
                    ),
                ),
                ("auto_applicable", models.BooleanField(default=False)),
                ("decision_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_health_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention_decisions",
                        to="mission_control.autonomoussessionhealthsnapshot",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_intervention_decisions",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousSessionHealthRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("KEEP_SESSION_RUNNING", "Keep session running"),
                            ("PAUSE_FOR_STABILIZATION", "Pause for stabilization"),
                            (
                                "STOP_FOR_PERSISTENT_BLOCKS",
                                "Stop for persistent blocks",
                            ),
                            ("RESUME_AFTER_RECOVERY", "Resume after recovery"),
                            (
                                "REQUIRE_MANUAL_HEALTH_REVIEW",
                                "Require manual health review",
                            ),
                            (
                                "ESCALATE_TO_INCIDENT_LAYER",
                                "Escalate to incident layer",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                (
                    "target_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_recommendations",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "target_health_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomoussessionhealthsnapshot",
                    ),
                ),
                (
                    "target_intervention_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomoussessioninterventiondecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousSessionInterventionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "intervention_status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("intervention_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_intervention_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="mission_control.autonomoussessioninterventiondecision",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_intervention_records",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
