# Generated by Django 5.1.4 on 2026-04-02 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0007_autonomoussessionhealthrun_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousSessionRecoveryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_session_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("ready_to_resume_count", models.PositiveIntegerField(default=0)),
                ("monitor_only_resume_count", models.PositiveIntegerField(default=0)),
                ("manual_review_count", models.PositiveIntegerField(default=0)),
                ("applied_resume_count", models.PositiveIntegerField(default=0)),
                (
                    "recommendation_summary",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousResumeDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("READY_TO_RESUME", "Ready to resume"),
                            (
                                "RESUME_IN_MONITOR_ONLY_MODE",
                                "Resume in monitor-only mode",
                            ),
                            ("KEEP_PAUSED", "Keep paused"),
                            ("REQUIRE_MANUAL_REVIEW", "Require manual review"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=12,
                    ),
                ),
                ("auto_applicable", models.BooleanField(default=False)),
                ("decision_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_decisions",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "linked_recovery_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resume_decisions",
                        to="mission_control.autonomoussessionrecoveryrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousResumeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume_status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "applied_mode",
                    models.CharField(
                        choices=[
                            ("MANUAL_RESUME", "Manual resume"),
                            ("AUTO_SAFE_RESUME", "Auto safe resume"),
                            ("MONITOR_ONLY_RESUME", "Monitor only resume"),
                        ],
                        max_length=24,
                    ),
                ),
                ("resume_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_resume_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_records",
                        to="mission_control.autonomousresumedecision",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_records",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousSessionRecoverySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recovery_status",
                    models.CharField(
                        choices=[
                            ("STABLE", "Stable"),
                            ("DEGRADED", "Degraded"),
                            ("BLOCKED", "Blocked"),
                            ("AMBIGUOUS", "Ambiguous"),
                        ],
                        default="AMBIGUOUS",
                        max_length=12,
                    ),
                ),
                ("recovery_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_health_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovery_snapshots",
                        to="mission_control.autonomoussessionhealthsnapshot",
                    ),
                ),
                (
                    "linked_recovery_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="mission_control.autonomoussessionrecoveryrun",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_snapshots",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "linked_timing_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovery_snapshots",
                        to="mission_control.autonomoussessiontimingsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousSessionRecoveryRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("SAFE_AUTO_RESUME", "Safe auto resume"),
                            ("RESUME_IN_MONITOR_ONLY", "Resume in monitor only"),
                            (
                                "KEEP_PAUSED_PENDING_REVIEW",
                                "Keep paused pending review",
                            ),
                            (
                                "REQUIRE_MANUAL_RECOVERY_REVIEW",
                                "Require manual recovery review",
                            ),
                        ],
                        max_length=44,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                (
                    "target_resume_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomousresumedecision",
                    ),
                ),
                (
                    "target_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_recovery_recommendations",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "target_recovery_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomoussessionrecoverysnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="autonomousresumedecision",
            name="linked_recovery_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resume_decisions",
                to="mission_control.autonomoussessionrecoverysnapshot",
            ),
        ),
        migrations.CreateModel(
            name="AutonomousRecoveryBlocker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("blocker_type", models.CharField(max_length=48)),
                (
                    "blocker_status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("RESOLVED", "Resolved")],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("blocker_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_blockers",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "linked_recovery_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blockers",
                        to="mission_control.autonomoussessionrecoverysnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
