# Generated by Django 5.1.4 on 2026-04-02 17:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0007_autonomoussessionhealthrun_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousSessionRecoveryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_session_count", models.PositiveIntegerField(default=0)),
                ("ready_to_resume_count", models.PositiveIntegerField(default=0)),
                ("keep_paused_count", models.PositiveIntegerField(default=0)),
                ("manual_review_count", models.PositiveIntegerField(default=0)),
                ("stop_recommended_count", models.PositiveIntegerField(default=0)),
                ("incident_escalation_count", models.PositiveIntegerField(default=0)),
                (
                    "recommendation_summary",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousResumeDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("KEEP_PAUSED", "Keep paused"),
                            ("READY_TO_RESUME", "Ready to resume"),
                            (
                                "RESUME_IN_MONITOR_ONLY_MODE",
                                "Resume in monitor only mode",
                            ),
                            (
                                "REQUIRE_MANUAL_RECOVERY_REVIEW",
                                "Require manual recovery review",
                            ),
                            ("STOP_SESSION_PERMANENTLY", "Stop session permanently"),
                            (
                                "ESCALATE_TO_INCIDENT_REVIEW",
                                "Escalate to incident review",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=12,
                    ),
                ),
                ("auto_applicable", models.BooleanField(default=False)),
                ("decision_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_decisions",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousSessionRecoverySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recovery_status",
                    models.CharField(
                        choices=[
                            ("RECOVERED", "Recovered"),
                            ("PARTIALLY_RECOVERED", "Partially recovered"),
                            ("STILL_BLOCKED", "Still blocked"),
                            ("STABILIZING", "Stabilizing"),
                            ("UNRECOVERABLE", "Unrecoverable"),
                        ],
                        default="STABILIZING",
                        max_length=24,
                    ),
                ),
                ("safety_block_cleared", models.BooleanField(default=True)),
                ("runtime_block_cleared", models.BooleanField(default=True)),
                ("incident_pressure_cleared", models.BooleanField(default=True)),
                (
                    "portfolio_pressure_state",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCK_NEW_ENTRIES", "Block new entries"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("cooldown_active", models.BooleanField(default=False)),
                ("recent_failed_ticks", models.PositiveIntegerField(default=0)),
                ("recent_blocked_ticks", models.PositiveIntegerField(default=0)),
                ("recent_successful_ticks", models.PositiveIntegerField(default=0)),
                ("recovery_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_latest_health_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovery_snapshots",
                        to="mission_control.autonomoussessionhealthsnapshot",
                    ),
                ),
                (
                    "linked_latest_intervention_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovery_snapshots",
                        to="mission_control.autonomoussessioninterventiondecision",
                    ),
                ),
                (
                    "linked_latest_intervention_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovery_snapshots",
                        to="mission_control.autonomoussessioninterventionrecord",
                    ),
                ),
                (
                    "linked_latest_timing_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovery_snapshots",
                        to="mission_control.autonomoussessiontimingsnapshot",
                    ),
                ),
                (
                    "linked_recovery_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="mission_control.autonomoussessionrecoveryrun",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_snapshots",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousSessionRecoveryRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("RESUME_SESSION_SAFELY", "Resume session safely"),
                            (
                                "RESUME_IN_MONITOR_ONLY_MODE",
                                "Resume in monitor only mode",
                            ),
                            ("KEEP_SESSION_PAUSED", "Keep session paused"),
                            (
                                "REQUIRE_MANUAL_RECOVERY_REVIEW",
                                "Require manual recovery review",
                            ),
                            (
                                "STOP_SESSION_FOR_UNRECOVERABLE_STATE",
                                "Stop session for unrecoverable state",
                            ),
                            (
                                "ESCALATE_RECOVERY_TO_INCIDENT_LAYER",
                                "Escalate recovery to incident layer",
                            ),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                (
                    "target_resume_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomousresumedecision",
                    ),
                ),
                (
                    "target_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovery_recommendations",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "target_recovery_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomoussessionrecoverysnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="autonomousresumedecision",
            name="linked_recovery_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resume_decisions",
                to="mission_control.autonomoussessionrecoverysnapshot",
            ),
        ),
        migrations.CreateModel(
            name="AutonomousRecoveryBlocker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blocker_type",
                    models.CharField(
                        choices=[
                            ("SAFETY_BLOCK_ACTIVE", "Safety block active"),
                            ("RUNTIME_BLOCK_ACTIVE", "Runtime block active"),
                            ("INCIDENT_PRESSURE_ACTIVE", "Incident pressure active"),
                            ("PORTFOLIO_PRESSURE_ACTIVE", "Portfolio pressure active"),
                            ("COOLDOWN_ACTIVE", "Cooldown active"),
                            ("RECENT_FAILURE_STREAK", "Recent failure streak"),
                            ("RECENT_BLOCKED_STREAK", "Recent blocked streak"),
                            ("MANUAL_REVIEW_REQUIRED", "Manual review required"),
                        ],
                        max_length=36,
                    ),
                ),
                (
                    "blocker_severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("CAUTION", "Caution"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=12,
                    ),
                ),
                ("blocker_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_blockers",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "linked_recovery_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockers",
                        to="mission_control.autonomoussessionrecoverysnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
