# Generated by Django 5.1.4 on 2026-04-02 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0008_autonomoussessionrecoveryrun_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousResumeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume_status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "applied_mode",
                    models.CharField(
                        choices=[
                            ("MANUAL_RESUME", "Manual resume"),
                            ("AUTO_SAFE_RESUME", "Auto safe resume"),
                            ("MONITOR_ONLY_RESUME", "Monitor only resume"),
                        ],
                        max_length=24,
                    ),
                ),
                ("resume_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_resume_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="mission_control.autonomousresumedecision",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_records",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
