# Generated by Django 5.1.4 on 2026-04-02 19:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0009_autonomousresumerecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomousGlobalCapacitySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("max_active_sessions", models.PositiveIntegerField(default=1)),
                ("current_running_sessions", models.PositiveIntegerField(default=0)),
                ("current_paused_sessions", models.PositiveIntegerField(default=0)),
                ("current_degraded_sessions", models.PositiveIntegerField(default=0)),
                ("current_blocked_sessions", models.PositiveIntegerField(default=0)),
                ("active_dispatch_load", models.PositiveIntegerField(default=0)),
                (
                    "open_position_pressure_state",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCK_NEW_ACTIVITY", "Block new activity"),
                        ],
                        default="NORMAL",
                        max_length=24,
                    ),
                ),
                (
                    "runtime_posture",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                (
                    "safety_posture",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("HARD_BLOCK", "Hard block"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                (
                    "incident_pressure_state",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("CAUTION", "Caution"),
                            ("HIGH", "High"),
                        ],
                        default="NONE",
                        max_length=12,
                    ),
                ),
                (
                    "capacity_status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("LIMITED", "Limited"),
                            ("THROTTLED", "Throttled"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="AVAILABLE",
                        max_length=12,
                    ),
                ),
                ("snapshot_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousSessionAdmissionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_session_count", models.PositiveIntegerField(default=0)),
                ("admitted_count", models.PositiveIntegerField(default=0)),
                ("resume_allowed_count", models.PositiveIntegerField(default=0)),
                ("parked_count", models.PositiveIntegerField(default=0)),
                ("deferred_count", models.PositiveIntegerField(default=0)),
                ("paused_count", models.PositiveIntegerField(default=0)),
                ("retired_count", models.PositiveIntegerField(default=0)),
                ("manual_review_count", models.PositiveIntegerField(default=0)),
                (
                    "recommendation_summary",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousSessionAdmissionDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("ADMIT_SESSION", "Admit session"),
                            ("ALLOW_RESUME", "Allow resume"),
                            ("PARK_SESSION", "Park session"),
                            ("DEFER_SESSION", "Defer session"),
                            ("PAUSE_SESSION", "Pause session"),
                            ("RETIRE_SESSION", "Retire session"),
                            (
                                "REQUIRE_MANUAL_ADMISSION_REVIEW",
                                "Require manual review",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=12,
                    ),
                ),
                ("auto_applicable", models.BooleanField(default=False)),
                ("decision_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission_decisions",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousSessionAdmissionReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_priority_state",
                    models.CharField(
                        choices=[
                            ("HIGH_VALUE", "High value"),
                            ("MEDIUM_VALUE", "Medium value"),
                            ("LOW_VALUE", "Low value"),
                            ("NO_VALUE", "No value"),
                        ],
                        default="MEDIUM_VALUE",
                        max_length=16,
                    ),
                ),
                (
                    "session_operability_state",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("RECOVERABLE", "Recoverable"),
                            ("CAUTION", "Caution"),
                            ("BLOCKED", "Blocked"),
                            ("RETIRE_CANDIDATE", "Retire candidate"),
                        ],
                        default="CAUTION",
                        max_length=20,
                    ),
                ),
                (
                    "admission_status",
                    models.CharField(
                        choices=[
                            ("ADMIT", "Admit"),
                            ("RESUME_ALLOWED", "Resume allowed"),
                            ("PARK", "Park"),
                            ("DEFER", "Defer"),
                            ("PAUSE", "Pause"),
                            ("RETIRE", "Retire"),
                            ("MANUAL_REVIEW", "Manual review"),
                        ],
                        default="DEFER",
                        max_length=16,
                    ),
                ),
                ("review_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_capacity_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_reviews",
                        to="mission_control.autonomousglobalcapacitysnapshot",
                    ),
                ),
                (
                    "linked_current_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admission_reviews",
                        to="mission_control.autonomousscheduleprofile",
                    ),
                ),
                (
                    "linked_latest_context_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admission_reviews",
                        to="mission_control.autonomoussessioncontextreview",
                    ),
                ),
                (
                    "linked_latest_health_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admission_reviews",
                        to="mission_control.autonomoussessionhealthsnapshot",
                    ),
                ),
                (
                    "linked_latest_recovery_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admission_reviews",
                        to="mission_control.autonomoussessionrecoverysnapshot",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission_reviews",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "linked_admission_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="mission_control.autonomoussessionadmissionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousSessionAdmissionRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            (
                                "ADMIT_HIGH_PRIORITY_SESSION",
                                "Admit high priority session",
                            ),
                            ("ALLOW_SAFE_RESUME", "Allow safe resume"),
                            ("PARK_LOW_SIGNAL_SESSION", "Park low signal session"),
                            (
                                "DEFER_FOR_CAPACITY_PRESSURE",
                                "Defer for capacity pressure",
                            ),
                            ("PAUSE_FOR_GLOBAL_THROTTLE", "Pause for global throttle"),
                            ("RETIRE_LOW_VALUE_SESSION", "Retire low value session"),
                            (
                                "REQUIRE_MANUAL_ADMISSION_REVIEW",
                                "Require manual admission review",
                            ),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                (
                    "target_admission_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomoussessionadmissiondecision",
                    ),
                ),
                (
                    "target_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admission_recommendations",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
                (
                    "target_admission_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.autonomoussessionadmissionreview",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="autonomoussessionadmissiondecision",
            name="linked_admission_review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisions",
                to="mission_control.autonomoussessionadmissionreview",
            ),
        ),
        migrations.AddField(
            model_name="autonomousglobalcapacitysnapshot",
            name="linked_admission_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capacity_snapshots",
                to="mission_control.autonomoussessionadmissionrun",
            ),
        ),
    ]
