# Generated by Django 5.1.4 on 2026-04-03 15:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0002_event_source_type_market_source_type"),
        ("mission_control", "0010_autonomousglobalcapacitysnapshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernanceReviewQueueRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("collected_item_count", models.PositiveIntegerField(default=0)),
                ("high_priority_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("deferred_count", models.PositiveIntegerField(default=0)),
                ("manual_review_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceReviewItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_module",
                    models.CharField(
                        choices=[
                            ("runtime_governor", "Runtime governor"),
                            ("mission_control", "Mission control"),
                            ("portfolio_governor", "Portfolio governor"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("mode_feedback_apply", "Mode feedback apply"),
                            ("mode_stabilization", "Mode stabilization"),
                            ("session_health", "Session health"),
                            ("session_recovery", "Session recovery"),
                            ("session_admission", "Session admission"),
                            ("exposure_coordination", "Exposure coordination"),
                            ("exposure_apply", "Exposure apply"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_object_id", models.PositiveIntegerField()),
                (
                    "item_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_REVIEW", "In review"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("CAUTION", "Caution"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="CAUTION",
                        max_length=12,
                    ),
                ),
                (
                    "queue_priority",
                    models.CharField(
                        choices=[
                            ("P1", "P1"),
                            ("P2", "P2"),
                            ("P3", "P3"),
                            ("P4", "P4"),
                        ],
                        default="P3",
                        max_length=2,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="governance_review_items",
                        to="markets.market",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="governance_review_items",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
            ],
            options={
                "ordering": ["queue_priority", "-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceReviewRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("REVIEW_NOW", "Review now"),
                            ("SAFE_TO_DISMISS", "Safe to dismiss"),
                            ("RETRY_LATER", "Retry later"),
                            (
                                "REQUIRE_OPERATOR_CONFIRMATION",
                                "Require operator confirmation",
                            ),
                            ("ESCALATE_PRIORITY", "Escalate priority"),
                        ],
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_review_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.governancereviewitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="governancereviewitem",
            constraint=models.UniqueConstraint(
                fields=("source_module", "source_type", "source_object_id"),
                name="governance_review_item_source_unique",
            ),
        ),
    ]
