# Generated by Django 5.1.4 on 2026-04-03 16:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mission_control",
            "0011_governancereviewqueuerun_governancereviewitem_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernanceReviewResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolution_type",
                    models.CharField(
                        choices=[
                            ("APPLY_MANUAL_APPROVAL", "Apply manual approval"),
                            ("KEEP_BLOCKED", "Keep blocked"),
                            ("DISMISS_AS_EXPECTED", "Dismiss as expected"),
                            ("REQUIRE_FOLLOWUP", "Require follow-up"),
                            ("RETRY_SAFE_APPLY", "Retry safe apply"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("resolution_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_review_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolutions",
                        to="mission_control.governancereviewitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
