# Generated by Django 5.1.4 on 2026-04-03 16:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0012_governancereviewresolution"),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernanceAutoResolutionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_item_count", models.PositiveIntegerField(default=0)),
                ("eligible_count", models.PositiveIntegerField(default=0)),
                ("applied_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceAutoResolutionDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("AUTO_DISMISS", "Auto dismiss"),
                            ("AUTO_RETRY_SAFE_APPLY", "Auto retry safe apply"),
                            ("AUTO_REQUIRE_FOLLOWUP", "Auto require follow-up"),
                            ("DO_NOT_AUTO_RESOLVE", "Do not auto-resolve"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=12,
                    ),
                ),
                ("auto_applicable", models.BooleanField(default=False)),
                ("decision_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_review_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_resolution_decisions",
                        to="mission_control.governancereviewitem",
                    ),
                ),
                (
                    "linked_auto_resolution_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions",
                        to="mission_control.governanceautoresolutionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceAutoResolutionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record_status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "effect_type",
                    models.CharField(
                        choices=[
                            ("DISMISSED", "Dismissed"),
                            (
                                "RETRY_SAFE_APPLY_TRIGGERED",
                                "Retry safe apply triggered",
                            ),
                            ("FOLLOWUP_MARKED", "Follow-up marked"),
                            ("NO_CHANGE", "No change"),
                        ],
                        max_length=32,
                    ),
                ),
                ("record_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_auto_resolution_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="mission_control.governanceautoresolutiondecision",
                    ),
                ),
                (
                    "linked_review_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_resolution_records",
                        to="mission_control.governancereviewitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
