# Generated by Django 5.1.4 on 2026-04-03 20:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0013_governanceautoresolutionrun_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernanceQueueAgingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_item_count", models.PositiveIntegerField(default=0)),
                ("stale_item_count", models.PositiveIntegerField(default=0)),
                ("escalated_count", models.PositiveIntegerField(default=0)),
                ("followup_due_count", models.PositiveIntegerField(default=0)),
                ("blocked_stale_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceQueueAgingReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "age_bucket",
                    models.CharField(
                        choices=[
                            ("FRESH", "Fresh"),
                            ("AGING", "Aging"),
                            ("STALE", "Stale"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="FRESH",
                        max_length=12,
                    ),
                ),
                (
                    "aging_status",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("PRIORITY_ESCALATION", "Priority escalation"),
                            ("FOLLOWUP_DUE", "Follow-up due"),
                            ("STALE_BLOCKED", "Stale blocked"),
                            ("MANUAL_REVIEW_OVERDUE", "Manual review overdue"),
                        ],
                        default="NORMAL",
                        max_length=32,
                    ),
                ),
                ("review_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_review_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aging_reviews",
                        to="mission_control.governancereviewitem",
                    ),
                ),
                (
                    "linked_aging_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="mission_control.governancequeueagingrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceQueueAgingRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("KEEP_PRIORITY", "Keep priority"),
                            ("ESCALATE_TO_P1", "Escalate to P1"),
                            ("ESCALATE_TO_P2", "Escalate to P2"),
                            ("REQUIRE_FOLLOWUP_NOW", "Require follow-up now"),
                            ("ESCALATE_BLOCKED_ITEM", "Escalate blocked item"),
                            (
                                "REQUIRE_OPERATOR_REVIEW_NOW",
                                "Require operator review now",
                            ),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_review_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aging_recommendations",
                        to="mission_control.governancereviewitem",
                    ),
                ),
                (
                    "linked_aging_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.governancequeueagingreview",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
