# Generated by Django 5.1.4 on 2026-04-03 20:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0013_governanceautoresolutionrun_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernanceBacklogPressureDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            (
                                "KEEP_BACKLOG_PRESSURE_NORMAL",
                                "Keep backlog pressure normal",
                            ),
                            (
                                "ELEVATE_RUNTIME_CAUTION_SIGNAL",
                                "Elevate runtime caution signal",
                            ),
                            ("ELEVATE_MONITOR_ONLY_BIAS", "Elevate monitor-only bias"),
                            (
                                "REQUIRE_MANUAL_BACKLOG_REVIEW",
                                "Require manual backlog review",
                            ),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "decision_status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPLIED", "Applied"),
                            ("SKIPPED", "Skipped"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PROPOSED",
                        max_length=12,
                    ),
                ),
                ("decision_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceBacklogPressureRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_item_count", models.PositiveIntegerField(default=0)),
                ("high_priority_item_count", models.PositiveIntegerField(default=0)),
                ("overdue_item_count", models.PositiveIntegerField(default=0)),
                ("blocked_stale_count", models.PositiveIntegerField(default=0)),
                ("followup_due_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceBacklogPressureSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("open_item_count", models.PositiveIntegerField(default=0)),
                ("in_review_count", models.PositiveIntegerField(default=0)),
                ("p1_count", models.PositiveIntegerField(default=0)),
                ("p2_count", models.PositiveIntegerField(default=0)),
                ("overdue_count", models.PositiveIntegerField(default=0)),
                ("stale_blocked_count", models.PositiveIntegerField(default=0)),
                ("followup_due_count", models.PositiveIntegerField(default=0)),
                (
                    "pressure_state",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                ("snapshot_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_pressure_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pressure_snapshots",
                        to="mission_control.governancebacklogpressurerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceBacklogPressureRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("KEEP_BACKLOG_STABLE", "Keep backlog stable"),
                            (
                                "REDUCE_RUNTIME_INTENSITY_FOR_BACKLOG",
                                "Reduce runtime intensity for backlog",
                            ),
                            (
                                "INCREASE_MANUAL_REVIEW_URGENCY",
                                "Increase manual review urgency",
                            ),
                            ("REQUIRE_BACKLOG_CLEARING", "Require backlog clearing"),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_pressure_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.governancebacklogpressuredecision",
                    ),
                ),
                (
                    "linked_pressure_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.governancebacklogpressuresnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="governancebacklogpressuredecision",
            name="linked_pressure_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisions",
                to="mission_control.governancebacklogpressuresnapshot",
            ),
        ),
    ]
