# Generated by Django 5.1.4 on 2026-04-03 21:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mission_control",
            "0014_governancequeueagingrun_governancequeueagingreview_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernanceBacklogPressureRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("considered_item_count", models.PositiveIntegerField(default=0)),
                (
                    "pressure_state",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("HIGH", "High"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceBacklogPressureDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("KEEP_NORMAL_PRESSURE", "Keep normal pressure"),
                            ("SET_CAUTION_PRESSURE", "Set caution pressure"),
                            ("SET_HIGH_PRESSURE", "Set high pressure"),
                        ],
                        max_length=32,
                    ),
                ),
                ("decision_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_backlog_pressure_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions",
                        to="mission_control.governancebacklogpressurerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceBacklogPressureSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("open_item_count", models.PositiveIntegerField(default=0)),
                ("overdue_count", models.PositiveIntegerField(default=0)),
                ("overdue_p1_count", models.PositiveIntegerField(default=0)),
                ("stale_blocked_count", models.PositiveIntegerField(default=0)),
                (
                    "persistent_stale_blocked_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("pressure_score", models.PositiveIntegerField(default=0)),
                (
                    "governance_backlog_pressure_state",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CAUTION", "Caution"),
                            ("HIGH", "High"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                ("snapshot_summary", models.CharField(blank=True, max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_backlog_pressure_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="mission_control.governancebacklogpressurerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceBacklogPressureRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("KEEP_BASELINE", "Keep baseline"),
                            ("PREFER_REDUCED_CADENCE", "Prefer reduced cadence"),
                            ("LIMIT_NEW_ACTIVITY", "Limit new activity"),
                        ],
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("confidence", models.FloatField(default=0.5)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "linked_backlog_pressure_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="mission_control.governancebacklogpressuredecision",
                    ),
                ),
                (
                    "linked_backlog_pressure_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="mission_control.governancebacklogpressuresnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="governancebacklogpressuredecision",
            name="linked_backlog_pressure_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisions",
                to="mission_control.governancebacklogpressuresnapshot",
            ),
        ),
    ]
