# Generated by Django 5.1.4 on 2026-04-15 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_control", "0015_governancebacklogpressurerun_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LlmShadowAnalysisArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(default="ollama", max_length=32)),
                ("model", models.CharField(default="unknown", max_length=80)),
                (
                    "llm_shadow_reasoning_status",
                    models.CharField(default="UNAVAILABLE", max_length=16),
                ),
                ("stance", models.CharField(default="unclear", max_length=16)),
                ("confidence", models.CharField(default="low", max_length=16)),
                ("summary", models.TextField(blank=True)),
                ("key_risks", models.JSONField(blank=True, default=list)),
                ("key_supporting_points", models.JSONField(blank=True, default=list)),
                (
                    "recommendation_mode",
                    models.CharField(default="observe", max_length=24),
                ),
                ("shadow_only", models.BooleanField(default=True)),
                ("advisory_only", models.BooleanField(default=True)),
                ("non_blocking", models.BooleanField(default=True)),
                (
                    "shadow_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("focus_case_source", models.CharField(blank=True, max_length=64)),
                ("source_scope", models.CharField(blank=True, max_length=80)),
                ("test_run_reference", models.CharField(blank=True, max_length=96)),
                ("handoff_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "prediction_candidate_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "risk_decision_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "shortlist_signal_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("focus_case_details", models.JSONField(blank=True, default=dict)),
                ("market_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "runtime_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_shadow_artifacts",
                        to="mission_control.autonomousruntimesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-shadow_timestamp", "-id"],
                "indexes": [
                    models.Index(
                        fields=["market_id", "-shadow_timestamp"],
                        name="mc_llm_shadow_market_ts_idx",
                    ),
                    models.Index(
                        fields=["runtime_session", "-shadow_timestamp"],
                        name="mc_llm_shadow_runtime_ts_idx",
                    ),
                    models.Index(
                        fields=["source_scope", "-shadow_timestamp"],
                        name="mc_llm_shadow_scope_ts_idx",
                    ),
                ],
            },
        ),
    ]
