# Generated by Django 5.1.4 on 2026-03-28 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autonomy_campaign", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomyProgramState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_campaigns_count", models.PositiveIntegerField(default=0)),
                ("blocked_campaigns_count", models.PositiveIntegerField(default=0)),
                ("waiting_approval_count", models.PositiveIntegerField(default=0)),
                ("observing_campaigns_count", models.PositiveIntegerField(default=0)),
                ("degraded_domains_count", models.PositiveIntegerField(default=0)),
                ("locked_domains", models.JSONField(blank=True, default=list)),
                (
                    "concurrency_posture",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CONSTRAINED", "Constrained"),
                            ("HIGH_RISK", "High risk"),
                            ("FROZEN", "Frozen"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CampaignConcurrencyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("max_active_campaigns", "Max active campaigns"),
                            ("incompatible_domains", "Incompatible domains"),
                            ("block_if_degraded", "Block if degraded"),
                            (
                                "block_if_under_observation",
                                "Block if under observation",
                            ),
                            (
                                "block_if_critical_incident",
                                "Block if critical incident",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("scope", models.CharField(default="global", max_length=80)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("rationale", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["rule_type", "scope"],
                        name="autonomy_pr_rule_ty_7a141c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CampaignHealthSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_wave", models.PositiveIntegerField(default=1)),
                ("domain_count", models.PositiveIntegerField(default=0)),
                ("blocked_checkpoints", models.PositiveIntegerField(default=0)),
                ("open_approvals", models.PositiveIntegerField(default=0)),
                ("rollout_warnings", models.PositiveIntegerField(default=0)),
                ("incident_impact", models.PositiveIntegerField(default=0)),
                ("degraded_impact", models.PositiveIntegerField(default=0)),
                ("health_score", models.PositiveIntegerField(default=100)),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("CAUTION", "Caution"),
                            ("BLOCKED", "Blocked"),
                            ("AT_RISK", "At risk"),
                        ],
                        default="HEALTHY",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_health_snapshots",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["campaign", "-created_at"],
                        name="autonomy_pr_campaig_5d47bb_idx",
                    ),
                    models.Index(
                        fields=["health_status", "-created_at"],
                        name="autonomy_pr_health__937c6a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProgramRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("CONTINUE_CAMPAIGN", "Continue campaign"),
                            ("PAUSE_CAMPAIGN", "Pause campaign"),
                            ("REORDER_QUEUE", "Reorder queue"),
                            ("ABORT_CAMPAIGN", "Abort campaign"),
                            ("HOLD_NEW_CAMPAIGNS", "Hold new campaigns"),
                            ("SAFE_TO_START_NEXT", "Safe to start next"),
                            ("WAIT_FOR_STABILIZATION", "Wait for stabilization"),
                        ],
                        max_length=32,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("impacted_domains", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program_recommendations",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recommendation_type", "-created_at"],
                        name="autonomy_pr_recomme_3ce654_idx",
                    )
                ],
            },
        ),
    ]
