# Generated by Django 5.1.4 on 2026-03-29 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autonomy_campaign", "0001_initial"),
        ("autonomy_insights", "0001_initial"),
        ("memory_retrieval", "0002_agentprecedentuse"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("ready_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("emitted_count", models.PositiveIntegerField(default=0)),
                ("duplicate_skipped_count", models.PositiveIntegerField(default=0)),
                ("memory_note_count", models.PositiveIntegerField(default=0)),
                ("roadmap_note_count", models.PositiveIntegerField(default=0)),
                ("scenario_note_count", models.PositiveIntegerField(default=0)),
                ("program_note_count", models.PositiveIntegerField(default=0)),
                ("manager_note_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AdvisoryRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            (
                                "EMIT_MEMORY_PRECEDENT_NOTE",
                                "Emit memory precedent note",
                            ),
                            (
                                "EMIT_ROADMAP_GOVERNANCE_NOTE",
                                "Emit roadmap governance note",
                            ),
                            (
                                "EMIT_SCENARIO_CAUTION_NOTE",
                                "Emit scenario caution note",
                            ),
                            ("EMIT_PROGRAM_POLICY_NOTE", "Emit program policy note"),
                            ("EMIT_MANAGER_REVIEW_NOTE", "Emit manager review note"),
                            ("SKIP_DUPLICATE_ADVISORY", "Skip duplicate advisory"),
                            (
                                "REQUIRE_MANUAL_ADVISORY_REVIEW",
                                "Require manual advisory review",
                            ),
                            ("REORDER_ADVISORY_PRIORITY", "Reorder advisory priority"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MEMORY_PRECEDENT_NOTE", "Memory precedent note"),
                            ("ROADMAP_GOVERNANCE_NOTE", "Roadmap governance note"),
                            ("SCENARIO_CAUTION_NOTE", "Scenario caution note"),
                            ("PROGRAM_POLICY_NOTE", "Program policy note"),
                            ("MANAGER_REVIEW_NOTE", "Manager review note"),
                        ],
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign_insight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advisory_recommendations",
                        to="autonomy_insights.campaigninsight",
                    ),
                ),
                (
                    "target_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advisory_recommendations",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "advisory_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_advisory.advisoryrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recommendation_type", "-created_at"],
                        name="autonomy_ad_recomme_21ea19_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AdvisoryArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("MEMORY_PRECEDENT_NOTE", "Memory precedent note"),
                            ("ROADMAP_GOVERNANCE_NOTE", "Roadmap governance note"),
                            ("SCENARIO_CAUTION_NOTE", "Scenario caution note"),
                            ("PROGRAM_POLICY_NOTE", "Program policy note"),
                            ("MANAGER_REVIEW_NOTE", "Manager review note"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "artifact_status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending review"),
                            ("READY", "Ready"),
                            ("EMITTED", "Emitted"),
                            ("BLOCKED", "Blocked"),
                            ("DUPLICATE_SKIPPED", "Duplicate skipped"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=24,
                    ),
                ),
                (
                    "target_scope",
                    models.CharField(
                        choices=[
                            ("memory", "Memory"),
                            ("roadmap", "Roadmap"),
                            ("scenario", "Scenario"),
                            ("program", "Program"),
                            ("manager", "Manager"),
                            ("operator_review", "Operator review"),
                        ],
                        max_length=24,
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("emitted_by", models.CharField(blank=True, max_length=120)),
                ("emitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "linked_feedback_artifact",
                    models.CharField(blank=True, max_length=128),
                ),
                ("linked_program_note", models.CharField(blank=True, max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advisory_artifacts",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "insight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advisory_artifacts",
                        to="autonomy_insights.campaigninsight",
                    ),
                ),
                (
                    "linked_memory_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advisory_artifacts",
                        to="memory_retrieval.memorydocument",
                    ),
                ),
                (
                    "advisory_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifacts",
                        to="autonomy_advisory.advisoryrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["insight", "artifact_type"],
                        name="autonomy_ad_insight_5b57f0_idx",
                    ),
                    models.Index(
                        fields=["artifact_status", "-created_at"],
                        name="autonomy_ad_artifac_5effc1_idx",
                    ),
                    models.Index(
                        fields=["target_scope", "-created_at"],
                        name="autonomy_ad_target__00f975_idx",
                    ),
                ],
            },
        ),
    ]
