# Generated by Django 5.1.4 on 2026-03-25 00:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RealMarketOperationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="SUCCESS",
                        max_length=12,
                    ),
                ),
                (
                    "triggered_from",
                    models.CharField(
                        choices=[
                            ("continuous_demo", "Continuous demo"),
                            ("automation", "Automation"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=24,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("providers_considered", models.PositiveIntegerField(default=0)),
                ("markets_considered", models.PositiveIntegerField(default=0)),
                ("markets_eligible", models.PositiveIntegerField(default=0)),
                ("proposals_generated", models.PositiveIntegerField(default=0)),
                ("auto_executed_count", models.PositiveIntegerField(default=0)),
                ("approval_required_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("skipped_stale_count", models.PositiveIntegerField(default=0)),
                (
                    "skipped_degraded_provider_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("skipped_no_pricing_count", models.PositiveIntegerField(default=0)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RealScopeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "provider_scope",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("kalshi", "Kalshi"),
                            ("polymarket", "Polymarket"),
                        ],
                        default="all",
                        max_length=24,
                    ),
                ),
                (
                    "market_scope",
                    models.CharField(
                        choices=[
                            ("active_only", "Active only"),
                            ("curated", "Curated"),
                            ("recent_only", "Recent only"),
                        ],
                        default="active_only",
                        max_length=24,
                    ),
                ),
                ("max_real_markets_per_cycle", models.PositiveIntegerField(default=8)),
                (
                    "max_real_auto_trades_per_cycle",
                    models.PositiveIntegerField(default=1),
                ),
                (
                    "max_real_exposure_total",
                    models.DecimalField(decimal_places=2, default=2500, max_digits=14),
                ),
                (
                    "max_real_exposure_per_market",
                    models.DecimalField(decimal_places=2, default=500, max_digits=14),
                ),
                ("require_fresh_sync", models.BooleanField(default=True)),
                ("stale_data_blocks_execution", models.BooleanField(default=True)),
                (
                    "degraded_provider_blocks_execution",
                    models.BooleanField(default=True),
                ),
                (
                    "min_liquidity_threshold",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "min_volume_threshold",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("allowed_categories", models.JSONField(blank=True, default=list)),
                ("exclude_categories", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
