# Generated by Django 5.1.4 on 2026-03-29 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autonomy_advisory", "0001_initial"),
        ("autonomy_advisory_resolution", "0001_initial"),
        ("autonomy_campaign", "0001_initial"),
        ("autonomy_insights", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacklogRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("ready_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("duplicate_skipped_count", models.PositiveIntegerField(default=0)),
                ("prioritized_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceBacklogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "backlog_type",
                    models.CharField(
                        choices=[
                            ("ROADMAP_CHANGE_CANDIDATE", "Roadmap change candidate"),
                            (
                                "SCENARIO_CAUTION_CANDIDATE",
                                "Scenario caution candidate",
                            ),
                            (
                                "PROGRAM_GOVERNANCE_CANDIDATE",
                                "Program governance candidate",
                            ),
                            ("MANAGER_REVIEW_ITEM", "Manager review item"),
                            ("OPERATOR_REVIEW_ITEM", "Operator review item"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "backlog_status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending review"),
                            ("READY", "Ready"),
                            ("PRIORITIZED", "Prioritized"),
                            ("DEFERRED", "Deferred"),
                            ("BLOCKED", "Blocked"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=24,
                    ),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                ("target_scope", models.CharField(max_length=24)),
                ("summary", models.CharField(max_length=255)),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("created_by", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "advisory_artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backlog_items",
                        to="autonomy_advisory.advisoryartifact",
                    ),
                ),
                (
                    "advisory_resolution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="backlog_items",
                        to="autonomy_advisory_resolution.advisoryresolution",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="governance_backlog_items",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "insight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="governance_backlog_items",
                        to="autonomy_insights.campaigninsight",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BacklogRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("CREATE_BACKLOG_ITEM", "Create backlog item"),
                            ("PRIORITIZE_BACKLOG_ITEM", "Prioritize backlog item"),
                            ("DEFER_BACKLOG_ITEM", "Defer backlog item"),
                            ("SKIP_DUPLICATE_BACKLOG", "Skip duplicate backlog item"),
                            (
                                "REQUIRE_MANUAL_BACKLOG_REVIEW",
                                "Require manual backlog review",
                            ),
                            ("REORDER_BACKLOG_PRIORITY", "Reorder backlog priority"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "backlog_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ROADMAP_CHANGE_CANDIDATE", "Roadmap change candidate"),
                            (
                                "SCENARIO_CAUTION_CANDIDATE",
                                "Scenario caution candidate",
                            ),
                            (
                                "PROGRAM_GOVERNANCE_CANDIDATE",
                                "Program governance candidate",
                            ),
                            ("MANAGER_REVIEW_ITEM", "Manager review item"),
                            ("OPERATOR_REVIEW_ITEM", "Operator review item"),
                        ],
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "advisory_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backlog_recommendations",
                        to="autonomy_advisory.advisoryartifact",
                    ),
                ),
                (
                    "insight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backlog_recommendations",
                        to="autonomy_insights.campaigninsight",
                    ),
                ),
                (
                    "backlog_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_backlog.backlogrun",
                    ),
                ),
                (
                    "backlog_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_backlog.governancebacklogitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="governancebacklogitem",
            index=models.Index(
                fields=["advisory_artifact", "-updated_at"],
                name="autonomy_ba_advisor_254b34_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="governancebacklogitem",
            index=models.Index(
                fields=["backlog_status", "-updated_at"],
                name="autonomy_ba_backlog_17f7dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="governancebacklogitem",
            index=models.Index(
                fields=["priority_level", "-updated_at"],
                name="autonomy_ba_priorit_113020_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="backlogrecommendation",
            index=models.Index(
                fields=["recommendation_type", "-created_at"],
                name="autonomy_ba_recomme_b0c13e_idx",
            ),
        ),
    ]
