# Generated by Django 5.1.4 on 2026-03-29 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autonomy_campaign", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationsRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_campaign_count", models.PositiveIntegerField(default=0)),
                ("on_track_count", models.PositiveIntegerField(default=0)),
                ("caution_count", models.PositiveIntegerField(default=0)),
                ("stalled_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("waiting_approval_count", models.PositiveIntegerField(default=0)),
                ("observing_count", models.PositiveIntegerField(default=0)),
                ("attention_signal_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CampaignAttentionSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("stalled_progress", "Stalled progress"),
                            ("blocked_checkpoint", "Blocked checkpoint"),
                            ("approval_delay", "Approval delay"),
                            ("rollout_warning", "Rollout warning"),
                            ("incident_impact", "Incident impact"),
                            ("degraded_pressure", "Degraded pressure"),
                            ("domain_conflict", "Domain conflict"),
                            ("observation_timeout", "Observation timeout"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("linked_trace", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations_attention_signals",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="autonomy_op_status_930920_idx",
                    ),
                    models.Index(
                        fields=["severity", "-created_at"],
                        name="autonomy_op_severit_419dfa_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CampaignRuntimeSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campaign_status", models.CharField(max_length=16)),
                ("current_wave", models.PositiveIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("last_progress_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stalled_duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("open_checkpoints_count", models.PositiveIntegerField(default=0)),
                ("pending_approvals_count", models.PositiveIntegerField(default=0)),
                ("blocked_steps_count", models.PositiveIntegerField(default=0)),
                ("incident_impact", models.PositiveIntegerField(default=0)),
                ("degraded_impact", models.PositiveIntegerField(default=0)),
                ("rollout_observation_impact", models.PositiveIntegerField(default=0)),
                (
                    "progress_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "runtime_status",
                    models.CharField(
                        choices=[
                            ("ON_TRACK", "On track"),
                            ("CAUTION", "Caution"),
                            ("STALLED", "Stalled"),
                            ("BLOCKED", "Blocked"),
                            ("WAITING_APPROVAL", "Waiting approval"),
                            ("OBSERVING", "Observing"),
                        ],
                        default="ON_TRACK",
                        max_length=20,
                    ),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations_runtime_snapshots",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "current_checkpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_runtime_snapshots",
                        to="autonomy_campaign.autonomycampaigncheckpoint",
                    ),
                ),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_runtime_snapshots",
                        to="autonomy_campaign.autonomycampaignstep",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["campaign", "-created_at"],
                        name="autonomy_op_campaig_17900f_idx",
                    ),
                    models.Index(
                        fields=["runtime_status", "-created_at"],
                        name="autonomy_op_runtime_ef30d9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OperationsRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("CONTINUE_CAMPAIGN", "Continue campaign"),
                            ("PAUSE_CAMPAIGN", "Pause campaign"),
                            ("RESUME_CAMPAIGN", "Resume campaign"),
                            ("ESCALATE_TO_APPROVAL", "Escalate to approval"),
                            ("REVIEW_FOR_ABORT", "Review for abort"),
                            ("WAIT_FOR_CHECKPOINT", "Wait for checkpoint"),
                            ("CLEAR_TO_CONTINUE", "Clear to continue"),
                            (
                                "REORDER_OPERATOR_ATTENTION",
                                "Reorder operator attention",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("impacted_domains", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "target_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_recommendations",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "operations_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_operations.operationsrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recommendation_type", "-created_at"],
                        name="autonomy_op_recomme_4733a4_idx",
                    )
                ],
            },
        ),
    ]
