# Generated by Django 5.1.4 on 2026-03-30 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autonomy_seed", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeedReviewRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("pending_count", models.PositiveIntegerField(default=0)),
                ("acknowledged_count", models.PositiveIntegerField(default=0)),
                ("accepted_count", models.PositiveIntegerField(default=0)),
                ("deferred_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("closed_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SeedResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("ACCEPTED", "Accepted"),
                            ("DEFERRED", "Deferred"),
                            ("REJECTED", "Rejected"),
                            ("BLOCKED", "Blocked"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                (
                    "resolution_type",
                    models.CharField(
                        choices=[
                            ("ROADMAP_SEED_ACKNOWLEDGED", "Roadmap seed acknowledged"),
                            (
                                "SCENARIO_SEED_ACKNOWLEDGED",
                                "Scenario seed acknowledged",
                            ),
                            ("PROGRAM_SEED_ACKNOWLEDGED", "Program seed acknowledged"),
                            ("MANAGER_SEED_ACKNOWLEDGED", "Manager seed acknowledged"),
                            (
                                "OPERATOR_SEED_ACKNOWLEDGED",
                                "Operator seed acknowledged",
                            ),
                            ("MANUAL_REVIEW_REQUIRED", "Manual review required"),
                        ],
                        default="MANUAL_REVIEW_REQUIRED",
                        max_length=48,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("resolved_by", models.CharField(blank=True, max_length=120)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "linked_target_artifact",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "governance_seed",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seed_resolution",
                        to="autonomy_seed.governanceseed",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["resolution_status", "-updated_at"],
                        name="autonomy_se_resolut_03f454_idx",
                    ),
                    models.Index(
                        fields=["governance_seed", "-updated_at"],
                        name="autonomy_se_governa_130527_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SeedReviewRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("ACKNOWLEDGE_SEED", "Acknowledge seed"),
                            ("MARK_SEED_ACCEPTED", "Mark seed accepted"),
                            ("MARK_SEED_DEFERRED", "Mark seed deferred"),
                            ("MARK_SEED_REJECTED", "Mark seed rejected"),
                            (
                                "REQUIRE_MANUAL_SEED_REVIEW",
                                "Require manual seed review",
                            ),
                            ("KEEP_SEED_PENDING", "Keep seed pending"),
                            (
                                "REORDER_SEED_REVIEW_PRIORITY",
                                "Reorder seed review priority",
                            ),
                        ],
                        max_length=56,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "governance_seed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seed_review_recommendations",
                        to="autonomy_seed.governanceseed",
                    ),
                ),
                (
                    "review_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_seed_review.seedreviewrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recommendation_type", "-created_at"],
                        name="autonomy_se_recomme_c33857_idx",
                    )
                ],
            },
        ),
    ]
