# Generated by Django 5.1.4 on 2026-03-29 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autonomy_package", "0001_initial"),
        ('autonomy_package_review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name="SeedRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("ready_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("registered_count", models.PositiveIntegerField(default=0)),
                ("duplicate_skipped_count", models.PositiveIntegerField(default=0)),
                ("roadmap_seed_count", models.PositiveIntegerField(default=0)),
                ("scenario_seed_count", models.PositiveIntegerField(default=0)),
                ("program_seed_count", models.PositiveIntegerField(default=0)),
                ("manager_seed_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceSeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seed_type",
                    models.CharField(
                        choices=[
                            ("ROADMAP_SEED", "Roadmap seed"),
                            ("SCENARIO_SEED", "Scenario seed"),
                            ("PROGRAM_SEED", "Program seed"),
                            ("MANAGER_SEED", "Manager seed"),
                            ("OPERATOR_REVIEW_SEED", "Operator review seed"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "seed_status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending review"),
                            ("READY", "Ready"),
                            ("REGISTERED", "Registered"),
                            ("BLOCKED", "Blocked"),
                            ("DUPLICATE_SKIPPED", "Duplicate skipped"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=24,
                    ),
                ),
                (
                    "target_scope",
                    models.CharField(
                        choices=[
                            ("roadmap", "Roadmap"),
                            ("scenario", "Scenario"),
                            ("program", "Program"),
                            ("manager", "Manager"),
                            ("operator_review", "Operator review"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.CharField(max_length=255)),
                ("rationale", models.CharField(max_length=255)),
                ("linked_packages", models.JSONField(blank=True, default=list)),
                ("linked_decisions", models.JSONField(blank=True, default=list)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("grouping_key", models.CharField(max_length=120)),
                ("registered_by", models.CharField(blank=True, max_length=120)),
                ("registered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "linked_target_artifact",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "governance_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="governance_seeds",
                        to="autonomy_package.governancepackage",
                    ),
                ),
                (
                    "package_resolution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="governance_seeds",
                        to="autonomy_package_review.packageresolution",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SeedRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("REGISTER_ROADMAP_SEED", "Register roadmap seed"),
                            ("REGISTER_SCENARIO_SEED", "Register scenario seed"),
                            ("REGISTER_PROGRAM_SEED", "Register program seed"),
                            ("REGISTER_MANAGER_SEED", "Register manager seed"),
                            ("SKIP_DUPLICATE_SEED", "Skip duplicate seed"),
                            (
                                "REQUIRE_MANUAL_SEED_REVIEW",
                                "Require manual seed review",
                            ),
                            ("REORDER_SEED_PRIORITY", "Reorder seed priority"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "seed_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ROADMAP_SEED", "Roadmap seed"),
                            ("SCENARIO_SEED", "Scenario seed"),
                            ("PROGRAM_SEED", "Program seed"),
                            ("MANAGER_SEED", "Manager seed"),
                            ("OPERATOR_REVIEW_SEED", "Operator review seed"),
                        ],
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "governance_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seed_recommendations",
                        to="autonomy_package.governancepackage",
                    ),
                ),
                (
                    "governance_seed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_seed.governanceseed",
                    ),
                ),
                (
                    "seed_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_seed.seedrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="governanceseed",
            index=models.Index(
                fields=["governance_package", "target_scope", "-updated_at"],
                name="autonomy_se_governa_f949db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="governanceseed",
            index=models.Index(
                fields=["seed_status", "-updated_at"],
                name="autonomy_se_seed_st_96c135_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="governanceseed",
            index=models.Index(
                fields=["target_scope", "priority_level", "-updated_at"],
                name="autonomy_se_target__96ad00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="seedrecommendation",
            index=models.Index(
                fields=["recommendation_type", "-created_at"],
                name="autonomy_se_recomme_57834e_idx",
            ),
        ),
    ]
