# Generated by Django 5.1.4 on 2026-03-28 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutonomyScenarioRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("summary", models.CharField(max_length=255)),
                ("evidence_snapshot", models.JSONField(blank=True, default=dict)),
                ("selected_option_key", models.CharField(blank=True, max_length=120)),
                (
                    "selected_recommendation_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BEST_NEXT_MOVE", "Best next move"),
                            ("SAFE_BUNDLE", "Safe bundle"),
                            ("SEQUENCE_FIRST", "Sequence first"),
                            ("DELAY_UNTIL_STABLE", "Delay until stable"),
                            ("DO_NOT_EXECUTE", "Do not execute"),
                            ("REQUIRE_APPROVAL_HEAVY", "Require approval heavy"),
                        ],
                        max_length=40,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("option_key", models.CharField(max_length=120)),
                ("option_type", models.CharField(max_length=40)),
                ("domains", models.JSONField(blank=True, default=list)),
                ("order", models.JSONField(blank=True, default=list)),
                ("requested_stages", models.JSONField(blank=True, default=dict)),
                ("is_bundle", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="autonomy_scenario.autonomyscenariorun",
                    ),
                ),
            ],
            options={
                "ordering": ["run_id", "option_key"],
                "unique_together": {("run", "option_key")},
            },
        ),
        migrations.CreateModel(
            name="ScenarioRiskEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dependency_conflict_risk",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "approval_friction_risk",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "degraded_posture_risk",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "incident_exposure_risk",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "rollback_likelihood_hint",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "bundle_risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("approval_heavy", models.BooleanField(default=False)),
                ("conflicts", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "option",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_estimate",
                        to="autonomy_scenario.scenariooption",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_estimates",
                        to="autonomy_scenario.autonomyscenariorun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_code",
                    models.CharField(
                        choices=[
                            ("BEST_NEXT_MOVE", "Best next move"),
                            ("SAFE_BUNDLE", "Safe bundle"),
                            ("SEQUENCE_FIRST", "Sequence first"),
                            ("DELAY_UNTIL_STABLE", "Delay until stable"),
                            ("DO_NOT_EXECUTE", "Do not execute"),
                            ("REQUIRE_APPROVAL_HEAVY", "Require approval heavy"),
                        ],
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("supporting_evidence", models.JSONField(blank=True, default=list)),
                ("estimated_blockers", models.JSONField(blank=True, default=list)),
                (
                    "score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="autonomy_scenario.scenariooption",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="autonomy_scenario.autonomyscenariorun",
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recommendation_code", "-created_at"],
                        name="autonomy_sc_recomme_921dd7_idx",
                    )
                ],
            },
        ),
    ]
