# Generated by Django 5.1.4 on 2026-03-23 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0001_initial"),
        ("paper_trading", "0001_initial"),
        ("risk_demo", "0001_initial"),
        ("signals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=8
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")], max_length=8
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "requested_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "estimated_gross_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "requested_by",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("automation_demo", "Automation demo"),
                            ("system", "System"),
                        ],
                        default="user",
                        max_length=32,
                    ),
                ),
                (
                    "triggered_from",
                    models.CharField(
                        choices=[
                            ("market_detail", "Market detail"),
                            ("automation", "Automation"),
                            ("signal", "Signal"),
                            ("system", "System"),
                        ],
                        default="market_detail",
                        max_length=32,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("AUTO_APPROVE", "Auto approve"),
                            ("APPROVAL_REQUIRED", "Approval required"),
                            ("HARD_BLOCK", "Hard block"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="LOW",
                        max_length=12,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("rationale", models.TextField(blank=True)),
                ("matched_rules", models.JSONField(blank=True, default=list)),
                ("recommendation", models.TextField(blank=True)),
                (
                    "risk_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("APPROVE", "Approve"),
                            ("CAUTION", "Caution"),
                            ("BLOCK", "Block"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "linked_signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_decisions",
                        to="signals.marketsignal",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_decisions",
                        to="markets.market",
                    ),
                ),
                (
                    "paper_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_decisions",
                        to="paper_trading.paperaccount",
                    ),
                ),
                (
                    "risk_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_decisions",
                        to="risk_demo.traderiskassessment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["decision", "-created_at"],
                        name="policy_engi_decisio_cc23ea_idx",
                    ),
                    models.Index(
                        fields=["market", "-created_at"],
                        name="policy_engi_market__de924e_idx",
                    ),
                    models.Index(
                        fields=["paper_account", "-created_at"],
                        name="policy_engi_paper_a_f17487_idx",
                    ),
                    models.Index(
                        fields=["triggered_from", "requested_by"],
                        name="policy_engi_trigger_a77eb1_idx",
                    ),
                ],
            },
        ),
    ]
