# Generated by Django 5.1.4 on 2026-03-26 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("postmortem_demo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostmortemBoardRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                        ],
                        default="READY",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("perspectives_run_count", models.PositiveIntegerField(default=0)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "related_trade_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="board_runs",
                        to="postmortem_demo.tradereview",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PostmortemBoardConclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("primary_failure_mode", models.CharField(max_length=64)),
                ("secondary_failure_modes", models.JSONField(blank=True, default=list)),
                ("lesson_learned", models.TextField()),
                ("recommended_adjustments", models.JSONField(blank=True, default=list)),
                ("should_update_learning_memory", models.BooleanField(default=True)),
                ("severity", models.CharField(default="medium", max_length=16)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "board_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conclusion",
                        to="postmortem_agents.postmortemboardrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PostmortemAgentReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "perspective_type",
                    models.CharField(
                        choices=[
                            ("narrative", "Narrative"),
                            ("prediction", "Prediction"),
                            ("risk", "Risk"),
                            ("runtime", "Runtime"),
                            ("learning", "Learning"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="SUCCESS",
                        max_length=12,
                    ),
                ),
                ("conclusion", models.TextField(blank=True)),
                ("key_findings", models.JSONField(blank=True, default=dict)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("recommended_actions", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "board_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perspective_reviews",
                        to="postmortem_agents.postmortemboardrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("board_run", "perspective_type"),
                        name="postmortem_board_unique_perspective_review",
                    )
                ],
            },
        ),
    ]
