# Generated by Django 5.1.4 on 2026-03-28 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approval_center", "0001_initial"),
        ("automation_policy", "0001_initial"),
        ("trust_calibration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyTuningCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_type", models.CharField(max_length=80)),
                ("current_trust_tier", models.CharField(blank=True, max_length=32)),
                ("proposed_trust_tier", models.CharField(blank=True, max_length=32)),
                ("proposed_conditions", models.JSONField(blank=True, default=dict)),
                ("rationale", models.CharField(blank=True, max_length=255)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("evidence_refs", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("APPLIED", "Applied"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "approval_request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policy_tuning_candidate",
                        to="approval_center.approvalrequest",
                    ),
                ),
                (
                    "current_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policy_tuning_candidates",
                        to="automation_policy.automationpolicyprofile",
                    ),
                ),
                (
                    "current_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policy_tuning_candidates",
                        to="automation_policy.automationpolicyrule",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policy_tuning_candidates",
                        to="trust_calibration.trustcalibrationrecommendation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PolicyTuningApplicationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("before_snapshot", models.JSONField(blank=True, default=dict)),
                ("after_snapshot", models.JSONField(blank=True, default=dict)),
                ("applied_at", models.DateTimeField()),
                ("result_summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "applied_to_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="automation_policy.automationpolicyprofile",
                    ),
                ),
                (
                    "applied_to_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="automation_policy.automationpolicyrule",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_logs",
                        to="policy_tuning.policytuningcandidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PolicyChangeSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("profile_slug", models.SlugField(max_length=80)),
                ("action_type", models.CharField(max_length=80)),
                ("old_trust_tier", models.CharField(blank=True, max_length=32)),
                ("new_trust_tier", models.CharField(blank=True, max_length=32)),
                ("old_conditions", models.JSONField(blank=True, default=dict)),
                ("new_conditions", models.JSONField(blank=True, default=dict)),
                ("apply_scope", models.CharField(default="RULE_ONLY", max_length=80)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_set",
                        to="policy_tuning.policytuningcandidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PolicyTuningReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("REQUIRE_MORE_EVIDENCE", "Require more evidence"),
                            ("DEFER", "Defer"),
                        ],
                        max_length=32,
                    ),
                ),
                ("review_status", models.CharField(default="COMPLETED", max_length=16)),
                ("reviewer_note", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="policy_tuning.policytuningcandidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="policytuningcandidate",
            index=models.Index(
                fields=["status", "-created_at"], name="policy_tuni_status_eb2678_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policytuningcandidate",
            index=models.Index(
                fields=["action_type", "-created_at"],
                name="policy_tuni_action__5227d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="policytuningapplicationlog",
            index=models.Index(
                fields=["-applied_at"], name="policy_tuni_applied_4ad188_idx"
            ),
        ),
    ]
