# Generated by Django 5.1.4 on 2026-03-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProviderSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("kalshi", "Kalshi"),
                            ("polymarket", "Polymarket"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("full", "Full"),
                            ("incremental", "Incremental"),
                            ("single_market", "Single market"),
                            ("active_only", "Active only"),
                        ],
                        default="full",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "triggered_from",
                    models.CharField(blank=True, default="api", max_length=64),
                ),
                ("markets_seen", models.PositiveIntegerField(default=0)),
                ("markets_created", models.PositiveIntegerField(default=0)),
                ("markets_updated", models.PositiveIntegerField(default=0)),
                ("snapshots_created", models.PositiveIntegerField(default=0)),
                ("errors_count", models.PositiveIntegerField(default=0)),
                ("summary", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["provider", "-started_at"],
                        name="real_data_s_provide_b9ef3a_idx",
                    ),
                    models.Index(
                        fields=["status", "-started_at"],
                        name="real_data_s_status_f3747d_idx",
                    ),
                ],
            },
        ),
    ]
