# Generated by Django 5.1.4 on 2026-03-29 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autonomy_advisory", "0001_initial"),
        ("autonomy_backlog", "0001_initial"),
        ("autonomy_campaign", "0001_initial"),
        ("autonomy_insights", "0001_initial"),
        ("autonomy_intake", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningReviewRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("pending_count", models.PositiveIntegerField(default=0)),
                ("acknowledged_count", models.PositiveIntegerField(default=0)),
                ("accepted_count", models.PositiveIntegerField(default=0)),
                ("deferred_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("closed_count", models.PositiveIntegerField(default=0)),
                ("recommendation_summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PlanningProposalResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("ACCEPTED", "Accepted"),
                            ("DEFERRED", "Deferred"),
                            ("REJECTED", "Rejected"),
                            ("BLOCKED", "Blocked"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                (
                    "resolution_type",
                    models.CharField(
                        choices=[
                            (
                                "ROADMAP_PROPOSAL_ACKNOWLEDGED",
                                "Roadmap proposal acknowledged",
                            ),
                            (
                                "SCENARIO_PROPOSAL_ACKNOWLEDGED",
                                "Scenario proposal acknowledged",
                            ),
                            (
                                "PROGRAM_REVIEW_ACKNOWLEDGED",
                                "Program review acknowledged",
                            ),
                            (
                                "MANAGER_REVIEW_ACKNOWLEDGED",
                                "Manager review acknowledged",
                            ),
                            (
                                "OPERATOR_REVIEW_ACKNOWLEDGED",
                                "Operator review acknowledged",
                            ),
                            ("MANUAL_REVIEW_REQUIRED", "Manual review required"),
                        ],
                        default="MANUAL_REVIEW_REQUIRED",
                        max_length=40,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("resolved_by", models.CharField(blank=True, max_length=120)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "linked_target_artifact",
                    models.CharField(blank=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "advisory_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_resolutions",
                        to="autonomy_advisory.advisoryartifact",
                    ),
                ),
                (
                    "backlog_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_resolutions",
                        to="autonomy_backlog.governancebacklogitem",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_resolutions",
                        to="autonomy_campaign.autonomycampaign",
                    ),
                ),
                (
                    "insight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_resolutions",
                        to="autonomy_insights.campaigninsight",
                    ),
                ),
                (
                    "planning_proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_resolution",
                        to="autonomy_intake.planningproposal",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["planning_proposal", "-updated_at"],
                        name="autonomy_pl_plannin_de01ce_idx",
                    ),
                    models.Index(
                        fields=["resolution_status", "-updated_at"],
                        name="autonomy_pl_resolut_f6077f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanningReviewRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("ACKNOWLEDGE_PROPOSAL", "Acknowledge proposal"),
                            ("MARK_ACCEPTED", "Mark accepted"),
                            ("MARK_DEFERRED", "Mark deferred"),
                            ("MARK_REJECTED", "Mark rejected"),
                            ("REQUIRE_MANUAL_REVIEW", "Require manual review"),
                            ("KEEP_PENDING", "Keep pending"),
                            (
                                "REORDER_PLANNING_REVIEW_PRIORITY",
                                "Reorder planning review priority",
                            ),
                        ],
                        max_length=56,
                    ),
                ),
                ("rationale", models.CharField(max_length=255)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "backlog_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_review_recommendations",
                        to="autonomy_backlog.governancebacklogitem",
                    ),
                ),
                (
                    "planning_proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_review_recommendations",
                        to="autonomy_intake.planningproposal",
                    ),
                ),
                (
                    "review_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="autonomy_planning_review.planningreviewrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recommendation_type", "-created_at"],
                        name="autonomy_pl_recomme_4cc8ba_idx",
                    )
                ],
            },
        ),
    ]
