# Generated by Django 5.1.4 on 2026-03-24 19:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0002_event_source_type_market_source_type"),
        ("paper_trading", "0001_initial"),
        ("proposal_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SemiAutoRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("scan_and_execute", "Scan and execute"),
                            ("execute_auto", "Execute auto"),
                            ("evaluate_only", "Evaluate only"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("markets_evaluated", models.PositiveIntegerField(default=0)),
                ("proposals_generated", models.PositiveIntegerField(default=0)),
                ("auto_executed_count", models.PositiveIntegerField(default=0)),
                ("approval_required_count", models.PositiveIntegerField(default=0)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PendingApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("EXECUTED", "Executed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "requested_action",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=8
                    ),
                ),
                ("suggested_side", models.CharField(max_length=8)),
                (
                    "suggested_quantity",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "policy_decision",
                    models.CharField(
                        choices=[
                            ("AUTO_APPROVE", "Auto approve"),
                            ("APPROVAL_REQUIRED", "Approval required"),
                            ("HARD_BLOCK", "Hard block"),
                        ],
                        max_length=24,
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("rationale", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "executed_trade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_approvals",
                        to="paper_trading.papertrade",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pending_approvals",
                        to="markets.market",
                    ),
                ),
                (
                    "paper_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pending_approvals",
                        to="paper_trading.paperaccount",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pending_approvals",
                        to="proposal_engine.tradeproposal",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="semi_auto_d_status_fbaa25_idx",
                    ),
                    models.Index(
                        fields=["market", "status"],
                        name="semi_auto_d_market__d072f1_idx",
                    ),
                    models.Index(
                        fields=["paper_account", "status"],
                        name="semi_auto_d_paper_a_b4f5ef_idx",
                    ),
                ],
            },
        ),
    ]
