# Generated by Django 5.1.4 on 2026-03-25 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReadinessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=96)),
                ("slug", models.SlugField(max_length=128, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("conservative", "Conservative"),
                            ("balanced", "Balanced"),
                            ("strict", "Strict"),
                            ("custom", "Custom"),
                        ],
                        default="balanced",
                        max_length=24,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["name", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "profile_type"],
                        name="readiness_l_is_acti_20df1c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReadinessAssessmentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("CAUTION", "Caution"),
                            ("NOT_READY", "Not ready"),
                        ],
                        default="CAUTION",
                        max_length=16,
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("rationale", models.TextField(blank=True)),
                ("gates_passed_count", models.PositiveIntegerField(default=0)),
                ("gates_failed_count", models.PositiveIntegerField(default=0)),
                ("warnings_count", models.PositiveIntegerField(default=0)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "readiness_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_runs",
                        to="readiness_lab.readinessprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="readiness_l_status_70e496_idx",
                    ),
                    models.Index(
                        fields=["readiness_profile", "-created_at"],
                        name="readiness_l_readine_70dfd0_idx",
                    ),
                ],
            },
        ),
    ]
