# Generated by Django 5.1.4 on 2026-03-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider_event_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("upcoming", "Upcoming"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("open_time", models.DateTimeField(blank=True, null=True)),
                ("close_time", models.DateTimeField(blank=True, null=True)),
                ("resolution_time", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("base_url", models.URLField(blank=True)),
                ("api_base_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider_market_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("ticker", models.CharField(blank=True, max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "market_type",
                    models.CharField(
                        choices=[
                            ("binary", "Binary"),
                            ("categorical", "Categorical"),
                            ("scalar", "Scalar"),
                            ("multi_outcome", "Multi-outcome"),
                            ("other", "Other"),
                        ],
                        default="binary",
                        max_length=24,
                    ),
                ),
                (
                    "outcome_type",
                    models.CharField(
                        choices=[
                            ("yes_no", "Yes/No"),
                            ("multiple_choice", "Multiple choice"),
                            ("numeric_range", "Numeric range"),
                            ("other", "Other"),
                        ],
                        default="yes_no",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("resolution_source", models.CharField(blank=True, max_length=255)),
                ("short_rules", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("open_time", models.DateTimeField(blank=True, null=True)),
                ("close_time", models.DateTimeField(blank=True, null=True)),
                ("resolution_time", models.DateTimeField(blank=True, null=True)),
                (
                    "current_market_probability",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "current_yes_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "current_no_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "liquidity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "volume_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "volume_total",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("spread_bps", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="markets",
                        to="markets.event",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="markets",
                        to="markets.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="markets.provider",
            ),
        ),
        migrations.CreateModel(
            name="MarketRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("provider", "Provider"),
                            ("internal", "Internal"),
                            ("manual", "Manual"),
                            ("imported", "Imported"),
                        ],
                        default="provider",
                        max_length=20,
                    ),
                ),
                ("rule_text", models.TextField()),
                ("resolution_criteria", models.TextField(blank=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "ordering": ["market__title", "source_type", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["market", "source_type"],
                        name="markets_mar_market__598c27_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("captured_at", models.DateTimeField()),
                (
                    "market_probability",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "yes_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "no_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "last_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "ask",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "spread",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "liquidity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "volume_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "open_interest",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["market", "-captured_at"],
                        name="markets_mar_market__e9fbb2_idx",
                    ),
                    models.Index(
                        fields=["captured_at"], name="markets_mar_capture_cff3ac_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("market", "captured_at"),
                        name="markets_snapshot_market_captured_at_uniq",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(
                fields=["provider", "status"], name="markets_mar_provide_560bbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(
                fields=["event", "status"], name="markets_mar_event_i_67d683_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(
                fields=["provider", "category"], name="markets_mar_provide_31108f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(
                fields=["close_time"], name="markets_mar_close_t_b82da9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(
                fields=["is_active", "status"], name="markets_mar_is_acti_4f04cd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_market_id__isnull", False)),
                fields=("provider", "provider_market_id"),
                name="markets_market_provider_provider_market_id_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.UniqueConstraint(
                fields=("provider", "slug"), name="markets_market_provider_slug_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["provider", "status"], name="markets_eve_provide_83bf72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["provider", "category"], name="markets_eve_provide_21ba63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["open_time"], name="markets_eve_open_ti_b8fc7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["close_time"], name="markets_eve_close_t_6e6c24_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_event_id__isnull", False)),
                fields=("provider", "provider_event_id"),
                name="markets_event_provider_provider_event_id_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("provider", "slug"), name="markets_event_provider_slug_uniq"
            ),
        ),
    ]
