# Generated by Django 5.1.4 on 2026-03-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="source_type",
            field=models.CharField(
                choices=[("demo", "Demo/Local"), ("real_read_only", "Real Read-only")],
                default="demo",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="source_type",
            field=models.CharField(
                choices=[("demo", "Demo/Local"), ("real_read_only", "Real Read-only")],
                default="demo",
                max_length=24,
            ),
        ),
    ]
