# Generated by Django 5.1.4 on 2026-03-23 20:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0001_initial"),
        ("paper_trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeRiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "side",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")], max_length=8
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=8
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "requested_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "current_market_probability",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "current_yes_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "current_no_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APPROVE", "Approve"),
                            ("CAUTION", "Caution"),
                            ("BLOCK", "Block"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("rationale", models.TextField(blank=True)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "suggested_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("is_actionable", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risk_assessments",
                        to="markets.market",
                    ),
                ),
                (
                    "paper_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_assessments",
                        to="paper_trading.paperaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["decision", "-created_at"],
                        name="risk_demo_t_decisio_a87428_idx",
                    ),
                    models.Index(
                        fields=["market", "-created_at"],
                        name="risk_demo_t_market__410d27_idx",
                    ),
                    models.Index(
                        fields=["paper_account", "-created_at"],
                        name="risk_demo_t_paper_a_8d1f28_idx",
                    ),
                ],
            },
        ),
    ]
