# Generated by Django 5.1.4 on 2026-03-23 18:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "US Dollar")], default="USD", max_length=8
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10000.00"), max_digits=14
                    ),
                ),
                (
                    "cash_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10000.00"), max_digits=14
                    ),
                ),
                (
                    "reserved_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "equity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10000.00"), max_digits=14
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "total_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "slug"],
                        name="paper_tradi_is_acti_e28f98_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PaperPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "side",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")], max_length=8
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                (
                    "average_entry_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=12
                    ),
                ),
                (
                    "current_mark_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=12
                    ),
                ),
                (
                    "cost_basis",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "market_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        max_length=8,
                    ),
                ),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("last_marked_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="paper_trading.paperaccount",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paper_positions",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaperTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=8
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")], max_length=8
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                ("price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EXECUTED", "Executed"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="EXECUTED",
                        max_length=12,
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="paper_trading.paperaccount",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paper_trades",
                        to="markets.market",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="paper_trading.paperposition",
                    ),
                ),
            ],
            options={
                "ordering": ["-executed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaperPortfolioSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "captured_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("cash_balance", models.DecimalField(decimal_places=2, max_digits=14)),
                ("equity", models.DecimalField(decimal_places=2, max_digits=14)),
                ("realized_pnl", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("total_pnl", models.DecimalField(decimal_places=2, max_digits=14)),
                ("open_positions_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="paper_trading.paperaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["account", "-captured_at"],
                        name="paper_tradi_account_23d71f_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="paperposition",
            index=models.Index(
                fields=["account", "status"], name="paper_tradi_account_25d35d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paperposition",
            index=models.Index(
                fields=["market", "status"], name="paper_tradi_market__38c718_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paperposition",
            index=models.Index(
                fields=["account", "side"], name="paper_tradi_account_6b7a6b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paperposition",
            constraint=models.UniqueConstraint(
                fields=("account", "market", "side"),
                name="paper_position_account_market_side_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="papertrade",
            index=models.Index(
                fields=["account", "status"], name="paper_tradi_account_d1baf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="papertrade",
            index=models.Index(
                fields=["market", "executed_at"], name="paper_tradi_market__28ff32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="papertrade",
            index=models.Index(
                fields=["trade_type", "side"], name="paper_tradi_trade_t_a51e75_idx"
            ),
        ),
    ]
